import React,{useEffect,useState} from 'react';import {ArrowLeft,CheckCircle2,Bookmark} from 'lucide-react';
import {books} from '../iq/service.js';
import {course} from './service.js';import {useDraft,DraftNotice} from './useDraft.jsx';import {catalog} from './catalog.js';import {Audio,Recorder} from './Audio.jsx';import Exercise from './Exercise.jsx';import Visual from './Visual.jsx';import Writing from './Writing.jsx';
const steps=['Ko‘rib tushun','So‘z va talaffuz','Grammatika','Tinglash','O‘qish','Yozish','Gapirish','Yakun'];
export default function Lesson({data,uid,onBack,onUpdated,onActive}){
 const lesson=data.lesson,[run,setRun]=useState(data.run),[error,setError]=useState(''),[busy,setBusy]=useState(false),[voiceBusy,setVoiceBusy]=useState(false),[exitAnswers,setExitAnswers]=useState({}),[word,setWord]=useState(null),[marked,setMarked]=useState([]),[recap,setRecap]=useState(false);
 useEffect(()=>{const t=setTimeout(()=>books('mark',{id:'book-'+lesson.id}).catch(()=>{}),4500);return()=>clearTimeout(t)},[lesson.id,uid]);
 const readonly=['submitted','reviewed','mastered'].includes(run.status),variant=(run.state.exitHistory?.length||0)%2;
 const draft=useDraft({key:`sq_en_draft:${uid}:${run.id}`,work:run,defaults:{step:0,writing:'',completed:[],speaking:{}},send:body=>course('save',body),fetchRemote:async()=>(await course('run',{id:run.id})).run,onSaved:setRun});
 const {step,writing,completed,speaking}=draft.draft, sync=draft.sync,flush=draft.flush;
 const setStep=value=>draft.update(d=>({step:typeof value==='function'?value(d.step):value}));
 const setWriting=writing=>draft.update({writing}),setSpeaking=speaking=>draft.update({speaking});
 const saveRecording=async speaking=>{draft.update({speaking});await flush()};
 useEffect(()=>{onActive(true);return ()=>onActive(false)},[]);
 useEffect(()=>{if(data.initialStep!=null)setStep(data.initialStep)},[]);
 const act=async(fn)=>{setBusy(true);setError('');try{return await fn()}catch(e){setError(e.message);throw e}finally{setBusy(false)}};
 const answer=async(q,a,evidence)=>{await flush();const res=await course('attempt',{id:run.id,questionId:q.id,answer:a,heard:evidence?.heard});setRun(res.run);return res};
 const done=t=>draft.update(d=>({completed:d.completed.includes(t)?d.completed:[...d.completed,t]}));
 const leave=()=>act(async()=>{await flush();onActive(false);onUpdated();onBack()}).catch(()=>{});
 const saveWord=w=>act(async()=>{await course('vocabSave',{id:run.id,wordId:w.id});setWord({...w,saved:true})}).catch(()=>{});
 const selection=()=>{const t=window.getSelection()?.toString().trim();if(t&&t.split(/\s+/).length<5){const w=lesson.vocabulary.find(v=>v.term.toLowerCase()===t.toLowerCase());setWord(w||{term:t,unknown:true})}};
 const exercises=qs=>qs.map(q=><Exercise key={q.id} q={q} busy={busy||readonly} result={run.state.results?.[q.id]} onAnswer={(a,evidence)=>act(()=>answer(q,a,evidence))} onHint={()=>act(()=>course('hint',{id:run.id,questionId:q.id}))}/>);
 return <div className="en-lesson"><header className="en-lesson-head"><button type="button" onClick={leave} disabled={busy||voiceBusy}><ArrowLeft size={17}/> Darsni saqlab chiqish</button><span className="en-badge">{lesson.level} · {lesson.order}-dars · v{run.revision}</span><span className="en-sync" role="status">{sync}</span></header><h1>{lesson.title}</h1><p>{lesson.objective}</p>{lesson.prerequisites.length>0&&<p className="en-meta">Tayanch dars: {lesson.prerequisites.map(id=>catalog.find(l=>l.id===id)?.title||id).join(", ")}</p>}<nav aria-label="Dars qadamlari" className="en-steps">{steps.map((t,i)=><button type="button" key={t} aria-label={t} className={step===i?'current':''} aria-current={step===i?'step':undefined} disabled={busy||voiceBusy} onClick={()=>setStep(i)}>{i+1}<span>{t}</span></button>)}</nav><progress value={Object.keys(run.state.results||{}).length} max={lesson.exercises.length+lesson.reading.questions.length+lesson.listening.questions.length} aria-label="Bajarilgan mashqlar"/>
 {error&&<p role="alert" className="en-error">{error}</p>}<DraftNotice draft={draft}/>
 {step===0&&<section><h2>Vaziyatdan boshlang</h2><p>{lesson.context}</p><Visual lesson={lesson}/><div className="en-rule-list">{lesson.rules.map((t,i)=><details key={t} open={lesson.levelIndex<2||undefined}><summary>{i+1}-izoh</summary><p>{t}</p></details>)}</div><h3>Gapda ko‘ring</h3><div className="en-examples">{lesson.examples.map((t,i)=><p key={t} lang="en"><span>{i+1}</span>{t}</p>)}</div><Visual lesson={lesson} index={1}/><button type="button" className="en-primary" onClick={()=>{done('learn');setStep(1)}}>Misollarni ko‘rdim · davom etish</button></section>}
 {step===1&&<section><h2>So‘zlarni vaziyatda ishlating</h2><div className="en-vocabulary">{lesson.vocabulary.map(w=><article key={w.id}><b lang="en">{w.term}</b><span>{w.meaning}</span><small>{w.ipa}</small><p lang="en">{w.example}</p><p lang="en" className="en-collocation">{w.collocation}</p><button type="button" onClick={()=>saveWord(w)}><Bookmark size={15}/> Lug‘atimga</button></article>)}</div><Audio src={lesson.pronunciation.audio} transcript={lesson.pronunciation.text} label="Talaffuz namunasi"/><p>{lesson.pronunciation.focus}</p><button type="button" className="en-primary" onClick={()=>{done('vocabulary');setStep(2)}}>Birikmalarni ko‘rdim · mashq qilish</button></section>}
 {step===2&&<section><h2>Ma’nodan gapga</h2>{exercises(lesson.exercises.filter(q=>!q.recap))}</section>}
 {step===3&&<section><h2>Tinglab tushuning</h2><p>Avval umumiy ma’noni tinglang. Keyin kerakli tafsilotlarni tekshiring.</p><Audio src={lesson.listening.audio} transcript={lesson.listening.transcript} onHeard={()=>done('listening')}/>{completed.includes('listening')?<p className="en-success">Yozuv yakunigacha tinglandi. Javoblarni tekshiring.</p>:<p>Audio tugamaguncha listening javobi qabul qilinmaydi.</p>}{exercises(lesson.listening.questions)}</section>}
 {step===4&&<section><h2>{lesson.reading.title}</h2><p>So‘z ustida matnni belgilab, ma’nosini oching. Dalil jumlalarni bosib ajrating.</p><div lang="en" className="en-reading" onMouseUp={selection} onTouchEnd={selection}>{lesson.reading.sentences.map((s,i)=><button type="button" key={i} className={marked.includes(i)?'marked':''} aria-pressed={marked.includes(i)} onClick={()=>setMarked(marked.includes(i)?marked.filter(v=>v!==i):[...marked,i])}>{s} </button>)}</div><div className="en-actions">{lesson.vocabulary.map(w=><button type="button" key={w.id} onClick={()=>setWord(w)}>{w.term}</button>)}</div>{word&&<aside className="en-word-popup"><b>{word.term}</b>{word.unknown?<><p>Bu so‘z darsning kichik lug‘atida yo‘q.</p><a href={'https://dictionary.cambridge.org/dictionary/english/'+encodeURIComponent(word.term)} target="_blank" rel="noreferrer">Cambridge lug‘atida tekshirish</a></>:<><p>{word.meaning} · {word.ipa}</p><p lang="en">{word.collocation}</p><button type="button" onClick={()=>saveWord(word)}>{word.saved?'Lug‘atga saqlandi':'Lug‘atga saqlash'}</button></>}<button type="button" onClick={()=>setWord(null)}>Yopish</button></aside>}{exercises(lesson.reading.questions)}</section>}
 {step===5&&<Writing task={lesson.writing} value={writing} onChange={setWriting} first={run.state.firstWriting} readonly={readonly||busy}/>}
 {step===6&&<section><h2>Fikringizni ayting</h2><p>{lesson.speaking.task}</p><ul>{lesson.speaking.prompts.map(t=><li key={t}>{t}</li>)}</ul><p>Yo‘nalish: {lesson.speaking.seconds} soniya. Yodlangan namuna o‘rniga o‘z javobingizni ayting.</p><Recorder uid={uid} id={run.id} value={speaking} onChange={setSpeaking} onUploaded={saveRecording} onBusyChange={setVoiceBusy} readonly={readonly} disabled={busy}/><details><summary>Baholash mezonlari</summary>{lesson.rubrics.speaking.map(t=><p key={t}>{t} · ustoz 0–5 ball beradi.</p>)}</details></section>}
 {step===7&&<section><h2>Amalda qo‘llang</h2><p>{lesson.realTask}</p><h3>Chiqish tekshiruvi · {variant?'B':'A'} variant</h3><p>Javoblar barchasi yuborilgandan keyin tahlil ochiladi.</p>{lesson.exit[variant].map(q=><Exercise key={q.id} q={q} exam value={exitAnswers[q.id]} onValue={a=>setExitAnswers(x=>({...x,[q.id]:a}))}/>)}<button type="button" disabled={busy||voiceBusy||readonly} className="en-primary" onClick={()=>act(async()=>{await flush();const res=await course('exit',{id:run.id,answers:exitAnswers});setRun(res.run);setExitAnswers({})}).catch(()=>{})}>Chiqish tekshiruvini topshirish</button>{run.state.exit&&<div className="en-model"><b>Natija: {run.state.exit.score}%</b>{run.state.exit.feedback.map(f=><p key={f.id}>{f.correct?'To‘g‘ri':'Qayta mashq'} · <span lang="en">{f.expected.join(' / ')}</span> · {f.explanation}</p>)}</div>}<h3>Writing va speakingni topshirish</h3><p>Natija ustoz tekshiruvidan so‘ng o‘zlashtirishga aylanadi. Listening yoki readingdagi xatolarni avval qayta ishlang.</p>{run.feedback&&<div className="en-feedback"><p>{run.feedback.text}</p><p>Writing {run.feedback.writing}% · Speaking {run.feedback.speaking}%</p></div>}{run.status==='needs_revision'&&<button type="button" onClick={()=>act(async()=>{const r=await course('resubmit',{id:run.id,writing,speaking,expectedDraftVersion:draft.store.version});setRun(r);setStep(5)}).catch(()=>{})}>Qayta ishlashni boshlash</button>}{!readonly&&run.status!=='needs_revision'&&<button type="button" className="en-primary" disabled={busy||voiceBusy} onClick={()=>act(async()=>{await flush();const r=await course('submit',{id:run.id,expectedDraftVersion:draft.store.version});setRun(r);onUpdated()}).catch(()=>{})}>Ustoz tekshiruviga topshirish</button>}{readonly&&<p className="en-success"><CheckCircle2 size={17}/> {run.status==='mastered'?'Dars o‘zlashtirildi. Keyingi qadam ochildi.':'Topshirildi. Ustoz tekshiruvi kutilmoqda.'}</p>}{lesson.recapQuestions?.length>0&&<><button type="button" onClick={()=>setRecap(!recap)}>Takrorlash nuqtasi</button>{recap&&<div><p>Oldingi uch darsdan aralash tekshiruv. Qaysi mavzu ekanini eslab, javobni yana asoslang.</p>{exercises(lesson.recapQuestions)}</div>}</>}<details><summary>Tekshirilgan qo‘shimcha manbalar</summary>{lesson.sources.map(s=><article key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.name}</a><p>{s.task}</p><small>{s.skill} · {s.levels.join(', ')} · tekshirildi {s.verified}</small></article>)}</details></section>}
 <footer className="en-lesson-footer"><button type="button" disabled={step===0||busy||voiceBusy} onClick={()=>setStep(s=>s-1)}>Oldingi</button><span>{step+1} / {steps.length}</span>{step<7?<button type="button" className="en-primary" disabled={busy||voiceBusy} onClick={()=>setStep(s=>s+1)}>Davom etish</button>:<button type="button" disabled={busy||voiceBusy} onClick={leave}>Saqlab, xaritaga qaytish</button>}</footer></div>
}
