// Public, original descriptions. User data and answer keys never enter these pages.
export const seoPages=[
 {path:'/ustozlar/sinfxona',title:'Sinfxona — elektron doska va dars vositalari',description:'Ustoz uchun elektron doska, 10 ko‘rinishli taymer, shovqin kuzatuvi va xolis raqam tanlash.',hash:'sinfxona',sections:[['Elektron doska','Qalam, marker, matn, geometrik shakllar va rasmlar bilan ishlang. Sahifalar, undo/redo, topshiriq shablonlari va PNG yuklash mavjud.'],['Taymer va shovqin','10 ko‘rinish bir xil taymer bilan ishlaydi. Mikrofon faqat ustoz yoqqanda ochiladi; 0–100 nisbiy shovqin darajasi va ko‘tariluvchi sharlar ko‘rinadi. Ovoz yozilmaydi.'],['Kirish va qoralama','Sinfxona faqat o‘qituvchi va administrator uchun. Qoralama hisob bo‘yicha shu brauzerda saqlanadi; boshqa qurilmaga avtomatik ko‘chmaydi.']]},
 {path:'/fanlar/kimyo',title:'Kimyo atlasi va virtual laboratoriya',description:'Atom, 118 elementli davriy jadval, molekula, pH va reagentlar bilan boshqariladigan kimyo mashqlari.',hash:'kimyo',sections:[['Atomdan moddaga','Atom tarkibi, elementlar, molekula formulalari va kimyoviy bog‘larni interaktiv modellarda o‘rganing.'],['Virtual tajriba stoli','Erkin laboratoriya va 12 amaliy ishda reagent, miqdor, vaqt, harorat va jihozlarni tanlaysiz. Grafik va kuzatuvlarni taqqoslaysiz.'],['Model chegarasi','Soddalashtirishlar sahnada aytilgan. Stoixiometriya va atomlar saqlanishi alohida hisoblanadi. Virtual ish haqiqiy xavfli tajribani nazoratsiz takrorlash yo‘riqnomasi emas.']]},
 {path:'/fanlar/biologiya',title:'Biologiya — tirik tabiat va odam anatomiyasi atlasi',description:'Bargdan tuproqqacha, o‘simlik o‘sishi, zoologiya va tayyor 3D anatomiya modellarini SinfQuizda o‘rganing.',hash:'biologiya',sections:[['Bargning sayohati','Namlik, harorat, kislorod, yomg‘ir va tuproq turini o‘zgartiring. Organik qoldiq, parchalovchilar va mineral oziqa orasidagi farqni ko‘ring.'],['Odam tanasi','Litsenziyalangan organ, skelet va mushak modellarini aylantiring. Nafas, qon aylanish va hazm jarayonlarini kuzating. Atlas tashxis vositasi emas.'],['Amaliy kuzatish','12 amaliy ishda savol, taxmin, sinov, kuzatish va xulosa ketma-ketligi ishlaydi. Natijalar ta’limiy modeldan olinadi.']]},
 {path:'/fanlar/matematika',title:'Matematika atlasi — algebra va geometriya tajribalari',description:'Son chizig‘i, tenglama tarozisi, funksiya grafigi, uchburchak yuzi va fazoviy jismlarni interaktiv o‘rganing.',hash:'matematika',sections:[['Algebra va funksiya','Son, kasr, tenglama, koordinata, formula va jadval bog‘lanishini parametrlarni o‘zgartirib tekshiring.'],['Geometriya','Nuqtani sudraganda shakl, o‘lchov va yuza birga yangilanadi. Yoyilma, kesim va hajm fazoviy shaklni tushunishga yordam beradi.'],['Tushunchalar xaritasi','55 tushuncha, qidiruv va tayyorgarlikka mos yo‘l orqali tayanch bilimdan keyingi mavzuga o‘ting.']]},
 {path:'/fanlar/informatika',title:'Informatika — Python, Word, Excel va PowerPoint',description:'SinfQuiz informatika darslari: Python muharriri, Word va Excel topshiriqlari, typing va kodli sinf testlari.',hash:'informatika',sections:[['Python amaliyoti','Ajratilgan brauzer muhitida boshlang‘ich dastur yozing, natijani ko‘ring va .py faylni yuklab oling.'],['Office dasturlari','Wordda matn, rasm va jadval; Excelda katak, formula va o‘rtacha qiymat; PowerPointda taqdimot bo‘yicha amaliy ishlar.'],['Sinf mashqlari','Ustoz ochgan kodli test, typing va bitta ekrandagi ikki kishilik bilim poygasiga qo‘shiling.']]},
 {path:'/ingliz-tili',title:'Ingliz tili darslari va inglizcha labirint',description:'Noldan C1 gacha darslar, daraja testi, tinglash, o‘qish, yozish, gapirish va matnli yoki ovozli labirint.',hash:'ingliz-darsi',sections:[['Dars yo‘li','108 dars va darajaga mos mavzular. Kirish amaldagi tayyorgarlik va bosqich qoidalariga bog‘liq.'],['Tinglash va matn','Lokal audio bilan mashq qiling. Labirintda eshitish imkoniyati bo‘lmasa, matn rejimini tanlang.'],['Mock va tahlil','CEFR/Multilevel mashqlari va javoblar tahlili bilimni mustahkamlaydi. Mashq natijasi rasmiy sertifikat emas.']]},
 {path:'/darsliklar',title:'O‘zbekcha darsliklar — to‘rtta fan bir joyda',description:'198 dars: Ingliz tili, Kimyo, Biologiya va Informatika. Tartibli mavzular, misollar, tekshiruv va amaliyot.',hash:'darsliklar',sections:[['To‘rtta fan','108 ingliz tili, 48 informatika, 30 biologiya va 12 kimyo darsi mavzu va fan bo‘yicha ajratilgan.'],['O‘qing va bajaring','Misolni tekshiring, xato tushunchani izohlang va atlas yoki amaliyot oynasida mustaqil sinab ko‘ring.'],['Ustoz darslari','Shaxsiy kontent amaldagi ruxsatlar bilan ajratiladi. Bu ochiq sahifaga sinf ma’lumotlari, yozishmalar yoki javob kalitlari chiqarilmaydi.']]},
];
const escape=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function publicSiteUrl(value){if(!value)return 'https://www.sinfquiz.uz';const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||u.pathname!=='/')throw Error('VITE_PUBLIC_SITE_URL HTTPS domeni bo‘lsin: https://www.sinfquiz.uz');return u.origin;}
export function seoHead(site,{title='SinfQuiz — darsliklar, atlaslar va sinfxona vositalari',description='O‘zbekcha darsliklar, matematika, kimyo va biologiya atlaslari, ingliz tili, Python, sinf testlari va ustoz uchun elektron doska.',path='',verification=''}={}){
 const url=site+(path||'/'),schema={'@context':'https://schema.org','@type':path?'WebPage':'WebSite',name:title,url,description,inLanguage:'uz',...(path?{isPartOf:{'@type':'WebSite',name:'SinfQuiz',url:site+'/'}}:{about:{'@type':'EducationalApplication',name:'SinfQuiz',applicationCategory:'EducationalApplication',operatingSystem:'Web'}})};
 return `<title>${escape(title)}</title><meta name="description" content="${escape(description)}"><meta name="robots" content="index, follow, max-image-preview:large"><link rel="canonical" href="${url}"><meta property="og:type" content="website"><meta property="og:locale" content="uz_UZ"><meta property="og:site_name" content="SinfQuiz"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${site}/og-sinfquiz.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="SinfQuiz — dars, tajriba va sinfxona"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${escape(title)}"><meta name="twitter:description" content="${escape(description)}"><meta name="twitter:image" content="${site}/og-sinfquiz.png">${verification?`<meta name="google-site-verification" content="${escape(verification)}">`:''}<script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script>`;
}
export function publicPageHTML(site,p){
 const links=seoPages.map(x=>`<a href="${x.path}">${escape(x.title)}</a>`).join('');
 return `<!doctype html><html lang="uz"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#007887"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="stylesheet" href="/seo.css">${seoHead(site,p)}<script src="/theme-init.js"></script></head><body><a class="seo-skip" href="#main">Asosiy mazmunga o‘tish</a><header class="seo-header"><a href="/" class="seo-brand">Sinf<span>Quiz</span></a><a href="/#${p.hash}" class="seo-open">Bo‘limni ochish</a></header><main class="seo-page" id="main"><nav aria-label="Yo‘l"><a href="/">Bosh sahifa</a> / ${escape(p.title)}</nav><p class="seo-kicker">SINFQUIZ / O‘RGANISH VA AMALIYOT</p><h1>${escape(p.title)}</h1><p class="seo-lead">${escape(p.description)}</p><div class="seo-cards">${p.sections.map(([h,t])=>`<section><h2>${escape(h)}</h2><p>${escape(t)}</p></section>`).join('')}</div><a class="seo-open" href="/#${p.hash}">Bo‘limni ochish</a><p class="seo-note">Bo‘lim amaldagi kirish va rol qoidalari orqali ochiladi.</p></main><footer class="seo-footer"><h2>Yana nimalarni o‘rganamiz?</h2><nav aria-label="Fanlar va imkoniyatlar">${links}</nav><p>SinfQuiz — bilimni mustaqil mashq orqali mustahkamlash uchun.</p></footer></body></html>`;
}
export const sitemapXML=site=>`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['',...seoPages.map(p=>p.path)].map(path=>`<url><loc>${site}${path||'/'}</loc></url>`).join('')}</urlset>\n`;
export function seoPlugin({url,verification}={}){
 const site=publicSiteUrl(url),pages=new Map(seoPages.map(p=>[p.path,publicPageHTML(site,p)])),robots=`User-agent: *\nAllow: /\nDisallow: /api/\n\nSitemap: ${site}/sitemap.xml\n`;
 const middleware=(req,res,next)=>{const path=(req.url||'/').split('?')[0].replace(/\/$/,'')||'/';let value,type;if(pages.has(path)){value=pages.get(path);type='text/html';}else if(path==='/sitemap.xml'){value=sitemapXML(site);type='application/xml';}else if(path==='/robots.txt'){value=robots;type='text/plain';}else return next();res.statusCode=200;res.setHeader('Content-Type',type+'; charset=utf-8');res.end(value);};
 return {name:'sinfquiz-public-seo',transformIndexHtml:html=>html.replace('<!-- SQ_PUBLIC_HEAD -->',seoHead(site,{verification})),configureServer(s){s.middlewares.use(middleware);},configurePreviewServer(s){s.middlewares.use(middleware);},generateBundle(){for(const [path,source] of pages)this.emitFile({type:'asset',fileName:path.slice(1)+'.html',source});this.emitFile({type:'asset',fileName:'sitemap.xml',source:sitemapXML(site)});this.emitFile({type:'asset',fileName:'robots.txt',source:robots});}};
}
