import test from 'node:test';import assert from 'node:assert/strict';
import {chemistryTopics} from '../src/chemistry-content.js';import {saltLattice} from '../src/chemistry-model.js';
import {validateChemistryForm,filterChemistryTopics,readChemistryDraft,writeChemistryDraft,chemistrySubmissionKey} from '../src/chemistry-workflow.js';
test('teacher form rejects blank answers, fractional particles, wrong scenes and out of range values',()=>{
 const base={...chemistryTopics[0],parameters:{protons:8}};assert.equal(validateChemistryForm(base),'');assert.equal(validateChemistryForm({...base,answer:0}),'');
 for(const answer of ['', ' ',true,null,1001,NaN,Infinity])assert.notEqual(validateChemistryForm({...base,answer}),'');
 for(const parameters of [{protons:8.5},{protons:21},{neutrons:-1},{electrons:21},{unknown:3},null,[]])assert.notEqual(validateChemistryForm({...base,parameters}),'');
 assert.notEqual(validateChemistryForm({...base,scene:'missing'}),'');assert.notEqual(validateChemistryForm({...base,grade:6.5}),'');assert.notEqual(validateChemistryForm({...base,title:'Ab'}),'');assert.equal(validateChemistryForm({...base,answer:'-2'}),'');
});
test('NaCl lattice alternates charge in both directions and is neutral',()=>{const lattice=saltLattice(6,4);assert.equal(lattice.reduce((sum,ion)=>sum+ion.charge,0),0);for(const ion of lattice){for(const [dx,dy] of [[1,0],[0,1]]){const neighbour=lattice.find(n=>n.x===ion.x+dx&&n.y===ion.y+dy);if(neighbour)assert.equal(neighbour.charge,-ion.charge)}}});
test('lab search returns a real empty result and preserves explicit teacher isolation',()=>{assert.equal(filterChemistryTopics(chemistryTopics,{tab:'lab',query:'atom ichiga'}).length,0);assert.equal(filterChemistryTopics(chemistryTopics,{query:'   MUZ   '}).length,1);const copies=[{...chemistryTopics[6],id:'one',custom:true,ownerId:'one',status:'published',active:true},{...chemistryTopics[6],id:'two',custom:true,ownerId:'two',status:'published',active:true},{...chemistryTopics[6],id:'hidden',custom:true,ownerId:'one',status:'published',active:false}];assert.deepEqual(filterChemistryTopics(copies,{source:'teacher:one'}).map(x=>x.id),['one']);});
test('draft format preserves old notes, numeric prediction and checked state, and handles blocked storage',()=>{const data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)},snapshot={note:'Suv holati o‘zgardi.',prediction:'-2',checked:true};storage.setItem('old','Eski kuzatish.');assert.equal(readChemistryDraft(storage,'old').note,'Eski kuzatish.');assert.equal(writeChemistryDraft(storage,'new',snapshot),true);assert.deepEqual(readChemistryDraft(storage,'new'),snapshot);assert.deepEqual(readChemistryDraft(storage,'other'),{note:'',prediction:'',checked:false});assert.equal(writeChemistryDraft(null,'key',snapshot),false);assert.equal(readChemistryDraft(null,'key').note,'');});
test('submission identity treats equivalent numeric answers equally, but new notes are a new submission',()=>{assert.equal(chemistrySubmissionKey('2','Kuzatish'),chemistrySubmissionKey('2.0','Kuzatish'));assert.notEqual(chemistrySubmissionKey('2','Kuzatish'),chemistrySubmissionKey('2','Boshqa kuzatish'));});

test('draft retains submission acknowledgement and scopes it to the current challenge',()=>{const store=new Map(),storage={getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},challengeKey='savol:1',snapshot={note:'Kuzatish',prediction:'2',checked:true,challengeKey,sentKey:chemistrySubmissionKey('2','Kuzatish',challengeKey)};writeChemistryDraft(storage,'draft',snapshot);assert.deepEqual(readChemistryDraft(storage,'draft'),snapshot);assert.notEqual(snapshot.sentKey,chemistrySubmissionKey('2','Kuzatish','savol:2'));});
