import {chemistryLabs,labDefaults} from '../src/chemistry-labs.js';
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {PGlite} from '@electric-sql/pglite';import {chemistryTopics} from '../src/chemistry-content.js';
const t1='20000000-0000-0000-0000-000000000001',t2='20000000-0000-0000-0000-000000000002',s1='20000000-0000-0000-0000-000000000003',s2='20000000-0000-0000-0000-000000000004',ad='20000000-0000-0000-0000-000000000005';
test('chemistry RLS enforces author isolation, admin approval, active visibility and private observations',async()=>{const db=new PGlite();try{
 await db.exec(`create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.uid',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on all functions in schema auth to authenticated;create function public.sq_is_admin() returns boolean language sql stable as $$select auth.uid()='${ad}'::uuid$$;create function public.sq_is_teacher() returns boolean language sql stable as $$select auth.uid() in ('${t1}'::uuid,'${t2}'::uuid,'${ad}'::uuid)$$;insert into auth.users values('${t1}'),('${t2}'),('${s1}'),('${s2}'),('${ad}');`);
 await db.exec(readFileSync(new URL('../supabase-chemistry-atlas.sql',import.meta.url),'utf8'));await db.exec(readFileSync(new URL('../supabase-chemistry-atlas.sql',import.meta.url),'utf8'));
 await db.exec(readFileSync(new URL('../supabase-chemistry-labs.sql',import.meta.url),'utf8'));await db.exec(readFileSync(new URL('../supabase-chemistry-labs.sql',import.meta.url),'utf8'));
 const login=async id=>{await db.exec('reset role');await db.query("select set_config('request.uid',$1,false)",[id]);await db.exec('set role authenticated')},data={...chemistryTopics[0],parameters:{protons:8}};
 await login(t1);
 for(const lab of chemistryLabs){const data={...lab,parameters:labDefaults(lab)};const r=await db.query('insert into public.chemistry_concepts(owner_id,status,data) values($1,$2,$3) returning id',[t1,'pending',JSON.stringify(data)]);assert.equal(r.rows.length,1);await db.query('delete from public.chemistry_concepts where id=$1',[r.rows[0].id]);const c=lab.controls[0];await assert.rejects(db.query('insert into public.chemistry_concepts(owner_id,status,data) values($1,$2,$3)',[t1,'pending',JSON.stringify({...data,parameters:{[c.key]:c.max+1}})]));await assert.rejects(db.query('insert into public.chemistry_concepts(owner_id,status,data) values($1,$2,$3)',[t1,'pending',JSON.stringify({...data,parameters:{protons:8}})]));}
 await assert.rejects(db.query('insert into public.chemistry_concepts(owner_id,status,data) values($1,$2,$3)',[t1,'published',JSON.stringify(data)]));const r=await db.query('insert into public.chemistry_concepts(owner_id,status,data) values($1,$2,$3) returning id',[t1,'pending',JSON.stringify(data)]),id=r.rows[0].id;
 await login(t2);assert.equal((await db.query('select id from public.chemistry_concepts')).rows.length,0);assert.equal((await db.query('update public.chemistry_concepts set active=false where id=$1 returning id',[id])).rows.length,0);
 await login(s1);assert.equal((await db.query('select id from public.chemistry_concepts')).rows.length,0);await assert.rejects(db.query('insert into public.chemistry_observations(concept_id,student_id,prediction) values($1,$2,$3)',[id,s1,-2]));
 await login(ad);await db.query("update public.chemistry_concepts set status='published' where id=$1",[id]);await assert.rejects(db.query('update public.chemistry_concepts set owner_id=$1 where id=$2',[ad,id]));await assert.rejects(db.query("update public.chemistry_concepts set data=jsonb_set(data,'{answer}','99') where id=$1",[id]));
 await login(s1);const o=await db.query('insert into public.chemistry_observations(concept_id,student_id,prediction,is_correct,observation) values($1,$2,$3,true,$4) returning *',[id,s1,2,'Men proton va elektronlarni solishtirdim.']);assert.equal(o.rows[0].is_correct,false,'server does not trust supplied correct flag');await assert.rejects(db.query('insert into public.chemistry_observations(concept_id,student_id,prediction) values($1,$2,$3)',[id,s2,-2]));const yes=await db.query('insert into public.chemistry_observations(concept_id,student_id,prediction) values($1,$2,$3) returning is_correct',[id,s1,-2]);assert.equal(yes.rows[0].is_correct,true);
 await login(s2);assert.equal((await db.query('select * from public.chemistry_observations')).rows.length,0);await login(t2);assert.equal((await db.query('select * from public.chemistry_observations')).rows.length,0);await login(t1);assert.equal((await db.query('select * from public.chemistry_observations')).rows.length,2);await db.query('update public.chemistry_concepts set active=false where id=$1',[id]);await login(s1);assert.equal((await db.query('select * from public.chemistry_concepts')).rows.length,0);await assert.rejects(db.query('insert into public.chemistry_observations(concept_id,student_id,prediction) values($1,$2,$3)',[id,s1,-2]));
 await login(t1);
 for(const lab of chemistryLabs){const data={...lab,parameters:labDefaults(lab)};const r=await db.query('insert into public.chemistry_concepts(owner_id,status,data) values($1,$2,$3) returning id',[t1,'pending',JSON.stringify(data)]);assert.equal(r.rows.length,1);await db.query('delete from public.chemistry_concepts where id=$1',[r.rows[0].id]);const c=lab.controls[0];await assert.rejects(db.query('insert into public.chemistry_concepts(owner_id,status,data) values($1,$2,$3)',[t1,'pending',JSON.stringify({...data,parameters:{[c.key]:c.max+1}})]));await assert.rejects(db.query('insert into public.chemistry_concepts(owner_id,status,data) values($1,$2,$3)',[t1,'pending',JSON.stringify({...data,parameters:{protons:8}})]));}
 await assert.rejects(db.query("update public.chemistry_concepts set data=jsonb_set(data,'{definition}',to_jsonb('Boshqa yangi izoh, qayta tasdiq kerak.'::text)) where id=$1",[id]));await db.query("update public.chemistry_concepts set status='pending',data=jsonb_set(data,'{definition}',to_jsonb('Boshqa yangi izoh, qayta tasdiq kerak.'::text)) where id=$1",[id]);
 await assert.rejects(db.query('insert into public.chemistry_concepts(owner_id,data) values($1,$2)',[t1,JSON.stringify({...data,answer:undefined})]));await assert.rejects(db.query('insert into public.chemistry_concepts(owner_id,data) values($1,$2)',[t1,JSON.stringify({...data,parameters:{protons:30}})]));
 }finally{await db.close()}});
