// Self-contained browser QA, fixture APIs only. No production database writes.
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const root=path.resolve(__dirname,'..'),out=process.env.QA_ARTIFACT_DIR||'/tmp/sinfquiz-chemistry';fs.mkdirSync(out,{recursive:true});const {chemistryLabs}=await import(pathToFileURL(path.join(root,'src/chemistry-labs.js')));const {labResult}=await import(pathToFileURL(path.join(root,'src/chemistry-lab-model.js')));const {createServer}=await import(pathToFileURL(path.join(root,'node_modules/vite/dist/node/index.js'))),{chemistryTopics}=await import(pathToFileURL(path.join(root,'src/chemistry-content.js')));const server=await createServer({root,server:{host:'127.0.0.1',port:4175,hmr:false}});await server.listen();const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];let record,save,recordCount=0,rows=[{id:'qa-ph',owner_id:'teacher-one',status:'published',active:true,data:{...chemistryTopics.find(t=>t.id==='ph'),title:'Ustozning pH tajribasi'},updated_at:new Date().toISOString()}];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/same key|Uncaught|ReferenceError|TypeError/.test(m.text()))errors.push(m.text())});await page.addInitScript(()=>window.__SINFQUIZ_LEGACY_TEST__=true);
 async function fixture(p,role='student'){await p.addInitScript(()=>window.__SINFQUIZ_LEGACY_TEST__=true);await p.route(/\/(auth|api)\//,async route=>{const url=new URL(route.request().url()).pathname;let value={};if(url==='/auth/session')value={user:{id:role==='student'?'qa-student':'teacher-one',name:'Javlon',role},csrf:'qa'};if(url==='/api/catalog')value={quizzes:[],lessons:[]};if(url==='/api/admin')value={quizzes:[],lessons:[],users:[],races:[],typing:[]};if(url==='/api/chemistry/concepts')value=rows;if(url==='/api/chemistry/record'){recordCount++;record=route.request().postDataJSON();value={...record,id:'obs-1',is_correct:true}}if(url==='/api/chemistry/save'){save=route.request().postDataJSON();const row={id:save.data.scene.startsWith('lab-')?'new-chem-lab':'new-chem',owner_id:save.ownerId,data:save.data,status:save.status,active:save.active,updated_at:new Date().toISOString()};rows.push(row);value=row}if(url==='/api/chemistry/observations')value=[{id:'obs-1',concept_id:'qa-ph',student_id:'qa-student',student_name:'Javlon',prediction:1,is_correct:false,observation:'Kislota miqdorini ko‘paytirdim.',created_at:new Date().toISOString()}];if(url==='/api/chemistry/review'){const body=route.request().postDataJSON();rows=rows.map(r=>r.id===body.id?{...r,status:body.status}:r);value={ok:true}}if(url==='/api/chemistry/toggle'){const body=route.request().postDataJSON();rows=rows.map(r=>r.id===body.id?{...r,active:body.active}:r);value={ok:true}}await route.fulfill({json:value})})}
 const map=async()=>page.getByRole('button',{name:'Mavzular xaritasi',exact:true}).click();const open=async id=>{await map();const t=chemistryTopics.find(t=>t.id===id);await page.locator('.ch-topic-card').filter({has:page.getByRole('heading',{name:t.title,exact:true})}).click();await page.locator('.ch-scene').waitFor()};
 try{await fixture(page);await page.goto('http://127.0.0.1:4175/#kimyo');await page.locator('.ch-topic-card').first().waitFor();await page.screenshot({path:path.join(out,'chemistry-desktop.png'),fullPage:true});assert.equal(await page.locator('.ch-topic-card').count(),13);await page.addScriptTag({path:path.join(root,'node_modules/axe-core/axe.min.js')});const axe=await page.evaluate(async()=>window.axe.run('.chemistry-atlas',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}));fs.writeFileSync(path.join(out,'accessibility.json'),JSON.stringify(axe.violations,null,2));assert.deepEqual(axe.violations.map(v=>v.id),[],'chemistry map accessibility');
 await open('atom');await page.getByRole('slider',{name:'Elektronlar',exact:true}).fill('10');assert.match(await page.locator('.ch-result').innerText(),/zaryad −?\-2|zaryad -2/);await page.getByLabel('Model qatlami',{exact:true}).selectOption('orbital');assert.match(await page.locator('.ch-model-note').first().innerText(),/1s/);await page.getByLabel('Sonli taxmin',{exact:true}).fill('2');await page.getByRole('button',{name:'Taxminni tekshirish',exact:true}).click();assert.match(await page.locator('.ch-feedback.retry').innerText(),/Yana/);await page.getByLabel('Sonli taxmin',{exact:true}).fill('-2');await page.getByRole('button',{name:'Taxminni tekshirish',exact:true}).click();assert.ok(await page.locator('.ch-feedback.correct').isVisible());await page.screenshot({path:path.join(out,'atom.png')});
 await open('periodic');assert.equal(await page.locator('.ch-element').count(),118);await page.getByRole('button',{name:'79. Oltin, Au',exact:true}).click();assert.match(await page.locator('.ch-result').innerText(),/79 proton/);await page.getByLabel('Element qidirish',{exact:true}).fill('kislorod');await page.getByRole('button',{name:'8. Kislorod, O',exact:true}).click();await page.screenshot({path:path.join(out,'periodic.png')});
 await open('molecule');await page.getByLabel('Molekula namunasi',{exact:true}).selectOption('methane');assert.match(await page.locator('.ch-result').innerText(),/CH₄/);await page.getByRole('button',{name:'Modelni o‘ngga aylantirish',exact:true}).click();await page.getByRole('button',{name:'Atom qo‘shish',exact:true}).click();assert.match(await page.locator('.ch-result').innerText(),/Ochiq valentlik/);await page.getByLabel('Molekula namunasi',{exact:true}).selectOption('water');await page.screenshot({path:path.join(out,'molecule.png')});await page.getByRole('button',{name:'Quruvchini tozalash',exact:true}).click();await page.getByRole('button',{name:'Atom qo‘shish',exact:true}).click();await page.getByRole('button',{name:'Atom qo‘shish',exact:true}).click();await page.getByLabel('Ikkinchi atom',{exact:true}).selectOption('1');await page.getByRole('button',{name:'Bog‘ni o‘rnatish',exact:true}).click();assert.match(await page.locator('.ch-result').innerText(),/Valentlik mos/);
 await open('states');await page.getByRole('slider',{name:'Suv harorati',exact:true}).fill('110');assert.match(await page.locator('.ch-result').innerText(),/gaz/);await page.getByRole('slider',{name:'Suv harorati',exact:true}).fill('-10');assert.match(await page.locator('.ch-result').innerText(),/qattiq/);
 await open('reaction');await page.getByLabel('H₂ koeffitsiyenti',{exact:true}).fill('2');await page.getByLabel('H₂O koeffitsiyenti',{exact:true}).fill('2');await page.getByRole('button',{name:'Atomlarning qayta joylashishini ko‘rish',exact:true}).click();assert.match(await page.locator('.ch-result').innerText(),/Balans to‘g‘ri/);await page.screenshot({path:path.join(out,'reaction.png')});
 await page.getByRole('button',{name:'Tajriba qil',exact:true}).click();await page.getByLabel('Kimyo mavzusini qidirish',{exact:true}).fill('atom ichiga');await page.getByText('Qidiruvga mos mavzu topilmadi. Qidiruv yoki darajani o‘zgartiring.',{exact:true}).waitFor();await page.getByLabel('Kimyo mavzusini qidirish',{exact:true}).fill('');await open('ph');await page.getByRole('slider',{name:'Kuchli asos miqdori',exact:true}).fill('1');assert.match(await page.locator('.ch-result').innerText(),/pH 7/);await page.getByRole('slider',{name:'Kuchli asos miqdori',exact:true}).fill('2');assert.match(await page.locator('.ch-result').innerText(),/Asos ortiqcha/);
 await open('rate');const old=await page.locator('.ch-result').innerText();await page.getByRole('slider',{name:'Harorat',exact:true}).fill('45');assert.notEqual(await page.locator('.ch-result').innerText(),old);
 await open('mixture');await page.getByLabel('Ajratish usuli',{exact:true}).selectOption('filter');assert.match(await page.locator('.ch-result').innerText(),/erigan tuz/);await page.getByLabel('Ajratish usuli',{exact:true}).selectOption('distill');assert.match(await page.locator('.ch-result').innerText(),/kondensatsiyalanib/);
 await open('bonds');const ions=await page.locator('[data-ion]').evaluateAll(nodes=>nodes.map(n=>n.dataset.ion));assert.notEqual(ions[0],ions[1]);assert.notEqual(ions[0],ions[6]);await page.getByLabel('Kuzatish holati',{exact:true}).selectOption('solution');await page.getByLabel('Bog‘ turi',{exact:true}).selectOption('covalent');assert.equal(await page.getByLabel('Kuzatish holati',{exact:true}).count(),0);for(const id of ['bonds','organic','electric','life']){await open(id);assert.ok(await page.locator('.ch-result').isVisible())}await page.getByLabel('Kundalik hodisa',{exact:true}).selectOption('air');await page.getByRole('button',{name:'Zarrachalarga yaqinlashish',exact:true}).click();assert.ok(await page.locator('.ch-model').isVisible());
 await map();await page.locator('.ch-topic-card').filter({has:page.getByRole('heading',{name:'Ustozning pH tajribasi',exact:true})}).click();await page.getByLabel('Sonli taxmin',{exact:true}).fill('10');await page.getByRole('button',{name:'Taxminni tekshirish',exact:true}).click();await page.getByLabel('Nimani kuzatdingiz va nima sababdan?',{exact:true}).fill('Kislota miqdorini o‘zgartirdim.');await page.getByRole('button',{name:'Ustozga yuborish',exact:true}).click();await page.getByText('Kuzatish ustozingizga yuborildi.',{exact:true}).waitFor();assert.equal(record.concept_id,'qa-ph');assert.equal(record.student_id,'qa-student');assert.equal(recordCount,1);assert.ok(await page.getByRole('button',{name:'Yuborilgan',exact:true}).isDisabled());await map();await page.locator('.ch-topic-card').filter({has:page.getByRole('heading',{name:'Ustozning pH tajribasi',exact:true})}).click();assert.ok(await page.getByRole('button',{name:'Yuborilgan',exact:true}).isDisabled());assert.equal(recordCount,1);await page.getByLabel('Nimani kuzatdingiz va nima sababdan?',{exact:true}).fill('Tez chiqishdan oldingi kuzatish.');await page.getByLabel('Sonli taxmin',{exact:true}).fill('2.5');await map();await page.locator('.ch-topic-card').filter({has:page.getByRole('heading',{name:'Ustozning pH tajribasi',exact:true})}).click();assert.equal(await page.getByLabel('Nimani kuzatdingiz va nima sababdan?',{exact:true}).inputValue(),'Tez chiqishdan oldingi kuzatish.');assert.equal(await page.getByLabel('Sonli taxmin',{exact:true}).inputValue(),'2.5');await page.getByLabel('Nimani kuzatdingiz va nima sababdan?',{exact:true}).fill('Kislota miqdorini o‘zgartirdim.');await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));await page.waitForFunction(()=>Object.values(localStorage).some(s=>s.includes('Kislota miqdorini o‘zgartirdim.')));const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Daftarni yuklash',exact:true}).click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'kimyo-kuzatish.txt');
 
 // Dedicated laboratory workbenches: real interactions, completed trial history and per-scene calculations.
 await page.setViewportSize({width:1440,height:1000});
 for(const lab of chemistryLabs){
  await page.getByRole('button',{name:'Tajriba qil',exact:true}).click();assert.equal(await page.locator('.vl-lab-card').count(),13);
  await page.locator('.ch-topic-card').filter({has:page.getByRole('heading',{name:lab.title,exact:true})}).click();
  await page.getByRole('button',{name:'2. Tajribani boshlash',exact:true}).waitFor();assert.ok(await page.getByRole('button',{name:'2. Tajribani boshlash',exact:true}).isDisabled());
  await page.getByRole('button',{name:'1. Tayyorlash',exact:true}).click();await page.getByRole('button',{name:'2. Tajribani boshlash',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.vl-timeline output').textContent!=='0%');await page.getByRole('button',{name:'To‘xtatish',exact:true}).click();
  assert.ok(await page.getByRole('slider',{name:lab.controls[0].label,exact:true}).isDisabled());
  await page.getByRole('slider',{name:'Jarayonning virtual bosqichi',exact:true}).fill('100');await page.locator('.vl-trials tbody tr').waitFor();
  const expected=labResult(lab.scene,Object.fromEntries(lab.controls.map(c=>[c.key,c.initial]))).values;
  const actual=await page.locator('.vl-readings strong').allTextContents();assert.deepEqual(actual,await page.evaluate(values=>values.map(n=>Number(n.toFixed(2)).toLocaleString('uz-UZ')),Object.values(expected)));
  await page.addScriptTag({path:path.join(root,'node_modules/axe-core/axe.min.js')});const violations=await page.evaluate(async()=>(await axe.run('.vl-lab',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})));assert.deepEqual(violations,[],lab.scene);
  if(['lab-volcano','lab-distillation','lab-filtration'].includes(lab.scene))await page.screenshot({path:path.join(out,`${lab.scene}.png`),fullPage:true});
  if(lab.scene==='lab-volcano'){
   await page.getByRole('button',{name:'Reaksiya va atomlar hisobini ochish',exact:true}).click();assert.equal(await page.locator('.vl-chemistry tbody tr').count(),4);
   const dl=page.waitForEvent('download');await page.getByRole('button',{name:'CSV yuklash',exact:true}).click();assert.equal((await dl).suggestedFilename(),'lab-volcano-natijalar.csv');
   await page.getByRole('button',{name:'Qayta tayyorlash',exact:true}).click();await page.getByRole('slider',{name:'Soda miqdori',exact:true}).fill('0');await page.getByRole('button',{name:'1. Tayyorlash',exact:true}).click();await page.getByRole('slider',{name:'Jarayonning virtual bosqichi',exact:true}).fill('100');await page.waitForFunction(()=>document.querySelectorAll('.vl-trials tbody tr').length===2);assert.equal(await page.locator('.vl-readings strong').first().textContent(),'0');assert.match(await page.locator('.vl-cause').innerText(),/hosil bo‘lmaydi/);
  }
 }

 // Let the last scene finish automatically, then verify the timer stops and a new trial is recorded.
 await page.getByRole('button',{name:'Qayta tayyorlash',exact:true}).click();await page.getByRole('slider',{name:'Kislorodning mavjud ulushi',exact:true}).fill('0');await page.getByRole('button',{name:'1. Tayyorlash',exact:true}).click();await page.getByRole('button',{name:'2. Tajribani boshlash',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.vl-timeline output').textContent==='100%',null,{timeout:8000});await page.waitForFunction(()=>document.querySelectorAll('.vl-trials tbody tr').length===2);assert.equal(await page.locator('.vl-readings strong').first().textContent(),'0');assert.ok(await page.getByRole('button',{name:'To‘xtatish',exact:true}).isDisabled());
  await page.getByRole('button',{name:'Tajriba qil',exact:true}).click();await page.locator('.ch-topic-card').filter({has:page.getByRole('heading',{name:chemistryLabs[0].title,exact:true})}).click();assert.equal(await page.locator('.vl-trials tbody tr').count(),2);
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.getByRole('button',{name:'1. Tayyorlash',exact:true}).click();await page.getByRole('slider',{name:'Jarayonning virtual bosqichi',exact:true}).fill('100');await page.screenshot({path:path.join(out,'volcano-mobile.png'),fullPage:true});await page.getByRole('button',{name:'Tungi ko‘rinishga o‘tish',exact:true}).click();await page.screenshot({path:path.join(out,'volcano-dark.png'),fullPage:true});const darkViolations=await page.evaluate(async()=>(await axe.run('.vl-lab',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})).violations.map(v=>v.id));assert.deepEqual(darkViolations,[]);await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Solishtirish jadvalini tozalash',exact:true}).click();assert.equal(await page.locator('.vl-trials tbody tr').count(),0);await page.getByRole('button',{name:'Kunduzgi ko‘rinishga o‘tish',exact:true}).click();
 await map();await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'chemistry-mobile.png'),fullPage:true});await open('periodic');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'periodic-mobile.png'),fullPage:true});await page.getByRole('button',{name:'Tungi ko‘rinishga o‘tish',exact:true}).click();await page.screenshot({path:path.join(out,'chemistry-dark.png'),fullPage:true});
 const teacher=await browser.newPage({viewport:{width:1440,height:1000}});teacher.on('pageerror',e=>errors.push(e.message));await fixture(teacher,'teacher');await teacher.goto('http://127.0.0.1:4175/#kimyo');await teacher.getByRole('button',{name:'Ustoz boshqaruvi',exact:true}).click();await teacher.getByRole('button',{name:'Atom ichiga sayohat',exact:true}).click();await teacher.getByLabel('Mavzu nomi',{exact:true}).fill('Mening atom tajribam');await teacher.getByLabel('To‘g‘ri sonli javob',{exact:true}).fill('');await teacher.getByRole('button',{name:'Adminga tasdiqlash uchun yuborish',exact:true}).click();await teacher.getByText('To‘g‘ri javobni −1000 dan 1000 gacha son bilan kiriting.',{exact:true}).waitFor();assert.equal(save,undefined);await teacher.getByLabel('To‘g‘ri sonli javob',{exact:true}).fill('-2');await teacher.getByRole('button',{name:'Adminga tasdiqlash uchun yuborish',exact:true}).click();await teacher.getByText('Sahna admin tasdig‘iga yuborildi.',{exact:true}).waitFor();assert.equal(save.ownerId,'teacher-one');assert.equal(save.status,'pending');await teacher.getByRole('button',{name:'Kuzatishlar',exact:true}).click();assert.match(await teacher.locator('.ch-stat').innerText(),/1 \/ 1 noto‘g‘ri/);await teacher.screenshot({path:path.join(out,'teacher-observations.png'),fullPage:true});const admin=await browser.newPage({viewport:{width:1440,height:1000}});await fixture(admin,'admin');await admin.goto('http://127.0.0.1:4175/#kimyo');await admin.getByRole('button',{name:'Ustoz boshqaruvi',exact:true}).click();await admin.getByRole('button',{name:'Tasdiqlash',exact:true}).click();await admin.getByText('O‘zgarish saqlandi.',{exact:true}).waitFor();assert.equal(rows.find(r=>r.id==='new-chem').status,'published');
 await teacher.getByRole('button',{name:'Ustoz boshqaruvi',exact:true}).click();await teacher.getByRole('button',{name:chemistryLabs[0].title,exact:true}).click();await teacher.getByLabel('Mavzu nomi',{exact:true}).fill('Ustozning virtual vulqoni');await teacher.getByLabel('Soda miqdori',{exact:true}).fill('9');await teacher.getByRole('button',{name:'Adminga tasdiqlash uchun yuborish',exact:true}).click();await teacher.getByText('Sahna admin tasdig‘iga yuborildi.',{exact:true}).waitFor();assert.equal(save.data.scene,'lab-volcano');assert.equal(save.data.parameters.soda,9);assert.equal(save.status,'pending');
 await admin.getByRole('button',{name:'Mavzular xaritasi',exact:true}).click();await admin.getByRole('button',{name:'Qayta ulanish',exact:true}).count();await admin.reload();await admin.getByRole('button',{name:'Ustoz boshqaruvi',exact:true}).click();await admin.getByRole('button',{name:'Tasdiqlash',exact:true}).click();await admin.getByText('O‘zgarish saqlandi.',{exact:true}).waitFor();assert.equal(rows.find(r=>r.id==='new-chem-lab').status,'published');
 await page.reload();await page.getByRole('button',{name:'Tajriba qil',exact:true}).click();await page.locator('.ch-topic-card').filter({has:page.getByRole('heading',{name:'Ustozning virtual vulqoni',exact:true})}).click();assert.equal(await page.getByRole('slider',{name:'Soda miqdori',exact:true}).inputValue(),'9');
 assert.deepEqual(errors,[]);console.log('PASS 13 labs: stage controls, pause/scrub, limiting reagent, no gas without soda, CSV, persistent comparisons, per-scene calculations, axe, mobile/dark, teacher lab params and admin approval; draft navigation/pagehide flush, restored prediction, duplicate submission guard, empty teacher answer validation, lab empty search, NaCl lattice; chemistry: all 12 scenes, 118 elements, atom/ion, molecule validation and rotation, phase changes, equation balance, pH, rate, separation, student submission, author save, analytics, mobile and dark.');
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e}finally{await browser.close();await server.close()}
})().catch(e=>{console.error(e);process.exit(1)});
