// Run with an installed Playwright browser. APIs are fixtures; no real accounts are changed.
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),out=process.env.QA_ARTIFACT_DIR||'/tmp/sinfquiz-discovery';fs.mkdirSync(out,{recursive:true});
(async()=>{const {createServer}=await import(pathToFileURL(path.join(root,'node_modules/vite/dist/node/index.js'))),{audioMazeLevels,mazePath}=await import(pathToFileURL(path.join(root,'src/audio-maze-content.js')));const server=await createServer({root,server:{host:'127.0.0.1',port:4173,hmr:false}});await server.listen();
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||undefined,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],level=audioMazeLevels[0],walkingRoute=mazePath(level.grid,level.start,level.exit);let result;
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',dialog=>dialog.accept());
async function fixtures(p){await p.addInitScript(()=>{window.__SINFQUIZ_LEGACY_TEST__=true});await p.route(/\/(auth|api)\//,async route=>{const url=new URL(route.request().url()).pathname;let value={};if(url==='/auth/session')value={user:{id:'qa-student',name:'Javlon',role:'student'},csrf:'qa'};if(url==='/api/catalog')value={quizzes:[],lessons:[]};if(url==='/api/audio-maze/active')value={active:[{id:'teacher-one',ownerId:'one',ownerName:'Birinchi ustoz',level},{id:'teacher-two',ownerId:'two',ownerName:'Ikkinchi ustoz',level},{id:'teacher-three',ownerId:'three',ownerName:'Uchinchi ustoz',level:audioMazeLevels[1]}]};if(url==='/api/audio-maze/result'){result=route.request().postDataJSON();value={ok:true}}await route.fulfill({json:value})})}
try{await fixtures(page);await page.goto('http://127.0.0.1:4173');await page.getByRole('button',{name:'Matematika atlasi',exact:true}).click();await page.locator('.lv-ready canvas').waitFor({state:'visible',timeout:20000});await page.screenshot({path:path.join(out,'atlas-desktop.png')});
await page.getByRole('button',{name:'Kubni ochib ko‘rish'}).click();await page.locator('.lv-ready canvas').waitFor({state:'visible'});await page.getByRole('slider',{name:'a uzunlik'}).fill('4');assert.match(await page.locator('.ma-result').innerText(),/V = 64/);await page.getByRole('slider',{name:'Yoyilmani ochish'}).fill('100');await page.screenshot({path:path.join(out,'cube-net.png')});await page.getByRole('button',{name:'Modelni chapga aylantirish'}).click();await page.getByRole('button',{name:'Ko‘ndalang kesimni ko‘rsatish'}).click();await page.getByRole('button',{name:'Chizma',exact:true}).click();assert.ok(await page.locator('.ma-stage svg').isVisible());
await page.getByRole('button',{name:'Xarita',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'atlas-mobile.png')});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.setViewportSize({width:1440,height:1050});
await page.getByRole('button',{name:'Bosh sahifaga chiqish'}).click();await page.getByRole('button',{name:/Inglizcha audio labirint/}).click();await page.locator('.scenic-maze').waitFor({state:'visible',timeout:20000});await page.getByRole('button',{name:/Ikkinchi ustoz/}).click();assert.equal(await page.locator('.am-level-card.chosen').count(),1);await page.screenshot({path:path.join(out,'maze-desktop.png')});
await page.getByRole('button',{name:'Boshlash',exact:true}).click();await page.locator('.scenic-maze').waitFor({state:'visible'});await page.getByRole('button',{name:'O‘yin sozlamalari',exact:true}).click();await page.locator('.scenic-settings').waitFor();await page.locator('.scenic-settings button').click();await page.getByRole('button',{name:'Ovoz effektlari',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Ovoz effektlari',exact:true}).getAttribute('aria-pressed'),'false');await page.screenshot({path:path.join(out,'maze-game.png')});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'maze-mobile.png')});
await page.getByRole('button',{name:'Tungi ko‘rinishga o‘tish',exact:true}).click();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.screenshot({path:path.join(out,'maze-dark.png')});await page.getByRole('button',{name:'Kunduzgi ko‘rinishga o‘tish',exact:true}).click();await page.setViewportSize({width:1440,height:1050});
// Freeze the pursuer while walking the complete fixture route and testing every gate.
const freeze=Date.now();await page.clock.install({time:freeze});await page.clock.pauseAt(freeze+2000);await page.emulateMedia({reducedMotion:'reduce'});let previous=walkingRoute[0];for(const point of walkingRoute.slice(1)){const dx=point[0]-previous[0],dy=point[1]-previous[1];await page.keyboard.press(dx===1?'ArrowRight':dx===-1?'ArrowLeft':dy===1?'ArrowDown':'ArrowUp');await page.waitForFunction(([x,y])=>document.querySelector('.scenic-maze')?.getAttribute('aria-label')?.includes(`${x+1}-ustun, ${y+1}-qatordasiz`)||document.querySelector('[role=dialog]')||document.querySelector('.am-result'),point,{polling:20});const gate=level.gateCells.findIndex(p=>p[0]===point[0]&&p[1]===point[1]);if(gate>=0){await page.getByRole('dialog').waitFor();if(gate===0){await page.locator('.am-options button').nth((level.tasks[gate].answer+1)%3).click();assert.match(await page.locator('.am-feedback').innerText(),/mos kelmadi/);await page.screenshot({path:path.join(out,'maze-question.png')})}await page.locator('.am-options button').nth(level.tasks[gate].answer).click()}previous=point}
await page.getByRole('heading',{name:'Yo‘lni topdingiz!'}).waitFor();assert.equal(result.ownerId,'two');assert.equal(result.correct,level.tasks.length);assert.equal(result.wrong,1);await page.clock.runFor(3000);const time=await page.locator('.am-result-stats').innerText();await page.clock.runFor(3000);assert.equal(await page.locator('.am-result-stats').innerText(),time,'finished time remains fixed');
const fallback=await browser.newPage({viewport:{width:390,height:844}});await fixtures(fallback);await fallback.addInitScript(()=>Object.defineProperty(window,'WebGLRenderingContext',{value:undefined}));await fallback.goto('http://127.0.0.1:4173/#audio-maze');await fallback.locator('.scenic-maze').waitFor();await fallback.getByRole('button',{name:'Boshlash',exact:true}).click();await fallback.getByRole('img',{name:/Labirint\./}).waitFor({state:'attached'});await fallback.screenshot({path:path.join(out,'fallback.png'),fullPage:true});await fallback.getByRole('img',{name:/Labirint\./}).waitFor();assert.ok(await fallback.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS: WebGL models, cube volume/net/section, mobile layouts, dark mode, SVG fallback, full maze route, incorrect-answer feedback, all gates, fixed result time, teacher ownership.');
}catch(error){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw error}finally{await browser.close();await server.close()}})().catch(e=>{console.error(e);process.exit(1)});
