const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
(async()=>{
 const root=path.resolve(__dirname,'..'),load=f=>import(pathToFileURL(path.join(root,f))),out=path.join(root,'qa-7.23.1','regression');fs.mkdirSync(out,{recursive:true});
 const {englishDb,ids}=await load('tests/english-fixture.js'),ctx=await englishDb(),{db,rpc,raw}=ctx;const {createServer}=await load('node_modules/vite/dist/node/index.js');const server=await createServer({root,server:{host:'127.0.0.1',port:4183,hmr:false}});await server.listen();
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE,args:['--no-sandbox','--no-zygote','--single-process','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['microphone']});let queue=Promise.resolve();const errors=[],axeResults=[],requests=[];const serial=(uid,fn)=>{const task=queue.then(async()=>{await ctx.login(uid);return fn()});queue=task.catch(()=>{});return task};
 const make=async(uid,role)=>{const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.addInitScript(()=>{window.__SINFQUIZ_LEGACY_TEST__=true;localStorage.setItem('sq_theme','light')});await page.route(/\/(auth|api)\//,async route=>{const pathname=new URL(route.request().url()).pathname,p=route.request().method()==='POST'?route.request().postDataJSON():{};requests.push(pathname);let data={},status=200;try{if(pathname==='/auth/session')data={user:{id:uid,role,name:role==='teacher'?'Ustoz':'Lola'},csrf:'fixture'};else if(pathname==='/api/catalog')data={quizzes:[],lessons:[]};else if(pathname==='/api/quizzes')data={quizzes:[],publicQuizzes:[],lessons:[],players:[],results:[],typing:{texts:[],results:[],active:false},race:{active:false}};else if(pathname.startsWith('/api/english/'))data=await serial(uid,()=>rpc(pathname.split('/').at(-1),p));}catch(e){data={error:e.message};status=400}await route.fulfill({status,json:data})});return page};
 const shot=async(p,name)=>{await p.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await p.screenshot({path:path.join(out,name+'.png'),fullPage:true})};const overflow=async p=>assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'viewport fits');
 const axe=async(p,name)=>{await p.addScriptTag({path:path.join(root,'node_modules/axe-core/axe.min.js')});const violations=await p.evaluate(async()=>(await axe.run('.en-course',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})));axeResults.push({name,violations});assert.deepEqual(violations,[],name)};
 let page;
 try{
  const p=await make(ids.student,'student');page=p;await p.goto('http://127.0.0.1:4183/#ingliz-darsi');await p.getByRole('button',{name:'Darajamni aniqlash',exact:true}).waitFor();await overflow(p);await axe(p,'home desktop');await shot(p,'english-home-desktop');
  await p.getByRole('button',{name:'Darajamni aniqlash',exact:true}).click();for(let i=0;i<4;i++)await p.getByRole('button',{name:'Bilmayman · o‘tkazib yuborish',exact:true}).click();await p.getByRole('heading',{name:'Tavsiya: PRE',exact:true}).waitFor();await shot(p,'placement-result');await p.getByLabel('Matningiz',{exact:true}).fill('A placement draft is saved in the same account.');await p.getByRole('button',{name:'Birinchi darsimni boshlash',exact:true}).click();await p.getByRole('heading',{name:'Harf, tovush va ismni harflab aytish',exact:true}).waitFor();await p.getByRole('button',{name:'Darsni saqlab chiqish',exact:true}).click();
  await p.getByRole('button',{name:'O‘quv xaritasi',exact:true}).click();await p.locator('.en-levels').getByRole('button',{name:'C1',exact:true}).click();await p.locator('.en-lesson-map article').first().getByRole('button').click();await p.getByRole('alert').filter({hasText:'Dars yopiq'}).waitFor();assert.equal(await p.locator('.en-lesson').count(),0);
  await p.locator('.en-levels').getByRole('button',{name:'Tayyorlov',exact:true}).click();await p.locator('.en-lesson-map article').first().getByRole('button',{name:'Ochish',exact:true}).click();await p.getByRole('heading',{name:'Harf, tovush va ismni harflab aytish',exact:true}).waitFor();await p.getByRole('button',{name:'Misollarni ko‘rdim · davom etish',exact:true}).click();await p.getByRole('button',{name:'Birikmalarni ko‘rdim · mashq qilish',exact:true}).click();
  const model=await serial(ids.student,()=>raw('en-pre-01'));const first=p.locator('.en-exercise').first();await first.locator('input[type=radio]').first().check();await first.getByRole('button',{name:'Tekshirish',exact:true}).click();await first.locator('[role=status]').waitFor();await first.getByRole('button',{name:'Ishora',exact:true}).click();await first.getByText(/Ishora:/).waitFor();
  const order=p.locator('.en-exercise').filter({hasText:'Kartalarni to‘g‘ri tartibga qo‘ying.'});for(const t of model.exercises.find(e=>e.type==='order').tokens)await order.locator('.en-token-list').getByRole('button',{name:t,exact:true}).first().click();await order.getByRole('button',{name:'Tekshirish',exact:true}).click();await order.getByText('To‘g‘ri.',{exact:true}).waitFor();
  await p.locator('.en-steps').getByRole('button',{name:'Tinglash',exact:false}).click();const audio=p.locator('.en-audio').first();await audio.getByRole('button',{name:'Tinglash',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.en-audio audio')?.duration>0);assert.ok(await p.evaluate(()=>!document.querySelector('.en-audio audio').paused));await audio.getByRole('button',{name:'To‘xtatish',exact:true}).click();await p.evaluate(()=>{const a=document.querySelector('.en-audio audio');a.currentTime=a.duration-.2;return a.play()});await p.getByText('Yozuv yakunigacha tinglandi. Javoblarni tekshiring.').waitFor();
  await p.locator('.en-steps').getByRole('button',{name:'Yozish',exact:false}).click();await p.getByLabel('Matningiz',{exact:true}).fill('My original draft is saved across a refresh.');await p.waitForTimeout(2000);await p.reload();await p.getByLabel('Matningiz',{exact:true}).waitFor();assert.equal(await p.getByLabel('Matningiz',{exact:true}).inputValue(),'My original draft is saved across a refresh.');await p.getByLabel('Matningiz',{exact:true}).fill('<img src=x onerror=window.__xss=1> My revised draft.');
  await p.locator('.en-steps').getByRole('button',{name:'Gapirish',exact:false}).click();await p.getByRole('button',{name:'Ovoz yozish',exact:true}).click();await p.getByRole('button',{name:/To‘xtatish ·/}).waitFor();await p.waitForTimeout(500);await p.getByRole('button',{name:/To‘xtatish ·/}).click();await p.getByRole('button',{name:'Yozuvni yuborish',exact:true}).waitFor();assert.equal(requests.filter(v=>v.includes('upload')).length,0);assert.ok(await p.locator('.en-recorder audio').count());
  await p.getByRole('button',{name:'Darsni saqlab chiqish',exact:true}).click();await p.getByRole('heading',{name:/Noldan C1/}).waitFor();assert.equal(await p.evaluate(()=>window.__xss),undefined);assert.equal(await p.locator('.en-work img').count(),0);
  await p.setViewportSize({width:390,height:844});await overflow(p);await axe(p,'home mobile');await shot(p,'english-home-mobile');await p.getByRole('button',{name:'Mening lug‘atim',exact:true}).click();await p.getByRole('heading',{name:'Mening lug‘atim',exact:true}).waitFor();await p.getByRole('button',{name:'Bugungi dars',exact:true}).click();await p.getByRole('button',{name:'Davom etish',exact:true}).click();await p.locator('.en-steps').getByRole('button',{name:'O‘qish',exact:false}).click();await overflow(p);await axe(p,'reading mobile');await shot(p,'english-reading-mobile');await p.evaluate(()=>document.documentElement.dataset.theme='dark');await axe(p,'reading dark');await shot(p,'english-reading-dark');await p.setViewportSize({width:1920,height:1080});await overflow(p);await shot(p,'english-reading-board');
  console.log('PASS student placement, gate, audio, draft, microphone, mobile and dark');
  const t=await make(ids.teacher,'teacher');page=t;await t.goto('http://127.0.0.1:4183/#ingliz-darsi');await t.getByRole('button',{name:'Ustoz boshqaruvi',exact:true}).click();await t.getByRole('heading',{name:'Ustoz boshqaruvi',exact:true}).waitFor();await t.getByLabel('Guruh',{exact:true}).selectOption(ids.group);await t.getByLabel('Dars va kontent versiyasi',{exact:true}).selectOption('en-pre-01');await t.getByRole('button',{name:'Dars biriktirish',exact:true}).click();await t.getByText('O‘zgarish saqlandi.',{exact:true}).waitFor();await t.getByRole('button',{name:'Tanlangan darsni tahrirlash',exact:true}).click();await t.getByLabel('Sarlavha',{exact:true}).fill('Ustozning test nusxasi');await t.getByLabel('Holat',{exact:true}).selectOption('published');await t.getByRole('button',{name:'Yangi versiyani saqlash',exact:true}).click();await t.getByText('O‘zgarish saqlandi.',{exact:true}).waitFor();await overflow(t);await axe(t,'teacher desktop');await shot(t,'english-teacher-desktop');
  const source=await serial(ids.teacher,()=>raw('en-pre-01'));await serial(ids.teacher,async()=>{await rpc('override',{studentId:ids.student,level:0,threshold:80,reason:'Jonli baholashda boshlang‘ich qadam tavsiya qilindi.'})});
  await serial(ids.student,async()=>{const d=await rpc('begin',{baseId:source.id});await rpc('save',{id:d.run.id,completed:['learn','vocabulary','listening'],writing:source.writing.model,speaking:{mode:'live',note:'Ustoz bilan sinfdagi amaliy suhbat'}});for(const q of [...source.exercises,...source.reading.questions,...source.listening.questions])await rpc('attempt',{id:d.run.id,questionId:q.id,answer:['matching','table','collocation'].includes(q.type)?q.answers:q.answers[0],heard:Boolean(q.audio)});await rpc('exit',{id:d.run.id,answers:Object.fromEntries(source.exit[0].map(q=>[q.id,q.answers[0]]))});await rpc('submit',{id:d.run.id})});
  await t.reload();await t.getByRole('button',{name:'Ustoz boshqaruvi',exact:true}).click();await t.locator('.en-review-item').first().click();const fields=t.locator('.en-review fieldset select');for(let i=0;i<8;i++)await fields.nth(i).selectOption('4');await t.getByLabel('Feedback: yaxshi tomoni, tuzatish va keyingi amal',{exact:true}).fill('Misollar aniq va vaziyatga mos. Keyingi darsda talaffuzni mashq qiling.');await t.getByRole('button',{name:'Rubrika bahosini saqlash',exact:true}).click();await t.getByText('O‘zgarish saqlandi.',{exact:true}).waitFor();assert.ok((await serial(ids.student,()=>rpc('home'))).lessons.find(l=>l.id==='en-pre-02').open);console.log('PASS teacher assignment, version and rubric review');
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'english-browser.json'),JSON.stringify({passed:true,errors,requests:requests.length,checks:['mandatory adaptive placement','direct locked gate','word order','hint feedback','local MP3 playback and ended evidence','server writing refresh (local PostgreSQL RPC fixture)','microphone explicit action and no automatic upload','XSS escaped text','teacher assignment','immutable content version','rubric mastery','mobile 390','desktop 1440','board 1920','dark mode']},null,2));fs.writeFileSync(path.join(out,'accessibility.json'),JSON.stringify(axeResults,null,2));
 }catch(e){if(page){await shot(page,'failure').catch(()=>{});fs.writeFileSync(path.join(out,'failure.txt'),e.stack+'\n'+await page.locator('body').innerText().catch(()=>''))}throw e}finally{await browser.close();await server.close();await db.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
