import {PGlite} from '@electric-sql/pglite';import {readFileSync} from 'node:fs';
export const ids={teacher:'72300000-0000-0000-0000-000000000001',other:'72300000-0000-0000-0000-000000000002',admin:'72300000-0000-0000-0000-000000000003',student:'72300000-0000-0000-0000-000000000004',stranger:'72300000-0000-0000-0000-000000000005',group:'72310000-0000-0000-0000-000000000001',otherGroup:'72310000-0000-0000-0000-000000000002'};
export async function englishDb(){
 const db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create table public.documents(collection text,id text,data jsonb,primary key(collection,id));create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.uid',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;create function public.sq_is_admin() returns boolean language sql stable as $$select coalesce(auth.uid()='${ids.admin}'::uuid,false)$$;create function public.sq_is_teacher() returns boolean language sql stable security definer as $$select coalesce(auth.uid() in ('${ids.teacher}'::uuid,'${ids.other}'::uuid,'${ids.admin}'::uuid),false)$$;create table public.sq_class_groups(id uuid primary key,owner_id uuid,title text,join_code text,active boolean default true);create table public.sq_class_members(group_id uuid,student_id uuid,student_name text,primary key(group_id,student_id));create schema storage;grant usage on schema storage to authenticated;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;grant select,insert,delete on storage.objects to authenticated;`);
 for(const id of Object.values(ids).slice(0,5))await db.query('insert into auth.users values($1)',[id]);
 await db.query('insert into public.sq_class_groups values($1,$2,$3,$4,true),($5,$6,$7,$8,true)',[ids.group,ids.teacher,'English group','AAAAAAAAAA',ids.otherGroup,ids.other,'Other group','BBBBBBBBBB']);await db.query('insert into public.sq_class_members values($1,$2,$3)',[ids.group,ids.student,'Lola']);
 const migration=readFileSync(new URL('../supabase-migration-7.23.sql',import.meta.url),'utf8');await db.exec(migration);await db.exec(migration);
 const login=async id=>{await db.exec('reset role');await db.query("select set_config('request.uid',$1,false)",[id]);await db.exec('set role authenticated')};
 const rpc=async(a,p={})=>(await db.query('select public.sq_en($1,$2) result',[a,JSON.stringify(p)])).rows[0].result;
 const owner=async fn=>{await db.exec('reset role');try{return await fn()}finally{await db.exec('set role authenticated')}};
 const raw=async(id,revision=1)=>owner(async()=>(await db.query('select payload from public.sq_en_content where id=$1 and revision=$2',[id,revision])).rows[0].payload);
 return {db,login,rpc,owner,raw};
}
