import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';import {createHash} from 'node:crypto';import {lessons,levels,counts} from '../data/english-course/index.js';import {englishDb,ids} from './english-fixture.js';
const noKeys=x=>{if(Array.isArray(x))return x.every(noKeys);if(!x||typeof x!=='object')return true;return !Object.hasOwn(x,'answers')&&!Object.hasOwn(x,'hint')&&Object.values(x).every(noKeys)};
test('7.23: 108 complete original lessons, all exercise formats and transcript audio integrity',()=>{
 assert.equal(lessons.length,108);assert.equal(new Set(lessons.map(l=>l.id)).size,108);assert.equal(new Set(lessons.map(l=>l.reading.text)).size,108);assert.equal(new Set(lessons.map(l=>l.writing.model)).size,108);
 assert.deepEqual(levels.map(level=>lessons.filter(l=>l.level===level).length),counts);
 const types=new Set();for(const l of lessons){assert.equal(l.examples.length,6);assert.equal(l.visuals.length,2);if(l.visuals[0].kind==='timeline')assert.equal(l.visuals[0].timeline.length,2);if(l.order%4===0){assert.equal(l.recapQuestions.length,3);assert.ok(l.recapQuestions.every(q=>q.recap&&q.sourceLesson));}assert.equal(l.exit.length,2);assert.ok(l.rules.length>=3);assert.ok(l.reading.text.length>100);assert.ok(l.writing.model.length>50);assert.ok(l.sources.length>=2);assert.ok(l.speaking.task);assert.ok(l.reading.questions.length>=3);assert.ok(l.listening.questions.length>=4);assert.ok(l.writing.model.split(/\s+/).length>=l.writing.minWords,l.id);for(const q of [...l.exercises,...l.reading.questions,...l.listening.questions,...l.exit.flat()]){types.add(q.type);assert.ok(q.answers.length&&q.explanation,q.id);if(q.type==='choice')assert.ok(q.options.includes(q.answers[0]),q.id);if(q.type==='evidence')assert.ok(q.options[+q.answers[0]],q.id)}}
 for(const t of ['choice','grammarFill','matching','order','picture','correction','transformation','dialogue','dictation','table','paragraphOrder','collocation','register','paraphrase','evidence'])assert.ok(types.has(t),t);
 const manifest=JSON.parse(readFileSync(new URL('../public/english-course/v7.23/manifest.json',import.meta.url)));assert.equal(manifest.length,216);for(const f of manifest){const data=readFileSync(new URL('../public/english-course/v7.23/'+f.file,import.meta.url));assert.equal(createHash('sha256').update(data).digest('hex'),f.audioSha256);assert.equal(createHash('sha256').update(f.transcript).digest('hex'),f.transcriptSha256);assert.ok(f.seconds>1);const l=lessons.find(l=>f.file.startsWith(l.id+'.')||f.file.startsWith(l.id+'-dictation'));assert.equal(f.transcript,f.file.includes('dictation')?l.pronunciation.text:l.listening.transcript)}
});
test('7.23: mandatory placement, balanced low-level stop, UID persistence, high placement pending human evidence and locked RPCs',async()=>{
 const {db,login,rpc,owner}=await englishDb();try{
  const keys=await owner(()=>db.query("select count(*) failures from public.sq_en_content c cross join lateral jsonb_array_elements((c.payload->'exercises')||(c.payload->'reading'->'questions')||(c.payload->'listening'->'questions')||(c.payload->'exit'->0)||(c.payload->'exit'->1)) q where not public.sq_en_grade(q.value,case when q.value->>'type' in ('matching','table','collocation') then q.value->'answers' else q.value->'answers'->0 end)"));assert.equal(Number(keys.rows[0].failures),0,'every accepted answer in all 108 lessons must grade correctly');
  await login(ids.student);assert.equal((await rpc('home')).lessons.filter(l=>l.open).length,0);await assert.rejects(rpc('begin',{baseId:'en-pre-01'}),/Dars yopiq/);
  let c=await rpc('checkStart',{kind:'placement'});assert.ok(noKeys(c));assert.equal(c.total,24);assert.equal((await rpc('checkStart',{kind:'placement'})).id,c.id);
  for(let i=0;i<4;i++)c=await rpc('checkAnswer',{id:c.id,cursor:i,skip:true});assert.equal(c.status,'objective_complete');assert.equal(c.result.recommended,0);assert.ok(Object.values(c.result.skills).every(v=>v.total===1));await rpc('checkSave',{id:c.id,writing:'A placement draft is kept in this account.',speaking:{}});assert.equal((await rpc('home')).checks[0].state.writing,'A placement draft is kept in this account.');const h=await rpc('home');assert.equal(h.profile.open_level,0);assert.equal(h.lessons.filter(l=>l.open).length,1);await assert.rejects(rpc('begin',{baseId:'en-c1-01'}));
  await assert.rejects(db.query('update public.sq_en_profiles set open_level=5'));await assert.rejects(db.query('select * from public.sq_en_content'));await assert.rejects(db.query("select public.sq_en_grade('{}','\"x\"')"));
  await login(ids.stranger);await assert.rejects(rpc('checkSave',{id:c.id,writing:'Someone else tries to edit.'}),/tahrirlab/);assert.equal((await rpc('home')).profile.placement_complete,false);c=await rpc('checkStart',{kind:'placement'});
  for(let i=0;i<24;i++){const bank=await owner(async()=>(await db.query('select bank from public.sq_en_checks where id=$1',[c.id])).rows[0].bank);const q=bank.questions[i];c=await rpc('checkAnswer',{id:c.id,cursor:i,answer:['matching','table','collocation'].includes(q.type)?q.answers:q.answers[0],heard:true});if(c.status!=='started')break}
  assert.equal(c.result.recommended,5);assert.equal((await rpc('home')).profile.open_level,2);await assert.rejects(rpc('begin',{baseId:'en-c1-01'}));
  await login(ids.teacher);assert.equal((await rpc('teacher')).checks.length,1);await assert.rejects(rpc('override',{studentId:ids.stranger,level:5,reason:'Sinov sababi yetarli va aniq'}));await login(ids.other);assert.equal((await rpc('teacher')).runs.length,0);assert.equal((await rpc('teacher')).checks.length,0);
 }finally{await db.close()}
});
async function finish(ctx,base='en-pre-01'){
 const {rpc,raw}=ctx;const d=await rpc('begin',{baseId:base}),l=await raw(base);
 await rpc('save',{id:d.run.id,step:3,completed:[],writing:'Draft'});
 await assert.rejects(rpc('attempt',{id:d.run.id,questionId:l.listening.questions[0].id,answer:l.listening.questions[0].answers[0]}),/audioni/);
 await rpc('save',{id:d.run.id,completed:['learn','vocabulary','listening'],writing:l.writing.model,speaking:{mode:'live',note:'Ustoz bilan sinfda ertaga suhbat va javob tekshiruvi'}});
 for(const q of [...l.exercises,...l.reading.questions,...l.listening.questions])await rpc('attempt',{id:d.run.id,questionId:q.id,answer:['table','matching','collocation'].includes(q.type)?q.answers:q.answers[0],heard:Boolean(q.audio)});
 const answers=Object.fromEntries(l.exit[0].map(q=>[q.id,q.answers[0]]));assert.equal((await rpc('exit',{id:d.run.id,answers})).score,100);return rpc('submit',{id:d.run.id});
}
test('7.23: lesson evidence, idempotent grades, review gating, revisions, versions, teacher isolation and private audio',async()=>{
 const ctx=await englishDb(),{db,login,rpc,raw,owner}=ctx;try{
  await login(ids.student);let c=await rpc('checkStart',{kind:'placement'});for(let i=0;i<4;i++)c=await rpc('checkAnswer',{id:c.id,cursor:i,skip:true});
  const d=await rpc('begin',{baseId:'en-pre-01'}),l=await raw('en-pre-01');await assert.rejects(rpc('save',{id:d.run.id,writing:null}),/qoralama/);assert.ok(noKeys(d.lesson));const token=crypto.randomUUID();const p={id:d.run.id,questionId:l.exercises[0].id,answer:l.exercises[0].answers[0],token};const a=await rpc('attempt',p);assert.equal(a.correct,true);assert.deepEqual(await rpc('attempt',p),a);
  let r=await finish(ctx);assert.equal(r.status,'submitted');await assert.rejects(rpc('exit',{id:r.id,answers:{}}),/Topshirilgan/);await assert.rejects(rpc('attempt',{id:r.id,questionId:l.exercises[0].id,answer:l.exercises[0].answers[0]}),/Topshirilgan/);await assert.rejects(rpc('begin',{baseId:'en-pre-02'}));await assert.rejects(rpc('review',{id:r.id,grades:{writing:[5,5,5,5],speaking:[5,5,5,5]},feedback:'O‘zim to‘liq baholadim.'}));
  await login(ids.other);await assert.rejects(rpc('review',{id:r.id,grades:{writing:[5,5,5,5],speaking:[5,5,5,5]},feedback:'Noto‘g‘ri ustozdan baho.'}));
  await login(ids.teacher);let rev=await rpc('review',{id:r.id,grades:{writing:[2,2,2,2],speaking:[4,4,4,4]},feedback:'Yozuvni o‘zingizdan misol bilan qayta ishlang.'});assert.equal(rev.status,'needs_revision');
  await login(ids.student);await rpc('resubmit',{id:r.id,writing:l.writing.model,speaking:r.state.speaking});r=await rpc('submit',{id:r.id});await login(ids.teacher);rev=await rpc('review',{id:r.id,grades:{writing:[4,4,4,4],speaking:[4,4,4,4]},feedback:'Vazifa, tushunarlilik va til vositalari mezonga yetdi.'});assert.equal(rev.status,'mastered');
  await login(ids.student);assert.ok((await rpc('begin',{baseId:'en-pre-02'})).run);await assert.rejects(rpc('checkStart',{kind:'level',level:0}),/barcha darslarni/);
  await login(ids.teacher);await assert.rejects(rpc('contentSave',{payload:{id:l.id,baseId:l.id,writing:{task:'text'},speaking:{task:'text'}},status:'published'}),/to‘liq/);await assert.rejects(rpc('review',{id:r.id,grades:{},feedback:'Bu rubrika bo‘sh, shu sababli rad qilinishi kerak.'}),/rubrikalari/);const edited={...l,title:'Ustozning shaxsiy nusxasi'};const version=await rpc('contentSave',{payload:edited,status:'published'});await rpc('assign',{groupId:ids.group,contentId:version.id,revision:version.revision,threshold:90});await login(ids.other);assert.ok(!(await rpc('teacher')).content.some(c=>c.id===version.id));await assert.rejects(rpc('assign',{groupId:ids.group,contentId:version.id,revision:1,threshold:80}));
  await login(ids.student);const assigned=(await rpc('home')).assignments[0];const v=await rpc('begin',{baseId:l.id,assignmentId:assigned.id});assert.equal(v.lesson.title,edited.title);await login(ids.teacher);await rpc('contentSave',{payload:{...edited,title:'Yangi ikkinchi nusxa'},status:'published'});await login(ids.student);assert.equal((await rpc('begin',{baseId:l.id,assignmentId:assigned.id})).lesson.title,edited.title);
  const path=ids.student+'/'+v.run.id+'/clip.webm';await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['english-recordings',path]);await login(ids.stranger);assert.equal((await db.query('select * from storage.objects')).rows.length,0);await assert.rejects(db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['english-recordings',path+'/evil']));await login(ids.teacher);assert.equal((await db.query('select * from storage.objects')).rows.length,1);await login(ids.other);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 }finally{await db.close()}
});
test('7.23: normalized apostrophes and case do not erase missing grammar; server level review requires all skills',async()=>{
 const {db,owner}=await englishDb();try{
 const grade=async(a,b)=>(await owner(()=>db.query('select public.sq_en_grade($1,$2) v',[JSON.stringify({type:'grammarFill',answers:a}),JSON.stringify(b)]))).rows[0].v;
 assert.equal(await grade(["I can't go."],'I CAN’T go!'),true);assert.equal(await grade(['She does not go.'],'She not go.'),false);assert.equal(await grade(['He has worked.'],'He worked.'),false);assert.equal(await grade(['I am here.',"I'm here."],"I'm here"),true);
 }finally{await db.close()}
});
test('7.23: anonymous UID joins course class without registering; final checks alternate and objective results alone never unlock the next level',async()=>{
 const ctx=await englishDb(),{db,login,rpc,owner}=ctx;try{
  await login(ids.stranger);await rpc('joinGroup',{code:'AAAAAAAAAA',name:'Mehmon o‘quvchi'});await login(ids.teacher);assert.ok((await rpc('teacher')).students.some(s=>s.id===ids.stranger));await rpc('override',{studentId:ids.student,level:0,threshold:80,reason:'Jonli boshlang‘ich baholash bilan joylashtirildi.'});
  for(let i=1;i<=6;i++){await login(ids.student);const r=await finish(ctx,'en-pre-'+String(i).padStart(2,'0'));await login(ids.teacher);await rpc('review',{id:r.id,grades:{writing:[4,4,4,4],speaking:[4,4,4,4]},feedback:'Vazifa bajarildi va suhbat tushunarli. Keyingi qadamga tayyor.'})}
  await login(ids.student);let c=await rpc('checkStart',{kind:'level',level:0});const firstId=c.question.id;assert.equal(c.variant,0);for(let i=0;i<c.total;i++){c=await rpc('checkAnswer',{id:c.id,cursor:i,skip:true});if(c.status!=='started')break}assert.equal((await rpc('home')).profile.open_level,0);
  c=await rpc('checkSubmit',{id:c.id,writing:'My name is Lola. I can spell my name and follow the task.',speaking:{mode:'live',note:'Ustoz bilan sinfda yakuniy suhbat'}});await login(ids.teacher);let reviewed=await rpc('review',{id:c.id,kind:'check',grades:{writing:[5,5,5,5],speaking:[5,5,5,5]},feedback:'Amaliy namuna yaxshi, lekin obyektiv savollar qayta ishlansin.'});assert.equal(reviewed.status,'needs_revision');
  await owner(()=>db.query("update public.sq_en_checks set created_at=now()-interval '1 minute' where id=$1",[c.id]));await login(ids.student);c=await rpc('checkStart',{kind:'level',level:0});assert.equal(c.variant,1);assert.notEqual(c.question.id,firstId);
  const bank=await owner(async()=>(await db.query('select bank from public.sq_en_checks where id=$1',[c.id])).rows[0].bank);
  for(let i=0;i<bank.questions.length;i++){const q=bank.questions[i];c=await rpc('checkAnswer',{id:c.id,cursor:i,answer:['matching','table','collocation'].includes(q.type)?q.answers:q.answers[0],heard:true})}assert.equal((await rpc('home')).profile.open_level,0);
  await rpc('checkSubmit',{id:c.id,writing:'My name is Lola. I am a student, and I can follow the lesson.',speaking:{mode:'live',note:'Ustoz bilan yakuniy amaliy suhbat o‘tkaziladi'}});await login(ids.teacher);reviewed=await rpc('review',{id:c.id,kind:'check',grades:{writing:[4,4,4,4],speaking:[4,4,4,4]},feedback:'To‘rt ko‘nikma dalili va rubrika mezoniga mos natija olindi.'});assert.equal(reviewed.status,'mastered');await login(ids.student);const h=await rpc('home');assert.equal(h.profile.open_level,1);assert.ok(h.lessons.find(l=>l.id==='en-a1-01').open);assert.ok(!h.lessons.find(l=>l.id==='en-a1-02').open);
 }finally{await db.close()}
});
