// Actual Chromium -> React -> RPC SQL on a local Postgres engine.
// API interception adapts the fixture transport; it does not invent scores.
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
(async()=>{
 const root=path.resolve(__dirname,'..'),load=f=>import(pathToFileURL(path.join(root,f))),out=process.env.LEARNING_QA_DIR||path.join(root,'qa-7.25/browser');fs.mkdirSync(out,{recursive:true});
 const {englishDb,ids}=await load('tests/english-fixture.js'),ctx=await englishDb();
 for(const f of ['01-schema.sql','02-iq-band-1.sql','03-iq-band-2.sql','04-iq-band-3.sql','05-book-keys.sql'])await ctx.db.exec(fs.readFileSync(path.join(root,'sql/7.25',f),'utf8'));
 for(const [role,id] of [['student',ids.student],['teacher',ids.teacher],['teacher',ids.other],['admin',ids.admin]])await ctx.db.query('insert into public.documents values($1,$2,$3)',['profiles',id,JSON.stringify({role,name:'Lola'})]);
 const {createServer}=await load('node_modules/vite/dist/node/index.js'),server=await createServer({root,server:{host:'127.0.0.1',port:4195,hmr:false}});await server.listen();
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE,args:['--no-sandbox','--no-zygote','--single-process','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),errors=[],axeChecks=[],calls=[],results={};let queue=Promise.resolve(),brokenAnswer=false,page;
 const sql=(uid,name,action,p)=>{const job=queue.then(async()=>{await ctx.login(uid);try{return (await ctx.db.query(`select public.${name}($1,$2::jsonb) value`,[action,JSON.stringify(p)])).rows[0].value}finally{await ctx.db.exec('reset role')}});queue=job.catch(()=>{});return job};
 const evil={id:'evil-public',title:'<img src=x onerror=window.__xss=1> Ustoz darsi',subject:'Kimyo',summary:'Matn sifatida ko‘rinadi',content:'## Tekshiruv\n<script>window.__xss=1</script>',ownerId:ids.teacher,ownerName:'Ustoz',visibility:'public',updatedAt:Date.now()};
 const make=async(uid,role)=>{const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.addInitScript(()=>{window.__SINFQUIZ_LEGACY_TEST__=true;localStorage.setItem('sq_theme','light')});await p.route(/\/(auth|api)\//,async route=>{
  const name=new URL(route.request().url()).pathname,body=route.request().method()==='POST'?route.request().postDataJSON():{};calls.push({name,uid,body});let data={},status=200;
  try{if(name==='/auth/session')data={user:{id:uid,role,name:role==='student'?'Lola':'Ustoz'},csrf:'fixture'};
   else if(name==='/api/catalog')data={lessons:[evil],quizzes:[]};
   else if(name==='/api/lessons')data={lessons:[]};
   else if(name==='/api/quizzes')data={quizzes:[],publicQuizzes:[],lessons:[],players:[],typing:{active:false,results:[]},race:{active:false}};
   else if(name.startsWith('/api/iq/')){if(brokenAnswer&&name.endsWith('/answer')){brokenAnswer=false;await route.abort('failed');return}data=await sql(uid,'sq_iq',name.split('/').at(-1),body)}
   else if(name.startsWith('/api/books/'))data=await sql(uid,'sq_books',name.split('/').at(-1),body);
   else if(name.startsWith('/api/english/'))data=await sql(uid,'sq_en',name.split('/').at(-1),body);
   else if(name==='/api/biology/concepts'||name==='/api/chemistry/concepts')data=[];
   else if(name==='/api/race/active'||name==='/api/typing/active')data={active:false};
  }catch(e){status=400;data={error:e.message,code:e.code}}
  await route.fulfill({status,json:data});
 });return p};
 const shot=async(p,name)=>{await p.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await p.screenshot({path:path.join(out,name+'.png'),fullPage:true})};
 const fits=async p=>assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'page fits viewport');
 const axe=async(p,label,scope='.sq-learning')=>{await p.addScriptTag({path:path.join(root,'node_modules/axe-core/axe.min.js')});const violations=await p.evaluate(async scope=>(await window.axe.run(scope,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),scope);axeChecks.push({label,violations});assert.deepEqual(violations,[],label)};
 try{
  page=await make(ids.student,'student');await page.goto('http://127.0.0.1:4195');await page.locator('.study-menu').getByRole('button',{name:/^Darsliklar/}).click();await page.getByRole('heading',{name:'Darsliklar, bitta joyda.'}).waitFor();assert.equal(await page.locator('.book-subjects button').count(),4);assert.equal(await page.locator('.book-section').count(),4);assert.match(await page.locator('.book-subjects').innerText(),/108 dars/);await fits(page);await axe(page,'library desktop');await shot(page,'library-desktop');
  await page.getByLabel('Dars yoki mavzu qidirish').fill('Atom ichiga');await page.locator('.book-section li button').first().click();await page.getByRole('heading',{name:'Atom ichiga sayohat',exact:true}).waitFor();await page.getByRole('radio',{name:'15',exact:true}).check();await page.getByRole('button',{name:'Bilimni tekshirish',exact:true}).click();await page.getByRole('status').filter({hasText:'To‘g‘ri.'}).waitFor();await page.waitForTimeout(4700);assert.ok(calls.some(c=>c.name==='/api/books/mark'&&c.body.id==='book-chemistry-atom'));await axe(page,'chemistry reader');await shot(page,'chemistry-book-desktop');
  await page.getByRole('button',{name:'Darsliklarga qaytish',exact:true}).click();await page.getByLabel('Dars yoki mavzu qidirish').fill('fotosintez');await page.locator('.book-section li button').filter({hasText:'Fotosintez: kirish va chiqish'}).click();await page.getByRole('heading',{name:'Fotosintez: kirish va chiqish',exact:true}).waitFor();await page.setViewportSize({width:390,height:844});await fits(page);await axe(page,'biology reader mobile');await shot(page,'biology-book-mobile');
  await page.getByRole('button',{name:'Darsliklarga qaytish',exact:true}).click();await page.getByLabel('Dars yoki mavzu qidirish').fill('onerror');assert.equal(await page.locator('.book-section img').count(),0);assert.equal(await page.evaluate(()=>window.__xss),undefined);await page.getByLabel('Dars yoki mavzu qidirish').fill('Python bilan tanishuv');await page.locator('.book-section li button').first().click();await page.getByRole('heading',{name:'Python bilan tanishuv',exact:true}).waitFor();await page.getByRole('button',{name:'Amaliyot oynasini ochish'}).click();await page.getByLabel('Python kodi').fill('print(6 * 7)');await page.getByRole('button',{name:'Kodni ishga tushirish',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.py-output pre')?.textContent.trim()==='42',null,{timeout:25000});results.realPythonWorker=true;
  await page.getByRole('button',{name:'Darsliklarga qaytish',exact:true}).click();await page.getByLabel('Dars yoki mavzu qidirish').fill('Excel oynasi');if(await page.locator('.book-section li button').count()===0)await page.getByLabel('Dars yoki mavzu qidirish').fill('Excel');await page.locator('.book-section li button').first().click();await page.getByRole('button',{name:'Amaliyot oynasini ochish'}).click();await page.getByLabel('Katak A2',{exact:true}).fill('Matematika');await page.getByLabel('Katak B2',{exact:true}).fill('12');await page.getByRole('button',{name:'Ishimni tekshirish'}).click();await page.getByText('100/100 mashq balli').waitFor();results.realOfficeGrading=true;
  await page.getByRole('button',{name:'Darsliklarga qaytish',exact:true}).click();await page.getByLabel('Dars yoki mavzu qidirish').fill('Grammatik tanlov');await page.locator('.book-section li button').first().click();await page.getByRole('alert').filter({hasText:'kirish shartlari'}).waitFor();assert.equal(await page.locator('.en-lesson').count(),0);results.englishGatePreserved=true;
  await page.locator('.en-top').getByRole('button',{name:'Bosh sahifa',exact:true}).click();await page.getByLabel('Dars yoki mavzu qidirish').fill('Harf, tovush');await page.locator('.book-section li button').first().click();await page.getByRole('alert').filter({hasText:'kirish shartlari'}).waitFor();await page.locator('.en-sidebar').getByRole('button',{name:'Bugungi dars',exact:true}).click();await page.getByRole('button',{name:'Darajamni aniqlash',exact:true}).click();for(let i=0;i<4;i++)await page.getByRole('button',{name:'Bilmayman · o‘tkazib yuborish',exact:true}).click();await page.getByRole('button',{name:'Birinchi darsimni boshlash',exact:true}).click();await page.getByRole('heading',{name:'Harf, tovush va ismni harflab aytish',exact:true}).waitFor();await page.getByRole('button',{name:'Darsni saqlab chiqish',exact:true}).click();await page.locator('.en-top').getByRole('button',{name:'Bosh sahifa',exact:true}).click();results.englishLessonWorks=true;
  await page.locator('.textbook-hub .learning-top').getByRole('button',{name:'Bosh sahifa',exact:true}).click();await page.setViewportSize({width:1440,height:1000});await page.locator('.study-menu').getByRole('button',{name:/^IQ va mantiq/}).click();await page.getByRole('heading',{name:'Fikrlashni sinab ko‘ring.'}).waitFor();await page.getByRole('button',{name:'32 savollik testni boshlash',exact:true}).waitFor();await axe(page,'IQ introduction');await shot(page,'iq-intro-desktop');
  await page.getByRole('button',{name:'Avval namuna bilan mashq qilish'}).click();await page.locator('.iq-options input').nth(0).check();await page.getByRole('button',{name:'Javobni izohlash',exact:true}).click();await page.getByText('35 + 7 = 42.',{exact:false}).waitFor();await page.locator('.learning-top').getByRole('button',{name:'Testni yakunlash',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Ha, yakunlash'}).click();await page.getByRole('heading',{name:'Mashq natijasi'}).waitFor();await page.locator('.learning-top').getByRole('button',{name:'Testlar oynasi'}).click();
  await page.getByLabel('Tayyorgarlik bosqichi').selectOption('1');await page.getByRole('button',{name:'32 savollik testni boshlash',exact:true}).click();await page.locator('.iq-options input').first().waitFor();assert.equal(await page.locator('.site-nav').getByRole('button',{name:'Tizimdan chiqish'}).count(),0);await page.evaluate(()=>location.hash='home');await page.waitForURL('**/#iq');await page.locator('.iq-options input').nth(1).check();await page.getByText('Javob saqlanmoqda…').waitFor({state:'detached'});await page.reload();await page.locator('.iq-options input').nth(1).waitFor();assert.ok(await page.locator('.iq-options input').nth(1).isChecked());results.activeReload=true;
  brokenAnswer=true;await page.locator('.iq-options input').nth(0).check();await page.getByRole('button',{name:'Javobni qayta yuborish'}).waitFor();const pending=await page.evaluate(()=>Object.keys(localStorage).find(k=>k.startsWith('sq-iq-pending:')));assert.ok(pending);await page.reload();await page.getByRole('button',{name:'Javobni qayta yuborish'}).waitFor();await page.getByRole('button',{name:'Javobni qayta yuborish'}).click();await page.getByRole('button',{name:'Javobni qayta yuborish'}).waitFor({state:'detached'});results.networkRecovery=true;
  const bank=await ctx.owner(async()=>(await ctx.db.query('select bank from public.sq_iq_runs where user_id=$1 and status=$2',[ids.student,'started'])).rows[0].bank);
  for(let n=0;n<bank.length;n++){if(n)await page.locator('.iq-question').getByRole('button',{name:'Keyingi',exact:true}).click();await page.locator('.iq-options input').nth(bank[n].answer).check();await page.waitForFunction(()=>!document.querySelector('.iq-options input:disabled'));if(n===8){await page.setViewportSize({width:390,height:844});await fits(page);await axe(page,'IQ question mobile');await shot(page,'iq-question-mobile');await page.setViewportSize({width:1440,height:1000})}}
  await page.locator('.iq-question').getByRole('button',{name:'Testni yakunlash',exact:true}).click();await axe(page,'finish dialog');await page.keyboard.press('Escape');assert.equal(await page.getByRole('alertdialog').count(),0);await page.locator('.iq-question').getByRole('button',{name:'Testni yakunlash',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Ha, yakunlash'}).click();await page.getByRole('heading',{name:'Mashq natijasi'}).waitFor();assert.match(await page.locator('.iq-score').innerText(),/32\s*\/ 32/);assert.equal(await page.evaluate(()=>sessionStorage.getItem('sq_active_hash')),null);results.canonicalScore=32;
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Natijani yuklash'}).click();assert.equal((await download).suggestedFilename(),'sinfquiz-mantiq-natija.txt');await page.setViewportSize({width:1920,height:1080});await fits(page);await axe(page,'results board');await shot(page,'iq-results-board');await page.getByRole('button',{name:'Tungi ko‘rinishga o‘tish',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.waitForTimeout(350);await fits(page);await axe(page,'results dark mobile');await shot(page,'iq-results-dark-mobile');await page.getByRole('button',{name:'Savollar va yechimlarni ko‘rish'}).click();await page.locator('.iq-explanation').waitFor();results.answerReview=true;
  for(const [uid,expected] of [[ids.teacher,1],[ids.other,0]]){const p=await make(uid,'teacher');await p.goto('http://127.0.0.1:4195/#iq');await p.getByRole('button',{name:'Guruhlarim natijalarini ko‘rish'}).click();if(expected)await p.locator('.learning-table tbody tr').waitFor();else await p.getByText('Guruhlaringizda yakunlangan urinish yo‘q.').waitFor();assert.equal(await p.locator('.learning-table tbody tr').count(),expected);await p.close()}results.teacherOwnership=true;
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'accessibility.json'),JSON.stringify(axeChecks,null,2));fs.writeFileSync(path.join(out,'learning-browser.json'),JSON.stringify({passed:true,browser:await browser.version(),transport:'Chromium fetch / local checked Postgres RPCs; not a live Supabase or Vercel deployment',...results,runtimeErrors:errors,requests:calls.length,accessibilityChecks:axeChecks.length},null,2));console.log('PASS complete IQ and four-subject library workflow, SQL score, draft recovery, ownership, real Python/Office and English gates.');
 }catch(e){if(page&&!page.isClosed())await shot(page,'failure').catch(()=>{});fs.writeFileSync(path.join(out,'accessibility.json'),JSON.stringify(axeChecks,null,2));throw e}
 finally{await browser.close();await server.close();await ctx.db.close()}
})().catch(e=>{console.error(e);process.exit(1)});
