import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';

const root=dirname(dirname(fileURLToPath(import.meta.url))),read=name=>readFileSync(join(root,name),'utf8');

test('Vercel build uses Supabase Auth, Postgres and Realtime without Firebase',()=>{
 const pkg=JSON.parse(read('package.json')),vercel=JSON.parse(read('vercel.json')),env=read('.env.example'),app=read('src/App.jsx'),data=read('src/supabase-data.js'),sdk=read('src/supabase-sdk.js'),schema=read('supabase-schema.sql');
 assert.equal(pkg.version,'7.3.0');
 assert.ok(pkg.dependencies['@supabase/supabase-js']);
 assert.equal(pkg.dependencies['firebase-admin'],undefined);
 assert.equal(pkg.dependencies.express,undefined);
 assert.equal(pkg.dependencies['socket.io'],undefined);
 assert.equal(vercel.outputDirectory,'dist');
 assert.equal(vercel.rewrites[0].destination,'/index.html');
 for(const name of ['VITE_SUPABASE_URL','VITE_SUPABASE_ANON_KEY','SUPABASE_SERVICE_ROLE_KEY','VITE_TELEGRAM_BOT_USERNAME','TELEGRAM_BOT_TOKEN'])assert.match(env,new RegExp(name));
 assert.doesNotMatch(env,/FIREBASE/);
 assert.match(vercel.headers.at(-1).headers.find(item=>item.key==='Content-Security-Policy').value,/supabase\.co/);
 assert.match(sdk,/createClient/);
 assert.match(sdk,/signInAnonymously/);
 assert.match(sdk,/postgres_changes/);
 assert.match(sdk,/recordActivity/);
 assert.match(read('src/api.js'),/navigator\.onLine/);
 assert.match(read('src/api.js'),/withTimeout/);
 assert.match(schema,/enable row level security/);
 assert.match(schema,/sq_is_teacher/);
 assert.match(schema,/sq_protect_live_questions/);
 assert.match(schema,/sq_protect_national_approval/);
 assert.match(schema,/nationalSections/);
 assert.match(schema,/questionsByLane/);
 assert.match(schema,/admin@sinfquiz\.uz/);
 assert.match(schema,/supabase_realtime/);
 assert.match(app,/TelegramLogin/);
 assert.match(app,/EmailLogin/);
 assert.match(app,/LessonAdmin/);
 assert.match(app,/UserAnalytics/);
 assert.match(app,/CefrWorkspace/);
 assert.match(app,/useActivityGuard/);
 assert.doesNotMatch(data,/import.*cefrMockBank/);
 assert.match(read('src/CefrWorkspace.jsx'),/SourceResources/);
 assert.match(read('api/telegram-auth.js'),/timingSafeEqual/);
 assert.match(read('api/telegram-auth.js'),/SUPABASE_SERVICE_ROLE_KEY/);
 assert.match(data,/questionsByLane/);
 assert.match(data,/quiz\.ownerId!==sdk\.auth\.currentUser\.uid/);
 assert.equal(existsSync(join(root,'firestore.rules')),false);
 assert.equal(existsSync(join(root,'firebase.json')),false);
 assert.equal(existsSync(join(root,'server.js')),false);
});
