// Public instructional examples; private test keys are not imported by the app.
export const practiceItems=[
 {id:'try-n1',domain:'numbers',prompt:'Keyingi son qaysi?',visual:{kind:'sequence',values:[7,14,21,28,35]},options:[40,42,49,36],answer:1,explanation:'Har safar 7 qo‘shiladi: 35 + 7 = 42.'},
 {id:'try-p1',domain:'patterns',prompt:'Har qatorda dastlabki ikki katakdagi nuqtalar qo‘shiladi. Oxirgi katakni to‘ldiring.',visual:{kind:'matrix',cellKind:'dots',cells:[2,3,5,1,4,5,3,4,null]},options:[6,8,7,5],answer:2,explanation:'3 + 4 = 7 ta nuqta.'},
 {id:'try-l1',domain:'logic',prompt:'Barcha A lar B. Barcha B lar C. Qaysi xulosa kelib chiqadi?',visual:{kind:'sets',labels:['A','B','C']},options:['Barcha C lar A.','Barcha A lar C.','Hech bir A C emas.','Barcha C lar B.'],answer:1,explanation:'A ⊆ B ⊆ C dan A ⊆ C keladi. Teskari xulosa shart emas.'},
 {id:'try-s1',domain:'spatial',prompt:'Strelka har gal 90° soat yo‘nalishida buriladi. Keyingi yo‘nalish qaysi?',visual:{kind:'arrows',values:[1,2,3]},options:[1,3,0,2],answer:2,explanation:'O‘ng → past → chap → tepa.'},
 {id:'try-n2',domain:'numbers',prompt:'O‘zgarish qoidasini davom ettiring.',visual:{kind:'sequence',values:[3,6,12,24]},options:[30,36,48,27],answer:2,explanation:'Har safar 2 ga ko‘paytiriladi: 24 × 2 = 48.'},
 {id:'try-p2',domain:'patterns',prompt:'Har qator va ustunda doira, uchburchak, kvadrat bir martadan. Bo‘sh katakni tanlang.',visual:{kind:'matrix',cellKind:'shape',cells:[0,1,2,1,2,0,2,0,null]},options:[0,2,1,3],answer:2,explanation:'Oxirgi qatorda doira va kvadrat bor; uchburchak yetishmaydi.'},
 {id:'try-l2',domain:'logic',prompt:'Gulbahor Boburdan oldinda. Bobur Ra’nodan oldinda. Kim eng orqada?',visual:{kind:'text'},options:['Gulbahor','Bobur','Ra’no','Aniqlab bo‘lmaydi'],answer:2,explanation:'Gulbahor → Bobur → Ra’no. Demak Ra’no eng orqada.'},
 {id:'try-s2',domain:'spatial',prompt:'Belgilangan kataklarni tik o‘qqa nisbatan akslantiring.',visual:{kind:'gridShape',points:[[0,0],[0,1]],axis:true},options:[[[0,0],[0,1]],[[2,0],[2,1]],[[0,1],[0,2]],[[1,0],[2,0]]],answer:1,explanation:'Chap chetdagi kataklar o‘ng chetga o‘tadi; qatorlari saqlanadi.'},
 {id:'try-n3',domain:'numbers',prompt:'Farqlarni kuzating. Keyingi son qaysi?',visual:{kind:'sequence',values:[1,4,9,16]},options:[20,25,24,32],answer:1,explanation:'Farqlar 3, 5, 7; keyingisi 9. 16 + 9 = 25.'},
 {id:'try-p3',domain:'patterns',prompt:'Ikkala katakda bor bo‘lak o‘chadi. Faqat bittasida bor bo‘lak qoladi.',visual:{kind:'matrix',cellKind:'tiles',cells:[3,1,2,5,1,4,6,2,null]},options:[2,6,4,0],answer:2,explanation:'Pastki chap bo‘lak qoladi; yuqori o‘ng bo‘lak ikkala katakda bor va bekor bo‘ladi.'},
 {id:'try-l3',domain:'logic',prompt:'Barcha M shakllar chiziqli. Q chiziqli emas. Q haqida nima aniq?',visual:{kind:'text'},options:['Q — M.','Q — M emas.','Barcha chiziqlilar Q.','Q chiziqli.'],answer:1,explanation:'M bo‘lsa chiziqli bo‘lishi kerak edi. Q chiziqli emas, demak M emas.'},
 {id:'try-s3',domain:'spatial',prompt:'Shaklni 90° soat yo‘nalishida buring.',visual:{kind:'gridShape',points:[[0,0],[1,0]]},options:[[[0,0],[1,0]],[[0,2],[1,2]],[[2,0],[2,1]],[[0,0],[0,1]]],answer:2,explanation:'Yuqori chap katak yuqori o‘ngga, yuqori o‘rtadagi esa o‘ng o‘rtaga o‘tadi.'}
];
