import React,{useEffect,useRef,useState} from 'react';
import {Mic,MicOff,RefreshCw} from 'lucide-react';
import {NoiseController} from './noise-controller.js';
import {clamp,noiseStatus} from './model.js';
export function useNoiseMonitor(settings,onLevel) {
  const [state,setState]=useState({active:false,requesting:false,level:0,error:'',calibrating:false}),controller=useRef(null),live=useRef(onLevel);live.current=onLevel;
  useEffect(()=>{let alive=true;controller.current=new NoiseController(update=>{if(!alive)return;const next=update.active===false?{...update,level:0,calibrating:false}:update;setState(s=>({...s,...next}));if(Number.isFinite(next.level)||typeof next.active==='boolean')live.current(next.level||0,next.active);});return()=>{alive=false;controller.current.stop(false);};},[]);
  useEffect(()=>{if(controller.current)controller.current.sensitivity=settings.sensitivity;},[settings.sensitivity]);
  return {state,controller};
}
export default function NoisePanel({settings,onChange,monitor}) {
  const {state,controller}=monitor;
  const status=noiseStatus(state.level,settings.threshold),rise=state.active?clamp((state.level-settings.threshold)/(100-settings.threshold),0,1):0;
  return <div className="cr-noise-panel"><div className={`cr-balloon-sky ${rise>0?'is-noisy':''}`} aria-hidden="true"><i className="cr-cloud cloud-one"/><i className="cr-cloud cloud-two"/>{['#13869a','#dc697a','#c49525','#597fbe','#70a37f'].map((c,i)=><div className="cr-balloon" key={c} style={{'--balloon-color':c,'--balloon-rise':`${rise*(125+i*9)}px`,'--balloon-speed':`${Math.max(.2,1.5-rise)}s`,left:`${12+i*18}%`}}><i/></div>)}</div><div className="cr-noise-reading"><strong>{Math.round(state.level)}<small>/100</small></strong><span role="status" className={!state.active?'is-off':rise?'is-loud':state.level>settings.threshold*.72?'is-rising':''}>{state.active?status:'Nazorat o‘chiq'}</span></div><meter min="0" max="100" value={state.level} aria-label="Nisbiy shovqin darajasi"/><label>Ruxsat etilgan chegara: {settings.threshold}<input type="range" min="10" max="95" value={settings.threshold} onChange={e=>onChange({...settings,threshold:Number(e.target.value)})}/></label><label>Sezgirlik: {settings.sensitivity.toFixed(1)}×<input type="range" min="0.4" max="2.5" step="0.1" value={settings.sensitivity} onChange={e=>onChange({...settings,sensitivity:Number(e.target.value)})}/></label><div className="cr-tool-actions"><button className="cr-primary" disabled={state.requesting} onClick={()=>state.active?controller.current.stop():controller.current.start()}>{state.active?<MicOff size={17}/>:<Mic size={17}/>} {state.requesting?'Ruxsat kutilmoqda…':state.active?'Nazoratni o‘chirish':'Shovqin nazoratini boshlash'}</button>{state.requesting&&<button onClick={()=>controller.current.stop()}>Bekor qilish</button>}<button disabled={!state.active||state.calibrating} onClick={()=>controller.current.calibrate()}><RefreshCw size={16}/>{state.calibrating?'Moslanmoqda…':'Kalibrlash'}</button></div>{state.calibrating&&<p role="status">2 soniya odatiy fon ovozini kuzatyapmiz. Hozircha gapirmay turing.</p>}{state.calibrated&&<p>Fon ovoziga moslandi.</p>}{state.error&&<div role="alert"><p>{state.error}</p><button onClick={()=>controller.current.start()}>Qayta urinish</button></div>}<p className="cr-help">0–100 — nisbiy ko‘rsatkich, professional desibel o‘lchovi emas. Ovoz yozilmaydi; serverga yuborilmaydi. Bo‘limdan chiqilganda mikrofon to‘xtaydi.</p></div>;
}
