import React,{useEffect,useRef,useState} from 'react';
import {Shuffle,RotateCcw} from 'lucide-react';
import {numberPool,chooseNumbers} from './model.js';
export default function NumberPicker({config,onChange}) {
  const [error,setError]=useState(''),[mixing,setMixing]=useState(false),timeout=useRef(null);
  useEffect(()=>()=>clearTimeout(timeout.current),[]);
  let pool,parseError='';try{pool=numberPool(config);}catch(e){parseError=e.message;}
  const used=config.poolKey===pool?.key?config.used:[],available=pool?.values.filter(n=>!config.unique||!used.includes(n))||[];
  const patch=p=>{setError('');onChange({...config,...p,result:[],used:[],poolKey:'',history:[]});};
  const choose=()=>{
    try {const next=chooseNumbers(config);setError('');setMixing(true);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
      onChange(next);timeout.current=setTimeout(()=>setMixing(false),reduced?0:650);
    }catch(e){setError(e.message);}
  };
  return <div className="cr-number-panel"><label>Raqamlar manbasi<select aria-label="Raqamlar manbasi" disabled={mixing} value={config.mode} onChange={e=>patch({mode:e.target.value})}><option value="limit">1 dan N gacha</option><option value="range">Boshlanish va tugash</option><option value="list">Maxsus ro‘yxat</option></select></label>{config.mode==='list'?<label>Raqamlar ro‘yxati<textarea aria-label="Raqamlar ro‘yxati" disabled={mixing} value={config.list} maxLength={10000} onChange={e=>patch({list:e.target.value})} placeholder="3, 7, 12, 18, 25"/></label>:<div className="cr-number-range">{config.mode==='range'&&<label>Boshlanish<input disabled={mixing} type="number" value={config.start} onChange={e=>patch({start:e.target.value})}/></label>}<label>{config.mode==='limit'?'N — oxirgi raqam':'Tugash'}<input disabled={mixing} type="number" value={config.end} onChange={e=>patch({end:e.target.value})}/></label></div>}<label>Bir safar nechta raqam?<input disabled={mixing} type="number" min="1" max="100" value={config.count} onChange={e=>{setError('');onChange({...config,count:e.target.value});}}/></label><label className="cr-checkbox"><input disabled={mixing} type="checkbox" checked={config.unique} onChange={e=>patch({unique:e.target.checked})}/> Oldin chiqqan raqamlar takrorlanmasin</label><p className="cr-number-left"><b>{available.length}</b> ta raqam qoldi</p>{pool?.duplicates>0&&<p role="status">{pool.duplicates} ta takroriy qiymat bir marta hisoblandi.</p>}{(error||parseError)&&<p role="alert" className="cr-error">{error||parseError}</p>}<div className={`cr-number-results ${mixing?'is-mixing':''}`} aria-live="polite" aria-busy={mixing}>{mixing?<><div className="cr-shuffle-cards" aria-hidden="true"><i>3</i><i>7</i><i>12</i></div><span>Aralashtirilmoqda…</span></>:config.result.length?config.result.map(n=><strong key={n}>{n}</strong>):<span>Tanlangan raqamlar shu yerda chiqadi</span>}</div><div className="cr-tool-actions"><button className="cr-primary" disabled={mixing||!!parseError||!available.length} onClick={choose}><Shuffle size={17}/>Raqam tanlash</button><button disabled={mixing} onClick={()=>{setError('');onChange({...config,used:[],result:[],history:[],poolKey:pool?.key||''});}}><RotateCcw size={16}/> Ro‘yxatni tiklash</button></div>{config.history.length>0&&<details><summary>Tanlov tarixi ({config.history.length})</summary><ol className="cr-picker-history">{[...config.history].reverse().map((h,i)=><li key={`${h.at}:${i}`}><time>{new Date(h.at).toLocaleTimeString('uz-UZ',{hour:'2-digit',minute:'2-digit'})}</time><b>{h.values.join(', ')}</b></li>)}</ol></details>}<p className="cr-help">Har bir qolgan raqamning tanlanish imkoniyati teng. Bir tanlov ichida raqamlar takrorlanmaydi.</p></div>;
}
