import React,{useEffect,useId,useState} from 'react';
import {Play,Pause,RotateCcw,Plus,Minus,Volume2} from 'lucide-react';
import {TIMER_STYLES,clamp,formatTime,timerAction} from './model.js';

export function TimerVisual({timer,remaining}) {
  const id=useId().replaceAll(':',''),ratio=clamp(remaining/timer.durationMs,0,1),time=formatTime(remaining),phase=ratio>.5?'green':ratio>.2?'amber':'red';
  const ticks=Array.from({length:12},(_,i)=>i),running=timer.status==='running';
  let art;
  if(timer.style==='digital')art=<div className="cr-clock-digital">{time}</div>;
  else if(timer.style==='flip')art=<div className="cr-flip">{[...time].map((n,i)=>n===':'?<span key={i}>:</span>:<b key={`${i}:${n}`}>{n}</b>)}</div>;
  else if(timer.style==='ring')art=<svg viewBox="0 0 220 220"><circle cx="110" cy="110" r="91" className="cr-dial-track"/><circle cx="110" cy="110" r="91" className="cr-dial-progress" strokeDasharray={`${2*Math.PI*91*ratio} ${2*Math.PI*91}`} transform="rotate(-90 110 110)"/><text x="110" y="117" textAnchor="middle">{time}</text></svg>;
  else if(timer.style==='analog')art=<svg viewBox="0 0 240 240"><circle cx="120" cy="120" r="100" className="cr-analog-face"/>{ticks.map(i=><g key={i} transform={`rotate(${i*30} 120 120)`}><path d="M120 24v10"/><text x="120" y="48" textAnchor="middle" transform={`rotate(${-i*30} 120 44)`} fontSize="12">{i||12}</text></g>)}<path d="M120 120V61" className="cr-hand" transform={`rotate(${-remaining/60000*30} 120 120)`}/><path d="M120 120V38" className="cr-second-hand" transform={`rotate(${-remaining/1000*6} 120 120)`}/><circle cx="120" cy="120" r="5"/><text x="120" y="164" textAnchor="middle">{time}</text></svg>;
  else if(timer.style==='hourglass')art=<svg viewBox="0 0 240 230"><defs><clipPath id={id}><path d="M68 30h104v35q0 30-42 48 42 18 42 48v39H68v-39q0-30 42-48-42-18-42-48z"/></clipPath></defs><path className="cr-glass" d="M68 30h104v35q0 30-42 48 42 18 42 48v39H68v-39q0-30 42-48-42-18-42-48z"/><g clipPath={`url(#${id})`}><rect x="68" y={113-80*ratio} width="104" height={80*ratio} className="cr-sand"/><rect x="68" y={200-72*(1-ratio)} width="104" height={72*(1-ratio)} className="cr-sand"/>{running&&<path d="M120 108v80" className="cr-sand-flow"/>}</g><path d="M58 25h124M58 204h124" className="cr-hourglass-frame"/><text x="120" y="228" textAnchor="middle">{time}</text></svg>;
  else if(timer.style==='battery')art=<div className="cr-battery-scene"><div className="cr-battery"><i style={{width:`${ratio*100}%`}}/>{[1,2,3,4].map(n=><span key={n}/>)}</div><strong>{time}</strong></div>;
  else if(timer.style==='water')art=<svg viewBox="0 0 240 230"><defs><clipPath id={id}><rect x="60" y="18" width="120" height="165" rx="12"/></clipPath></defs><rect x="60" y="18" width="120" height="165" rx="12" className="cr-glass"/><g clipPath={`url(#${id})`}><rect x="60" y={183-155*ratio} width="120" height={155*ratio} className="cr-water-fill"/><path d="M40 0q20-10 40 0t40 0t40 0t40 0t40 0" className="cr-water-wave" transform={`translate(0 ${183-155*ratio})`}/></g>{[0,1,2,3,4].map(n=><path key={n} d={`M160 ${40+n*32}h12`} className="cr-measure-tick"/>)}<text x="120" y="220" textAnchor="middle">{time}</text></svg>;
  else if(timer.style==='runner')art=<svg viewBox="0 0 320 210"><path d="M18 150h282M18 166h282" className="cr-track-line"/><path d="M286 50v105m0-100h25v30h-25" className="cr-finish-flag"/><g transform={`translate(${25+(1-ratio)*235} 108)`}><circle cy="-35" r="10"/><path d="M0-24l-8 24 18 7m-16-22 20 0 12-12" className="cr-runner-body"/><g className={running?'cr-running-legs':''}><path d="M-6 0l-18 25-12 4m30-29 12 18 13 8" className="cr-runner-body"/></g></g><text x="160" y="200" textAnchor="middle">{time}</text></svg>;
  else if(timer.style==='space')art=<svg viewBox="0 0 320 210"><rect x="6" y="8" width="308" height="155" rx="20" className="cr-space-bg"/>{[0,1,2,3,4,5,6,7,8,9].map(i=><circle key={i} cx={22+(i*71)%270} cy={22+(i*29)%120} r={i%2?2:1} className="cr-star"/>)}<circle cx="280" cy="75" r="24" className="cr-planet"/><g transform={`translate(${30+(1-ratio)*220} 98) rotate(90)`}><path d="M0-26q-15 17-12 38h24q3-21-12-38z" className="cr-rocket"/><circle cy="-3" r="6" className="cr-rocket-window"/><path d="M-12 8l-7 13 9-4m22-9 7 13-9-4" className="cr-rocket"/>{running&&<path d="M-6 14l6 20 6-20" className="cr-rocket-fire"/>}</g><text x="160" y="202" textAnchor="middle">{time}</text></svg>;
  else art=<div className="cr-traffic"><div>{['red','amber','green'].map(c=><i key={c} className={phase===c?`is-lit ${c}`:''}/>)}</div><strong>{time}</strong><small>{phase==='green'?'Vaqt yetarli':phase==='amber'?'Yakunlashga tayyorlaning':'Oxirgi vaqt'}</small></div>;
  return <div className={`cr-timer-visual style-${timer.style} ${remaining<=10000?'is-urgent':''}`} role="img" aria-label={`${timer.label}: ${time} qoldi`}>{art}</div>;
}

export default function TimerPanel({timer,remaining,onChange,onSoundUnlock}) {
  const [fields,setFields]=useState({hours:0,minutes:5,seconds:0});
  useEffect(()=>{const n=Math.floor(timer.durationMs/1000);setFields({hours:Math.floor(n/3600),minutes:Math.floor(n%3600/60),seconds:n%60});},[timer.durationMs]);
  const ms=(fields.hours*3600+fields.minutes*60+fields.seconds)*1000;
  const action=(name,value)=>{if(name==='start'&&timer.sound)onSoundUnlock();let t=timer;if(name==='start'&&['idle','finished'].includes(t.status)&&ms!==t.durationMs)t=timerAction(t,'set',Date.now(),ms);onChange(timerAction(t,name,Date.now(),value));};
  return <div className="cr-timer-panel"><label>Taymer nomi<input value={timer.label} maxLength={60} onChange={e=>onChange({...timer,label:e.target.value})}/></label><label>Taymer ko‘rinishi<select aria-label="Taymer ko‘rinishi" value={timer.style} onChange={e=>onChange({...timer,style:e.target.value})}>{TIMER_STYLES.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><TimerVisual timer={timer} remaining={remaining}/><div className="cr-time-inputs">{[['hours','Soat',23],['minutes','Daqiqa',59],['seconds','Soniya',59]].map(([key,label,max])=><label key={key}>{label}<input type="number" min="0" max={max} disabled={['running','paused'].includes(timer.status)} value={fields[key]} onChange={e=>setFields({...fields,[key]:clamp(Number(e.target.value)||0,0,max)})}/></label>)}</div><div className="cr-presets">{[30,60,180,300,600,2700].map(s=><button key={s} onClick={()=>action('set',s*1000)}>{s<60?`${s} s`:`${s/60} daq`}</button>)}</div><div className="cr-tool-actions"><button className="cr-primary" onClick={()=>action(timer.status==='running'?'pause':'start')}>{timer.status==='running'?<Pause size={16}/>:<Play size={16}/>} {timer.status==='running'?'Pauza':timer.status==='paused'?'Davom ettirish':'Boshlash'}</button><button onClick={()=>action('reset')} aria-label="Taymerni qayta boshlash"><RotateCcw size={17}/></button><button onClick={()=>action('adjust',60000)} aria-label="Bir daqiqa qo‘shish"><Plus size={16}/>1 daq</button><button disabled={remaining===0} onClick={()=>action('adjust',-60000)} aria-label="Bir daqiqa ayirish"><Minus size={16}/>1 daq</button></div><label className="cr-checkbox"><input type="checkbox" checked={timer.sound} onChange={e=>{if(e.target.checked)onSoundUnlock();onChange({...timer,sound:e.target.checked});}}/><Volume2 size={16}/> Vaqt tugaganda signal</label>{timer.status==='finished'&&<p className="cr-ended" role="status">Vaqt tugadi. Ishni yakunlang.</p>}</div>;
}
