import express from 'express';
import {createServer} from 'node:http';
import {Server} from 'socket.io';
import {existsSync,mkdirSync,readFileSync,writeFileSync,renameSync} from 'node:fs';
import {join} from 'node:path';
import {randomToken,cookies,secureEqual,validateQuiz,safeQuestion} from './security.js';
import {gradeAnswer} from '../src/grading.js';

const ADMIN_ID='local-admin';

export function createQuizServer({root,dataDir,config}){
 mkdirSync(dataDir,{recursive:true});
 const file=join(dataDir,'db.json');
 const starter=join(dataDir,'default-db.json');
 let db=existsSync(file)?JSON.parse(readFileSync(file,'utf8')):existsSync(starter)?JSON.parse(readFileSync(starter,'utf8')):{users:[],quizzes:[],players:[],contentVersion:4};
 db.players||=[];db.quizzes||=[];db.users||=[];
 const bankFile=join(root,'data','question-bank.json');
 const typingLessons=JSON.parse(readFileSync(join(root,'data','typing-lessons.json'),'utf8'));
 if(existsSync(bankFile)&&!db.quizzes.some(quiz=>quiz.id==='keyboard-mouse-lab')){
  const bundled=JSON.parse(readFileSync(bankFile,'utf8')).find(quiz=>quiz.id==='keyboard-mouse-lab');
  if(bundled){let pin=bundled.pin;while(db.quizzes.some(quiz=>quiz.pin===pin))pin=String(Math.floor(100000+Math.random()*900000));db.quizzes.push({...structuredClone(bundled),pin,status:'passive',ownerId:ADMIN_ID,version:1})}
 }
 // Lokal admin modeli: eski testlar yagona administratorga o‘tkaziladi.
 for(const quiz of db.quizzes)quiz.ownerId=ADMIN_ID;
 db.typing||={active:false,results:[]};db.typing.results||=[];
 delete db.duels;if(db.race?.active){db.race.active=false;db.race.phase='closed'}db.contentVersion=7;
 const save=()=>{writeFileSync(file+'.tmp',JSON.stringify(db,null,2),{mode:0o600});renameSync(file+'.tmp',file)};save();

 const sessions=new Map(),tickets=new Map(),games=new Map(),raceSessions=new Map(),typingSessions=new Map(),limits=new Map();
 const app=express();app.disable('x-powered-by');const httpServer=createServer(app);
 const allowedOrigin=origin=>origin===config.origin;
 const io=new Server(httpServer,{maxHttpBufferSize:20000,allowRequest:(req,callback)=>callback(null,allowedOrigin(req.headers.origin))});
 const cookieOptions={httpOnly:true,sameSite:'lax',secure:config.origin.startsWith('https://'),path:'/'};
 const failure=(status,message)=>Object.assign(Error(message),{status});
 const live=(map,id)=>{const session=map.get(id);if(!session||session.expires<Date.now()){map.delete(id);return null}return session};
 const teacher=req=>live(sessions,cookies(req).sq_teacher);
 const game=req=>live(games,cookies(req).sq_player);
 const racer=req=>live(raceSessions,cookies(req).sq_racer);
 const typist=req=>live(typingSessions,cookies(req).sq_typist);
 const requireTeacher=(req,res,next)=>{req.session=teacher(req);if(!req.session)return next(failure(401,'Admin login va parolini kiriting.'));next()};
 const requireGame=(req,res,next)=>{req.game=game(req);if(!req.game)return next(failure(401,'O‘yin sessiyasi tugagan. Kod bilan qayta kiring.'));next()};
 const requireRacer=(req,res,next)=>{req.race=racer(req);if(!req.race)return next(failure(401,'Poyga sessiyasi tugagan. Qayta qo‘shiling.'));next()};
 const requireTypist=(req,res,next)=>{req.typing=typist(req);if(!req.typing)return next(failure(401,'Typing sessiyasi tugagan. Qayta qo‘shiling.'));next()};
 const csrf=(req,res,next)=>{if(req.headers['x-csrf-token']!==(req.session||req.game||req.race||req.typing)?.csrf)return next(failure(403,'So‘rov tasdiqlanmadi. Sahifani yangilang.'));next()};
 const rate=(req,res,next)=>{const now=Date.now(),key=(teacher(req)?.userId||game(req)?.playerId||racer(req)?.playerId||typist(req)?.playerId||req.socket.remoteAddress||'unknown')+':'+(req.originalUrl.startsWith('/auth')?'auth':'api');let item=limits.get(key);if(!item||item.until<now)item={count:0,until:now+60000};item.count++;limits.set(key,item);if(item.count>(req.originalUrl.startsWith('/auth')?30:240)){res.set('Retry-After','60');return next(failure(429,'Juda ko‘p urinish. Bir daqiqadan keyin qayta urinib ko‘ring.'))}next()};

 app.use((req,res,next)=>{res.set({'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' ws: wss:; frame-ancestors 'none'; base-uri 'none'; form-action 'self'"});if(config.origin.startsWith('https://'))res.set('Strict-Transport-Security','max-age=31536000');if(req.path.startsWith('/api')||req.originalUrl.startsWith('/auth'))res.set('Cache-Control','no-store');next()});
 app.use(['/api','/auth'],rate);
 app.use((req,res,next)=>{if(!['GET','HEAD','OPTIONS'].includes(req.method)&&(!allowedOrigin(req.headers.origin)||!req.is('application/json')))return next(failure(403,'So‘rov manbasi tasdiqlanmadi.'));next()});
 app.use(express.json({limit:'1mb'}));

 const adminUser={id:ADMIN_ID,name:config.adminName||'Administrator',username:config.adminUsername};
 app.get('/auth/session',(req,res)=>{const session=teacher(req);res.json({user:session?adminUser:null,csrf:session?.csrf||null})});
 app.post('/auth/login',(req,res)=>{
  const username=typeof req.body?.username==='string'?req.body.username.trim():'';
  const password=typeof req.body?.password==='string'?req.body.password:'';
  if(username.length>80||password.length>200||!secureEqual(username,config.adminUsername)||!secureEqual(password,config.adminPassword))throw failure(401,'Login yoki parol noto‘g‘ri.');
  const previous=cookies(req).sq_teacher;if(previous){sessions.delete(previous);io.in('teacher-session:'+previous).disconnectSockets(true)}
  const token=randomToken();sessions.set(token,{userId:ADMIN_ID,csrf:randomToken(),expires:Date.now()+8*3600000});
  res.cookie('sq_teacher',token,{...cookieOptions,maxAge:8*3600000});res.json({user:adminUser,csrf:sessions.get(token).csrf});
 });
 app.post('/auth/logout',requireTeacher,csrf,(req,res)=>{const id=cookies(req).sq_teacher;sessions.delete(id);io.in('teacher-session:'+id).disconnectSockets(true);res.clearCookie('sq_teacher',cookieOptions);res.json({ok:true})});

 const publicRacer=player=>({id:player.id,name:player.name,avatar:player.avatar,ready:player.ready,index:player.index,correct:player.correct,attempts:player.attempts,joinedAt:player.joinedAt,finishedAt:player.finishedAt||null});
 const tickRace=()=>{if(db.race?.active&&db.race.phase==='countdown'&&Date.now()>=db.race.startsAt){db.race.phase='running';db.race.startedAt=db.race.startsAt;save();return true}return false};
 const raceSummary=()=>db.race?{id:db.race.id,active:db.race.active,phase:db.race.phase,title:db.race.title,questionCount:db.race.questions?.length||0,startsAt:db.race.startsAt||null,startedAt:db.race.startedAt||null,winnerId:db.race.winnerId||null,createdAt:db.race.createdAt,racers:(db.race.racers||[]).map(publicRacer)}:null;
 const raceState=current=>{tickRace();if(!db.race||!db.race.active||db.race.id!==current.raceId)throw failure(410,'Poyga yopilgan.');const player=db.race.racers.find(item=>item.id===current.playerId);if(!player)throw failure(410,'Poygachi topilmadi.');const question=db.race.phase==='running'&&!db.race.winnerId?safeQuestion(db.race.questions[player.index]):null;return {race:raceSummary(),playerId:player.id,question,index:player.index,feedback:current.feedback||null,csrf:current.csrf,serverNow:Date.now()}};
 const broadcastRace=()=>{for(const [token,current]of raceSessions){try{io.to('race-session:'+token).emit('race',raceState(current))}catch{raceSessions.delete(token)}}};
 const typingSummary=()=>({active:!!db.typing.active,activatedAt:db.typing.activatedAt||null,studentCount:typingSessions.size,stageCount:typingLessons.length,results:db.typing.results.slice(0,50)});
 const typingStage=index=>{const stage=typingLessons[index];return stage?{...stage,wordCount:stage.text.trim().split(/\s+/u).length}:null};
 const typingState=current=>{if(!db.typing.active)throw failure(410,'Typing mashqi hozir PASSIVE.');return {active:true,playerId:current.playerId,name:current.name,avatar:current.avatar,index:current.index,stage:typingStage(current.index),stageStartedAt:current.stageStartedAt||null,results:current.results,feedback:current.feedback||null,finished:current.index>=typingLessons.length,csrf:current.csrf,serverNow:Date.now()}};
 const ownerState=id=>{const quizzes=db.quizzes.filter(q=>q.ownerId===id);const ids=new Set(quizzes.map(q=>q.id));return {quizzes,players:db.players.filter(p=>ids.has(p.quizId)),race:raceSummary(),typing:typingSummary()}};
 const owned=(id,user)=>{const quiz=db.quizzes.find(q=>q.id===id&&q.ownerId===user);if(!quiz)throw failure(404,'Test topilmadi.');return quiz};
 const publicPlayer=player=>({id:player.id,quizId:player.quizId,name:player.name,avatar:player.avatar,score:player.score,correct:player.correct,answers:player.answers,startedAt:player.startedAt,finishedAt:player.finishedAt,lastEarned:player.lastEarned});
 const ranking=id=>db.players.filter(player=>player.quizId===id).map(publicPlayer).sort((a,b)=>b.score-a.score||(a.finishedAt||Infinity)-(b.finishedAt||Infinity)||a.startedAt-b.startedAt);
 const broadcast=()=>{io.to('owner:'+ADMIN_ID).emit('state',ownerState(ADMIN_ID));for(const quiz of db.quizzes)io.to('quiz:'+quiz.id).emit('ranking',ranking(quiz.id));broadcastRace()};

 app.get('/api/state',requireTeacher,(req,res)=>res.json(ownerState(req.session.userId)));
 app.get('/api/quizzes',requireTeacher,(req,res)=>res.json(ownerState(req.session.userId)));
 const ensurePin=(quiz,id)=>{if(db.quizzes.some(item=>item.id!==id&&item.pin===quiz.pin))throw failure(409,'Bu kod band. Boshqa 6 xonali kod tanlang.')};
 app.post('/api/quizzes',requireTeacher,csrf,(req,res)=>{const quiz=validateQuiz(req.body);ensurePin(quiz);Object.assign(quiz,{id:randomToken(),ownerId:ADMIN_ID,createdAt:Date.now(),version:1});db.quizzes.push(quiz);save();broadcast();res.status(201).json({quiz})});
 app.put('/api/quizzes/:id',requireTeacher,csrf,(req,res)=>{const old=owned(req.params.id,req.session.userId),quiz=validateQuiz(req.body);ensurePin(quiz,old.id);Object.assign(old,quiz,{version:(old.version||0)+1});save();broadcast();res.json({quiz:old})});
 app.delete('/api/quizzes/:id',requireTeacher,csrf,(req,res)=>{const quiz=owned(req.params.id,req.session.userId);db.quizzes=db.quizzes.filter(item=>item.id!==quiz.id);db.players=db.players.filter(player=>player.quizId!==quiz.id);for(const [key,current]of games)if(current.quiz.id===quiz.id)games.delete(key);io.to('quiz:'+quiz.id).emit('closed');io.in('quiz:'+quiz.id).disconnectSockets(true);save();broadcast();res.json({ok:true})});
 app.post('/api/results/reset',requireTeacher,csrf,(req,res)=>{const ids=new Set(db.quizzes.map(q=>q.id));if([...games.values()].some(current=>ids.has(current.quiz.id)&&!current.finished&&current.expires>Date.now()))throw failure(409,'O‘quvchilar testni tugatgach natijalarni tozalang.');db.players=[];save();broadcast();res.json({ok:true})});

 const closeTypingSessions=()=>{typingSessions.clear();io.to('typing-live').emit('typing-closed');io.in('typing-live').disconnectSockets(true)};
 const editDistance=(left,right)=>{const a=[...left],b=[...right],row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let diagonal=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const above=row[j],cost=a[i-1]===b[j-1]?0:1;row[j]=Math.min(row[j]+1,row[j-1]+1,diagonal+cost);diagonal=above}}return row[b.length]};
 const typingMetrics=(target,value,elapsedMs)=>{const expected=target.normalize('NFC'),typed=value.normalize('NFC'),distance=editDistance(expected,typed),length=Math.max(1,expected.length,typed.length),accuracy=Math.max(0,Math.round((1-distance/length)*1000)/10),correctChars=Math.max(0,expected.length-distance),seconds=Math.max(1,elapsedMs/1000),wpm=Math.max(0,Math.round((correctChars/5)/(seconds/60)));return {accuracy,wpm,seconds:Math.round(seconds*10)/10,errors:distance,typedChars:typed.length,expectedChars:expected.length,passed:accuracy>=90&&typed.length>=expected.length*.9}};
 app.get('/api/typing/active',(_req,res)=>res.json({active:!!db.typing.active,stageCount:typingLessons.length,title:'O‘zbekcha Typing Akademiyasi'}));
 app.post('/api/typing/status',requireTeacher,csrf,(req,res)=>{const active=req.body?.active;if(typeof active!=='boolean')throw failure(400,'ACTIVE yoki PASSIVE holatini tanlang.');if(!active){db.typing.active=false;db.typing.deactivatedAt=Date.now();closeTypingSessions()}else if(!db.typing.active){db.typing={active:true,activatedAt:Date.now(),results:[]}}save();broadcast();res.json({typing:typingSummary()})});
 app.post('/api/typing/results/reset',requireTeacher,csrf,(_req,res)=>{db.typing.results=[];save();broadcast();res.json({ok:true})});
 app.post('/api/typing/join',(req,res)=>{if(!db.typing.active)throw failure(409,'Typing mashqi hozir PASSIVE. Admin yoqishini kuting.');const name=typeof req.body?.name==='string'?req.body.name.trim():'';if(!name||name.length>30)throw failure(400,'Ismingizni kiriting.');const allowedAvatars=['🧑‍💻','👩‍🚀','🤖','🥷','🧙','🦸','👾','🦊','🐼','🦁','🐯','🐸'];if(!allowedAvatars.includes(req.body.avatar))throw failure(400,'Avatarni tanlang.');const token=randomToken(),current={playerId:randomToken(),name,avatar:req.body.avatar,index:0,results:[],stageStartedAt:null,feedback:null,csrf:randomToken(),expires:Date.now()+8*3600000};const previous=cookies(req).sq_typist;if(previous)typingSessions.delete(previous);typingSessions.set(token,current);res.cookie('sq_typist',token,{...cookieOptions,maxAge:8*3600000});broadcast();res.status(201).json(typingState(current))});
 app.get('/api/typing/session',requireTypist,(req,res)=>res.json(typingState(req.typing)));
 app.post('/api/typing/start',requireTypist,csrf,(req,res)=>{if(!db.typing.active)throw failure(409,'Typing mashqi hozir PASSIVE.');if(req.typing.index>=typingLessons.length)return res.json(typingState(req.typing));if(!req.typing.stageStartedAt){req.typing.stageStartedAt=Date.now();req.typing.feedback=null}res.json(typingState(req.typing))});
 app.post('/api/typing/submit',requireTypist,csrf,(req,res)=>{if(!db.typing.active)throw failure(409,'Typing mashqi hozir PASSIVE.');const current=req.typing,stage=typingLessons[current.index];if(!stage)throw failure(409,'Barcha bosqichlar tugagan.');if(!current.stageStartedAt)throw failure(409,'Avval bosqichni boshlang.');const value=req.body?.value;if(typeof value!=='string'||value.length>stage.text.length*2+200)throw failure(400,'Kiritilgan matn noto‘g‘ri.');const metrics=typingMetrics(stage.text,value,Date.now()-current.stageStartedAt),result={stage:stage.level,title:stage.title,...metrics};current.feedback=result;current.stageStartedAt=null;if(metrics.passed){current.results.push(result);current.index++;if(current.index>=typingLessons.length){const completedAt=Date.now(),averageAccuracy=Math.round(current.results.reduce((sum,item)=>sum+item.accuracy,0)/current.results.length*10)/10,averageWpm=Math.round(current.results.reduce((sum,item)=>sum+item.wpm,0)/current.results.length);db.typing.results.unshift({id:current.playerId,name:current.name,avatar:current.avatar,averageAccuracy,averageWpm,totalSeconds:Math.round(current.results.reduce((sum,item)=>sum+item.seconds,0)*10)/10,completedAt,stages:current.results});db.typing.results=db.typing.results.slice(0,100);save()}}broadcast();res.json(typingState(current))});
 app.post('/api/typing/leave',requireTypist,csrf,(req,res)=>{const token=cookies(req).sq_typist;typingSessions.delete(token);io.in('typing-session:'+token).disconnectSockets(true);res.clearCookie('sq_typist',cookieOptions);broadcast();res.json({ok:true})});

 const closeRaceSessions=()=>{raceSessions.clear();io.to('race-live').emit('race-closed');io.in('race-live').disconnectSockets(true)};
 app.get('/api/race/active',(_req,res)=>{const changed=tickRace();if(changed)broadcast();const race=db.race;if(!race?.active)return res.json({active:false});res.json({active:true,id:race.id,title:race.title,phase:race.phase,questionCount:race.questions.length,playerCount:race.racers.length,startsAt:race.startsAt||null,winnerId:race.winnerId||null})});
 app.post('/api/race/activate',requireTeacher,csrf,(req,res)=>{
  const unique=new Map();for(const quiz of db.quizzes)for(const question of quiz.questions||[])if(question.type==='test'&&Array.isArray(question.options)&&question.options.length===4&&!unique.has(question.text))unique.set(question.text,question);
  if(unique.size<10)throw failure(400,'1v1 poyga uchun kamida 10 ta variantli test savoli kerak.');
  if(db.race?.active)closeRaceSessions();const source=[...unique.values()];for(let i=source.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[source[i],source[j]]=[source[j],source[i]]}
  const id=randomToken(),questions=source.slice(0,10).map((question,index)=>({...structuredClone(question),id:`${id}-${index+1}`}));
  db.race={id,title:'1v1 Bilim poygasi',active:true,phase:'lobby',questions,racers:[],winnerId:null,createdAt:Date.now(),startsAt:null,startedAt:null};save();broadcast();res.status(201).json({race:raceSummary()});
 });
 app.post('/api/race/stop',requireTeacher,csrf,(_req,res)=>{if(db.race){db.race.active=false;db.race.phase='closed';db.race.closedAt=Date.now()}save();closeRaceSessions();broadcast();res.json({ok:true})});
 app.post('/api/race/join',(req,res)=>{
  tickRace();if(!db.race?.active||db.race.phase!=='lobby')throw failure(409,'Poygaga hozir qo‘shilib bo‘lmaydi. Admin yangi poyga ochishini kuting.');if(db.race.racers.length>=2)throw failure(409,'Poygada ikki o‘rin ham band.');
  const name=typeof req.body?.name==='string'?req.body.name.trim():'';if(!name||name.length>30)throw failure(400,'Ismingizni kiriting.');if(db.race.racers.some(player=>player.name.toLocaleLowerCase()===name.toLocaleLowerCase()))throw failure(409,'Bu ism bilan poygachi allaqachon qo‘shilgan.');
  const allowedAvatars=['🧑‍💻','👩‍🚀','🤖','🥷','🧙','🦸','👾','🦊','🐼','🦁','🐯','🐸'];if(!allowedAvatars.includes(req.body.avatar))throw failure(400,'Avatarni tanlang.');
  const token=randomToken(),player={id:randomToken(),name,avatar:req.body.avatar,ready:false,index:0,correct:0,attempts:0,joinedAt:Date.now()};db.race.racers.push(player);const current={raceId:db.race.id,playerId:player.id,csrf:randomToken(),expires:Date.now()+8*3600000,feedback:null};const previous=cookies(req).sq_racer;if(previous){raceSessions.delete(previous);io.in('race-session:'+previous).disconnectSockets(true)}raceSessions.set(token,current);res.cookie('sq_racer',token,{...cookieOptions,maxAge:8*3600000});save();broadcast();res.status(201).json(raceState(current));
 });
 app.get('/api/race/session',requireRacer,(req,res)=>res.json(raceState(req.race)));
 app.post('/api/race/ready',requireRacer,csrf,(req,res)=>{tickRace();if(!db.race?.active||db.race.id!==req.race.raceId)throw failure(410,'Poyga yopilgan.');if(db.race.phase!=='lobby')return res.json(raceState(req.race));const player=db.race.racers.find(item=>item.id===req.race.playerId);player.ready=true;req.race.feedback=null;if(db.race.racers.length===2&&db.race.racers.every(item=>item.ready)){db.race.phase='countdown';db.race.startsAt=Date.now()+3000;setTimeout(()=>{if(tickRace())broadcast()},3100).unref()}save();broadcast();res.json(raceState(req.race))});
 app.post('/api/race/answer',requireRacer,csrf,(req,res)=>{
  tickRace();if(!db.race?.active||db.race.id!==req.race.raceId||db.race.phase!=='running'||db.race.winnerId)throw failure(409,'Poyga hozir javob qabul qilmaydi.');if((req.race.retryAt||0)>Date.now())throw failure(429,'Noto‘g‘ri javobdan keyin bir soniya kuting.');const player=db.race.racers.find(item=>item.id===req.race.playerId),question=db.race.questions[player.index];if(!question||req.body?.questionId!==question.id)throw failure(409,'Savol tartibi o‘zgargan.');const value=req.body?.value;if(!Number.isInteger(value)||value<0||value>3)throw failure(400,'Javob variantini tanlang.');player.attempts++;const correct=value===question.correct,at=Date.now();req.race.retryAt=correct?0:at+1000;req.race.feedback={correct,at,retryAt:req.race.retryAt};if(correct){player.correct++;player.index++;if(player.index===db.race.questions.length){player.finishedAt=Date.now();db.race.winnerId=player.id;db.race.phase='finished';db.race.finishedAt=player.finishedAt}}save();broadcast();res.json(raceState(req.race));
 });
 app.post('/api/race/leave',requireRacer,csrf,(req,res)=>{if(db.race?.id===req.race.raceId){const leaving=db.race.racers.find(item=>item.id===req.race.playerId);if(db.race.phase==='running'&&!db.race.winnerId){const opponent=db.race.racers.find(item=>item.id!==req.race.playerId);if(opponent){db.race.winnerId=opponent.id;db.race.phase='finished';opponent.finishedAt=Date.now();db.race.finishedAt=opponent.finishedAt}}else if(['lobby','countdown'].includes(db.race.phase)){db.race.racers=db.race.racers.filter(item=>item.id!==req.race.playerId);db.race.phase='lobby';db.race.startsAt=null;for(const player of db.race.racers)player.ready=false}save();broadcast()}const token=cookies(req).sq_racer;raceSessions.delete(token);io.in('race-session:'+token).disconnectSockets(true);res.clearCookie('sq_racer',cookieOptions);res.json({ok:true})});

 const activeByPin=pin=>{const quiz=db.quizzes.find(q=>q.pin===pin&&q.status==='active'&&q.ownerId===ADMIN_ID);if(!quiz)throw failure(404,'Kod topilmadi yoki test hali ochilmagan.');return quiz};
 const quizInfo=quiz=>({id:quiz.id,title:quiz.title,group:quiz.group,subject:quiz.subject,questionCount:quiz.questions.length});
 app.post('/api/resolve',(req,res)=>{if(!/^[0-9]{6}$/.test(req.body?.pin||''))throw failure(400,'6 xonali kodni kiriting.');const quiz=activeByPin(req.body.pin),ticket=randomToken();tickets.set(ticket,{quizId:quiz.id,version:quiz.version,expires:Date.now()+300000});res.json({quiz:quizInfo(quiz),ticket})});
 app.post('/api/play/join',(req,res)=>{const ticket=live(tickets,req.body?.ticket);if(!ticket)throw failure(401,'Kodning amal qilish vaqti tugadi. Qayta kiriting.');const quiz=db.quizzes.find(q=>q.id===ticket.quizId&&q.status==='active'&&q.version===ticket.version);if(!quiz)throw failure(409,'Test o‘zgardi yoki yopildi. Kodni qayta kiriting.');if(typeof req.body.name!=='string'||!req.body.name.trim()||req.body.name.length>30)throw failure(400,'Ismingizni kiriting.');const avatars=['🧑‍💻','👩‍🚀','🤖','🥷','🧙','🦸','👾','🦊','🐼','🦁','🐯','🐸'];if(!avatars.includes(req.body.avatar))throw failure(400,'Avatarni tanlang.');tickets.delete(req.body.ticket);const token=randomToken(),now=Date.now();const player={id:randomToken(),quizId:quiz.id,name:req.body.name.trim(),avatar:req.body.avatar,score:0,correct:0,answers:0,startedAt:now,responses:[]};db.players.push(player);const current={playerId:player.id,quiz:structuredClone(quiz),index:0,deadline:now+quiz.questions[0].time*1000,csrf:randomToken(),expires:now+8*3600000,feedback:null,finished:false};const prior=cookies(req).sq_player;if(prior){games.delete(prior);io.in('player-session:'+prior).disconnectSockets(true)}games.set(token,current);res.cookie('sq_player',token,{...cookieOptions,maxAge:8*3600000});save();broadcast();res.status(201).json(playState(current))});
 function playState(current){const player=db.players.find(item=>item.id===current.playerId);if(!player)throw failure(410,'Natijalar tozalangan.');return {quiz:quizInfo(current.quiz),player:publicPlayer(player),question:current.finished?null:safeQuestion(current.quiz.questions[current.index]),index:current.index,deadline:current.deadline,serverNow:Date.now(),csrf:current.csrf,feedback:current.feedback,finished:current.finished,ranking:ranking(current.quiz.id)}}
 app.get('/api/play/session',requireGame,(req,res)=>res.json(playState(req.game)));
 const activeGame=current=>{if(!db.quizzes.some(q=>q.id===current.quiz.id&&q.status==='active'))throw failure(409,'O‘qituvchi testni to‘xtatgan.');if(current.finished)throw failure(409,'Test allaqachon tugagan.')};
 app.post('/api/play/answer',requireGame,csrf,(req,res)=>{const current=req.game;activeGame(current);const question=current.quiz.questions[current.index];if(req.body?.questionId!==question.id)throw failure(409,'Savol tartibi o‘zgargan. Sahifani yangilang.');if(current.feedback)return res.json(playState(current));const seconds=Math.max(0,(current.deadline-Date.now())/1000),expired=seconds<=0,value=req.body.value;if(!expired){if(question.type==='test'&&(!Number.isInteger(value)||value<0||value>3))throw failure(400,'Javobni tanlang.');if(question.type!=='test'&&(typeof value!=='string'||!value.trim()||value.length>8000))throw failure(400,'Javob 1–8000 belgidan iborat bo‘lsin.')}const result=expired?{ratio:0,earned:0,correct:false,checks:[]}:gradeAnswer(question,value,seconds);const player=db.players.find(item=>item.id===current.playerId);if(!player)throw failure(410,'Natijalar tozalangan.');player.score+=result.earned;player.answers++;player.correct+=Number(result.correct);player.lastEarned=result.earned;player.responses.push({questionId:question.id,type:question.type,text:question.text,value:expired?'':value,earned:result.earned,checks:result.checks,expired});current.feedback={...result,expired,answer:question.answer||null,correctIndex:question.type==='test'?question.correct:null,explanation:question.explanation};save();broadcast();res.json(playState(current))});
 app.post('/api/play/next',requireGame,csrf,(req,res)=>{const current=req.game;if(current.finished)return res.json(playState(current));activeGame(current);if(!current.feedback||req.body?.questionId!==current.quiz.questions[current.index].id)throw failure(409,'Avval joriy savolga javob bering.');if(current.index===current.quiz.questions.length-1){current.finished=true;db.players.find(item=>item.id===current.playerId).finishedAt=Date.now();save();broadcast()}else{current.index++;current.deadline=Date.now()+current.quiz.questions[current.index].time*1000;current.feedback=null}res.json(playState(current))});
 app.post('/api/play/leave',requireGame,csrf,(req,res)=>{const id=cookies(req).sq_player;games.delete(id);io.in('player-session:'+id).disconnectSockets(true);res.clearCookie('sq_player',cookieOptions);res.json({ok:true})});

 io.use((socket,next)=>{const req=socket.request,session=teacher(req),current=game(req),race=racer(req),typing=typist(req);if(!session&&!current&&!race&&!typing)return next(Error('Unauthorized'));socket.data.teacher=session;socket.data.game=current;socket.data.race=race;socket.data.typing=typing;next()});
 io.on('connection',socket=>{const session=socket.data.teacher,current=socket.data.game,race=socket.data.race,typing=socket.data.typing,allCookies=cookies(socket.request);if(session){socket.join('owner:'+session.userId);socket.join('teacher-session:'+allCookies.sq_teacher);socket.emit('state',ownerState(session.userId))}if(current){socket.join('quiz:'+current.quiz.id);socket.join('player-session:'+allCookies.sq_player);socket.emit('ranking',ranking(current.quiz.id))}if(race){socket.join('race-live');socket.join('race-session:'+allCookies.sq_racer);try{socket.emit('race',raceState(race))}catch{socket.disconnect(true)}}if(typing){socket.join('typing-live');socket.join('typing-session:'+allCookies.sq_typist);try{socket.emit('typing',typingState(typing))}catch{socket.disconnect(true)}}});
 const cleanup=setInterval(()=>{const changed=tickRace();for(const map of [sessions,tickets,games,raceSessions,typingSessions])for(const [key,value]of map)if(value.expires<Date.now())map.delete(key);for(const [key,value]of limits)if(value.until<Date.now())limits.delete(key);for(const socket of io.sockets.sockets.values())if((socket.data.teacher&&!teacher(socket.request))||(socket.data.game&&!game(socket.request))||(socket.data.race&&!racer(socket.request))||(socket.data.typing&&!typist(socket.request)))socket.disconnect(true);if(changed)broadcast()},1000);cleanup.unref();

 app.use('/api',(_req,res)=>res.status(404).json({error:'API topilmadi.'}));
 app.use(express.static(join(root,'dist')));app.get(/.*/,(_req,res)=>res.sendFile(join(root,'dist','index.html')));
 app.use((err,req,res,next)=>{if(res.headersSent)return next(err);res.status(err.status||500).json({error:err.status?err.message:'Server xatosi. Qayta urinib ko‘ring.'})});
 return {app,httpServer,io,close:()=>{clearInterval(cleanup);io.close();httpServer.close()}};
}
