import React,{useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Eye,FlaskConical} from 'lucide-react';
import {books} from '../iq/service.js';
import {bookById} from './model.js';
import {LessonSections,LessonChecks} from '../LessonText.jsx';
function Diagram({labels,title}){return <figure className="book-diagram" tabIndex="0" aria-label="O‘quv sxemasi; kichik ekranda yon tomonga aylantirish mumkin"><svg viewBox="0 0 660 132" role="img" aria-label={`${title}. Sxema: ${labels.join(' → ')}`}><defs><marker id="book-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0 0L6 3 0 6" fill="currentColor"/></marker></defs>{labels.map((l,i)=><g key={l}><rect x={10+i*222} y="22" width="192" height="86" rx="15" className="book-diagram-box"/><text x={106+i*222} y="57" textAnchor="middle" fill="currentColor" fontSize="12">{i+1 < 10?'0':''}{i+1}</text><text x={106+i*222} y="83" textAnchor="middle" fill="currentColor" fontSize="13">{l}</text>{i<2&&<path d={`M${205+i*222} 65h20`} fill="none" stroke="currentColor" strokeWidth="2" markerEnd="url(#book-arrow)"/>}</g>)}</svg><figcaption>O‘quv sxemasi. Tuzilmalar va bosqichlar o‘rtasidagi aloqani ko‘rsatadi; haqiqiy o‘lcham yoki barcha oraliq jarayonlar emas.</figcaption></figure>}
export default function BookReader({book,onBack,onOpen,onActivity,onProgress,progress,next}){
 const [read,setRead]=useState(!!progress[book.id]?.read),[notice,setNotice]=useState('');
 useEffect(()=>{let alive=true;const timer=setTimeout(()=>{books('mark',{id:book.id}).then(p=>{if(alive){setRead(true);onProgress(p)}}).catch(e=>alive&&setNotice(e.message))},4500);return()=>{alive=false;clearTimeout(timer)}},[book.id]);
 const guide=book.guide,image=typeof guide?.image==='string'&&/^\/course-visuals\/[a-z0-9-]+\.svg$/.test(guide.image)?guide.image:null;
 return <article className="learning-book"><header><button onClick={onBack}><ArrowLeft size={18}/> Darsliklarga qaytish</button><span className="learning-kicker">{book.group} / {book.ordinal}-DARS</span><h1>{book.title}</h1><p className="book-lead">{book.summary}</p><div className="learning-pills"><span>{book.minutes} daqiqa</span>{book.grade&&<span>{book.grade}-sinf uchun tayanch</span>}<span><Eye size={14}/>{progress[book.id]?.count||0} o‘quvchi o‘qigan</span><span>{read?'O‘qilgan':'O‘qish davom etmoqda'}</span></div></header>
 <div className="book-reader-grid"><div className="learning-card book-content">{book.kind==='science'?<><h2>Asosiy tushuncha</h2><p>{book.definition}</p><Diagram labels={book.diagram} title={book.title}/><h2>Qanday va nima sababdan?</h2><p>{book.reason}</p><h2>Misolni ko‘rib chiqamiz</h2><p>{book.example}</p><h2>Hayotdagi bog‘lanish</h2><p>{book.life}</p><aside className="book-misconception"><b>Chalkashtirmang</b><p>{book.misconception}</p></aside><h2>Virtual amaliy vazifa</h2><p>{book.activity}</p>{book.subject==='chemistry'&&<p className="learning-help">Bu vazifalar SinfQuiz virtual modelida bajariladi. Moddalar bilan haqiqiy tajriba o‘tkazish yo‘riqnomasi emas.</p>}<LessonChecks checks={book.checks}/></>:<>{image&&<figure><img src={image} alt={`${guide.visualTitle}. ${guide.visualCaption}`} loading="lazy"/><figcaption>{guide.visualCaption} O‘quv sxemasi; dastur oynasi versiyaga qarab farq qilishi mumkin.</figcaption></figure>}<LessonSections content={book.content}/>{guide&&<section><h2>Birga bajaramiz</h2><p>{guide.setup}</p><ol>{guide.steps.map((s,i)=><li key={i}>{s}</li>)}</ol><p>{guide.result}</p><h2>Ko‘p uchraydigan xatolar</h2><ul>{guide.mistakes.map((s,i)=><li key={i}>{s}</li>)}</ul><LessonChecks checks={guide.checks}/></section>}</>}
 <div className="learning-actions"><button className="learning-primary" onClick={()=>onActivity(book)}><FlaskConical size={18}/>{book.subject==='informatics'?'Amaliyot oynasini ochish':'Atlasda sinab ko‘rish'}</button>{next&&<button onClick={()=>onOpen(next)}>Keyingi dars <ArrowRight size={18}/></button>}</div>{notice&&<p className="learning-message" role="status">{notice} Darsni o‘qishni davom ettirishingiz mumkin.</p>}</div><aside className="learning-card book-roadmap"><h2>Dars yo‘li</h2><p>O‘qilgan belgi ko‘rish tarixidir; o‘zlashtirish yoki baho degani emas.</p>{book.prerequisites?.length>0&&<><h3>Oldin bilish foydali</h3>{book.prerequisites.map(id=>bookById[id]&&<button key={id} onClick={()=>onOpen(bookById[id])}>{bookById[id].title}</button>)}</>}<h3>Hozirgi mavzu</h3><p><b>{book.title}</b></p>{next&&<><h3>Keyingi qadam</h3><button onClick={()=>onOpen(next)}>{next.title}</button></>}<details className="learning-details"><summary>Manba va model haqida</summary><p>Matn va sxemalar SinfQuiz uchun yozilgan. Ilmiy tayanchlar ZIP ichidagi CHEMISTRY-SOURCES.md va BIOLOGY-SOURCES.md fayllarida keltirilgan. Atlasdagi soddalashtirish izohlarini amaliyotda ham tekshiring.</p></details></aside></div></article>
}
