import React, { useEffect, useMemo, useRef, useState } from 'react';
import {api,subscribeRealtime,setTeacherCsrf,setPlayerCsrf,setRaceCsrf,setTypingCsrf} from './api.js';
import {
  Activity, ArrowLeft, Award, BarChart3, Check, ChevronRight, Clock3,
  Code2, Copy, Eye, EyeOff, Gamepad2, GraduationCap, Home, LayoutDashboard,
  LockKeyhole, LogOut, Medal, Menu, Pencil, Play, Plus, Radio, Save,
  BookOpen, Flag, Headphones, Keyboard, Search, Settings, Sparkles, Trash2,
  Trophy, Users, Volume2, X, Zap
} from 'lucide-react';
import './styles.css';
import './theme.css';
import bank from '../data/question-bank.json';
import {placementBank,placementLevels,randomPlacementQuestion} from '../data/placement-bank.js';
import {questionTypes} from './grading.js';
import {ExperienceControls,Avatar3D,MotionScene,Celebration,playSound} from './effects.jsx';
import ShortcutInput from './ShortcutInput.jsx';
import {firebaseReady} from './firebase-sdk.js';
const KurashArena=React.lazy(()=>import('./KurashArena.jsx'));

const avatars = ['🧑‍💻','👩‍🚀','🤖','🥷','🧙','🦸','👾','🦊','🐼','🦁','🐯','🐸'];
const englishLevels={A1:'Boshlang‘ich',A2:'Elementar',B1:'O‘rta',B2:'Yuqori o‘rta'};
const newPlacementTest=()=>({step:0,level:'A1',question:randomPlacementQuestion('A1'),history:[],used:[]});

function speakEnglish(text,rate=.86){
 if(typeof window==='undefined'||!window.speechSynthesis||!text)return false;
 window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='en-US';utterance.rate=rate;utterance.pitch=1;window.speechSynthesis.speak(utterance);return true;
}

function uid(){ return `${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`; }
function normalize(value){ return value.trim().toLowerCase().replace(/[“”‘’`]/g,"'").replace(/\s+/g,' '); }
function rankRows(players){ return [...players].sort((a,b)=>b.score-a.score || (a.finishedAt||Infinity)-(b.finishedAt||Infinity) || a.startedAt-b.startedAt); }

function App(){
  const deploymentReady=firebaseReady()||globalThis.__SINFQUIZ_LEGACY_TEST__===true;
  const [db,setDb]=useState({quizzes:[],players:[]});const [view,setView]=useState('home');
  const [user,setUser]=useState(null);const [authReady,setAuthReady]=useState(false);
  const [entry,setEntry]=useState(null);const [game,setGame]=useState(null);const [raceGame,setRaceGame]=useState(null);const [typingGame,setTypingGame]=useState(null);const [toast,setToast]=useState('');const [connection,setConnection]=useState('');
  const notify=message=>setToast(message);
  const reload=async()=>{const next=await api('/api/quizzes');setConnection('');setDb(next);return next};
  const applyGame=next=>{setConnection('');setPlayerCsrf(next.csrf);setGame(next);setView(next.finished?'result':'play');location.hash='play'};
  const applyRace=next=>{setConnection('');setRaceCsrf(next.csrf);setRaceGame(next);setView('race');location.hash='race'};
  const applyTyping=next=>{setConnection('');setTypingCsrf(next.csrf);setTypingGame(next);setView('typing');location.hash='typing'};
  useEffect(()=>{const online=()=>setConnection(''),offline=()=>setConnection('Internet aloqasi uzildi. Tugmalar aloqa qaytgach yana ishlaydi.');window.addEventListener('online',online);window.addEventListener('offline',offline);if(!navigator.onLine)offline();return()=>{window.removeEventListener('online',online);window.removeEventListener('offline',offline)}},[]);
  useEffect(()=>{
    if(!deploymentReady){setAuthReady(true);return}
    localStorage.removeItem('sinfquiz_v1');sessionStorage.removeItem('sq_admin');
    api('/auth/session').then(async info=>{setUser(info.user);setTeacherCsrf(info.csrf);if(info.user)await reload();if(location.hash==='#dashboard')setView(info.user?'admin':'login');if(location.hash==='#play'){try{applyGame(await api('/api/play/session'))}catch{notify('O‘yin sessiyasi tugagan. Kod bilan qayta kiring.');history.replaceState(null,'',location.pathname)}}if(location.hash==='#race'){try{applyRace(await api('/api/race/session'))}catch{notify('Poyga sessiyasi tugagan. Qayta qo‘shiling.');history.replaceState(null,'',location.pathname)}}if(location.hash==='#typing'){try{applyTyping(await api('/api/typing/session'))}catch{notify('Typing sessiyasi tugagan. Qayta qo‘shiling.');history.replaceState(null,'',location.pathname)}}}).catch(e=>notify(e.message)).finally(()=>setAuthReady(true));
  },[]);
  useEffect(()=>{if(!user&&!game&&!raceGame&&!typingGame)return;const stop=subscribeRealtime({onState:setDb,onRanking:ranking=>setGame(g=>g?{...g,ranking}:g),onRace:applyRace,onTyping:applyTyping,onClosed:()=>{setGame(null);setView('home');notify('O‘qituvchi testni yopdi.')},onRaceClosed:()=>{setRaceGame(null);setRaceCsrf('');setView('home');notify('Admin 1v1 poygani yopdi.')},onTypingClosed:()=>{setTypingGame(null);setTypingCsrf('');setView('home');notify('Admin typing mashqini PASSIVE qildi.')},onError:()=>setConnection('Jonli aloqa yo‘q. Internetni tekshiring.')});if(stop){setConnection('');return stop}},[user?.id,game?.player?.id,raceGame?.playerId,typingGame?.playerId]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t)},[toast]);
  const home=()=>{setView('home');history.replaceState(null,'',location.pathname)};
  const openAuth=()=>setView('login');
  const login=async credentials=>{const info=await api('/auth/login',{method:'POST',data:credentials});setTeacherCsrf(info.csrf);setUser(info.user);await reload();setView('admin');location.hash='dashboard'};
  const logout=async()=>{try{await api('/auth/logout',{method:'POST'});setUser(null);setDb({quizzes:[],players:[]});setTeacherCsrf('');home()}catch(e){notify(e.message)}};
  const leave=async()=>{try{await api('/api/play/leave',{method:'POST',role:'player'});setGame(null);setPlayerCsrf('');home()}catch(e){notify(e.message)}};
  const leaveRace=async()=>{try{await api('/api/race/leave',{method:'POST',role:'race'});setRaceGame(null);setRaceCsrf('');home()}catch(e){notify(e.message)}};
  const leaveTyping=async()=>{try{await api('/api/typing/leave',{method:'POST',role:'typing'});setTypingGame(null);setTypingCsrf('');home()}catch(e){notify(e.message)}};
  if(!deploymentReady)return <FirebaseSetupRequired/>;
  return <div className="app-shell">
    <nav className="site-nav" aria-label="Asosiy navigatsiya"><button className="nav-brand" onClick={typingGame?leaveTyping:raceGame?leaveRace:game?leave:home} aria-label="SinfQuiz bosh sahifasi"><Brand/></button><div className="nav-actions"><ExperienceControls/>{authReady&&(user?<><button className="btn btn-ghost" onClick={()=>{setView('admin');location.hash='dashboard'}}>Mening testlarim</button><button className="nav-logout" onClick={logout} title="Akkauntdan chiqish" aria-label="Akkauntdan chiqish"><LogOut size={18}/></button></>:<button className="btn btn-ghost teacher-entry" onClick={openAuth}><LockKeyhole size={16}/> Admin kirishi</button>)}</div></nav>
    {toast&&<div className="toast" role="status">{toast}</div>}{connection&&<div className="connection-banner" role="status">{connection}</div>}
    {!authReady?<div className="page-loading">Yuklanmoqda…</div>:<>
    {view==='home'&&<Landing onJoin={setEntryAndJoin} onRace={offer=>{setEntry({race:offer});setView('raceJoin')}} onTyping={offer=>{setEntry({typing:offer});setView('typingJoin')}}/>}
    {view==='login'&&<AdminLogin onBack={home} onLogin={login}/>} 
    {view==='admin'&&user&&<AdminPanel user={user} db={db} reload={reload} onHome={home} notify={notify} onLogout={logout}/>}
    {view==='join'&&entry&&<Join quiz={entry.quiz} onBack={home} onStart={async p=>{const next=await api('/api/play/join',{method:'POST',data:{ticket:entry.ticket,name:p.name,avatar:p.avatar}});playSound('arena');applyGame(next)}}/>}
    {view==='raceJoin'&&entry?.race&&<RaceJoin race={entry.race} onBack={home} onStart={async player=>{const next=await api('/api/race/join',{method:'POST',data:player});playSound('arena');applyRace(next)}}/>}
    {view==='typingJoin'&&entry?.typing&&<TypingJoin onBack={home} onStart={async player=>applyTyping(await api('/api/typing/join',{method:'POST',data:player}))}/>} 
    {view==='race'&&raceGame&&<RaceScreen game={raceGame} onUpdate={applyRace} onLeave={leaveRace}/>} 
    {view==='typing'&&typingGame&&<TypingScreen game={typingGame} onUpdate={applyTyping} onLeave={leaveTyping}/>} 
    {view==='play'&&game&&<PlayQuiz game={game} onUpdate={applyGame}/>}
    {view==='result'&&game&&<Result quiz={{...game.quiz,questions:Array(game.quiz.questionCount)}} player={game.player} db={{players:game.ranking}} onHome={leave}/>}
    </>}
  </div>;
  function setEntryAndJoin(data){setEntry(data);setView('join')}
}

function FirebaseSetupRequired(){
 return <main className="firebase-setup-page"><section><div className="firebase-setup-icon"><Settings/></div><span>VERCEL UCHUN BIR MARTALIK SOZLASH</span><h1>Firebase ma’lumotlari kiritilmagan</h1><p>Saytning test, real-time reyting, 1v1 va typing funksiyalari ishlashi uchun `.env.example` dagi 7 ta qiymatni Vercel Environment Variables bo‘limiga kiriting.</p><div className="firebase-setup-steps"><div><b>1</b><span>Firebase’da Web App, Firestore va Authentication yarating.</span></div><div><b>2</b><span>Email/Password hamda Anonymous login usullarini yoqing.</span></div><div><b>3</b><span>`firestore.rules` faylini Firebase Console’da Publish qiling.</span></div><div><b>4</b><span>Vercel o‘zgaruvchilarini kiriting va Redeploy qiling.</span></div></div><small>Batafsil ko‘rsatma ZIP ichidagi FIREBASE-VERCEL.md faylida.</small></section></main>
}

function Brand({light=false}){ return <div className={`brand ${light?'brand-light':''}`}><span className="brand-mark"><Zap size={20} fill="currentColor"/></span><span>Sinf<span>Quiz</span></span></div> }
function Arena(props){return <React.Suspense fallback={<div className="solo-arena compact"><div className="arena-loader"><i/><span>3D arena tayyorlanmoqda…</span></div></div>}><KurashArena {...props}/></React.Suspense>}

function Landing({onJoin,onRace,onTyping}){
  const [pin,setPin]=useState(''); const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [race,setRace]=useState(null);const [typing,setTyping]=useState(null);
  useEffect(()=>{let alive=true,timer;const load=async()=>{try{const data=await api('/api/race/active');if(alive)setRace(data.active?data:null)}catch{}finally{if(alive)timer=setTimeout(load,5000)}};load();return()=>{alive=false;clearTimeout(timer)}},[]);
  useEffect(()=>{let alive=true,timer;const load=async()=>{try{const data=await api('/api/typing/active');if(alive)setTyping(data.active?data:null)}catch{}finally{if(alive)timer=setTimeout(load,6500)}};load();return()=>{alive=false;clearTimeout(timer)}},[]);
  const joinPin=async e=>{e.preventDefault();if(busy)return;if(!/^\d{6}$/.test(pin)){setError('O‘qituvchi bergan 6 xonali kodni kiriting.');return}setBusy(true);setError('');try{onJoin(await api('/api/resolve',{method:'POST',data:{pin}}))}catch(err){setError(err instanceof TypeError?'Server bilan aloqa yo‘q. Qayta urinib ko‘ring.':err.message)}finally{setBusy(false)}};
  return <main className="landing">
    <section className="hero">
      <div className="hero-copy">
        <div className="eyebrow"><span className="live-dot"/> O‘QUVCHI KIRISHI · AKKAUNTSIZ</div>
        <h1>Kod sizda.<br/><span>Navbat bilimda.</span></h1>
        <p>Hech qanday ro‘yxatdan o‘tish talab qilinmaydi. O‘qituvchi bergan 6 xonali kodni kiriting va bellashuvga qo‘shiling.</p>
        <form className="pin-box" onSubmit={joinPin}>
          <label className="pin-label" htmlFor="game-pin">O‘YIN KODI</label>
          <div className="pin-row"><input id="game-pin" aria-describedby="pin-help pin-error" aria-invalid={!!error} autoComplete="off" inputMode="numeric" maxLength={6} value={pin} onChange={e=>{setPin(e.target.value.replace(/\D/g,'').slice(0,6));setError('')}} placeholder="000000" disabled={busy}/><button disabled={busy||pin.length!==6} type="submit">{busy?'Tekshirilmoqda…':'Qo‘shilish'} <ChevronRight size={20}/></button></div>
          <p id="pin-help" className="pin-help"><LockKeyhole size={13}/> O‘quvchiga akkaunt ham, parol ham kerak emas.</p>
          <div id="pin-error" className="form-error" role="alert">{error}</div>
        </form>
        <div className="entry-steps"><span><b>01</b> Kodni kiriting</span><i/><span><b>02</b> Avatar tanlang</span><i/><span><b>03</b> Boshlang</span></div>
      </div>
      <div className="hero-visual"><MotionScene/></div>
    </section>
    {race&&<section className={`race-invite ${race.phase}`} aria-live="polite"><div className="race-invite-icon"><Flag/></div><div><span>ADMIN YOQQAN JONLI REJIM</span><h2>1v1 Bilim poygasi</h2><p>{race.phase==='lobby'?`${race.playerCount}/2 o‘quvchi · Kod kerak emas · 10 ta bir xil savol`:race.phase==='finished'?'Poyga yakunlandi. Admin yangi poyga ochishi mumkin.':'Poyga hozir davom etmoqda.'}</p></div><button className="btn btn-primary" disabled={race.phase!=='lobby'||race.playerCount>=2} onClick={()=>onRace(race)}>{race.phase==='lobby'&&race.playerCount<2?'Poygaga qo‘shilish':'Hozir yopiq'} <ChevronRight/></button></section>}
    {typing&&<section className="typing-invite" aria-live="polite"><div className="typing-invite-icon"><Headphones/></div><div><span>ACTIVE · IKKI XIL TYPING REJIMI</span><h2>English + Uzun matn Typing</h2><p>192 savollik adaptiv test · A1–B2 audio va vocabulary · 300–500 so‘zli yakuniy matn</p></div><button className="btn btn-primary" onClick={()=>onTyping(typing)}>Mashqni boshlash <ChevronRight/></button></section>}
    <div className="subject-ribbon" aria-label="Dars yo‘nalishlari"><span>INFORMATIKA LAB</span><b>Word</b><b>Excel</b><b>PowerPoint</b><b>Keyboard shortcuts</b><b>Prompt engineering</b></div>
    <footer><Brand/><span>Informatika darslari uchun yaratilgan</span></footer>
  </main>
}

function AdminLogin({onBack,onLogin}){
  const [username,setUsername]=useState('admin'),[password,setPassword]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const submit=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await onLogin({username,password})}catch(err){setError(err.message)}finally{setBusy(false)}};
  return <div className="auth-page"><div className="auth-side"><div className="eyebrow light"><Sparkles size={15}/> FAQAT O‘QITUVCHI UCHUN</div><div><h1>Darsni yarating.<br/>Kodni ulashing.</h1><p>Admin testlarni yaratadi va faollashtiradi. O‘quvchilar esa ro‘yxatdan o‘tmasdan, faqat 6 xonali kod bilan kiradi.</p></div><div className="auth-quote"><BarChart3/><span>Testlar, 3D arena va jonli natijalar.</span></div></div><div className="auth-form-wrap"><button className="back-link" onClick={onBack}><ArrowLeft size={18}/> Kod kiritish sahifasi</button><form className="auth-card" onSubmit={submit}><div className="auth-icon"><LockKeyhole/></div><span className="auth-role">ADMIN PANELI</span><h2>Login va parol bilan kirish</h2><p>Test yaratish va natijalarni boshqarish uchun admin ma’lumotlarini kiriting.</p><label>Login<input autoComplete="username" maxLength={80} value={username} onChange={e=>setUsername(e.target.value)} placeholder="Admin login"/></label><label>Parol<div className="password"><input type={show?'text':'password'} autoComplete="current-password" maxLength={200} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Admin parol"/><button type="button" onClick={()=>setShow(!show)} aria-label={show?'Parolni yashirish':'Parolni ko‘rsatish'}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn btn-primary wide auth-submit" disabled={busy||!username.trim()||!password}>{busy?'Tekshirilmoqda…':'Admin paneliga kirish'}<ChevronRight size={18}/></button><p className="demo-hint">Login: <b>admin</b>. Parol Firebase Authentication’da yaratiladi.</p><p className="student-note"><Check size={17}/><span><b>O‘quvchilar bu yerga kirmaydi.</b> Ular bosh sahifada 6 xonali kodni kiritadi.</span></p></form></div></div>
}

function AdminPanel({user,db,reload,onHome,onLogout,notify}){
  const [section,setSection]=useState('quizzes');const [editing,setEditing]=useState(null);const [mobile,setMobile]=useState(false);
  const players=rankRows(db.players);
  const active=db.quizzes.filter(q=>q.status==='active').length;
  const [pending,setPending]=useState(false);
  const mutate=async(path,method,data)=>{if(pending)return null;setPending(true);try{const result=await api(path,{method,data});await reload();return result}catch(e){notify(e.message);return null}finally{setPending(false)}};
  const toggle=async id=>{const q=db.quizzes.find(q=>q.id===id);if(await mutate('/api/quizzes/'+id,'PUT',{...q,status:q.status==='active'?'passive':'active'}))notify('Test holati yangilandi')};
  const remove=async id=>{if(!confirm('Bu test va uning natijalari o‘chirilsinmi?'))return;if(await mutate('/api/quizzes/'+id,'DELETE'))notify('Test o‘chirildi')};
  const resetResults=async()=>{if(confirm('O‘z testlaringizning natijalari tozalansinmi?')&&await mutate('/api/results/reset','POST'))notify('Natijalar tozalandi')};
  const activateRace=async()=>{if(db.race?.active&&!confirm('Joriy poyga yopilib, yangi 10 savollik poyga ochilsinmi?'))return;if(await mutate('/api/race/activate','POST'))notify('1v1 bilim poygasi yoqildi. O‘quvchilar bosh sahifadan kodsiz kiradi.')};
  const stopRace=async()=>{if(confirm('1v1 poyga yopilsinmi?')&&await mutate('/api/race/stop','POST'))notify('1v1 poyga yopildi.')};
  const setTypingStatus=async active=>{if(await mutate('/api/typing/status','POST',{active}))notify(active?'Typing mashqi ACTIVE qilindi.':'Typing mashqi PASSIVE qilindi.')};
  const resetTyping=async()=>{if(confirm('Typing natijalari tozalansinmi?')&&await mutate('/api/typing/results/reset','POST'))notify('Typing natijalari tozalandi.')};
  const addPack=async pack=>{const result=await mutate('/api/quizzes','POST',{...structuredClone(pack),pin:String(Math.floor(100000+Math.random()*900000)),status:'passive',title:pack.title+' (nusxa)'});if(result)setEditing(result.quiz.id)};
  if(editing!==null)return <QuizEditor quiz={editing==='new'?null:db.quizzes.find(q=>q.id===editing)} saving={pending} onCancel={()=>setEditing(null)} onSave={async quiz=>{const exists=db.quizzes.some(q=>q.id===quiz.id);if(await mutate(exists?'/api/quizzes/'+quiz.id:'/api/quizzes',exists?'PUT':'POST',quiz)){setEditing(null);notify('Test saqlandi')}}}/>;
  return <div className="admin-shell">
    <aside className={mobile?'open':''}><div className="aside-brand"><Brand light/><button onClick={()=>setMobile(false)}><X/></button></div><nav><button className={section==='quizzes'?'selected':''} onClick={()=>{setSection('quizzes');setMobile(false)}}><LayoutDashboard/> Testlar</button><button className={section==='results'?'selected':''} onClick={()=>{setSection('results');setMobile(false)}}><Trophy/> Jonli reyting</button><button className={section==='race'?'selected':''} onClick={()=>{setSection('race');setMobile(false)}}><Flag/> 1v1 poyga</button><button className={section==='typing'?'selected':''} onClick={()=>{setSection('typing');setMobile(false)}}><Keyboard/> Typing mashqi</button></nav><div className="aside-bottom"><button onClick={onHome}><Home/> Saytni ko‘rish</button><button onClick={onLogout}><LogOut/> Chiqish</button></div></aside>
    <div className="admin-main"><header><button className="menu-btn" onClick={()=>setMobile(true)}><Menu/></button><div><small>ADMIN PANEL</small><h1>{section==='quizzes'?'Testlar boshqaruvi':section==='results'?'Jonli reyting':section==='race'?'1v1 bilim poygasi':'Typing boshqaruvi'}</h1></div><div className="admin-user"><span>{user.name.slice(0,2).toUpperCase()}</span><div><b>{user.name}</b><small>O‘qituvchi</small></div></div></header>
      <div className="admin-content">
      {section==='quizzes'?<>
        <div className="stats-grid"><Stat icon={<Gamepad2/>} label="Jami testlar" value={db.quizzes.length} color="purple"/><Stat icon={<Radio/>} label="Faol testlar" value={active} color="green"/><Stat icon={<Users/>} label="Ishtirokchilar" value={db.players.length} color="blue"/><Stat icon={<Activity/>} label="Javoblar" value={db.players.reduce((n,p)=>n+(p.answers||0),0)} color="orange"/></div>
        <section className="bank-banner"><div><span className="eyebrow"><Sparkles size={15}/> TAYYOR SAVOLLAR BANKI</span><h2>Bugungi darsni bir bosishda tayyorlang</h2><p>6 yo‘nalish · 45 ta savol · tayyor 3D arena animatsiyalari</p></div><div className="bank-packs">{bank.map(pack=><button key={pack.id} className={pack.color} disabled={pending} onClick={()=>addPack(pack)}><Plus size={15}/>{pack.subject}</button>)}</div></section><div className="panel-card"><div className="panel-head"><div><h2>Barcha testlar</h2><p>Testlarni yarating va holatini boshqaring</p></div><button className="btn btn-primary" onClick={()=>setEditing('new')}><Plus/> Yangi test</button></div>
        <div className="table-wrap"><table><thead><tr><th>TEST NOMI</th><th>GURUH</th><th>SAVOLLAR</th><th>KOD</th><th>HOLAT</th><th></th></tr></thead><tbody>{db.quizzes.map(q=><tr key={q.id}><td><div className={`table-icon ${q.color}`}><Code2/></div><div><b>{q.title}</b><small>{q.subject}</small></div></td><td><span className="group-tag">{q.group}</span></td><td>{q.questions.length} ta</td><td><code>{q.pin}</code></td><td><button className={`status-switch ${q.status}`} onClick={()=>toggle(q.id)}><i/>{q.status==='active'?'ACTIVE':'PASSIVE'}</button></td><td><div className="row-actions"><button title="Tahrirlash" onClick={()=>setEditing(q.id)}><Pencil/></button><button className="danger" title="O‘chirish" onClick={()=>remove(q.id)}><Trash2/></button></div></td></tr>)}</tbody></table></div></div>
      </>:section==='results'?<Leaderboard players={players} quizzes={db.quizzes} onReset={resetResults}/>:section==='race'?<RaceAdmin race={db.race} pending={pending} onActivate={activateRace} onStop={stopRace}/>:<TypingAdmin typing={db.typing} pending={pending} onStatus={setTypingStatus} onReset={resetTyping}/>} 
      </div>
    </div>
  </div>
}

function Stat({icon,label,value,color}){return <div className="stat-card"><span className={`stat-icon ${color}`}>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>}

function RaceAdmin({race,pending,onActivate,onStop}){
 const active=race?.active,players=race?.racers||[];
 const phases={lobby:'O‘quvchilar kutilmoqda',countdown:'Start sanog‘i',running:'Poyga davom etmoqda',finished:'Poyga yakunlandi',closed:'Yopilgan'};
 return <section className="race-admin panel-card"><div className="race-admin-hero"><div><span className="eyebrow"><Flag/> BITTA KOMPYUTER · SPLIT SCREEN</span><h2>Ikki o‘quvchi, bir xil 10 savol</h2><p>Admin ACTIVE qilgach, ikkala o‘quvchi bitta monitorda chap va o‘ng yo‘lakda mustaqil javob beradi. Alohida qurilmadan kirish kerak emas.</p></div><button className="btn btn-primary" disabled={pending} onClick={onActivate}>{active?'Yangi poyga ochish':'Poygani yoqish'} <Play/></button></div>
  {active?<><div className="race-admin-status"><span className={`live-dot ${race.phase}`}/><div><b>{phases[race.phase]||race.phase}</b><small>{players.length}/2 o‘quvchi · {race.questionCount} savol</small></div><button className="btn btn-outline" disabled={pending} onClick={onStop}>Poygani yopish</button></div><div className="race-admin-racers">{[0,1].map(index=>{const player=players[index];return <article key={index}><span>{player?.avatar||'🏁'}</span><div><b>{player?.name||`${index+1}-o‘quvchi kutilmoqda`}</b><small>{player?`${player.index}/10 · ${player.ready?'Tayyor':'Tayyor emas'}`:'Bosh sahifadan kodsiz kiradi'}</small></div><strong>{player?.index||0}<small>/10</small></strong></article>})}</div>{race.phase==='finished'&&<div className="race-admin-winner"><Trophy/><b>{players.find(player=>player.id===race.winnerId)?.name} g‘olib!</b></div>}</>:<div className="empty-card compact"><Flag/><h3>Poyga hozir o‘chiq</h3><p>Yoqilganda bosh sahifada “Poygaga qo‘shilish” tugmasi avtomatik paydo bo‘ladi. Hech qanday kod kerak emas.</p></div>}
 </section>
}

function TypingAdmin({typing,pending,onStatus,onReset}){
 const active=!!typing?.active,results=typing?.results||[];
 return <section className="typing-admin panel-card">
  <div className="typing-admin-hero"><div><span className="eyebrow"><Headphones/> ENGLISH + UZUN MATN · 5 BOSQICH</span><h2>Ikki rejimli Typing Akademiyasi</h2><p>English rejimida 192 savoldan adaptiv 10 talik test, A1–B2 audio va vocabulary ishlaydi. Uzun matn rejimida eski 5 bosqich hamda 300–500 so‘zli yakuniy matn saqlangan.</p></div><button className={`status-switch large ${active?'active':'passive'}`} disabled={pending} onClick={()=>onStatus(!active)}><i/>{active?'ACTIVE':'PASSIVE'}</button></div>
  <div className="typing-levels">{Object.entries(englishLevels).map(([code,label])=><div key={code}><b>{code}</b><span>{label}</span></div>)}</div>
  <div className="typing-admin-status"><div><span className={`live-dot ${active?'running':''}`}/><b>{active?'O‘quvchilar uchun ochiq':'Hozir yopiq'}</b><small>{active?'Bosh sahifada typing tugmasi ko‘rinadi.':'ACTIVE qilinganda mashq ochiladi.'}</small></div><div><strong>{typing?.studentCount||0}</strong><small>Hozir ishlayapti</small></div><div><strong>{results.length}</strong><small>Tugatganlar</small></div></div>
  <div className="panel-head typing-results-head"><div><h2>Typing natijalari</h2><p>5 bosqichni to‘liq tugatgan o‘quvchilar</p></div>{results.length>0&&<button className="btn btn-outline" disabled={pending} onClick={onReset}><Trash2/> Tozalash</button>}</div>
  {results.length?<div className="table-wrap"><table><thead><tr><th>O‘QUVCHI</th><th>REJIM</th><th>DARAJA</th><th>TEZLIK</th><th>ANIQLIK</th><th>VAQT</th></tr></thead><tbody>{results.map(item=><tr key={item.id+item.completedAt}><td><span className="typing-result-avatar">{item.avatar}</span><b>{item.name}</b></td><td>{item.courseMode==='longtext'?'Uzun matn':'English'}</td><td><strong>{item.courseMode==='longtext'?'5 bosqich':item.englishLevel||'A1'}</strong></td><td><strong>{item.averageWpm} WPM</strong></td><td>{item.averageAccuracy}%</td><td>{Math.floor(item.totalSeconds/60)} min {Math.round(item.totalSeconds%60)} s</td></tr>)}</tbody></table></div>:<div className="empty-card compact"><Headphones/><h3>Hali natija yo‘q</h3><p>O‘quvchi English yoki uzun matn rejimini tugatgach natijasi shu yerda ko‘rinadi.</p></div>}
 </section>
}

function Leaderboard({players:allPlayers,quizzes,onReset}){
  const [filter,setFilter]=useState('');
  const players=allPlayers.filter(p=>!filter||p.quizId===filter);
  return <div className="panel-card"><div className="panel-head"><div><div className="eyebrow"><span className="live-dot"/> REAL TIME</div><h2>O‘quvchilar reytingi</h2><p>Natijalar javob berilgan sari avtomatik yangilanadi</p></div><button className="btn btn-outline" onClick={onReset}><Trash2/> Tozalash</button></div>
    <div className="rank-filter"><select aria-label="Reyting testini tanlang" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Barcha testlar</option>{quizzes.map(q=><option value={q.id} key={q.id}>{q.title} · {q.group}</option>)}</select></div>{players.length?<div className="leader-list">{players.map((p,i)=><div className={`leader-row ${i<3?'top-'+(i+1):''}`} key={p.id}><div className="place">{i===0?'🥇':i===1?'🥈':i===2?'🥉':i+1}</div><div className="leader-avatar"><Avatar3D value={p.avatar}/></div><div className="leader-name"><b>{p.name}</b><small>{quizzes.find(q=>q.id===p.quizId)?.title||'Test'}</small></div><div className="progress"><i style={{width:`${Math.min(100,p.score/8)}%`}}/></div><strong>{p.score} <small>ball</small></strong></div>)}</div>:<div className="empty-card compact"><Trophy/><h3>Hali natijalar yo‘q</h3><p>O‘quvchilar test boshlaganda shu yerda ko‘rinadi.</p></div>}
    {players.some(p=>p.responses?.length)&&<details className="answer-review"><summary>Yozma javoblar va baholash tafsilotlari</summary>{players.map(p=><div key={p.id}>{p.responses?.filter(r=>r.type!=='test').map((r,i)=><article key={i}><b>{p.name} · {r.earned} ball</b><p>{r.text}</p><pre>{r.value||'Javob berilmagan'}</pre>{r.checks?.map((c,j)=><span key={j}>{c.passed?'✓':'○'} {c.label} · </span>)}</article>)}</div>)}</details>}
  </div>
}

function QuizEditor({quiz,onCancel,onSave,saving=false}){
  const [data,setData]=useState(quiz||{id:uid(),title:'',group:'',subject:'Informatika',status:'passive',pin:String(Math.floor(100000+Math.random()*900000)),color:'violet',questions:[],createdAt:Date.now()});
  const blank=()=>({type:'test',text:'',options:['','','',''],correct:0,answer:'',points:100,time:30,subject:'Word',criteria:[],acceptedAnswers:[],explanation:''});
  const [form,setForm]=useState(blank);
  const [editingQ,setEditingQ]=useState(null);
  const saveQuestion=()=>{if(!form.text.trim())return alert('Savol matnini kiriting'); if(form.type==='test'&&form.options.some(x=>!x.trim()))return alert('4 ta variantni ham kiriting'); if(form.type!=='test'&&!form.answer.trim())return alert('Namuna javobni kiriting');if(form.type==='prompt'&&(!form.criteria?.length||form.criteria.some(c=>!c.label.trim()||!c.keywords.some(k=>k.trim()))))return alert('Prompt uchun kamida bitta nomlangan kalit so‘z mezoni kiriting');if(Number(form.time)<10||Number(form.time)>3600||Number(form.points)<10||Number(form.points)>10000)return alert('Vaqt 10–3600 sekund, ball 10–10000 oralig‘ida bo‘lsin');const q={...form,id:editingQ||uid(),points:Number(form.points),time:Number(form.time)}; setData(d=>({...d,questions:editingQ?d.questions.map(x=>x.id===editingQ?q:x):[...d.questions,q]}));cancelQuestion()};
  const cancelQuestion=()=>{setForm(blank());setEditingQ(null)};
  const editQ=q=>{setForm({...blank(),...q,options:q.options||['','','',''],answer:q.answer||''});setEditingQ(q.id);window.scrollTo({top:0,behavior:'smooth'})};
  const submit=()=>{if(!data.title.trim()||!data.group.trim())return alert('Test nomi va guruhni kiriting');if(!/^\d{6}$/.test(data.pin))return alert('Kod 6 ta raqamdan iborat bo‘lsin');if(!data.questions.length)return alert('Kamida 1 ta savol qo‘shing');onSave(data)};
  return <div className="editor-page"><header><button className="back-circle" onClick={onCancel}><ArrowLeft/></button><div><small>TEST MUHARRIRI</small><h1>{quiz?'Testni tahrirlash':'Yangi test yaratish'}</h1></div><button className="btn btn-primary" disabled={saving} onClick={submit}><Save/> {saving?'Saqlanmoqda…':'Saqlash'}</button></header><div className="editor-layout"><div className="editor-main">
    <section className="panel-card form-card"><h2>Asosiy ma’lumotlar</h2><div className="form-grid"><label>Test nomi<input value={data.title} onChange={e=>setData({...data,title:e.target.value})} placeholder="Masalan: Word va Excel"/></label><label>Guruh<input value={data.group} onChange={e=>setData({...data,group:e.target.value})} placeholder="Masalan: 8-A"/></label><label>Fan<input value={data.subject} onChange={e=>setData({...data,subject:e.target.value})}/></label><label>O‘yin kodi<input value={data.pin} onChange={e=>setData({...data,pin:e.target.value.replace(/\D/g,'').slice(0,6)})}/></label></div></section>
    <section className="panel-card form-card"><div className="panel-head"><div><h2>{editingQ?'Savolni tahrirlash':'Yangi savol'}</h2><p>Test, klaviatura, formula yoki prompt topshirig‘i</p></div><div className="type-tabs">{Object.entries(questionTypes).map(([type,label])=><button key={type} className={form.type===type?'on':''} onClick={()=>setForm({...form,type})}>{label}</button>)}</div></div><label>Mavzu<select value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}>{['Word','Excel','PowerPoint','Keyboard shortcuts','Prompt engineering','Informatika'].map(t=><option key={t}>{t}</option>)}</select></label><label>Savol matni<textarea value={form.text} onChange={e=>setForm({...form,text:e.target.value})} placeholder="Savol yoki topshiriqni yozing..."/></label>
      {form.type==='test'?<div className="options-editor">{form.options.map((op,i)=><label className={form.correct===i?'correct-option':''} key={i}><button onClick={()=>setForm({...form,correct:i})}>{String.fromCharCode(65+i)}</button><input value={op} onChange={e=>{const a=[...form.options];a[i]=e.target.value;setForm({...form,options:a})}} placeholder={`${i+1}-variant`}/>{form.correct===i&&<Check/>}</label>)}</div>:<label>Namuna to‘g‘ri javob<textarea className="code-input" value={form.answer} onChange={e=>setForm({...form,answer:e.target.value})} placeholder={form.type==='shortcut'?'Masalan: Ctrl+B':'Namuna javob, formula yoki prompt...'}/></label>}
      {form.type==='prompt'&&<div className="rubric-editor"><h3>Baholash mezonlari</h3><p>Har bir mezonda kalit so‘zlardan bittasi topilsa ball beriladi. Bu AI orqali mazmuniy baholash emas.</p>{form.criteria.map((c,i)=><div className="criterion-edit" key={i}><label>Mezon nomi<input value={c.label} onChange={e=>setForm({...form,criteria:form.criteria.map((x,j)=>j===i?{...x,label:e.target.value}:x)})}/></label><label>Kalit so‘zlar (; bilan ajrating)<input value={c.keywords.join(';')} onChange={e=>setForm({...form,criteria:form.criteria.map((x,j)=>j===i?{...x,keywords:e.target.value.split(';')}:x)})}/></label><button className="btn btn-ghost" aria-label="Mezonni o‘chirish" onClick={()=>setForm({...form,criteria:form.criteria.filter((_,j)=>j!==i)})}><Trash2 size={16}/></button></div>)}<button className="btn btn-outline" onClick={()=>setForm({...form,criteria:[...form.criteria,{label:'',keywords:[]}]})}><Plus size={16}/> Mezon qo‘shish</button></div>}
      {form.type==='practical'&&<label>Boshqa qabul qilinadigan javoblar (har qatorga bittadan)<textarea value={form.acceptedAnswers.join('\n')} onChange={e=>setForm({...form,acceptedAnswers:e.target.value.split('\n').filter(Boolean)})}/></label>}
      <label>Javobdan keyingi tushuntirish<textarea value={form.explanation} onChange={e=>setForm({...form,explanation:e.target.value})} placeholder="Ixtiyoriy izoh..."/></label>
      <div className="question-meta"><label>Ball<input type="number" min="10" value={form.points} onChange={e=>setForm({...form,points:e.target.value})}/></label><label>Vaqt (sekund)<input type="number" min="10" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label><button className="btn btn-primary" onClick={saveQuestion}>{editingQ?<Save/>:<Plus/>}{editingQ?'Yangilash':'Savol qo‘shish'}</button>{editingQ&&<button className="btn btn-ghost" onClick={cancelQuestion}>Bekor qilish</button>}</div>
    </section></div>
    <aside className="questions-side"><div className="side-title"><div><h3>Savollar</h3><p>{data.questions.length} ta savol</p></div></div>{data.questions.map((q,i)=><div className="question-item" key={q.id}><span>{i+1}</span><div><b>{q.text}</b><small>{questionTypes[q.type]} · {q.points} ball</small></div><button onClick={()=>editQ(q)}><Pencil/></button><button className="danger" onClick={()=>setData({...data,questions:data.questions.filter(x=>x.id!==q.id)})}><Trash2/></button></div>)}{!data.questions.length&&<div className="side-empty">Savollar hali qo‘shilmagan</div>}</aside>
  </div></div>
}

function Join({quiz,onBack,onStart}){
  const [name,setName]=useState('');const [avatar,setAvatar]=useState(avatars[0]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const start=async()=>{if(busy)return;setBusy(true);setError('');try{await onStart({name:name.trim(),avatar})}catch(e){setError(e.message)}finally{setBusy(false)}};
  if(!quiz)return null;
  return <div className="join-page"><div className="join-top"><button onClick={onBack}><ArrowLeft/></button><Brand light/><span/></div><div className="join-card"><div className="join-quiz"><span><Code2/></span><div><small>{quiz.subject} · {quiz.group}</small><h2>{quiz.title}</h2><p>{quiz.questionCount} savol · aralash topshiriqlar</p><div className="no-account-badge"><Check size={15}/> Akkaunt talab qilinmaydi</div></div></div><div className="join-form"><span className="join-step">KOD TASDIQLANDI</span><h1>O‘yinga qo‘shiling</h1><p>Reytingda tanish uchun faqat ismingiz va avataringizni tanlang. Bu ro‘yxatdan o‘tish emas.</p><label>Ismingiz<input value={name} onChange={e=>setName(e.target.value.slice(0,30))} placeholder="Ismingizni kiriting" autoFocus/></label><label>Kurashchi avatarini tanlang</label><div className="avatar-grid">{avatars.map((a,i)=><button aria-label={`Avatar ${i+1}`} aria-pressed={avatar===a} key={a} className={avatar===a?'chosen':''} onClick={()=>setAvatar(a)}><Avatar3D value={a} index={i}/>{avatar===a&&<i><Check/></i>}</button>)}</div><button className="btn btn-primary wide join-button" disabled={!name.trim()||busy} onClick={start}>{busy?'Ulanmoqda…':'Maydonga kirish'} <Play size={19} fill="currentColor"/></button>{error&&<p className="form-error" role="alert">{error}</p>}</div></div></div>
}

function TypingJoin({onBack,onStart}){
 const [name,setName]=useState('');const [avatar,setAvatar]=useState(avatars[0]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [courseMode,setCourseMode]=useState('english');const [entryMode,setEntryMode]=useState('placement');const [englishLevel,setEnglishLevel]=useState('A1');const [adaptive,setAdaptive]=useState(newPlacementTest);const [testDone,setTestDone]=useState(false);const [placementScore,setPlacementScore]=useState(null);
 const profileReady=courseMode==='longtext'||entryMode==='selected'||testDone;
 const resetPlacement=()=>{setAdaptive(newPlacementTest());setTestDone(false);setPlacementScore(null);setEnglishLevel('A1');setError('')};
 const answerPlacement=optionIndex=>{const correct=optionIndex===adaptive.question.answer,currentIndex=placementLevels.indexOf(adaptive.level),nextIndex=Math.max(0,Math.min(placementLevels.length-1,currentIndex+(correct?1:-1))),nextLevel=placementLevels[nextIndex],record={id:adaptive.question.id,level:adaptive.level,correct},history=[...adaptive.history,record],used=[...adaptive.used,adaptive.question.id];if(history.length===10){setPlacementScore(history.filter(item=>item.correct).length);setEnglishLevel(nextLevel);setTestDone(true);setAdaptive({...adaptive,history,used,step:10,level:nextLevel});return}setAdaptive({step:history.length,level:nextLevel,question:randomPlacementQuestion(nextLevel,used),history,used})};
 const start=async()=>{if(busy||!name.trim()||!profileReady)return;setBusy(true);setError('');try{await onStart({name:name.trim(),avatar,courseMode,englishLevel,entryMode:courseMode==='longtext'?'longtext':entryMode,placementScore})}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <div className="join-page typing-join-page"><div className="join-top"><button onClick={onBack}><ArrowLeft/></button><Brand light/><span/></div><div className="join-card typing-join-card"><div className="join-quiz typing-join-banner"><span>{courseMode==='english'?<Headphones/>:<Keyboard/>}</span><div><small>IKKI XIL MASHQ REJIMI</small><h2>{courseMode==='english'?'English Typing':'Uzun matn Typing'}</h2><p>{courseMode==='english'?'Tinglang, tushuning va to‘liq gapni tering':'Qisqa gapdan 300–500 so‘zli matngacha'}</p><div className="no-account-badge"><Check size={15}/> Ro‘yxatdan o‘tish shart emas</div></div></div><div className="join-form typing-join-form"><span className="join-step">1-QADAM · MASHQ TURI</span><h1>Typing rejimini tanlang</h1><p>English Vocabulary ham, avvalgi uzun matn mashqlari ham saqlangan.</p>
   <div className="course-mode-grid"><button className={courseMode==='english'?'active':''} onClick={()=>setCourseMode('english')}><Headphones/><b>English + Vocabulary</b><small>Adaptiv test, audio, tarjima va gap terish</small></button><button className={courseMode==='longtext'?'active':''} onClick={()=>setCourseMode('longtext')}><Keyboard/><b>Uzun matn Typing</b><small>5 bosqich, yakunda 300–500 so‘zli matn</small></button></div>
   {courseMode==='english'&&<><div className="typing-profile-separator"><span>2-QADAM · ENGLISH DARAJA</span></div><div className="typing-choice-tabs"><button className={entryMode==='placement'?'active':''} onClick={()=>{setEntryMode('placement');resetPlacement()}}><GraduationCap/> Adaptiv daraja testi <small>Tavsiya</small></button><button className={entryMode==='selected'?'active':''} onClick={()=>{setEntryMode('selected');setTestDone(false);setError('')}}><BookOpen/> Darajani tanlash</button></div>
   {entryMode==='placement'&&!testDone&&<section className="adaptive-placement"><div className="placement-head"><b>192 savoldan adaptiv test</b><span>{adaptive.step+1} / 10</span></div><div className="adaptive-level-path">{placementLevels.map(level=><span className={level===adaptive.level?'current':''} key={level}>{level}</span>)}</div><small>To‘g‘ri javob → bir daraja yuqori · xato → bir daraja past</small><h2>{adaptive.question.text}</h2><div className="adaptive-options">{adaptive.question.options.map((option,index)=><button onClick={()=>answerPlacement(index)} key={option}><span>{String.fromCharCode(65+index)}</span>{option}</button>)}</div></section>}
   {entryMode==='placement'&&testDone&&<section className="placement-result"><Award/><div><small>SIZGA MOS DARAJA</small><h2>{englishLevel} · {englishLevels[englishLevel]}</h2><p>{placementScore}/10 ta to‘g‘ri javob. Test har safar 192 savollik bankdan yangilanadi.</p></div><button className="btn btn-outline" onClick={resetPlacement}>Qayta test</button></section>}
   {entryMode==='selected'&&<div className="english-level-grid">{Object.entries(englishLevels).map(([code,label])=><button className={englishLevel===code?'chosen':''} aria-pressed={englishLevel===code} onClick={()=>setEnglishLevel(code)} key={code}><b>{code}</b><span>{label}</span><small>{code==='A1'?'Oddiy kundalik gaplar':code==='A2'?'Maktab va odatiy mavzular':code==='B1'?'Bog‘langan, o‘rta gaplar':'Murakkab va akademik gaplar'}</small>{englishLevel===code&&<Check/>}</button>)}</div>}</>}
   {profileReady&&<><div className="typing-profile-separator"><span>{courseMode==='english'?'3':'2'}-QADAM · PROFIL</span></div><label>Ismingiz<input value={name} onChange={e=>setName(e.target.value.slice(0,30))} placeholder="Ismingizni kiriting" autoFocus/></label><label>Avatarni tanlang</label><div className="avatar-grid">{avatars.map((avatarValue,index)=><button aria-label={`Avatar ${index+1}`} aria-pressed={avatar===avatarValue} key={avatarValue} className={avatar===avatarValue?'chosen':''} onClick={()=>setAvatar(avatarValue)}><Avatar3D value={avatarValue} index={index}/>{avatar===avatarValue&&<i><Check/></i>}</button>)}</div><button className="btn btn-primary wide join-button" disabled={!name.trim()||busy} onClick={start}>{busy?'Ulanmoqda…':courseMode==='longtext'?'Uzun matn mashqiga kirish':`${englishLevel} mashqiga kirish`} {courseMode==='longtext'?<Keyboard size={19}/>:<Headphones size={19}/>}</button></>}{error&&<p className="form-error" role="alert">{error}</p>}</div></div></div>
}

function TypingScreen({game,onUpdate,onLeave}){
 const {stage,stageStartedAt,feedback,finished}=game;const [typed,setTyped]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [pasteBlocked,setPasteBlocked]=useState(false);const [now,setNow]=useState(Date.now());const inflight=useRef(false);const inputRef=useRef(null);const total=game.stageCount||5,isEnglish=game.courseMode!=='longtext';
 useEffect(()=>{setTyped('');setError('');setPasteBlocked(false)},[stage?.id]);
 useEffect(()=>{if(!stageStartedAt)return;const timer=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(timer)},[stageStartedAt]);
 useEffect(()=>{if(stageStartedAt&&!feedback)inputRef.current?.focus()},[stageStartedAt,feedback,stage?.id]);
 useEffect(()=>()=>{if(typeof window!=='undefined')window.speechSynthesis?.cancel()},[]);
 const target=stage?.text||'',elapsed=Math.max(1,(now-(stageStartedAt||now))/1000),targetChars=[...target],typedChars=[...typed],errors=typedChars.reduce((count,char,index)=>count+Number(char!==targetChars[index]),0),accuracy=typedChars.length?Math.max(0,Math.round((1-errors/typedChars.length)*100)):100,wpm=stageStartedAt?Math.max(0,Math.round(((typedChars.length-errors)/5)/(elapsed/60))):0,progress=target.length?Math.min(100,Math.round(typed.length/target.length*100)):0;
 const action=async(path,data)=>{if(inflight.current)return;inflight.current=true;setBusy(true);setError('');try{const next=await api(path,{method:'POST',role:'typing',data});if(path.endsWith('/submit'))playSound(next.feedback?.passed?'correct':'wrong');onUpdate(next)}catch(e){setError(e.message)}finally{inflight.current=false;setBusy(false)}};
 const listen=rate=>{if(!speakEnglish(stage?.text,rate))setError('Bu brauzer ovozli o‘qishni qo‘llamaydi. Chrome yoki Edge’da ochib ko‘ring.')};
 const begin=()=>{setTyped('');setNow(Date.now());if(isEnglish)speakEnglish(stage?.text,.86);action('/api/typing/start')};
 if(finished){const averageAccuracy=Math.round(game.results.reduce((sum,item)=>sum+item.accuracy,0)/Math.max(1,game.results.length)*10)/10,averageWpm=Math.round(game.results.reduce((sum,item)=>sum+item.wpm,0)/Math.max(1,game.results.length));return <main className="typing-page"><section className="typing-finish"><Celebration/><div className="typing-finish-icon"><Trophy/></div><span>{isEnglish?game.englishLevel:'UZUN MATN'} · {total} BOSQICH TUGADI</span><h1>Barakalla, {game.name}!</h1><p>{isEnglish?'Siz inglizcha gaplarni tinglash, tushunish va klaviaturada terish mashqlarini yakunladingiz.':'Siz qisqa gapdan 300–500 so‘zli matngacha bo‘lgan barcha typing bosqichlarini yakunladingiz.'}</p><div className="typing-finish-stats"><div><strong>{averageWpm}</strong><small>O‘rtacha WPM</small></div><div><strong>{averageAccuracy}%</strong><small>O‘rtacha aniqlik</small></div><div><strong>{isEnglish?game.englishLevel:`${total}/${total}`}</strong><small>{isEnglish?'English level':'Bosqich'}</small></div></div><button className="btn btn-primary" onClick={onLeave}><Home/> Bosh sahifaga qaytish</button></section></main>}
 return <main className="typing-page"><header className="typing-header"><div><span>{isEnglish?<Headphones/>:<Keyboard/>} {isEnglish?`ENGLISH LISTENING + TYPING · ${game.englishLevel}`:'UZUN MATN TYPING · 5 BOSQICH'}</span><h1>{stage.title}</h1><p>{game.name} · {stage.description} · {stage.wordCount} so‘z</p></div><button className="btn btn-outline" onClick={()=>{if(confirm('Typing mashqidan chiqilsinmi?'))onLeave()}}><ArrowLeft/> Chiqish</button></header>
  <nav className="typing-steps" aria-label="Typing bosqichlari">{Array.from({length:total},(_,index)=>index+1).map(level=><div className={level<stage.level?'done':level===stage.level?'current':''} key={level}><span>{level<stage.level?<Check/>:level}</span><b>{level}-bosqich</b></div>)}</nav>
  {!stageStartedAt&&feedback&&<section className={`typing-stage-result ${feedback.passed?'passed':'retry'}`}><span>{feedback.passed?<Check/>:<X/>}</span><div><small>{feedback.passed?'BOSQICH MUVAFFAQIYATLI':'YANA BIR MARTA URINING'}</small><h2>{feedback.passed?`${feedback.stage}-bosqich tugadi`:isEnglish?'Gapni yana tinglang':'Aniqlikni oshiring'}</h2><p className="typing-correct-answer"><b>{isEnglish?feedback.correctText:'Kamida 90% aniqlik bilan matnni qayta tering.'}</b>{isEnglish&&<small>{feedback.translation}</small>}</p></div><div className="typing-result-numbers"><b>{feedback.wpm}<small>WPM</small></b><b>{feedback.accuracy}%<small>Aniqlik</small></b><b>{feedback.errors}<small>Xato</small></b></div><button className="btn btn-primary" disabled={busy} onClick={begin}>{feedback.passed?'Keyingi bosqich':'Qayta boshlash'} <ChevronRight/></button></section>}
  {!stageStartedAt&&!feedback&&<section className="typing-ready">{isEnglish?<Headphones/>:<Keyboard/>}<span>{isEnglish?game.englishLevel:'UZUN MATN'} · {stage.level}-BOSQICH</span><h2>{stage.title}</h2><p>{isEnglish?'“Tinglash va boshlash” tugmasini bosing. Gap inglizcha aytiladi; bo‘sh joyni topib, gapni to‘liq yozasiz.':'Matnni ko‘rib chiqing. Boshlangach vaqt yuradi; yakuniy bosqichda 300–500 so‘zli matn beriladi.'}</p><div><b>{stage.wordCount}<small>so‘z</small></b><b>90%<small>kerakli aniqlik</small></b></div><button className="btn btn-primary" disabled={busy} onClick={begin}>{isEnglish?<><Volume2/> Tinglash va boshlash</>:<><Play/> Boshlash</>}</button></section>}
  {stageStartedAt&&!feedback&&<section className="typing-workspace"><div className="typing-live-stats"><div><strong>{wpm}</strong><small>WPM</small></div><div><strong>{accuracy}%</strong><small>Aniqlik</small></div><div><strong>{errors}</strong><small>Xato</small></div><div><strong>{Math.floor(elapsed/60)}:{String(Math.floor(elapsed%60)).padStart(2,'0')}</strong><small>Vaqt</small></div></div><div className="typing-progress"><i style={{width:`${progress}%`}}/><span>{progress}%</span></div>{isEnglish?<div className="english-learning-card"><div className="english-prompt-head"><span>{game.englishLevel} · LISTEN & COMPLETE</span><div><button onClick={()=>listen(.86)}><Volume2/> Eshitish</button><button onClick={()=>listen(.62)}><Headphones/> Sekin</button></div></div><h2>{stage.prompt}</h2><p>{stage.translation}</p><div className="vocabulary-row">{stage.words?.map(item=><span key={item.word}><b>{item.word}</b><small>{item.meaning}</small></span>)}</div></div>:<div className="typing-reference" aria-label="Ko‘chiriladigan matn">{targetChars.map((char,index)=><span className={index<typedChars.length?(typedChars[index]===char?'correct':'wrong'):index===typedChars.length?'cursor':''} key={index}>{char}</span>)}</div>}<label className="typing-input-label">{isEnglish?'Eshitgan to‘liq inglizcha gapni yozing':'Matnni shu yerga to‘liq yozing'}<textarea ref={inputRef} spellCheck="false" autoCapitalize="off" autoCorrect="off" value={typed} maxLength={target.length*2+200} onPaste={event=>{event.preventDefault();setPasteBlocked(true)}} onChange={event=>{setTyped(event.target.value);setPasteBlocked(false)}} placeholder={isEnglish?'Masalan: I go to school every day.':'Yozishni boshlang…'}/></label>{pasteBlocked&&<p className="typing-warning">Nusxa ko‘chirish mumkin emas — matnni klaviaturada yozing.</p>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="typing-submit-row"><small>{typed.length} / {target.length} belgi {isEnglish&&<>· asosiy so‘z: <b>{stage.focus}</b></>}</small><button className="btn btn-primary" disabled={busy||typed.length<Math.max(1,target.length*(isEnglish ? .65 : .8))} onClick={()=>action('/api/typing/submit',{value:typed})}>{busy?'Tekshirilmoqda…':isEnglish?'Gapni tekshirish':'Bosqichni tekshirish'} <Check/></button></div></section>}
 </main>
}

function RaceJoin({race,onBack,onStart}){
 const [players,setPlayers]=useState([{name:'',avatar:avatars[0]},{name:'',avatar:avatars[1]}]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const update=(lane,field,value)=>setPlayers(current=>current.map((player,index)=>index===lane?{...player,[field]:value}:player));
 const start=async()=>{if(busy||players.some(player=>!player.name.trim()))return;setBusy(true);setError('');try{await onStart({players:players.map(player=>({...player,name:player.name.trim()}))})}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <div className="join-page race-join-page"><div className="join-top"><button onClick={onBack}><ArrowLeft/></button><Brand light/><span/></div><div className="join-card local-race-join"><div className="join-quiz race-join-banner"><span><Flag/></span><div><small>BITTA KOMPYUTER · SPLIT SCREEN · 10 SAVOL</small><h2>{race.title}</h2><p>Ikki o‘quvchi bir monitorda yonma-yon poyga qiladi</p><div className="no-account-badge"><Check size={15}/> Admin poygani ACTIVE qilgan</div></div></div><div className="join-form"><span className="join-step">IKKI YUGURUVCHI</span><h1>Bitta ekranda 1v1</h1><p>Ikkala o‘quvchi ma’lumotini kiriting. Startdan keyin ekran ikki mustaqil yo‘lakka bo‘linadi.</p><div className="local-player-setup">{players.map((player,lane)=><section key={lane}><div><span>{lane+1}</span><b>{lane===0?'Chap yo‘lak':'O‘ng yo‘lak'}</b></div><label>{lane+1}-o‘quvchi ismi<input value={player.name} onChange={e=>update(lane,'name',e.target.value.slice(0,30))} placeholder={`${lane+1}-o‘quvchi ismi`} autoFocus={lane===0}/></label><label>Avatar<select value={player.avatar} onChange={e=>update(lane,'avatar',e.target.value)}>{avatars.map((value,index)=><option value={value} key={value}>{value} Avatar {index+1}</option>)}</select></label></section>)}</div><button className="btn btn-primary wide join-button" disabled={players.some(player=>!player.name.trim())||busy} onClick={start}>{busy?'Tayyorlanmoqda…':'Split poygani boshlash'} <Flag size={19}/></button>{error&&<p className="form-error" role="alert">{error}</p>}</div></div></div>
}

function RaceTrack({race,playerId}){
 return <div className="race-split" aria-label="Ikki yuguruvchining poyga holati">{[0,1].map(lane=>{const player=race.racers[lane],winner=race.winnerId===player?.id;const state=race.phase==='finished'?(winner?'victory':'wrong'):race.phase==='running'?'running':player?.ready?'ready':'idle';return <section className={`race-lane lane-${lane} ${player?.id===playerId?'mine':''}`} key={lane}><div className="race-lane-head"><span>{player?.avatar||'🏁'}</span><div><small>{lane===0?'1-YO‘LAK':'2-YO‘LAK'} {player?.id===playerId?'· SIZ':''}</small><b>{player?.name||'Yuguruvchi kutilmoqda'}</b></div><strong>{player?.index||0}<small>/10</small></strong></div><Arena state={state} compact label={winner?'G‘OLIB!':race.phase==='running'?'YUGURMOQDA':player?.ready?'STARTGA TAYYOR':'KUTILMOQDA'}/><div className="race-distance"><i style={{width:`${(player?.index||0)*10}%`}}/><span style={{left:`calc(${(player?.index||0)*10}% - 13px)`}}>{player?.avatar||'•'}</span></div></section>})}</div>
}

function RaceScreen(props){return props.game.localMode?<LocalRaceScreen {...props}/>:<RemoteRaceScreen {...props}/>}

function LocalRaceScreen({game,onUpdate,onLeave}){
 const {race,questions=[],playerIds=[]}=game;const [selected,setSelected]=useState([null,null]);const [busy,setBusy]=useState([false,false]);const [errors,setErrors]=useState(['','']);const [now,setNow]=useState(Date.now());const inflight=useRef([false,false]);
 useEffect(()=>{setSelected([null,null]);setErrors(['',''])},[questions.map(question=>question?.id||'').join('|')]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),100);return()=>clearInterval(timer)},[]);
 useEffect(()=>{let alive=true,timer;const poll=async()=>{try{const next=await api('/api/race/session');if(alive)onUpdate(next)}catch{}finally{if(alive)timer=setTimeout(poll,race.phase==='countdown'?700:1800)}};poll();return()=>{alive=false;clearTimeout(timer)}},[race.phase]);
 const answer=async lane=>{if(inflight.current[lane]||selected[lane]===null)return;inflight.current[lane]=true;setBusy(value=>value.map((item,index)=>index===lane?true:item));setErrors(value=>value.map((item,index)=>index===lane?'':item));try{const next=await api('/api/race/answer',{method:'POST',role:'race',data:{playerId:playerIds[lane],questionId:questions[lane]?.id,value:selected[lane]}}),feedback=next.feedbackByPlayer?.[playerIds[lane]];playSound(feedback?.correct?'correct':'wrong');if(next.race.phase==='finished')playSound('finish');onUpdate(next)}catch(error){setErrors(value=>value.map((item,index)=>index===lane?error.message:item))}finally{inflight.current[lane]=false;setBusy(value=>value.map((item,index)=>index===lane?false:item))}};
 const countdown=Math.max(1,Math.ceil(((race.startsAt||now)-now)/1000)),winner=race.racers.find(player=>player.id===race.winnerId);
 return <main className="race-page local-race-page"><header className="race-header"><div><span><Flag/> LOCAL 1V1 · BITTA MONITOR</span><h1>{race.title}</h1><p>Chap va o‘ng yo‘lak mustaqil ishlaydi · har to‘g‘ri javob — bir qadam</p></div><button className="btn btn-outline" onClick={()=>{if(race.phase==='finished'||confirm('Poygadan chiqilsinmi?'))onLeave()}}><ArrowLeft/> Chiqish</button></header><RaceTrack race={race} playerId={null}/>
  {race.phase==='countdown'&&<div className="race-countdown" role="status"><strong>{countdown}</strong><span>IKKALA YUGURUVCHI TAYYOR!</span></div>}
  {race.phase==='running'&&<div className="local-question-split">{[0,1].map(lane=>{const player=race.racers.find(item=>item.id===playerIds[lane]),question=questions[lane],feedback=game.feedbackByPlayer?.[playerIds[lane]],retrying=feedback&&!feedback.correct&&feedback.retryAt>now;return <section className={`local-question-lane lane-${lane}`} key={playerIds[lane]}><div className="local-question-title"><span>{player?.avatar}</span><div><small>{lane===0?'CHAP YO‘LAK':'O‘NG YO‘LAK'} · SAVOL {(player?.index||0)+1}/10</small><b>{player?.name}</b></div></div>{question&&<><h2>{question.text}</h2><div className="local-answer-grid">{question.options.map((option,index)=><button disabled={busy[lane]||retrying} onClick={()=>setSelected(value=>value.map((item,itemIndex)=>itemIndex===lane?index:item))} className={selected[lane]===index?'selected':''} key={index}><span>{String.fromCharCode(65+index)}</span><b>{option}</b></button>)}</div>{feedback&&<p className={`race-feedback ${feedback.correct?'correct':'wrong'}`}>{feedback.correct?'To‘g‘ri — oldinga!':retrying?'Xato. Bir soniya kuting.':'Qayta javob bering.'}</p>}{errors[lane]&&<p className="form-error" role="alert">{errors[lane]}</p>}<button className="btn btn-primary local-answer-button" disabled={busy[lane]||retrying||selected[lane]===null} onClick={()=>answer(lane)}>{busy[lane]?'Tekshirilmoqda…':'Javobni yuborish'} <ChevronRight/></button></>}</section>})}</div>}
  {race.phase==='finished'&&<section className="race-finish winner" role="status"><Trophy/><span>LOCAL POYGA YAKUNLANDI</span><h2>{winner?.name} g‘olib!</h2><p>10 ta savolni birinchi bo‘lib to‘g‘ri yakunladi.</p><button className="btn btn-primary" onClick={onLeave}><Home/> Bosh sahifaga qaytish</button></section>}
 </main>
}

function RemoteRaceScreen({game,onUpdate,onLeave}){
 const {race,playerId,question}=game;const mine=race.racers.find(player=>player.id===playerId);const [selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[now,setNow]=useState(Date.now());const inflight=useRef(false);
 useEffect(()=>{setSelected(null);setError('')},[question?.id,game.feedback?.at]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),100);return()=>clearInterval(timer)},[]);
 useEffect(()=>{let alive=true,timer;const poll=async()=>{try{const next=await api('/api/race/session');if(alive)onUpdate(next)}catch{}finally{if(alive)timer=setTimeout(poll,race.phase==='countdown'?900:2500)}};poll();return()=>{alive=false;clearTimeout(timer)}},[playerId,race.phase]);
 const action=async(path,data)=>{if(inflight.current)return;inflight.current=true;setBusy(true);setError('');try{const next=await api(path,{method:'POST',role:'race',data});if(path.endsWith('/answer'))playSound(next.feedback?.correct?'correct':'wrong');if(next.race.phase==='finished')playSound('finish');onUpdate(next)}catch(e){setError(e.message)}finally{inflight.current=false;setBusy(false)}};
 const countdown=Math.max(1,Math.ceil(((race.startsAt||now)-now)/1000)),retrying=game.feedback&&!game.feedback.correct&&game.feedback.retryAt>now;const winner=race.racers.find(player=>player.id===race.winnerId);
 return <main className="race-page"><header className="race-header"><div><span><Flag/> 1V1 BILIM POYGASI</span><h1>{race.title}</h1><p>Bir xil 10 savol · har to‘g‘ri javob — bir qadam oldinga</p></div><button className="btn btn-outline" onClick={()=>{if(race.phase==='finished'||confirm('Poygadan chiqilsinmi?'))onLeave()}}><ArrowLeft/> Chiqish</button></header><RaceTrack race={race} playerId={playerId}/>
  {race.phase==='lobby'&&<section className="race-stage"><Flag/><h2>{race.racers.length<2?'Ikkinchi yuguruvchi kutilmoqda':'Ikkala yuguruvchi startda'}</h2><p>Har ikki o‘quvchi “Tayyorman”ni bosgach poyga avtomatik boshlanadi.</p><button className="btn btn-primary" disabled={busy||mine?.ready} onClick={()=>action('/api/race/ready')}>{mine?.ready?<><Check/> Siz tayyorsiz</>:<><Flag/> Tayyorman</>}</button></section>}
  {race.phase==='countdown'&&<div className="race-countdown" role="status"><strong>{countdown}</strong><span>STARTGA TAYYOR!</span></div>}
  {race.phase==='running'&&question&&<section className="race-question" key={question.id}><div className="race-question-meta"><span>SAVOL {mine.index+1} / 10</span><b>{question.subject||'Informatika'}</b></div><h2>{question.text}</h2><div className="answer-grid">{question.options.map((option,index)=><button disabled={busy||retrying} onClick={()=>setSelected(index)} className={selected===index?'selected':''} key={index}><span>{String.fromCharCode(65+index)}</span><b>{option}</b></button>)}</div>{game.feedback&&<p className={`race-feedback ${game.feedback.correct?'correct':'wrong'}`}>{game.feedback.correct?'To‘g‘ri! Yuguruvchi oldinga o‘tdi.':retrying?'Noto‘g‘ri. Bir soniyadan keyin qayta urinishingiz mumkin.':'Noto‘g‘ri. Shu savolga qayta javob bering.'}</p>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn btn-primary race-answer" disabled={busy||retrying||selected===null} onClick={()=>action('/api/race/answer',{questionId:question.id,value:selected})}>{busy?'Tekshirilmoqda…':retrying?'Qayta urinish…':'Javobni yuborish'} <ChevronRight/></button></section>}
  {race.phase==='finished'&&<section className={`race-finish ${winner?.id===playerId?'winner':'runner-up'}`} role="status"><Trophy/><span>POYGA YAKUNLANDI</span><h2>{winner?.name} g‘olib!</h2><p>{winner?.id===playerId?'Siz 10 ta savolni birinchi bo‘lib to‘g‘ri yakunladingiz.':'Raqib 10 ta savolni birinchi bo‘lib yakunladi.'}</p><button className="btn btn-primary" onClick={onLeave}><Home/> Bosh sahifaga qaytish</button></section>}
 </main>
}

function PlayQuiz({game,onUpdate}){
  const {quiz,player:current,question:q,index,feedback:grade,deadline,serverNow}=game;
  const checked=!!grade;const [selected,setSelected]=useState(null);const [code,setCode]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [seconds,setSeconds]=useState(Math.max(0,Math.ceil((deadline-serverNow)/1000)));const inflight=useRef(false);const clock=useRef({received:Date.now(),server:serverNow});
  useEffect(()=>{setSelected(null);setCode('');setError('');clock.current={received:Date.now(),server:serverNow};setSeconds(Math.max(0,Math.ceil((deadline-serverNow)/1000)))},[q?.id]);
  useEffect(()=>{if(checked)return;const update=()=>setSeconds(Math.max(0,Math.ceil((deadline-(clock.current.server+Date.now()-clock.current.received))/1000)));const t=setInterval(update,250);return()=>clearInterval(t)},[q?.id,checked,deadline]);
  useEffect(()=>{if(seconds>0&&seconds<=5&&!checked)playSound('tick')},[seconds,checked]);
  const check=async()=>{if(inflight.current||checked)return;inflight.current=true;setBusy(true);setError('');try{const next=await api('/api/play/answer',{method:'POST',role:'player',data:{questionId:q.id,value:q.type==='test'?selected:code}});playSound(next.feedback.ratio>0?'correct':'wrong');onUpdate(next)}catch(e){setError(e.message)}finally{inflight.current=false;setBusy(false)}};
  useEffect(()=>{if(seconds===0&&!checked)check()},[seconds,checked,q?.id]);
  const next=async()=>{if(inflight.current)return;inflight.current=true;setBusy(true);setError('');try{const data=await api('/api/play/next',{method:'POST',role:'player',data:{questionId:q.id}});if(data.finished)playSound('finish');onUpdate(data)}catch(e){setError(e.message)}finally{inflight.current=false;setBusy(false)}};
  if(!q)return null;
  const myRank=Math.max(1,game.ranking.findIndex(p=>p.id===current.id)+1);
  const arenaState=grade?(grade.ratio>0?'correct':'wrong'):'idle';
  return <div className="play-page"><header><div className="play-title">{quiz.title}</div><div className="play-progress"><span>{index+1} / {quiz.questionCount}</span><div><i style={{width:`${((index+1)/quiz.questionCount)*100}%`}}/></div></div><div className="score-pill"><Trophy/> {current.score}</div></header><div className="play-arena"><Arena state={arenaState} compact/><div className="play-arena-copy"><span>3D BILIM ARENA</span><b>{grade?(grade.ratio>0?'Zo‘r! Tayyor “Punch” animatsiyasi ishga tushdi.':'Keyingi savolda yana urinib ko‘ring.'):'Savolga javob bering — qahramon natijaga mos harakat qiladi.'}</b><small>Model ichidagi tayyor rig va animation clip’lar ishlatilmoqda.</small></div></div><main key={q.id} className="question-enter"><div className="question-top"><span className={`q-type ${q.type}`}><Code2/>{questionTypes[q.type]} · {q.subject||quiz.subject}</span><div className={`timer ${seconds<=5?'urgent':''}`} aria-label="Qolgan vaqt"><Clock3/>{seconds}s</div></div><h1>{q.text}</h1>
    {q.type==='test'?<div className="answer-grid">{q.options.map((op,i)=><button disabled={checked||busy} onClick={()=>setSelected(i)} className={`${selected===i?'selected':''} ${checked&&i===grade.correctIndex?'right':''} ${checked&&selected===i&&i!==grade.correctIndex?'wrong':''}`} key={i}><span>{String.fromCharCode(65+i)}</span><b>{op}</b>{selected===i&&<i><Check/></i>}</button>)}</div>:q.type==='shortcut'?<ShortcutInput value={code} onChange={setCode} disabled={checked||busy}/>:<><div className={`code-editor ${q.type==='prompt'?'prompt-editor':''}`}><div className="code-head"><span/><span/><span/><small>{q.type==='prompt'?'Prompt studiyasi':q.subject==='Excel'?'Formula laboratoriyasi':'Amaliy javob'}</small></div><textarea aria-label={q.type==='prompt'?'Prompt javobi':'Amaliy javob'} disabled={checked||busy} spellCheck="false" maxLength={8000} value={code} onChange={e=>setCode(e.target.value)} placeholder={q.type==='prompt'?'Maqsad, auditoriya, kontekst va javob formatini yozing...':'Javobingizni shu yerga yozing...'}/></div>{q.type==='prompt'&&<div className="rubric-hints"><b>Mezonlar</b>{q.criteria.map((c,i)=><span key={i}>{c.label}</span>)}<small>Kalit so‘zlar bo‘yicha mashq bahosi. Mazmunni o‘qituvchi ko‘rib chiqadi.</small></div>}</>}
    {error&&<p className="form-error" role="alert">{error}</p>}
    {!checked?<button className="btn btn-primary check-btn" onClick={check} disabled={busy||(seconds>0&&((q.type==='test'&&selected===null)||(q.type!=='test'&&!code.trim())))}>{busy?'Yuborilmoqda…':seconds===0?'Natijani olish':'Javobni yuborish'} <ChevronRight/></button>:<><div className={`feedback ${grade.ratio>0?'success':'failure'}`} role="status"><div className="feedback-icon">{grade.ratio>0?<Check/>:<X/>}</div><div><h3>{grade.expired?'Vaqt tugadi':grade.correct?'Ajoyib! To‘g‘ri javob':grade.ratio>0?'Mezonlarning bir qismi bajarildi':'Bu safar xato'}</h3><p>+{current.lastEarned} ball</p></div><div className="mini-rank"><Medal/><span>Hozirgi o‘rin<b>{myRank}-o‘rin</b></span></div><button className="btn btn-primary" disabled={busy} onClick={next}>{busy?'Yuklanmoqda…':index===quiz.questionCount-1?'Yakunlash':'Keyingi savol'} <ChevronRight/></button></div><div className="answer-explanation">{q.type!=='test'&&<p><b>Namuna javob:</b> {grade.answer}</p>}{grade.explanation&&<p>{grade.explanation}</p>}{grade.checks.map((c,i)=><span className={c.passed?'criterion-pass':'criterion-fail'} key={i}>{c.passed?'✓':'○'} {c.label}</span>)}</div></>}
  </main></div>
}

function Result({quiz,player,db,onHome}){
  const rows=rankRows(db.players.filter(p=>p.quizId===quiz.id));const rank=rows.findIndex(p=>p.id===player.id)+1||1;const icons=['🥇','🥈','🥉'];
  return <div className="result-page"><Celebration/><div className="confetti c1">◆</div><div className="confetti c2">●</div><div className="confetti c3">▲</div><Brand light/><div className="result-layout"><Arena state="victory" compact label="TEST YAKUNLANDI"/><div className="result-card"><div className="result-avatar"><Avatar3D value={player.avatar} large/><i>{icons[rank-1]||<Medal/>}</i></div><div className="eyebrow"><Sparkles/> TEST YAKUNLANDI</div><h1>Barakalla, {player.name}!</h1><p>“{quiz.title}” testini muvaffaqiyatli yakunladingiz.</p><div className="result-rank"><small>SIZNING O‘RNINGIZ</small><strong>{rank}<sup>-o‘rin</sup></strong></div><div className="result-stats"><div><Trophy/><span><b>{player.score}</b>Jami ball</span></div><div><Check/><span><b>{player.correct} / {quiz.questions.length}</b>To‘g‘ri javob</span></div><div><Zap/><span><b>{Math.round(player.score/Math.max(1,quiz.questions.length))}</b>O‘rtacha ball</span></div></div><button className="btn btn-primary wide" onClick={onHome}><Home/> Bosh sahifaga qaytish</button></div></div></div>
}

export default App;
