import React,{useMemo,useState} from 'react';
import {BookOpen,Check,ChevronRight,LocateFixed,X,RotateCcw} from 'lucide-react';
import {benchById,benchEquipment} from './chemistry-bench-content.js';
import {tutorialState} from './chemistry-bench-tutorial.js';

const conditions=s=>[`${s.temperature} °C`,s.stir!==undefined?`Aralashtirish ${s.stir?'yoqilgan':'o‘chirilgan'}`:null,s.evaporated!==undefined?`Bug‘latish ${s.evaporated}%`:null,s.filtered?'Filtrlash bajarilgan':null,s.oxygen!==undefined?`Kislorod ${s.oxygen?'bor':'yo‘q'}`:null,s.rustDays!==undefined?`${s.rustDays} model kuni`:null].filter(Boolean);
export default function BenchTutorial({missionId,parameters,trials,onLocate,onNewSample,onHelp}){
 const [open,setOpen]=useState(missionId!=='free'),state=useMemo(()=>tutorialState(missionId,parameters,trials),[missionId,parameters,trials]),{guide,completed,done,round,steps,current,warning}=state;
 if(!open)return <button className="cb-tutorial-open" onClick={()=>{setOpen(true);onHelp?.()}}><BookOpen size={19}/><span><b>Bosqichli qo‘llanma</b><small>Qaysi modda, qancha miqdor, qaysi jihoz?</small></span><ChevronRight size={18}/></button>;
 return <section className="cb-tutorial" aria-label="Virtual tajriba qo‘llanmasi"><header><div><small>BOSQICHLI QO‘LLANMA · FAQAT VIRTUAL MODEL</small><h3>{done?'Taqqoslash tayyor':`${completed+1}/${guide.rounds.length} namuna · ${round.title}`}</h3></div><button aria-label="Qo‘llanmani yopish" onClick={()=>setOpen(false)}><X size={18}/></button></header><p className="cb-tutorial-intro">{guide.intro}</p>{!done&&<><ol className="cb-tutorial-steps" tabIndex={0} aria-label="Qo‘llanma bosqichlari">{steps.map((s,i)=><li key={s.id} className={s.ok?'complete':s.id===current?.id?'current':''} aria-current={s.id===current?.id?'step':undefined}><span>{s.ok?<Check size={13}/>:i+1}</span>{s.title}</li>)}</ol><div className="cb-tutorial-grid"><div className="cb-tutorial-task"><b>{current?.title}</b><p>{current?.text}</p>{current?.id==='equipment'&&<strong>{benchEquipment.find(e=>e.id===round.equipment)?.name}</strong>}{current?.id==='conditions'&&<ul>{conditions(round.settings).map(c=><li key={c}>{c}</li>)}</ul>}{warning&&<p className="cb-tutorial-warning" role="status">{warning}</p>}<div className="cb-tutorial-actions"><button className="cb-primary" onClick={()=>{onLocate?.(warning?{target:'additions'}:current,round);onHelp?.()}}><LocateFixed size={16}/> Qayerdaligini ko‘rsat</button>{parameters.additions.length>0&&<button onClick={()=>onNewSample?.()}><RotateCcw size={16}/> Yangi namuna uchun stolni tozalash</button>}</div></div><div className="cb-tutorial-recipe"><small>SHU NAMUNA UCHUN</small><div className="cb-recipe-items">{round.ingredients.map(i=><div key={i.substance}><span className="cb-recipe-bottle" style={{'--reagent':benchById[i.substance].color}} aria-hidden="true"><b>{benchById[i.substance].formula}</b></span><span><b>{benchById[i.substance].name}</b><small>{i.amount} {benchById[i.substance].unit}{['hcl','naoh','vinegar','cacl2','carbonate'].includes(i.substance)?` · ${i.concentration} mol/l`:''}</small></span></div>)}</div><details><summary>Nimaga e’tibor beraman?</summary><p>{round.observe}</p><p>{round.why}</p></details></div></div><p className="cb-tutorial-note">Bu miqdorlar simulyatsiyadagi taqqoslash namunalari. Ular haqiqiy laboratoriyada mustaqil tajriba bajarish uchun retsept emas.</p></>}{done&&<div className="cb-tutorial-done" role="status"><Check size={24}/><div><b>Barcha {guide.rounds.length} namuna yig‘ildi va natijalari saqlandi.</b><p>Pastdagi jadvalda natijalarni solishtiring. Tajriba daftariga o‘z kuzatishingiz va xulosangizni yozing.</p><button onClick={()=>onLocate?.({target:'notebook'})}>Tajriba daftariga o‘tish <ChevronRight size={16}/></button></div></div>}</section>
}
