import React,{useEffect,useRef,useState} from 'react';
import {RotateCcw,RotateCw,ZoomIn,ZoomOut,Home,Box,Layers} from 'lucide-react';
export default function BiologyWorld({topic,p,q,fallback}){
 const host=useRef(null),engine=useRef(null),latest=useRef({p,q}),[view,setView]=useState('3d'),[status,setStatus]=useState('loading'),[parts,setParts]=useState([]),[selected,setSelected]=useState(null);latest.current={p,q};
 useEffect(()=>{if(view!=='3d')return;let gone=false,failed=false;const fail=()=>{if(gone)return;failed=true;setStatus('fallback');engine.current?.dispose();engine.current=null};setStatus('loading');if(!window.WebGLRenderingContext||!window.ResizeObserver){fail();return}const timer=setTimeout(fail,8000);import('./biology-world-3d.js').then(({mountBiologyWorld})=>{if(gone||failed)return;try{engine.current=mountBiologyWorld(host.current,topic.scene,latest.current,{onReady:()=>{clearTimeout(timer);if(!gone)setStatus('ready')},onFail:fail,onParts:setParts,onSelect:setSelected})}catch{fail()}}).catch(fail);return()=>{gone=true;clearTimeout(timer);engine.current?.dispose();engine.current=null}},[view,topic.scene]);
 useEffect(()=>engine.current?.update({p,q}),[p,q]);
 const act=(name,value)=>engine.current?.[name](value),ready=view==='3d'&&status==='ready';
 return <section className="bio-world" aria-label={`${topic.title}: boshqariladigan model`}><div className="bio-world-toolbar"><div role="group" aria-label="Model ko‘rinishi"><button aria-pressed={view==='3d'} onClick={()=>setView('3d')}><Box size={16}/>3D model</button><button aria-pressed={view==='2d'} onClick={()=>setView('2d')}><Layers size={16}/>Izohli chizma</button></div><span>{ready?'Aylantiring · yaqinlashtiring':view==='2d'?'Qismlarni bosib o‘rganing':'Chizma hozirdan ishlaydi'}</span></div><div className={`bio-world-stage bio-world-${status}`}><div ref={host} className="bio-world-canvas" style={{visibility:ready?'visible':'hidden',position:ready?'relative':'absolute'}} tabIndex={ready?0:-1} role="group" aria-label="3D model. Chap va o‘ng tugmalari aylantiradi, yuqori va past tugmalari masofani o‘zgartiradi, Home boshlang‘ich ko‘rinish." onKeyDown={e=>{const keys={ArrowLeft:['rotate',-.2],ArrowRight:['rotate',.2],ArrowUp:['zoom',.9],ArrowDown:['zoom',1.1],Home:['reset']};if(keys[e.key]){e.preventDefault();act(...keys[e.key])}}}/>{!ready&&fallback}{view==='3d'&&status==='loading'&&<p className="bio-world-loading" role="status">3D sahna ochilmoqda…</p>}{view==='3d'&&status==='fallback'&&<p className="bio-world-fallback">Bu qurilmada 3D ochilmadi. Interaktiv chizma orqali davom eting.</p>}</div>{ready&&<><div className="bio-world-camera" role="group" aria-label="3D kamerani boshqarish"><button aria-label="Modelni chapga aylantirish" onClick={()=>act('rotate',-.3)}><RotateCcw size={18}/></button><button aria-label="Modelni o‘ngga aylantirish" onClick={()=>act('rotate',.3)}><RotateCw size={18}/></button><button aria-label="Modelga yaqinlashish" onClick={()=>act('zoom',.85)}><ZoomIn size={18}/></button><button aria-label="Modeldan uzoqlashish" onClick={()=>act('zoom',1.15)}><ZoomOut size={18}/></button><button aria-label="Model kamerasini tiklash" onClick={()=>act('reset')}><Home size={18}/></button></div><div className="bio-world-parts" role="group" aria-label="Model qismlari">{parts.map(part=><button key={part.name} aria-pressed={selected?.name===part.name} onClick={()=>act('select',part.name)}>{part.name}</button>)}</div><p className="bio-world-detail" aria-live="polite">{selected?<><b>{selected.name}.</b> {selected.description}</>:'Model qismiga yoki uning nomiga bosing. Harakatni pastdagi vaqt shkalasi boshqaradi.'}</p></>}<p className="bio-model-note">Hajm, rang va zarracha o‘lchamlari tushunishni osonlashtirish uchun soddalashtirilgan. Hisoblar va jarayon bir xil tajriba parametrlariga bog‘langan.</p></section>
}
