import {getSupabase} from './supabase-sdk.js';
function check(e){if(!e)return;if(['42P01','PGRST205'].includes(e.code))throw Error('Ustoz ishlari uchun supabase-biology-atlas.sql migratsiyasini RUN qiling.');throw Error(e.message||'Biologiya ma’lumoti saqlanmadi.')}
async function fixture(path,data){if(globalThis.__SINFQUIZ_LEGACY_TEST__!==true)return null;const r=await fetch(`/api/biology/${path}`,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});if(!r.ok)throw Error('Sinov serveri javob bermadi');return r.json()}
export async function biologyLoad(){const f=await fixture('concepts');if(f)return f;const {db}=await getSupabase(),r=await db.from('biology_concepts').select('*').order('updated_at',{ascending:false}).limit(300);check(r.error);return r.data||[]}
export async function biologySave({id,ownerId,data,status,active}){const f=await fixture('save',{id,ownerId,data,status,active});if(f)return f;const s=await getSupabase();if(s.auth.currentUser?.uid!==ownerId)throw Error('Faqat muallif tahrirlaydi.');const v={owner_id:ownerId,data,status,active},r=id?await s.db.from('biology_concepts').update(v).eq('id',id).eq('owner_id',ownerId).select().single():await s.db.from('biology_concepts').insert(v).select().single();check(r.error);return r.data}
export async function biologyToggle(id,ownerId,active){const f=await fixture('toggle',{id,ownerId,active});if(f)return f;const s=await getSupabase();if(s.auth.currentUser?.uid!==ownerId)throw Error('Faqat muallif faollashtiradi.');const r=await s.db.from('biology_concepts').update({active}).eq('id',id).eq('owner_id',ownerId);check(r.error)}
export async function biologyReview(id,status){const f=await fixture('review',{id,status});if(f)return f;const {db}=await getSupabase(),r=await db.from('biology_concepts').update({status}).eq('id',id);check(r.error)}
export async function biologyDelete(id,ownerId){const f=await fixture('delete',{id,ownerId});if(f)return f;const s=await getSupabase();if(s.auth.currentUser?.uid!==ownerId)throw Error('Faqat muallif o‘chiradi.');const r=await s.db.from('biology_concepts').delete().eq('id',id).eq('owner_id',ownerId);check(r.error)}
export async function biologyObservations(){const f=await fixture('observations');if(f)return f;const {db}=await getSupabase(),r=await db.from('biology_observations').select('*').order('created_at',{ascending:false}).limit(500);check(r.error);return r.data||[]}
export async function biologyRecord({conceptId,user,prediction,observation,conclusion,trials,token}){const row={concept_id:conceptId,student_id:user.id,student_name:(user.name||'O‘quvchi').slice(0,80),prediction,observation,conclusion,trials,client_token:token},f=await fixture('record',row);if(f)return f;const {db}=await getSupabase(),r=await db.from('biology_observations').insert(row).select().single();if(r.error?.code==='23505')return {duplicate:true};check(r.error);return r.data}
export async function biologyFeedback(id,feedback){const f=await fixture('feedback',{id,feedback});if(f)return f;const {db}=await getSupabase(),r=await db.from('biology_observations').update({feedback}).eq('id',id);check(r.error)}
