// Original Uzbek content. Model assumptions and source references: BIOLOGY-SOURCES.md.
const n=(key,label,initial,min,max,step=1,unit='')=>({key,label,initial,min,max,step,unit,type:'number'}),e=(key,label,initial,options)=>({key,label,initial,options,type:'enum'});
const water=n('water','Namlik',60,0,100,5,'%'),temperature=n('temperature','Harorat',20,0,45,1,'°C'),oxygen=n('oxygen','Kislorod mavjudligi',100,0,100,10,'%'),soil=e('soil','Tuproq turi','humus',[['sand','Qumli'],['clay','Loyli'],['humus','Chirindili qumoq']]),light=n('light','Yorug‘lik darajasi',70,0,100,5,'%');
export const biologyScenes={
 cell:{title:'Hujayra',controls:[e('cell','Hujayra turi','plant',[['plant','O‘simlik'],['animal','Hayvon']]),e('layer','Ko‘rish qatlami','whole',[['whole','Butun hujayra'],['membrane','Membrana'],['nucleus','Yadro'],['energy','Energiya organoidlari']])]},
 leaf:{title:'Bargning sayohati',controls:[water,temperature,oxygen,soil,n('rain','Virtual yomg‘ir',30,0,60,5,'mm'),n('leaves','Quruq barg massasi',100,20,300,10,'g')]},
 soil:{title:'Suvning singishi',controls:[soil,n('rain','Yomg‘ir qatlami',30,0,60,5,'mm'),n('compaction','Zichlanish',20,0,100,10,'%')]},
 compost:{title:'Parchalovchilar',controls:[water,temperature,oxygen,n('bacteria','Bakteriyalar ishtiroki',100,0,100,10,'%'),n('fungi','Zamburug‘lar ishtiroki',100,0,100,10,'%'),n('worms','Tuproq jonivorlari',50,0,100,10,'%')]},
 seed:{title:'Unish',controls:[water,temperature,oxygen,n('seeds','Urug‘lar soni',10,5,30,1,'ta')]},growth:{title:'O‘sish',controls:[light,water]},photosynthesis:{title:'Fotosintez',controls:[light,water,n('co2','CO₂ mavjudligi',70,0,100,5,'%')]},
 transport:{title:'Ksilema va floema',controls:[water,light,e('vessel','O‘tkazuvchi to‘qima','xylem',[['xylem','Ksilema: suv va minerallar'],['phloem','Floema: organik moddalar']])]},
 pollination:{title:'Changlanish',controls:[e('carrier','Chang tashuvchi','insect',[['insect','Hasharot'],['wind','Shamol']]),n('visits','Tashuvchining yetib kelishi',5,0,10,1,'marta'),e('compatible','Chang mosligi','yes',[['yes','Mos chang'],['no','Mos bo‘lmagan chang']])]},
 habitat:{title:'Hayvon va muhit',controls:[e('animal','Hayvon guruhi','fish',[['fish','Baliq'],['frog','Amfibiya'],['reptile','Sudralib yuruvchi'],['bird','Qush'],['mammal','Sutemizuvchi'],['insect','Hasharot'],['worm','Halqali chuvalchang'],['mollusc','Mollyuska'],['cnidarian','Bo‘shliqichli']]),e('habitat','Yashash muhiti','water',[['water','Suv'],['land','Quruqlik'],['soil','Nam tuproq']])]},
 adaptation:{title:'Tumshuq va ozuqa',controls:[e('beak','Tumshuq shakli','seed',[['seed','Qisqa, baquvvat'],['insect','Ingichka, uchli'],['nectar','Uzun, tor']]),e('food','Ozuqa turi','seed',[['seed','Qattiq urug‘'],['insect','Hasharot'],['nectar','Gul nektari']])]},
 lifecycle:{title:'Hayot davri',controls:[e('organism','Organizm','frog',[['frog','Qurbaqa'],['butterfly','Kapalak'],['plant','Gulli o‘simlik']])]},foodchain:{title:'Oziq zanjiri',controls:[n('grass','Boshlang‘ich o‘t indeksi',70,10,100,5),n('rabbits','O‘txo‘r indeksi',20,0,60,5),n('foxes','Yirtqich indeksi',4,0,15,1)]},
 anatomy:{title:'Odam tanasi',controls:[]},breathing:{title:'Nafas mexanikasi',controls:[n('depth','Nafas chuqurligi',70,20,100,5,'%'),n('cycles','Ko‘rsatiladigan sikllar',3,1,6,1)]},circulation:{title:'Qon aylanishi',controls:[n('cycles','Ko‘rsatiladigan doiralar',1,1,3,1)]},digestion:{title:'Hazm yo‘li',controls:[e('meal','Asosiy oziqa','carbohydrate',[['carbohydrate','Uglevod'],['protein','Oqsil'],['fat','Yog‘']]),n('portion','Shartli oziqa miqdori',10,5,20,1,'birlik')]},movement:{title:'Bo‘g‘im va mushak',controls:[n('angle','Tirsakning bukilishi',90,0,140,5,'°')]},reflex:{title:'Refleks',controls:[e('path','Signal yo‘li','reflex',[['reflex','Himoya refleksi'],['conscious','Ongli sezgi']])]},senses:{title:'Sezgi',controls:[e('sense','Sezgi','vision',[['vision','Ko‘rish'],['hearing','Eshitish'],['touch','Teri sezgisi']])]},excretion:{title:'Nefron',controls:[n('reabsorption','Suv qayta so‘rilishi',80,50,95,5,'%')]},endocrine:{title:'Qayta aloqa',controls:[n('meal','Ovqatdan keyingi shartli signal',60,0,100,10)]},immunity:{title:'Himoya',controls:[n('barrier','Tashqi to‘siq samarasi',80,0,100,10,'%'),n('response','Immun javob',70,0,100,10,'%')]},reproduction:{title:'Irsiyat',controls:[e('stage','Jarayon','meiosis',[['meiosis','Gameta hosil bo‘lishi'],['fertilisation','Urug‘lanish']])]}
};
const rows=[
 ['plant-cell','O‘simlik hujayrasi',5,'Botanika','O‘simlikning eng kichik tirik birligi nima?','Hujayra organizmning tuzilish va faoliyat birligidir. O‘simlik hujayrasida membrana, devor, yadro va vakuola bor.','Membrana almashinuvni tartiblaydi, devor tayanch beradi. Fotosintez qiladigan hujayralarda xloroplast bo‘ladi.','Yashil barg hujayralari yorug‘likni o‘zlashtiradi.','Har bir o‘simlik hujayrasida xloroplast bo‘lishi shart emas. Organoidlar masshtabi umumlashtirilgan.','cell',[]],
 ['root','Ildiz va ildiz tukchalari',6,'Botanika','Suv ildizga qayerdan kiradi?','Ildiz tukchalari tuproq bilan aloqa yuzasini oshiradi. Suv va ayrim mineral ionlar ildizdan ksilemaga o‘tadi.','Suv potensiali va membrana transporti muhim; ionlarning kirishi faqat suv oqimiga bog‘liq emas.','Ko‘chat ildizi tuproq g‘ovaklaridagi suvdan foydalanadi.','Ildiz butun bargni so‘rmaydi. Organik uglerodning asosiy manbasi havodagi CO₂.','transport',['plant-cell']],
 ['stem','Poya: ksilema va floema',7,'Botanika','Bir poyada ikki xil transport bormi?','Ksilema asosan suv va minerallarni yuqoriga olib boradi. Floema organik moddalarni manbadan talab joyiga yetkazadi.','Transpiratsiya suv oqimiga yordam beradi. Floema yo‘nalishi manba va iste’mol yoki saqlash joyiga bog‘liq.','Bargdan shakar ildiz va mevalarga yetkaziladi.','Floema doimo faqat pastga oqmaydi. Sahna barg manba, ildiz talab joyi holatini tanlagan.','transport',['root']],
 ['leaf','Bargning tuzilishi',6,'Botanika','Barg yorug‘lik va havoni qanday oladi?','Barg tomirlari transportda, og‘izchalar gaz almashinuvi va suv bug‘i chiqishida qatnashadi.','Yorug‘lik, suv va CO₂ fotosintezga kerak; og‘izchalar suv yo‘qotishiga ham ta’sir qiladi.','Yashil bargning keng yuzasi yorug‘lik tutadi.','O‘simlik faqat fotosintez qilmaydi: tirik hujayralari kecha-kunduz nafas oladi.','photosynthesis',['plant-cell']],
 ['photosynthesis','Fotosintez: kirish va chiqish',8,'Botanika','Yorug‘lik energiyasi qanday saqlanadi?','Fotosintez yorug‘lik yordamida CO₂ dan organik modda hosil qiladi. Umumiy modelda suv sarflanib, O₂ ajraladi.','Yorug‘lik energiyasi organik birikmalarda saqlanadi. Ajraladigan kislorod suvdan keladi.','Ko‘p oziq zanjirlari fotosintez qiluvchi ishlab chiqaruvchilardan boshlanadi.','Netto tenglama barcha oraliq bosqichlar emas. Mineral oziqa organik uglerod yoki energiya manbasi bilan bir xil emas.','photosynthesis',['leaf']],
 ['seed','Urug‘dan niholgacha',5,'Botanika','Urug‘ga unish uchun nima kerak?','Embrion mos namlik, harorat va kislorodda unishi mumkin. Dastlab urug‘ zaxiralaridan foydalanadi.','Suv almashinuv jarayonlarini faollashtiradi; kislorod nafas olishga kerak. Suv bosishi aeratsiyani kamaytirishi mumkin.','Loviya niholida ildiz odatda poyadan oldin chiqadi.','Bu tinim holatida bo‘lmagan shartli bog‘ urug‘i. Barcha turlarning yorug‘lik va harorat talabi bir xil emas.','seed',[]],
 ['growth','Yorug‘lik, suv va o‘sish',7,'Botanika','Ko‘p suv doimo ko‘proq o‘sishmi?','O‘sish hujayralar bo‘linishi va kattalashishi bilan bog‘liq. Bir necha muhit omili birgalikda ta’sir qiladi.','Kam suv cheklaydi; ortiqcha suv ildiz aeratsiyasini kamaytirishi mumkin. Boshqa omillar modelda yetarli.','Bir xil navning ko‘chatlari turli sharoitda turlicha o‘sadi.','O‘sish indeksi haqiqiy santimetr yoki hosil bashorati emas.','growth',['seed','photosynthesis']],
 ['flower','Gul: changlanish va urug‘lanish',7,'Botanika','Chang urug‘ga qanday aloqador?','Changlanish changning urug‘chi tumshuqchasiga ko‘chishidir. Mos chang naychasi urug‘kurtakka yetgach urug‘lanish bo‘lishi mumkin.','Changlanish va urug‘lanish ikki bosqich. Urug‘kurtak urug‘ga, tuxumdon ko‘pincha mevaning asosiy qismiga aylanadi.','Hasharot yoki shamol changni boshqa gulga tashiydi.','Mos bo‘lmagan chang urug‘lanishni kafolatlamaydi. Qo‘sh urug‘lanishning barcha bosqichlari bu sahnada yo‘q.','pollination',['seed']],
 ['plant-cycle','O‘simlik hayot davri',8,'Botanika','Urug‘dan keyingi avlodgacha qanday yo‘l bor?','Urug‘dan nihol, yetuk o‘simlik, gul va yangi urug‘ bosqichlari bog‘langan.','O‘sish va ko‘payish bir xil jarayon emas. Har bosqichning davomiyligi turga va muhitga bog‘liq.','Bir yillik o‘simlik yangi urug‘lar orqali keyingi avlodni beradi.','Slayder teng vaqt emas, bosqichlar ketma-ketligini ko‘rsatadi. Vegetativ ko‘payish alohida yo‘l.','lifecycle',['flower']],
 ['animals','Hayvonlar guruhlari va tuzilishi',5,'Zoologiya','Muhit va tana tuzilishi qanday bog‘liq?','Hayvon guruhlari tana qoplami, harakat, nafas va ko‘payish belgilariga ko‘ra farqlanadi.','Sahnada har guruhdan bitta umumlashtirilgan vakil tanlangan. Uning tana qismlari yashash usuliga yordam beradi.','Baliq jabra, chuvalchang nam teri orqali gaz almashinadi.','Bir guruhning barcha vakillari bir xil muhitda yashamaydi. Mollyuska misoli quruqlik chig‘anog‘i.','habitat',[]],
 ['fish','Baliq: suvda harakat va jabra',6,'Zoologiya','Baliq suvdan kislorodni qanday oladi?','Jabralar suvda erigan kislorodni olishga yordam beradi. Tana va suzgichlar harakat va muvozanatda qatnashadi.','Suv jabra yuzasidan o‘tadi. Ko‘p baliqlarning oqimli tana shakli suv qarshiligini kamaytiradi.','Akvarium baliqlari suvdagi gaz almashinuviga bog‘liq.','Baliq suv molekulasini parchalab kislorod olmaydi; suvda erigan O₂ dan foydalanadi.','habitat',['animals']],
 ['bird','Tumshuq shakli va ozuqa',7,'Zoologiya','Tumshuq ozuqani olishga qanday yordam beradi?','Tumshuq shakli ozuqani olish usuliga bog‘liq bo‘lishi mumkin. Qisqa baquvvat, uchli va uzun shakllarni taqqoslang.','Model uch ixtisoslashgan shaklni tanlaydi. Xulq, ozuqa mavjudligi va tur ham natijaga ta’sir qiladi.','Donxo‘r qush urug‘ni, nektarxo‘r qush guldagi suyuqlikni oladi.','Moslanish bir hayvon slayderni surishi bilan evolyutsion o‘zgarish yuz berishi degani emas.','adaptation',['animals']],
 ['animal-cycle','Metamorfoz va hayot davri',6,'Zoologiya','Lichinka va yetuk hayvon bir xilmi?','Kapalak tuxum, qurt, g‘umbak, yetuk bosqichlardan o‘tadi. Qurbaqa tuxumdan itbaliq va yetuk hayvonga rivojlanadi.','Bosqichlarda tuzilma, oziqlanish va muhit talabi farqlanishi mumkin.','Kapalak qurti va yetuk kapalak ozuqani turlicha oladi.','Bosqichlar teng vaqt davom etmaydi. Barcha hayvonlarda metamorfoz bo‘lmaydi.','lifecycle',['animals']],
 ['food-chain','Oziq zanjiri va populyatsiya',8,'Zoologiya','Bitta tur o‘zgarsa boshqalariga nima bo‘ladi?','Ishlab chiqaruvchi, o‘txo‘r va yirtqich oziqlanish orqali bog‘langan. Sonlar birga vaqt bo‘yicha o‘zgaradi.','O‘txo‘rlik o‘simlikni, yirtqichlik o‘txo‘rni kamaytiradi; ozuqa ularga o‘sish imkonini beradi.','Yaylov o‘ti, quyon va yirtqich orasidagi bog‘lanish.','Bu yopiq shartli zanjir, haqiqiy daladagi populyatsiya bashorati emas; migratsiya va kasalliklar kiritilmagan.','foodchain',['animals','photosynthesis']],
 ['human-cell','Hujayra → to‘qima → organ',7,'Odam tanasi','Bir xil hujayralar turli ish bajara oladimi?','Odam hujayralari ixtisoslashadi. To‘qimalar va organlar birgalikda tizimlarni hosil qiladi.','Umumlashtirilgan eukariot hujayrada membrana, yadro va mitoxondriya vazifalarini oching.','Mushak va nerv to‘qimalari turlicha tuzilma va vazifaga ega.','Bu barcha odam hujayrasining nusxasi emas: masalan, yetuk eritrotsit yadrosiz.','cell',['plant-cell']],
 ['anatomy','Odam tanasini qatlamlarda ochish',8,'Odam tanasi','Organlar tananing qayerida?','Organlar o‘zaro bog‘langan tizimlar bo‘lib ishlaydi. Tana qatlamlarini ochib, joylashuv va aloqalarni ko‘ring.','Yurak o‘pkalar orasida biroz chapda; jigar asosan o‘ng yuqori qorin qismida; buyraklar orqaroqda.','Nafas, qon aylanish va hazm hujayralarni ta’minlashda hamkorlik qiladi.','Chap/o‘ng odamning o‘z tomoni. BodyParts3D katta yoshli odamning tayanch sirt modelidir. Rang, kesim va harakat o‘quv maqsadida moslashtirilgan; tibbiy tashxis uchun emas.','anatomy',['human-cell']],
 ['movement','Skelet va mushaklar hamkorligi',8,'Odam tanasi','Mushak suyakka qanday ta’sir qiladi?','Mushak pay orqali suyakka birikadi. Qisqarish suyaklarni bo‘g‘im atrofida harakatlantiradi.','Suyak richag, bo‘g‘im aylanish joyi; bukuvchi va yozuvchilar hamkorlik qiladi.','Tirsak bukilib, qo‘l buyumni ko‘taradi.','Mushak faol tortadi; bir mushak barcha qarama-qarshi harakatni bajarmaydi. Uzunlik modeli nisbiy.','movement',['anatomy']],
 ['breathing','Nafas: diafragma va o‘pka',8,'Odam tanasi','Havo o‘pkaga nimaning hisobiga kiradi?','Diafragma qisqarib pastlaganda ko‘krak hajmi oshadi. Bosim farqi havo kirishiga yordam beradi.','Chiqarishda diafragma bo‘shashib ko‘tariladi, hajm kamayadi. Alveola va kapillyarda gaz almashinuvi bo‘ladi.','Tinch nafas va chuqur nafasning hajm o‘zgarishini taqqoslang.','O‘pka faol nasos mushagi emas. Hajm indekslari klinik litr o‘lchovi emas.','breathing',['anatomy']],
 ['circulation','Yurak va qonning ikki doirasi',9,'Odam tanasi','Qon o‘pkaga va tanaga qanday boradi?','Yurakning o‘ng tomoni qonni o‘pkaga, chap tomoni tanaga haydaydi. Ikki doira ketma-ket bog‘langan.','Bo‘lmacha qabul qiladi, qorincha chiqaradi; arteriya yurakdan, vena yurakka yo‘naladi.','Kapillyarlarda hujayralar bilan modda almashinuvi bo‘ladi.','Ko‘k rang haqiqiy ko‘k qon emas. O‘pka arteriyasi va venasidagi O₂ nisbatiga e’tibor bering.','circulation',['breathing']],
 ['digestion','Ovqatning hazm yo‘li',8,'Odam tanasi','Ovqat qayerda parchalanadi va so‘riladi?','Ovqat og‘iz, qizilo‘ngach, oshqozon va ichaklar bo‘ylab boradi. Hazm mahsulotlarining ko‘pi ingichka ichakda so‘riladi.','Vorsinkalar so‘rilish yuzasini oshiradi. Ko‘p yog‘ mahsulotlari limfaga, boshqa ko‘p kichik mahsulotlar qonga o‘tadi.','Non, oqsil va yog‘li ovqatlarning kichik tarkibiy qismlari organizmga yetkaziladi.','Ovqat jigar yoki oshqozon osti bezidan o‘tmaydi. Ular ichakka yordamchi moddalar chiqaradi. So‘rilish ulushi shartli.','digestion',['anatomy']],
 ['reflex','Asab va himoya refleksi',9,'Odam tanasi','Javob har doim ongli qarorni kutadimi?','Retseptor ta’sirni sezadi, sezuvchi neyron signalni markazga olib boradi. Harakat neyroni mushak javobiga xizmat qiladi.','Dastlabki himoya refleksi ongli qarorni kutishi shart emas; ongli sezgi yo‘li ham davom etadi.','Qo‘lning yoqimsiz ta’sirdan tortilishi.','Sahna xavfli haqiqiy tajriba yo‘riqnomasi emas. Barcha reflekslar aynan bir xil yo‘lga ega emas.','reflex',['anatomy']],
 ['senses','Ko‘rish, eshitish va teri sezgisi',9,'Odam tanasi','Signal retseptordan miyaga qanday boradi?','Sezgi organlaridagi retseptorlar yorug‘lik, tovush yoki mexanik ta’sirni nerv signaliga aylantirishda qatnashadi.','Signal nerv yo‘llari orqali markazga boradi; idrok miyada qayta ishlash bilan bog‘liq.','Ko‘z to‘r pardasi va quloq chig‘anog‘idagi retseptorlarning yo‘llari.','Ko‘z yoki quloq yakka o‘zi barcha idrokni yaratmaydi. Bu yo‘llar umumlashtirilgan.','senses',['reflex']],
 ['excretion','Buyrak: filtrlash va qayta so‘rilish',10,'Odam tanasi','Filtratning hammasi siydik bo‘ladimi?','Nefron filtrlash, qayta so‘rilish va sekretsiya bilan siydik hosil qilishda qatnashadi. Suvning katta qismi qonga qaytadi.','Qon hujayralari va katta oqsillar dastlabki filtrga odatda o‘tmaydi. Filtrat va oxirgi siydik bir xil emas.','Organizm suv va ayrim tuzlar muvozanatini boshqaradi.','Slayder klinik normal ulush emas; arifmetik taqqoslash uchun. Sekretsiya to‘liq hisoblanmagan.','excretion',['circulation']],
 ['endocrine','Gormonlar: qayta aloqa',10,'Odam tanasi','Organlar masofadan qanday signal oladi?','Gormonlar bezlardan chiqib, nishon hujayralar faoliyatiga ta’sir qiladi. Qayta aloqa signalni boshqaradi.','Ovqatdan keyingi shartli signal, insulin javobi va signal pasayishini kuzating.','Oshqozon osti bezining gormonal boshqaruvdagi roli.','Ko‘rsatilgan indekslar qon tahlili yoki tashxis qiymatlari emas. Barcha metabolik yo‘llar kiritilmagan.','endocrine',['digestion']],
 ['immunity','Organizmning himoya qatlamlari',9,'Odam tanasi','Teri va immun hujayralar qanday hamkor?','Teri va shilliq qavatlar tashqi to‘siq bo‘ladi. Ichki immun javob kirgan begona omillarga qarshi qatnashadi.','To‘siqdan o‘tgan shartli birliklar keyingi javobda kamayadi. Bir necha himoya bosqichi bor.','Teri va shilliq qavat organizmni tashqi muhitdan ajratadi.','Bu kasallik, davolash yoki individual xavf modeli emas. Immun javobning hamma turlari ko‘rsatilmagan.','immunity',['human-cell']],
 ['reproduction','Odamda ko‘payish va irsiyat',10,'Odam tanasi','Gameta va zigotada xromosoma qanday farq qiladi?','Meioz gametaning xromosoma to‘plamini kamaytiradi. Urug‘lanishda ikki gameta irsiy ma’lumotini birlashtiradi.','Odatiy inson modelida 46 dan 23; urug‘lanishda 23+23 dan 46 xromosoma.','Irsiy belgilar keyingi avlodga o‘tadi.','Barcha meioz fazalari, rekombinatsiya va xromosoma istisnolari bu sxemada yo‘q.','reproduction',['human-cell']],
 ['leaf-journey','Bargning tabiatdagi sayohati',6,'Ekologiya','Barg qoldig‘i ildiz oziqasiga qanday bog‘lanadi?','Barg tushgach maydalanib, mikroorganizmlar organik birikmalarini parchalaydi. Bir qismi CO₂ va tuproq organik moddasi, ayrim oziqa elementlari mineral yo‘lga o‘tadi.','Minerallashuv ayrim oziqa elementlarini ildiz oladigan shaklga o‘tkazadi. Chirindining hammasi darhol tayyor mineral o‘g‘it emas.','Kuzgi barglar tuproq hayoti va keyingi o‘simlik avlodiga hissa qo‘shadi.','Barg darhol o‘g‘itga aylanmaydi. Energiya yorug‘likdan, uglerodning asosiy qismi CO₂ dan; model koeffitsiyentlari shartli.','leaf',['leaf','root']],
 ['soil','Tuproq qatlamlari va suv singishi',6,'Ekologiya','Yomg‘ir suvi har bir tuproqda bir xil o‘tadimi?','Tuproq zarrachalari orasidagi g‘ovaklarda suv va havo bo‘ladi. Tuzilma va zichlanish suv o‘tishiga ta’sir qiladi.','Qumli, loyli va chirindili qumoq misollarida singgan, saqlangan va pastga oqgan suvni ajrating.','Yomg‘irdan keyin ayrim yerda ko‘lmak uzoq turadi.','Singgan suvning hammasi saqlanmaydi. Model sig‘imlari dala o‘lchovi emas.','soil',['root']],
 ['compost','Mikroblar, tuproq jonivorlari va kompost',8,'Ekologiya','Parchalovchilar bir xil ishni bajaradimi?','Bakteriyalar va zamburug‘lar kimyoviy parchalaydi; tuproq jonivorlari qoldiqlarni maydalash va aralashtirishga yordam beradi.','Aerob yo‘l namlik, kislorod va haroratga bog‘liq. Ortiqcha suv g‘ovak havosini kamaytirishi mumkin.','Kompost tuproqning organik moddasi va tuzilishiga hissa qo‘shadi.','Chuvalchang yagona parchalovchi emas. Anaerob yo‘llar bor, ammo bu model faqat aerob yo‘lni ko‘rsatadi.','compost',['leaf-journey']],
 ['ecosystem','Ekotizim: moddalar va energiya',11,'Ekologiya','Modda aylanishi energiya oqimi bilan bir xilmi?','Moddalar organizm va muhit o‘rtasida aylanadi; energiya tizimdan o‘tib, issiqlik sifatida tarqaladi.','Ishlab chiqaruvchi, iste’molchi va parchalovchilarni bog‘lang. Ushbu grafik uch darajaning shartli javobini ko‘rsatadi.','Yaylov, tuproq va havodagi moddalar o‘zaro aloqador.','Ekotizim bitta zanjirdan murakkabroq; ko‘p tarmoqli oziq tarmog‘i bu sahnada to‘liq hisoblanmagan.','foodchain',['food-chain','compost']]
];
export const biologyTopics=rows.map(([id,title,grade,group,question,definition,reason,life,misconception,scene,prerequisites])=>({id,title,grade,group,question,definition,reason,life,misconception,scene,prerequisites,keywords:`${group} ${scene}`,parameters:id==='human-cell'?{cell:'animal'}:id==='plant-cycle'?{organism:'plant'}:{}}));
export const biologyById=Object.fromEntries(biologyTopics.map(t=>[t.id,t]));
const labs=[['leaf-journey','Barg parchalanish tezligini taqqoslang','Bir xil barg massasida namlik yoki haroratni almashtiring. 365 model kunidagi qoldiqni solishtiring.',2],['soil','Uch tuproqda suv singishi','Bir xil yomg‘ir miqdorida tuproq turini almashtiring. Singgan va pastga oqgan suvni ajrating.',2],['compost','Kompostda kim nima qiladi?','Mikroblar yoki jonivorlarning ishtirokini o‘zgartiring. Kimyoviy parchalanish va maydalashni farqlang.',2],['seed','Urug‘ uchun sharoit tanlang','Namlik, harorat yoki kisloroddan bittasini almashtiring. Ungan urug‘lar sonini taqqoslang.',2],['growth','Yorug‘lik va suvning o‘sishga ta’siri','Bir omilni o‘zgartirib ikki sinovni bajaring. Boshqa omillar yetarli deb olinganini xulosada ayting.',2],['photosynthesis','Fotosintezning kirish va chiqishi','Yorug‘lik yoki CO₂ ni almashtiring. Sarflangan va hosil bo‘lgan moddalarning nisbatini taqqoslang.',2],['flower','Changdan urug‘lanishgacha','Mos va mos bo‘lmagan chang bilan ikki sinov bajaring. Changlanish va urug‘lanish qayerda ajralishini toping.',2],['bird','Tumshuq va ozuqani moslang','Bir xil ozuqaga ikki tumshuqni solishtiring. Shakldan tashqari yana qaysi omil muhimligini yozing.',2],['food-chain','Oziq zanjiriga aralashing','Boshlang‘ich yirtqich indeksini o‘zgartiring. Uch populyatsiya natijasini birga solishtiring.',2],['breathing','Diafragma va nafasni kuzating','Nafas siklini boshlang, o‘rtada pauza qiling. Diafragma, hajm va havo yo‘nalishini izohlang.',1],['circulation','Qonning ikki doirasini kuzating','Qon yo‘lini to‘liq kuzating. O‘ng va chap qorincha qonni qayerga yuborishini xulosada ayting.',1],['digestion','Ovqat va so‘rilish yo‘li','Ovqat yo‘lini kuzating. Hazm, so‘rilish, qon va limfa yo‘llarini bir-biridan ajrating.',1]];
export const biologyLabs=labs.map(([topicId,title,challenge,minTrials],i)=>({id:`bio-lab-${i+1}`,topicId,title,challenge,minTrials,number:i+1}));export const biologyLabByTopic=Object.fromEntries(biologyLabs.map(l=>[l.topicId,l]));
export const organInfo={
 brain:{name:'Bosh miya',place:'Bosh suyagi ichida',function:'Sezgi, harakat va ko‘plab boshqaruv jarayonlarini muvofiqlashtiradi.',connection:'Orqa miya va nervlar orqali tana bilan aloqa.',inside:'Katta miya yarimsharlari, miyacha va miya ustuni.'},lungs:{name:'O‘pkalar',place:'Ko‘krak qafasida, yurakning ikki tomonida',function:'Alveola-kapillyar chegarasida O₂ va CO₂ almashinuvi.',connection:'Traxeya/bronxlar va kichik qon aylanish doirasi.',inside:'Bronxlar, bronxiolalar va alveolalar.'},heart:{name:'Yurak',place:'O‘pkalar orasida, biroz chapda',function:'Qonni o‘pka va katta doiraga haydaydi.',connection:'Arteriya, vena va kapillyarlar.',inside:'O‘ng/chap bo‘lmacha, o‘ng/chap qorincha va klapanlar.'},liver:{name:'Jigar',place:'Asosan o‘ng yuqori qorin qismida',function:'Modda almashinuvi, qayta ishlash va safro hosil qilish.',connection:'Hazm tizimi va qon tomirlari.',inside:'Jigar hujayralari, tomirlar va o‘t yo‘llari.'},stomach:{name:'Oshqozon',place:'Chap yuqori qorin qismida',function:'Ovqatni aralashtirish va kimyoviy hazmda qatnashish.',connection:'Qizilo‘ngach va o‘n ikki barmoqli ichak.',inside:'Mushak devori va shilliq qavat burmalari.'},intestine:{name:'Ichaklar',place:'Qorin bo‘shlig‘ida',function:'Hazm mahsulotlarini va suvni so‘rish.',connection:'Oshqozon, qon va limfa tomirlari.',inside:'Ingichka ichak vorsinkalari va yo‘g‘on ichak.'},kidneys:{name:'Buyraklar',place:'Qorin orqasida, umurtqaning ikki tomonida',function:'Filtrlash, qayta so‘rilish va sekretsiya orqali siydik hosil qilish.',connection:'Qon tomirlari, siydik naylari va qovuq.',inside:'Po‘stloq, mag‘iz, jom va nefronlar.'},skeleton:{name:'Skelet',place:'Butun tana bo‘ylab ichki tayanch',function:'Tayanch, himoya va harakat richaglari.',connection:'Bo‘g‘im va mushaklar.',inside:'Zich/g‘ovak suyak, ko‘mik va bo‘g‘im yuzasi.'},muscles:{name:'Skelet mushaklari',place:'Suyak va bo‘g‘imlar atrofida',function:'Qisqarib, paylar orqali suyakni tortish.',connection:'Suyak, nerv va qon tomirlari.',inside:'Tolalar tutami, mushak tolalari va pay.'},pancreas:{name:'Oshqozon osti bezi',place:'Oshqozon orqasida',function:'Hazm fermentlari va ayrim gormonlarni chiqarish.',connection:'Ichakka fermentlar, qonga gormonal signal.',inside:'Ferment chiqaruvchi bo‘lakchalar va gormon chiqaruvchi orolchalar.'},skin:{name:'Teri',place:'Tananing tashqi qoplami',function:'Himoya, sezgi va harorat boshqaruvida qatnashish.',connection:'Asab, tomir va bezlar.',inside:'Epidermis, derma va teri osti qavati.'}
};
