import React,{useEffect,useRef,useState} from 'react';
import {Play,Pause,RotateCcw,Download,Send,Check} from 'lucide-react';
import {biologyScenes} from './biology-content.js';import {biologyDefaults,biologyResult} from './biology-model.js';import {biologyRecord} from './biology-service.js';
import {biologyMinTrials,biologyContext,biologyDraftKey,readBiologyDraft,writeBiologyDraft,biologyStorage,distinctBiologyTrials,canFinishBiology} from './biology-workflow.js';import BiologyScene from './BiologyScenes.jsx';
const fmt=n=>Number(n.toFixed(3)).toLocaleString('uz-UZ');
export default function BiologyActivity({topic,user}){
 const context=biologyContext(topic),key=biologyDraftKey(user,topic),[draft]=useState(()=>readBiologyDraft(biologyStorage(),key,context,topic.scene));
 const [p,setP]=useState(()=>biologyDefaults(topic.scene,topic.parameters)),[q,setQ]=useState(0),[running,setRunning]=useState(false),[started,setStarted]=useState(false),[speed,setSpeed]=useState(1),[prediction,setPrediction]=useState(draft?.prediction||''),[observation,setObservation]=useState(draft?.observation||''),[conclusion,setConclusion]=useState(draft?.conclusion||''),[trials,setTrials]=useState(draft?.trials||[]),[finished,setFinished]=useState(draft?.finished===true),[sentKey,setSentKey]=useState(draft?.sentKey||''),[token,setToken]=useState(draft?.token||crypto.randomUUID()),[tokenKey,setTokenKey]=useState(draft?.tokenKey||''),[status,setStatus]=useState(''),[storageState,setStorageState]=useState(''),[busy,setBusy]=useState(false);
 const recorded=useRef(false),snapshot=useRef(null),sending=useRef(false),spec=biologyScenes[topic.scene],result=biologyResult(topic.scene,p,q),ready=prediction.trim().length>=12,canFinish=canFinishBiology({scene:topic.scene,prediction,observation,conclusion,trials}),submissionKey=JSON.stringify([context,prediction,observation,conclusion,trials]);
 snapshot.current={context,prediction,observation,conclusion,trials,finished,sentKey,token,tokenKey};
 useEffect(()=>{const flush=()=>writeBiologyDraft(biologyStorage(),key,snapshot.current);window.addEventListener('pagehide',flush);return()=>{flush();window.removeEventListener('pagehide',flush)}},[key]);
 useEffect(()=>{const t=setTimeout(()=>setStorageState(writeBiologyDraft(biologyStorage(),key,snapshot.current)?'saved':'blocked'),600);return()=>clearTimeout(t)},[prediction,observation,conclusion,trials,finished,sentKey,token,tokenKey,key]);
 useEffect(()=>{if(!running)return;let frame,last=performance.now(),pending=0;const tick=now=>{const elapsed=Math.max(0,Math.min(100,now-last));last=now;if(!document.hidden){pending+=elapsed;if(pending>=1000/30){const delta=pending;pending=0;setQ(v=>Math.min(1,v+delta*speed/10000))}}else pending=0;frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[running,speed]);
 useEffect(()=>{if(q<1)return;setRunning(false);if(recorded.current)return;recorded.current=true;setTrials(t=>[...t,{parameters:{...p},date:new Date().toISOString()}].slice(-6));setFinished(false);setStatus('Sinov tugadi. Natijani kuzatish va xulosaga yozing.')},[q,p]);
 const edit=(setter,v)=>{setter(v);setFinished(false);setStatus('')},change=(c,v)=>{setP(p=>({...p,[c.key]:v}));setFinished(false)},reset=()=>{setRunning(false);setQ(0);setStarted(false);recorded.current=false;setFinished(false);setStatus('Yangi sinov: bitta sharoitni o‘zgartiring.')};
 const download=()=>{const text=`SinfQuiz — Biologiya tajriba daftari\n${topic.title}\nSavol: ${topic.challenge}\nTaxmin: ${prediction}\n${trials.map((t,i)=>`Sinov ${i+1}: ${JSON.stringify(t.parameters)}\nModel: ${JSON.stringify(biologyResult(topic.scene,t.parameters,1).readings)}`).join('\n')}\nKuzatish: ${observation}\nXulosa: ${conclusion}\n${finished?'Yakunlangan':'Qoralama'}`,url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='biologiya-tajriba-daftari.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const submit=async()=>{if(sending.current||!finished||!canFinish||sentKey===submissionKey)return;sending.current=true;setBusy(true);const nextToken=tokenKey===submissionKey?token:(tokenKey||sentKey?crypto.randomUUID():token),attempt=submissionKey;setToken(nextToken);setTokenKey(attempt);try{await biologyRecord({conceptId:topic.dbId,user,prediction,observation,conclusion,trials,token:nextToken});setSentKey(attempt);setStatus('Ish ustozingizga yuborildi. Ustozning fikri natijalar bo‘limida ko‘rinadi.')}catch(e){setStatus(e.message)}finally{sending.current=false;setBusy(false)}};
 const unit={leaf:'365 model kun',compost:'120 model kun',soil:'60 model daqiqa',seed:'14 model kun',growth:'30 model kun'}[topic.scene]||'Jarayon bosqichi';
 return <section className="bio-activity"><div className="bio-question"><small>SAVOL → TAXMIN</small><h2>{topic.challenge}</h2><label>Sinovdan oldingi taxmin<textarea aria-label="Sinovdan oldingi taxmin" rows="2" maxLength={500} value={prediction} onChange={e=>edit(setPrediction,e.target.value)} placeholder="Qaysi parametr qanday ta’sir qiladi deb o‘ylaysiz? Nega?"/></label><small>Sinovni darhol boshlash mumkin. Ishni yakunlash uchun kamida 12 belgilik taxmin yozing.</small></div>
 <div className="bio-workbench"><div className="bio-controls"><h3>Sharoitni tanlang</h3>{spec.controls.map(c=><label key={c.key}><span>{c.label}{c.type==='number'&&<output>{fmt(p[c.key])} {c.unit}</output>}</span>{c.type==='enum'?<select aria-label={c.label} disabled={started} value={p[c.key]} onChange={e=>change(c,e.target.value)}>{c.options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select>:<input aria-label={c.label} type="range" min={c.min} max={c.max} step={c.step} value={p[c.key]} disabled={started} onChange={e=>change(c,+e.target.value)}/>}</label>)}{!spec.controls.length&&<p>Qatlam va organlarni model ichidan tanlang.</p>}<p className="bio-help">{started?'Parametrni almashtirish uchun qayta tayyorlang.':'Bir sinovda bir omilni o‘zgartiring.'}</p><button className="bio-primary" disabled={running} onClick={()=>{if(q===1)reset();setStarted(true);setRunning(true);setFinished(false);if(!ready)setStatus('Sinov boshlandi. Yakunlashdan oldin taxminingizni ham yozing.')}}><Play size={16}/>{q===1?'Yangi sinov':q>0?'Davom ettirish':'Sinovni boshlash'}</button><div className="bio-action-row"><button disabled={!running} onClick={()=>setRunning(false)}><Pause size={16}/> Pauza</button><button onClick={reset}><RotateCcw size={16}/> Qayta tayyorlash</button></div><label>Ko‘rsatish tezligi<select aria-label="Ko‘rsatish tezligi" value={speed} onChange={e=>setSpeed(+e.target.value)}><option value=".5">Sekin · 0,5×</option><option value="1">Oddiy · 1×</option><option value="2">Tez · 2×</option></select></label></div>
 <div className="bio-model"><BiologyScene topic={topic} p={p} q={q} result={result}/><label className="bio-timeline">{unit}<output>{Math.round(q*100)}%</output><input aria-label="Biologik jarayon bosqichi" type="range" min="0" max="100" step="1" value={Math.round(q*100)} disabled={running} onChange={e=>{setStarted(true);setQ(+e.target.value/100)}}/></label><small>Vaqt tezlashtirilgan; dala yoki klinik tajribaning haqiqiy vaqti emas.</small></div></div>
 <div className="bio-readings" aria-live={q===1?'polite':'off'}><h3>{q===1?'Yakuniy kuzatuv':'Joriy kuzatuv'} <small>{result.unit}</small></h3><div>{Object.entries(result.readings).map(([label,v])=><p key={label}><span>{label}</span><strong>{fmt(v)}</strong></p>)}</div><p className="bio-cause">{result.cause}</p></div>
 <section className="bio-comparison"><div className="bio-section-heading"><h3>Sinovlarni solishtiring</h3><button disabled={!trials.length} onClick={()=>{setTrials([]);setFinished(false)}}>Jadvalni tozalash</button></div><p>Talab: {biologyMinTrials(topic.scene)} xil sharoit. Hozir: {distinctBiologyTrials(trials)}. Oxirgi 6 sinov saqlanadi.</p>{trials.length?<div className="bio-table-scroll" tabIndex="0" role="region" aria-label="Biologiya sinovlari jadvali"><table><caption>Parametrlar va yakuniy model hisoblari</caption><thead><tr><th>Sinov</th>{spec.controls.map(c=><th key={c.key}>{c.label}</th>)}{Object.keys(result.readings).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{trials.map((t,i)=>{const tp=biologyDefaults(topic.scene,t.parameters);return <tr key={`${t.date}-${i}`}><th>{i+1}</th>{spec.controls.map(c=><td key={c.key}>{c.type==='enum'?c.options.find(o=>o[0]===tp[c.key])?.[1]:fmt(tp[c.key])}</td>)}{Object.entries(biologyResult(topic.scene,tp,1).readings).map(([k,v])=><td key={k}>{fmt(v)}</td>)}</tr>})}</tbody></table></div>:<p>Sinov yakunlanganda natija shu yerga yoziladi.</p>}</section>
 <section className="bio-notebook"><small>KUZATISH → XULOSA</small><label>Kuzatish<textarea aria-label="Kuzatish" rows="3" maxLength={1200} value={observation} onChange={e=>edit(setObservation,e.target.value)} placeholder="Sharoitlar va natijada nima farq qildi?"/></label><label>Xulosa<textarea aria-label="Xulosa" rows="3" maxLength={1200} value={conclusion} onChange={e=>edit(setConclusion,e.target.value)} placeholder="Taxmin tasdiqlandimi? Sabab va model cheklovi nima?"/></label><p className="bio-help">Har biri kamida 20 belgi. Ustoz dalil va izohni ko‘rib chiqadi; avtomatik imtihon bahosi yo‘q.</p><div className="bio-action-row"><button className="bio-primary" disabled={!canFinish||finished} onClick={()=>{setFinished(true);setStatus('Ish yakunlandi. Daftarni yuklab yoki ustozga yuborishingiz mumkin.')}}><Check size={16}/>{finished?'Ish yakunlangan':'Ishni yakunlash'}</button><button onClick={download}><Download size={16}/> Daftarni yuklash</button>{topic.dbId&&<button disabled={!finished||!canFinish||busy||sentKey===submissionKey} onClick={submit}><Send size={16}/>{busy?'Yuborilmoqda…':sentKey===submissionKey?'Ustozga yuborilgan':'Ustozga yuborish'}</button>}</div>{!topic.dbId&&<p className="bio-help">Mustaqil mashq shu brauzerda saqlanadi. Natijani ustozga yuborish uchun «Ustoz ishlari»dan uning faol nusxasini tanlang.</p>}<p className="bio-help">{storageState==='blocked'?'Brauzer saqlashga ruxsat bermadi. Daftarni yuklab oling.':'Qoralama shu hisob, mavzu va brauzerda saqlanadi.'}</p>{status&&<p className="bio-feedback" role="status">{status}</p>}</section></section>;
}
