import {biologyScenes} from './biology-content.js';
export const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
export function biologyDefaults(scene,values={}){const s=biologyScenes[scene];if(!s)throw Error('Noma’lum biologiya sahnasi');return Object.fromEntries(s.controls.map(c=>{const v=values?.[c.key];return[c.key,c.type==='enum'?(c.options.some(o=>o[0]===v)?v:c.initial):(typeof v==='number'&&Number.isFinite(v)?clamp(v,c.min,c.max):c.initial)]}))}
export function validateBiologyParameters(scene,p){return Boolean(biologyScenes[scene]&&p&&typeof p==='object'&&!Array.isArray(p)&&Object.entries(p).every(([k,v])=>{const c=biologyScenes[scene].controls.find(x=>x.key===k);return c&&(c.type==='enum'?c.options.some(o=>o[0]===v):typeof v==='number'&&Number.isFinite(v)&&v>=c.min&&v<=c.max&&Math.abs((v-c.min)/c.step-Math.round((v-c.min)/c.step))<1e-9)}))}
export const moistureFactor=w=>w<=60?w/60:Math.max(0,(100-w)/40),temperatureFactor=t=>t<=25?t/25:Math.max(0,(45-t)/20);
export function leafJourney(values,days=365){const p=biologyDefaults('leaf',values),rate=.009*moistureFactor(p.water)*temperatureFactor(p.temperature)*p.oxygen/100,d=1-Math.exp(-rate*Math.max(0,days)),c=p.leaves*.45,n=p.leaves*.01,mineralised=n*d*.6,leached=mineralised*({sand:.3,clay:.08,humus:.12}[p.soil])*p.water/100,available=mineralised-leached,uptake=available*.35*moistureFactor(p.water)*clamp((days-35)/180);return {fraction:d,rate,carbon:{leaf:c*(1-d),soil:c*d*.25,co2:c*d*.75},nitrogen:{leaf:n*(1-d),organic:n*d*.4,available:available-uptake,root:uptake,leached},leafDry:p.leaves*(1-d),growth:clamp(uptake/Math.max(.001,n*.15)),days}}
export const soilCoefficients={sand:{k:.18,store:8},clay:{k:.025,store:24},humus:{k:.10,store:20}};
export function infiltrate(values,minutes=60){const p=biologyDefaults('soil',values),s=soilCoefficients[p.soil],infil=p.rain*(1-Math.exp(-s.k*(1-.8*p.compaction/100)*minutes)),surface=p.rain-infil,runoff=surface*.65*(1-Math.exp(-minutes/15)),stored=Math.min(s.store,infil);return {infil,stored,drained:infil-stored,runoff,surface:surface-runoff,minutes}}
export function seedGrowth(values,days=14){const p=biologyDefaults('seed',values),suitable=moistureFactor(p.water)*temperatureFactor(p.temperature)*p.oxygen/100,fraction=clamp((days-2)/8)*suitable;return {fraction,germinated:Math.round(p.seeds*fraction),seeds:p.seeds,days}}
export function foodChain(values,q=1){const p=biologyDefaults('foodchain',values),steps=Math.floor(clamp(q)*240),history=[];let g=p.grass,h=p.rabbits,c=p.foxes;for(let i=0;i<=steps;i++){if(i%12===0||i===steps)history.push([g,h,c]);if(i===steps)break;const eat=.009*g*h,hunt=.035*h*c;g=Math.max(0,g+.035*(.7*g*(1-g/100)-eat));h=Math.max(0,h+.035*(.13*eat-.18*h-hunt));c=Math.max(0,c+.035*(.12*hunt-.17*c))}return {grass:g,rabbits:h,foxes:c,history}}
export const circulationPath=['Tana kapillyarlari','Tana venalari → o‘ng bo‘lmacha','O‘ng qorincha','O‘pka arteriyasi','O‘pka kapillyarlari','O‘pka venalari → chap bo‘lmacha','Chap qorincha','Aorta → tana arteriyalari','Tana kapillyarlari'],digestionPath=['Og‘iz','Qizilo‘ngach','Oshqozon','O‘n ikki barmoq ichak','Ingichka ichak','Yo‘g‘on ichak','To‘g‘ri ichak va chiqish'];
export function photosynthesisTotals(){const species={left:[{C:1,O:2,n:6},{H:2,O:1,n:6}],right:[{C:6,H:12,O:6,n:1},{O:2,n:6}]};return Object.fromEntries(Object.entries(species).map(([side,list])=>[side,list.reduce((a,s)=>{for(const k of ['C','H','O'])a[k]=(a[k]||0)+(s[k]||0)*s.n;return a},{})]))}
export function biologyResult(scene,values={},progress=1){const p=biologyDefaults(scene,values),q=clamp(Number.isFinite(progress)?progress:0),f=x=>Math.round(x*1000)/1000,out=(readings,unit,cause,extra={})=>({readings,unit,cause,...extra});
 if(scene==='leaf'){const r=leafJourney(p,365*q),waterFlow=infiltrate({soil:p.soil,rain:p.rain,compaction:20},60*q);return out({'Model kuni':f(r.days),'Barg qoldig‘i':f(r.leafDry),'Mavjud mineral N':f(r.nitrogen.available),'Ildiz olgan N':f(r.nitrogen.root),'Singgan yomg‘ir':f(waterFlow.infil),'Pastga oqgan suv':f(waterFlow.drained)},'kun; qoldiq/N g; suv mm',r.rate===0?'Aerob yo‘l cheklangan: bu modelda parchalanish yo‘q. Tabiatda anaerob yo‘llar ham bor.':'Namlik, harorat va kislorod aerob yo‘lni boshqaradi. Organik N ning bir qismi mineral yo‘lga o‘tadi.',{...r,waterFlow})}
 if(scene==='soil'){const r=infiltrate(p,60*q);return out({'Model daqiqasi':f(r.minutes),'Singgan suv':f(r.infil),'Tuproqda qolgan':f(r.stored),'Pastga oqgan':f(r.drained),'Yuzadagi suv':f(r.surface),'Sirt oqimi':f(r.runoff)},'daqiqa; suv mm','G‘ovak va zichlanish singishni o‘zgartiradi. Singgan suvning hammasi tuproqda qolmaydi.',r)}
 if(scene==='compost'){const r=leafJourney({...p,leaves:100,soil:'humus'},120*q),roles=(.55*p.bacteria+.45*p.fungi)/100*(.8+.2*p.worms/100),fraction=1-Math.exp(-r.rate*120*q*roles);return out({'Model kuni':f(120*q),'Parchalangan ulush':f(fraction*100),'Qolgan organik qoldiq':f(100*(1-fraction))},'kun; %; shartli g','Mikroblar kimyoviy parchalaydi; jonivorlar maydalash va aralashtirishga yordam beradi. Model aerob yo‘l uchun.',{fraction,roles})}
 if(scene==='seed'){const r=seedGrowth(p,14*q);return out({'Model kuni':f(r.days),'Ungan urug‘':r.germinated,'Jami urug‘':p.seeds},'kun; ta','Mos suv, harorat va kislorod kerak. Ushbu model urug‘i unishda yorug‘likni talab qilmaydi.',r)}
 if(scene==='growth'){const growth=p.light/100*moistureFactor(p.water)*(1-Math.exp(-3*q));return out({'Model kuni':f(30*q),'O‘sish indeksi':f(growth)},'kun; indeks 0–1','Boshqa omillar yetarli. Kam yorug‘lik/suv cheklaydi; haddan ortiq suv aeratsiyani kamaytiradi.',{growth})}
 if(scene==='photosynthesis'){const extent=Math.min(p.light/100,moistureFactor(p.water),p.co2/100)*q;return out({'Sarflangan CO₂':f(6*extent),'Sarflangan H₂O':f(6*extent),'Organik modda birligi':f(extent),'Ajralgan O₂':f(6*extent)},'shartli reaksiya birliklari','Umumiy nisbat 6 CO₂ + 6 H₂O → C₆H₁₂O₆ + 6 O₂. Ajralgan O₂ suvdan keladi.',{extent})}
 if(scene==='transport'){const flow=p.water/100*(p.vessel==='xylem'?.4+.6*p.light/100:p.light/100)*q;return out({'Transport indeksi':f(flow)},'nisbiy 0–1',p.vessel==='xylem'?'Ildiz → ksilema → barg. Suv va transpiratsiya oqimga ta’sir qiladi.':'Bu sahnada barg manba, ildiz talab joyi. Floema doimo pastga oqadi degani emas.',{flow})}
 if(scene==='pollination'){const delivered=p.visits>0&&q>=.35,fertilised=delivered&&p.compatible==='yes'&&q>=.75;return out({'Tumshuqchaga yetdi':+delivered,'Urug‘lanish modelda yuz berdi':+fertilised},'ha=1; yo‘q=0',!delivered?'Chang hali yetmadi. Tashuvchi kelmasa changlanish yo‘q.':p.compatible==='no'?'Chang tushdi, lekin mos emas: urug‘lanish avtomatik bo‘lmaydi.':fertilised?'Mos chang naychasi urug‘kurtakka yetdi; urug‘lanish keyingi bosqich.':'Mos chang tushdi; chang naychasi yo‘li hali davom etmoqda.',{delivered,fertilised})}
 if(scene==='habitat'){const match=({fish:'water',frog:'water',reptile:'land',bird:'land',mammal:'land',insect:'land',worm:'soil',mollusc:'land',cnidarian:'water'}[p.animal])===p.habitat;return out({'Namuna uchun mos muhit':+match},'mos=1; boshqa=0',match?'Tanlangan vakilga mos muhit. Tana qismlarini ochib vazifalarini o‘rganing.':'Ushbu vakil uchun boshqa muhit. Guruhning barcha turlariga umumlashtirmang; kit, suv qushi kabi istisnolar bor.',{match})}
 if(scene==='adaptation'){const efficiency=p.beak===p.food?1:.25;return out({'Ozuqa olishning shartli samarasi':f(efficiency*q)},'nisbiy 0–1','Uch ixtisoslashgan tumshuq taqqoslanadi. Real natijaga xulq va ozuqa mavjudligi ham ta’sir qiladi.',{efficiency})}
 if(scene==='lifecycle'){const stages={frog:['Tuxum','Itbaliq','Oyoqli yosh bosqich','Yetuk qurbaqa'],butterfly:['Tuxum','Qurt','G‘umbak','Kapalak'],plant:['Urug‘','Nihol','Yetuk o‘simlik','Gul va yangi urug‘']}[p.organism],index=Math.min(3,Math.floor(q*4));return out({'Bosqich':index+1},'1–4',`${stages[index]}. Bosqichlar teng vaqt davom etmaydi.`,{stages,index})}
 if(scene==='foodchain'){const r=foodChain(p,q);return out({'O‘simlik indeksi':f(r.grass),'O‘txo‘r indeksi':f(r.rabbits),'Yirtqich indeksi':f(r.foxes)},'shartli indeks','O‘sish, o‘txo‘rlik va yirtqichlik birga hisoblanadi. Bu haqiqiy daladagi sonlar bashorati emas.',r)}
 if(scene==='anatomy')return out({'Tuzilish darajalari':4},'qatlam','Tana → tayanch/harakat → organ → ichki tuzilma. Chap/o‘ng odamning o‘z tomoni.');
 if(scene==='cell')return out({'Tanlangan qatlam':['whole','membrane','nucleus','energy'].indexOf(p.layer)+1},'qatlam',p.cell==='plant'?'Devor tayanch, membrana almashinuv chegarasi. Xloroplast fotosintez qiladigan hujayrada ko‘rsatilgan.':'Hayvon hujayrasida devor va xloroplast yo‘q. Mitoxondriya ko‘plab hujayralarda hujayra nafasida qatnashadi.');
 if(scene==='breathing'){const phase=q===1?0:q*p.cycles%1,inflation=(.5-.5*Math.cos(2*Math.PI*phase))*p.depth/100;return out({'O‘tgan to‘liq sikl':Math.floor(q*p.cycles),'O‘pka nisbiy hajmi':f(1+.3*inflation),'Diafragma pastlashishi':f(inflation)},'sikl; shartli indeks',phase<.5?'Nafas olish: diafragma qisqarib pastlaydi, hajm oshadi, havo kiradi.':'Nafas chiqarish: diafragma bo‘shashib ko‘tariladi, hajm kamayadi, havo chiqadi.',{phase,inflation})}
 if(scene==='circulation'){const index=Math.min(8,Math.floor((q===1?1:q*p.cycles%1)*8));return out({'Yo‘l bosqichi':index+1,'Tugagan doira':Math.floor(q*p.cycles)},'bosqich; sikl',circulationPath[index],{index,path:circulationPath})}
 if(scene==='digestion'){const index=Math.min(6,Math.floor(q*7)),absorbed=clamp((q-.43)/.35)*p.portion*.85;return out({'Yo‘l bosqichi':index+1,'So‘rilgan oziqa indeksi':f(absorbed),'Hali so‘rilmagan':f(p.portion-absorbed)},'bosqich; shartli birlik',`${digestionPath[index]}. ${p.meal==='fat'?'Ko‘plab yog‘ mahsulotlari vorsinka limfa yo‘liga o‘tadi.':'Ko‘p kichik oziqa mahsulotlari vorsinkadan qonga o‘tadi.'}`,{index,absorbed,path:digestionPath})}
 if(scene==='movement'){const angle=p.angle*q,length=1-.3*Math.sin(angle*Math.PI/360);return out({'Bukilish':f(angle),'Bukuvchi mushak nisbiy uzunligi':f(length)},'°; nisbiy uzunlik','Mushak pay orqali tortadi; suyak richag, bo‘g‘im aylanish joyi.',{angle,length})}
 if(scene==='reflex'||scene==='senses'){const path=scene==='reflex'?(p.path==='reflex'?['Retseptor','Sezuvchi neyron','Orqa miya oraliq neyroni','Harakat neyroni','Mushak javobi']:['Retseptor','Sezuvchi neyron','Markaziy yo‘l','Bosh miyada qayta ishlash','Ongli sezgi']):({vision:['Yorug‘lik','Shox parda/linsa','To‘r parda retseptorlari','Ko‘ruv nervi','Miyada qayta ishlash'],hearing:['Tovush','Quloq pardasi/suyakchalar','Chig‘anoq retseptorlari','Eshituv nervi','Miyada qayta ishlash'],touch:['Teri ta’siri','Retseptor','Sezuvchi neyron','Markaziy yo‘l','Miyada qayta ishlash']}[p.sense]),index=Math.min(4,Math.floor(q*5));return out({'Signal bosqichi':index+1},'1–5',path[index],{path,index})}
 if(scene==='excretion'){const filtered=100*q,returned=filtered*p.reabsorption/100;return out({'Boshlang‘ich filtrat':f(filtered),'Qayta olingan suv':f(returned),'Siydik tomonga qolgan':f(filtered-returned)},'shartli suv birligi','Filtratning hammasi siydik emas. Qon hujayralari va katta oqsillar odatda qonda qoladi; real nefronda sekretsiya ham bor.',{filtered,returned})}
 if(scene==='endocrine'){const signal=p.meal/100*(1-q*.75),insulin=p.meal/100*Math.sin(Math.PI*q);return out({'Ovqat signali':f(signal),'Insulin javob indeksi':f(insulin)},'nisbiy; klinik birlik emas','Bez → gormon → nishon hujayra javobi → qayta aloqa. Barcha metabolik yo‘llar hisoblanmagan.',{signal,insulin})}
 if(scene==='immunity'){const entered=100*(1-p.barrier/100),remaining=entered*Math.exp(-3*p.response/100*q);return out({'To‘siqdan o‘tgan shartli birlik':f(entered),'Qolgan shartli birlik':f(remaining)},'shartli birlik','Tashqi to‘siq va ichki javob turli bosqichlar. Bu kasallik yoki muolaja modeli emas.',{entered,remaining})}
 if(scene==='reproduction')return out({'Boshlang‘ich xromosoma':p.stage==='meiosis'?46:23,'Natijadagi xromosoma':q<.6?(p.stage==='meiosis'?46:23):(p.stage==='meiosis'?23:46)},'ta; odatiy inson modeli',p.stage==='meiosis'?'Meioz gameta to‘plamini kamaytiradi. Barcha fazalar va rekombinatsiya ko‘rsatilmagan.':'23 + 23 → odatda 46 xromosomali zigota. Embrion rivojlanishi keyingi jarayon.');
 throw Error('Biologik model topilmadi');
}
