import React,{useEffect,useState} from 'react';
import {Plus,ArrowLeft,Save,Headphones,BookOpen,Mic,Pencil,RefreshCw,Archive,Check} from 'lucide-react';
import {cefrRpc,speakingUrl} from './cefr-service.js';
import {newCefrTest,newCefrQuestion,cefrIssues,cefrLabels,cefrQuestions,safeMediaUrl} from './cefr-model.js';
import './cefr-admin.css';
const labels={draft:'Qoralama',published:'O‘quvchilar uchun ochiq',archived:'Yopiq'};
const count=t=>t.sections.reduce((n,s)=>n+s.parts.reduce((v,p)=>v+p.questions.length,0),0);
export default function CefrAdmin(){
 const [rows,setRows]=useState([]),[results,setResults]=useState([]),[tab,setTab]=useState('tests'),[edit,setEdit]=useState(null),[review,setReview]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const run=async fn=>{if(busy)return;setBusy(true);setError('');try{return await fn()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const load=()=>run(async()=>{
  try{const seed=await cefrRpc('sq_cefr_seed');if(seed.added)setNotice('10 ta Multilevel mashq varianti o‘quvchilarga ochildi.')}
  catch(e){setNotice(`Tayyor variantlar uchun supabase-migration-7.7.sql ni RUN qiling. ${e.message}`)}
  const [a,b]=await Promise.all([cefrRpc('sq_cefr_admin',{p_action:'list'}),cefrRpc('sq_cefr_admin',{p_action:'results'})]);setRows(a);setResults(b)
 });
 useEffect(()=>{load()},[]);
 const save=async payload=>run(async()=>{const row=await cefrRpc('sq_cefr_admin',{p_action:'save',p_id:edit.id||null,p_body:{payload,revision:edit.revision}});setRows(old=>[row,...old.filter(r=>r.id!==row.id)]);setEdit(row);setNotice('Qoralama saqlandi. O‘quvchilarga ochish uchun ro‘yxatda “E’lon qilish”ni bosing.');return row});
 const status=(row,action)=>run(async()=>{if(action==='publish'){const issues=cefrIssues(row.payload);if(issues.length)throw Error(issues.slice(0,6).join('\n'))}const updated=await cefrRpc('sq_cefr_admin',{p_action:action,p_id:row.id});setRows(old=>old.map(r=>r.id===row.id?updated:r));setNotice(action==='publish'?'Variant o‘quvchilarga ochildi.':'Yangi qatnashuvchilar uchun yopildi. Boshlangan sessiyalar davom etadi.')});
 return <section className="ca-root">
  {error&&<p className="ca-alert" role="alert">{error}</p>}{notice&&<p className="ca-notice" role="status">{notice}</p>}
  {edit?<CefrEditor key={edit.id||'new'} row={edit} busy={busy} onSave={save} onBack={()=>{setEdit(null);setNotice('')}}/>:review?<CefrMarking attempt={review} busy={busy} onBack={()=>setReview(null)} onSave={value=>run(async()=>{const a=await cefrRpc('sq_cefr_admin',{p_action:'review',p_id:review.id,p_body:value});setReview(a);setResults(old=>old.map(r=>r.id===a.id?{...r,assessment:a.assessment}:r));setNotice('Baho va izoh o‘quvchiga yuborildi.')})}/>:<>
   <div className="ca-heading"><div><span className="ca-eyebrow">CEFR / MULTILEVEL</span><h2>Variantlar va yozma ishlar</h2><p>To‘rt ko‘nikmani bitta variantda boshqaring. Qoralamalar o‘quvchilarga ko‘rinmaydi.</p></div><button onClick={load} disabled={busy}><RefreshCw size={17}/> Yangilash</button></div>
   <div className="ca-tabs"><button aria-pressed={tab==='tests'} onClick={()=>setTab('tests')}>Variantlar ({rows.length})</button><button aria-pressed={tab==='results'} onClick={()=>setTab('results')}>Tekshirish ({results.filter(r=>!r.assessment).length})</button></div>
   {tab==='tests'?<><div className="ca-actions"><button className="ca-primary" onClick={()=>{setEdit({payload:newCefrTest(true)});setNotice('')}}><Plus size={18}/> Multilevel shabloni</button><button onClick={()=>{setEdit({payload:newCefrTest()});setNotice('')}}><Plus size={18}/> Qisqa mashq yaratish</button></div><p className="ca-help">10 ta tayyor original mashq varianti ro‘yxatda. Har birida Listening 35, Reading 35, Writing 3 topshiriq va Speaking 4 qism bor. O‘zingiz ham yangi variant yaratishingiz mumkin.</p>
    <div className="ca-grid">{rows.map(row=><article className="ca-card" key={row.id}><span className={'ca-badge '+row.status}>{labels[row.status]}</span><h3>{row.payload.title}</h3><p>{row.payload.description||'Tavsif kiritilmagan'}</p><small>{row.payload.level} · {count(row.payload)} topshiriq · {row.payload.sections.reduce((n,s)=>n+Number(s.minutes),0)} daqiqa</small><div className="ca-actions"><button onClick={()=>{setEdit(row);setNotice('')}}><Pencil size={16}/> Tahrirlash</button>{row.status!=='published'?<button className="ca-primary" disabled={busy} onClick={()=>status(row,'publish')}><Check size={16}/> E’lon qilish</button>:<button disabled={busy} onClick={()=>status(row,'archive')}><Archive size={16}/> Yopish</button>}</div></article>)}</div>{!rows.length&&!busy&&<div className="ca-empty"><BookOpen/><h3>Birinchi CEFR variantini yarating</h3><p>Saqlash, tekshirish va e’lon qilish — barchasi shu bo‘limda.</p></div>}</>:<div className="ca-result-list">{results.map(r=><article className="ca-card" key={r.id}><div><span className="ca-badge">{r.assessment?'Baholangan':'Tekshirish kutilmoqda'}</span><h3>{r.student_name}</h3><p>{r.title} · {new Date(r.finished_at).toLocaleString('uz-UZ')}</p></div><button disabled={busy} onClick={()=>run(async()=>{setReview(await cefrRpc('sq_cefr_admin',{p_action:'attempt',p_id:r.id}));setNotice('')})}>Javoblarni ko‘rish</button></article>)}{!results.length&&<p className="ca-empty">Hali topshirilgan ish yo‘q.</p>}<p className="ca-help">Oxirgi 100 ta topshirilgan ish ko‘rsatiladi.</p></div>}
  </>}
 </section>;
}
function CefrEditor({row,busy,onSave,onBack}){
 const [data,setData]=useState(()=>structuredClone(row.payload)),[si,setSi]=useState(0),[pi,setPi]=useState(0),[qi,setQi]=useState(0),[dirty,setDirty]=useState(false),[showIssues,setShowIssues]=useState(false);
 const section=data.sections[si],part=section.parts[pi],q=part.questions[qi],issues=cefrIssues(data);
 const change=fn=>{setData(old=>{const next=structuredClone(old);fn(next);return next});setDirty(true)};
 const field=(key,value)=>change(d=>{d[key]=value});
 const pf=(key,value)=>change(d=>{d.sections[si].parts[pi][key]=value});
 const qf=(key,value)=>change(d=>{d.sections[si].parts[pi].questions[qi][key]=value});
 useEffect(()=>{const guard=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty]);
 return <div className="ca-editor"><div className="ca-heading"><button onClick={()=>{if(!dirty||confirm('Saqlanmagan o‘zgarishlar bor. Chiqasizmi?'))onBack()}}><ArrowLeft size={16}/> Variantlar</button><div className="ca-actions"><button onClick={()=>setShowIssues(!showIssues)}>Tekshirish ({issues.length})</button><button className="ca-primary" disabled={busy||!data.title.trim()} onClick={async()=>{if(await onSave(data))setDirty(false)}}><Save size={17}/>{busy?'Saqlanmoqda…':'Qoralamani saqlash'}</button></div></div>
  {row.status==='published'&&<p className="ca-notice">Tahrirni saqlasangiz, variant qoralamaga qaytadi. Tekshirib, yana e’lon qiling. Boshlangan testlar o‘zgarmaydi.</p>}
  {showIssues&&<div className="ca-alert" role="status">{issues.length?<ul>{issues.map((v,i)=><li key={i}>{v}</li>)}</ul>:'Tuzilma to‘liq. Audio ijrosi va savollarning mazmunini tekshirib, e’lon qiling.'}</div>}
  <section className="ca-card ca-form"><h3>Variant haqida</h3><div className="ca-two"><label>Variant nomi<input maxLength={160} value={data.title} onChange={e=>field('title',e.target.value)}/></label><label>Maqsadli daraja<select value={data.level} onChange={e=>field('level',e.target.value)}>{['B1–C1','B1','B2','C1'].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Tavsif<textarea value={data.description} maxLength={1000} onChange={e=>field('description',e.target.value)}/></label><label className="ca-check"><input type="checkbox" checked={data.rightsConfirmed} onChange={e=>field('rightsConfirmed',e.target.checked)}/> Matn, savol va audiolardan foydalanish huquqim bor; manbalarni ko‘rsatdim.</label></section>
  <div className="ca-tabs">{data.sections.map((s,i)=><button key={s.skill} aria-pressed={i===si} onClick={()=>{setSi(i);setPi(0);setQi(0)}}>{cefrLabels[s.skill]}</button>)}</div>
  <div className="ca-edit-layout"><aside className="ca-card ca-form"><label>Bo‘lim vaqti (daqiqa)<input type="number" min={1} max={180} value={section.minutes} onChange={e=>change(d=>{d.sections[si].minutes=Number(e.target.value)})}/></label><h3>Qismlar</h3>{section.parts.map((p,i)=><button key={p.id} aria-pressed={i===pi} onClick={()=>{setPi(i);setQi(0)}}>{p.title} · {p.questions.length}</button>)}{data.format==='practice'&&<button onClick={()=>change(d=>{d.sections[si].parts.push({id:crypto.randomUUID(),title:`Part ${section.parts.length+1}`,text:'',source:'',audioUrl:'',imageUrl:'',questions:[newCefrQuestion(section.skill,crypto.randomUUID())]})})}><Plus size={16}/> Qism qo‘shish</button>}</aside>
   <div className="ca-form"><section className="ca-card ca-form"><label>Qism nomi<input value={part.title} onChange={e=>pf('title',e.target.value)}/></label><label>{si===1?'Reading matni':'Ko‘rsatma / vaziyat'}<textarea className="ca-long" value={part.text} maxLength={40000} onChange={e=>pf('text',e.target.value)}/></label><label>Muallif va manba<input value={part.source} placeholder="Muallif, kitob / maqola nomi, sana yoki URL" onChange={e=>pf('source',e.target.value)}/></label>{si===0&&<><label>Audio manzili (HTTPS)<input type="url" value={part.audioUrl} placeholder="https://…/listening.mp3" onChange={e=>pf('audioUrl',e.target.value)}/></label>{safeMediaUrl(part.audioUrl)&&<audio controls preload="none" src={part.audioUrl}/> }<small>O‘quvchi audioni shu oynada tinglaydi. To‘g‘ridan-to‘g‘ri MP3/WAV/M4A manzilini kiriting va ijroni tekshiring.</small></>}<label>Rasm manzili (ixtiyoriy, HTTPS)<input type="url" value={part.imageUrl} onChange={e=>pf('imageUrl',e.target.value)}/></label>{safeMediaUrl(part.imageUrl)&&<img className="ca-task-image" src={part.imageUrl} alt="Topshiriq uchun rasm"/>}</section>
    <section className="ca-card ca-form"><div className="ca-heading"><h3>{qi+1}-topshiriq</h3><button onClick={()=>{change(d=>{d.sections[si].parts[pi].questions.push(newCefrQuestion(section.skill,crypto.randomUUID()))});setQi(part.questions.length)}}><Plus size={16}/> Savol qo‘shish</button></div><div className="ca-qmap">{part.questions.map((item,i)=><button key={item.id} aria-pressed={qi===i} onClick={()=>setQi(i)}>{i+1}</button>)}</div><label>Savol / topshiriq matni<textarea value={q.text} maxLength={20000} onChange={e=>qf('text',e.target.value)}/></label>{si<2&&<><label>Javob turi<select value={q.type} onChange={e=>qf('type',e.target.value)}><option value="text">Qisqa javob / bo‘shliqni to‘ldirish</option><option value="choice">Variant tanlash / moslashtirish</option></select></label>{q.type==='choice'&&<label>Variantlar — har qatorga bittadan<textarea value={q.options.join('\n')} onChange={e=>qf('options',e.target.value.split('\n'))}/></label>}<label>To‘g‘ri javoblar — har qatorga bittadan<textarea value={q.answers.join('\n')} onChange={e=>qf('answers',e.target.value.split('\n'))}/></label><small>Variantli savolda javob kaliti variant matniga aynan teng bo‘lsin.</small><label>Javob izohi<textarea value={q.explanation} onChange={e=>qf('explanation',e.target.value)}/></label></>}{part.questions.length>1&&<button className="ca-danger" onClick={()=>{if(confirm('Shu savol o‘chirilsinmi?')){change(d=>d.sections[si].parts[pi].questions.splice(qi,1));setQi(0)}}}>Savolni o‘chirish</button>}</section>
   </div></div><p className="ca-help">Maqsadli daraja variantning murakkabligini belgilaydi. Sayt bu tanlov asosida o‘quvchiga avtomatik sertifikat darajasi bermaydi.</p>
 </div>;
}
export function RecordingPlayer({path}){const [url,setUrl]=useState(''),[error,setError]=useState('');return <div>{url?<audio controls src={url}/>:<button onClick={async()=>{try{setUrl(await speakingUrl(path))}catch(e){setError(e.message)}}}><Headphones size={16}/> Yozuvni tinglash</button>}{error&&<p role="alert">{error}</p>}</div>}
function CefrMarking({attempt,busy,onBack,onSave}){
 const [form,setForm]=useState(attempt.assessment||{writing:'',speaking:'',feedback:''});
 return <div className="ca-form"><button onClick={onBack}><ArrowLeft size={16}/> Natijalarga qaytish</button><h2>{attempt.snapshot.title}</h2><p>Listening: {attempt.result.scores.listening.correct}/{attempt.result.scores.listening.total} · Reading: {attempt.result.scores.reading.correct}/{attempt.result.scores.reading.total}</p>{[2,3].map(step=><section key={step} className="ca-card ca-form"><h3>{cefrLabels[attempt.snapshot.sections[step].skill]}</h3>{cefrQuestions(attempt.snapshot,step).map(q=><article key={q.id} className="ca-submission"><p>{q.part.text}</p><h4>{q.text}</h4>{step===2?<p className="ca-preserve">{attempt.answers[q.id]||'Javob berilmagan'}</p>:attempt.answers[q.id]?<RecordingPlayer path={attempt.answers[q.id]}/>:<p>Audio topshirilmagan.</p>}</article>)}</section>)}<section className="ca-card ca-form"><h3>Admin bahosi</h3><p className="ca-help">0–75 — platformadagi mashq bahosi. Bu rasmiy Rasch hisob-kitobi yoki sertifikat darajasi emas.</p><div className="ca-two">{['writing','speaking'].map(k=><label key={k}>{cefrLabels[k]} (0–75)<input type="number" min={0} max={75} step={1} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><label>O‘quvchiga izoh<textarea maxLength={5000} value={form.feedback} onChange={e=>setForm({...form,feedback:e.target.value})}/></label><button className="ca-primary" disabled={busy||form.writing===''||form.speaking===''||!form.feedback.trim()} onClick={()=>onSave(form)}><Check size={17}/> Bahoni saqlash</button></section></div>;
}
