import {getSupabase} from './supabase-sdk.js';
const check=error=>{if(!error)return;if(['42P01','PGRST205'].includes(error.code))throw Error('Ustoz sahnalari va natijalari uchun supabase-chemistry-atlas.sql migratsiyasini ishga tushiring.');throw Error(error.message||'Kimyo ma’lumotlari saqlanmadi.');};
async function fixture(path,data){if(globalThis.__SINFQUIZ_LEGACY_TEST__===true){const r=await fetch(`/api/chemistry/${path}`,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});if(!r.ok)throw Error('Sinov serveri javob bermadi');return r.json()}return null}
export async function chemistryLoad(){const f=await fixture('concepts');if(f)return f;const {db}=await getSupabase();const {data,error}=await db.from('chemistry_concepts').select('*').order('updated_at',{ascending:false}).limit(300);check(error);return data||[];}
export async function chemistrySave({id,ownerId,data,status,active}){const f=await fixture('save',{id,ownerId,data,status,active});if(f)return f;const sdk=await getSupabase();if(sdk.auth.currentUser?.uid!==ownerId)throw Error('Faqat muallif tahrirlaydi.');const row={owner_id:ownerId,data,status,active};const result=id?await sdk.db.from('chemistry_concepts').update(row).eq('id',id).eq('owner_id',ownerId).select().single():await sdk.db.from('chemistry_concepts').insert(row).select().single();check(result.error);return result.data;}
export async function chemistryToggle(id,ownerId,active){const f=await fixture('toggle',{id,ownerId,active});if(f)return f;const sdk=await getSupabase();if(sdk.auth.currentUser?.uid!==ownerId)throw Error('Faqat muallif faollashtiradi.');const {error}=await sdk.db.from('chemistry_concepts').update({active}).eq('id',id).eq('owner_id',ownerId);check(error);}
export async function chemistryReview(id,status){const f=await fixture('review',{id,status});if(f)return f;const {db}=await getSupabase();const {error}=await db.from('chemistry_concepts').update({status}).eq('id',id);check(error);}
export async function chemistryDelete(id,ownerId){const f=await fixture('delete',{id,ownerId});if(f)return f;const sdk=await getSupabase();if(sdk.auth.currentUser?.uid!==ownerId)throw Error('Faqat muallif o‘chiradi.');const {error}=await sdk.db.from('chemistry_concepts').delete().eq('id',id).eq('owner_id',ownerId);check(error);}
export async function chemistryObservations(){const f=await fixture('observations');if(f)return f;const {db}=await getSupabase();const {data,error}=await db.from('chemistry_observations').select('*').order('created_at',{ascending:false}).limit(500);check(error);return data||[];}
export async function chemistryRecord({conceptId,user,prediction,observation}){const row={concept_id:conceptId,student_id:user.id,student_name:user.name||'O‘quvchi',prediction,observation};const f=await fixture('record',row);if(f)return f;const {db}=await getSupabase();const {data,error}=await db.from('chemistry_observations').insert(row).select().single();check(error);return data;}
