import {chemistryLabs} from './chemistry-labs.js';
const rows=[
['atom','Atom ichiga sayohat',7,'Atom va element','Nega atomlar boshqa-boshqa?','Elementni yadrodagi proton soni belgilaydi. Neytron o‘zgarsa izotop, elektron o‘zgarsa ion hosil bo‘ladi.','Proton sonini o‘zgartirish boshqa elementga o‘tishdir; kimyoviy reaksiyada yadrolar bunday o‘zgarmaydi.','Uglerod izotoplari qadimgi buyumlarni sanalashda ishlatiladi.','Elektron qavatlari aniq sayyora yo‘llari emas. Orbital elektron topilish ehtimolini tavsiflaydi.','Kislorodda proton 8, elektron 10 bo‘lsa zaryad nechaga teng?',-2,'8 − 10 = −2; bu O²⁻ ionining hisobiy tarkibi.','Proton elektron neytron ion izotop'],
['periodic','118 elementli davriy jadval',7,'Atom va element','Nega elementlar jadvalda guruhlangan?','Elementlar atom raqami ortishi bilan joylashadi. Ustunlar guruh, qatorlar davr deb ataladi.','Bir guruhda valent elektronlar tuzilishi o‘xshash bo‘lishi mumkin; xossalar aynan bir xil emas.','Kremniy mikrochipda, mis elektr simida ishlatiladi.','Atom raqami nisbiy atom massasi emas. Lantanoidlar va aktinoidlar pastga ixcham ko‘rinish uchun chiqarilgan.','Kislorodning atom raqami nechaga teng?',8,'O atomining yadrosida 8 proton bor.','element jadval guruh davr'],
['molecule','Molekula quruvchisi',8,'Bog‘ va molekula','Nega suv molekulasi egilgan?','Molekula atomlarning bog‘langan guruhidir. Atomlar soni formula, joylashuvi esa geometriya orqali ifodalanadi.','Suvdagi kislorodning bog‘lanmagan elektron juftlari H–O–H burchagini shakllantiradi.','Suvning qutbliligi ko‘p ionli moddalarni eritishga yordam beradi.','Valentlikka mos chizma har doim barqaror yoki mavjud modda degani emas. Shar o‘lchami haqiqiy masshtab emas.','CH₄ molekulasida nechta vodorod atomi bor?',4,'Pastki indeks H atomlari sonini ko‘rsatadi.','molekula formula valentlik 3d'],
['bonds','Bog‘lar va modda xossalari',8,'Bog‘ va molekula','Nega tuz eritmasi tok o‘tkazadi?','Kovalent bog‘da elektron zichligi atomlar orasida umumiy; ion bog‘ida qarama-qarshi zaryadli ionlar tortishadi. Metallarda elektronlar kengroq delokallashgan.','Qattiq ion kristalida ionlar joyiga bog‘langan. Erigan yoki suyuqlangan holatda ular harakat qilib zaryad tashiydi.','Mis sim tok o‘tkazadi; sof suvga qaraganda tuzli suv yaxshiroq o‘tkazadi.','NaCl alohida molekulalardan iborat emas; formula kristaldagi ionlar nisbatini bildiradi.','NaCl da Na⁺ va Cl⁻ sonlarining nisbati 1 ga nechta?',1,'Kristallda umumiy zaryad nol bo‘lishi uchun nisbat 1:1.','ion kovalent metall tok'],
['states','Muzdan bug‘gacha',5,'Modda va aralashma','Muz eriganda molekula o‘zgaradimi?','Qattiq, suyuq va gaz holatlari zarrachalar joylashuvi va harakati bilan farqlanadi. Suv eriganda H₂O formulasi saqlanadi.','Issiqlik molekulalar harakatini va ular orasidagi o‘zaro ta’sirga qarshi ajralishni o‘zgartiradi.','Muz bo‘lagi eriydi, sovuq oynada suv bug‘i kondensatsiyalanadi.','Suv 100 °C dan pastda ham yuzasidan bug‘lanadi. Qaynash harorati bosimga bog‘liq.','1 atm bosimda suvning qaynash harorati taxminan necha °C?',100,'Bu model sof suv va 1 atm bosim uchun.','muz erish qotish bug‘ kondensatsiya'],
['reaction','Reaksiya va atomlar saqlanishi',8,'Reaksiya va muvozanat','Reaksiyada atomlar qayerga ketadi?','Kimyoviy reaksiyada atomlar yangi bog‘lanishlarda qayta joylashadi. Tenglamada elementning atomlari chap va o‘ng tomonda teng bo‘ladi.','Koeffitsiyent butun modda formulasini ko‘paytiradi; formula ichidagi indeksni almashtirish boshqa moddani bildiradi.','Nam havoda temir zanglaydi; zangning haqiqiy tarkibi gidratlangan oksidlar aralashmasidir.','4Fe + 3O₂ → 2Fe₂O₃ zanglashning soddalashtirilgan yakuniy modeli, barcha bosqichlar emas.','2H₂ + O₂ → 2H₂O ning har tomonida nechta H atomi bor?',4,'2 × 2 = 4 vodorod atomi.','balans tenglama zang atom saqlanish'],
['ph','pH va neytrallanish',8,'Reaksiya va muvozanat','Nega indikator rangi o‘zgaradi?','pH eritmaning kislotaligini logarifmik ifodalaydi. 25 °C da neytral suv pH ≈ 7; pastroq qiymat kislotali, yuqoriroq asosli.','Kuchli kislota va asosning H₃O⁺ hamda OH⁻ ionlari suv hosil qiladi. Teng mol miqdori neytrallanishga olib keladi.','Oziq-ovqat va suv sifatini tekshirishda pH muhim o‘lchovdir.','pH ni arifmetik o‘rtachalash bilan aralashma pH ini topib bo‘lmaydi. Indikator ranglari taxminiy.','pH 3 dan pH 2 ga tushsa H₃O⁺ konsentratsiyasi necha marta ortadi?',10,'pH logarifmik: bir birlik farq 10 marta.','kislota asos indikator ph'],
['rate','Energiya va reaksiya tezligi',9,'Reaksiya va muvozanat','Nega maydalangan modda tezroq reaksiyaga kirishadi?','Reaksiya tezligi samarali to‘qnashuvlar va aktivlanish energiyasiga bog‘liq. Harorat, konsentratsiya, sirt yuzasi va katalizator ta’sir qilishi mumkin.','Yuqori haroratda aktivlanish to‘sig‘idan o‘ta oladigan zarrachalar ulushi ko‘payadi. Katalizator boshqa yo‘l beradi.','Maydalangan qattiq modda suyuqlikka kattaroq sirt bilan tegadi.','Haroratni oshirish barcha reaksiyalarni bir xil miqdorda tezlashtirmaydi. Katalizator ΔH ni o‘zgartirmaydi.','Mazkur modelda konsentratsiya 2 marta oshsa boshlang‘ich tezlik necha marta ortadi?',2,'Model birinchi tartibli deb tanlangan; haqiqiy tartib tajribadan aniqlanadi.','tezlik harorat energiya katalizator'],
['mixture','Aralashmalarni ajratish',6,'Modda va aralashma','Nega tuz filtrdan o‘tib ketadi?','Aralashmani ajratishda tarkibiy qismlarning eruvchanligi, zarracha o‘lchami yoki uchuvchanligidagi farqdan foydalaniladi.','Filtr erimagan qumni ushlaydi, eritmadagi ionlar esa suv bilan o‘tadi. Bug‘latishda suv ketadi; distillashda bug‘ qayta yig‘iladi.','Qum, tuz va suv aralashmasining qismlari turli usul bilan ajratiladi.','Oddiy filtr erigan tuzni olib tashlamaydi. Dengiz suvini tozalashda boshqa texnologiya kerak.','Oddiy filtrlash erigan tuzni olib tashlaydimi? Ha=1, yo‘q=0.',0,'Tuz ionlari oddiy filtr teshiklaridan suv bilan o‘tadi.','eritma filtrlash bug‘latish distillash'],
['organic','Uglerod va organik moddalar',10,'Kimyo hayotimizda','Nega uglerod juda ko‘p birikma hosil qiladi?','Uglerod odatda to‘rtta kovalent bog‘ tartibiga ega. U zanjir va halqalar hosil qilishi mumkin; funksional guruhlar xossalarga ta’sir qiladi.','Bir, qo‘sh va uch bog‘lar atomlarning joylashuvi hamda vodorodlar sonini o‘zgartiradi.','Polimer qadoqlar, oziq-ovqat va dorilar ko‘plab organik birikmalarni o‘z ichiga oladi.','Organik modda doim xavfsiz yoki tabiiy degani emas. CO₂ kabi uglerodli moddalar odatda noorganik o‘rganiladi.','Eten C₂H₄ da uglerodlar orasidagi bog‘ tartibi nechta?',2,'C=C qo‘sh bog‘, jami ikki bog‘ tartibi.','organik uglerod metan eten etin etanol'],
['electric','Elektr va kimyo',9,'Kimyo hayotimizda','Batareyadagi elektronlar qayerdan keladi?','Galvanik elementda oksidlanish va qaytarilish elektronlarni tashqi zanjir orqali o‘tkazadi. Eritmada zaryadni ionlar tashiydi.','Zn → Zn²⁺ + 2e⁻; Cu²⁺ + 2e⁻ → Cu. Elektrolizda esa tashqi elektr manbai majburiy jarayonni yuritadi.','Batareya kimyoviy energiyani elektr energiyasiga aylantiradi.','Elektronlar eritmada ionlar o‘rniga sim kabi oqmaydi. Anod oksidlanish joyi, katod qaytarilish joyi.','Zn atomining Zn²⁺ ioniga aylanishida nechta elektron ajraladi?',2,'Zaryad +2 bo‘lishi uchun 2 elektron chiqadi.','batareya elektroliz ion elektron'],
['life','Kimyo kundalik hayotda',5,'Kimyo hayotimizda','Havodagi kislorod yonishga qanday yordam beradi?','Kundalik hodisalar modda tarkibi va uning o‘zgarishi bilan bog‘liq. Fizik o‘zgarishda modda kimligi, kimyoviy o‘zgarishda esa bog‘lanishlar o‘zgaradi.','Suvning erishi fizik o‘zgarish; temirning oksidlanishi yangi moddalarni hosil qiladi.','Havo aralashma; suv erituvchi; ovqat murakkab birikmalar aralashmasi.','Dorining foydasi modda nomigagina emas, doza va mutaxassis tavsiyasiga ham bog‘liq.','Muz eriganda yangi modda hosil bo‘ladimi? Ha=1, yo‘q=0.',0,'H₂O saqlanadi; bu fizik o‘zgarish.','suv havo ovqat dori material tabiat']
];
export const chemistryTopics=rows.map(([id,title,grade,group,question,definition,reason,life,misconception,challenge,answer,feedback,keywords],i)=>({id,title,grade,group,question,definition,reason,life,misconception,challenge,answer,feedback,keywords,scene:id,prerequisites:i===0||id==='states'||id==='life'?[]:id==='periodic'?['atom']:id==='molecule'?['atom','bonds']:id==='bonds'?['atom']:id==='reaction'?['molecule']:id==='ph'?['reaction']:id==='rate'?['reaction']:id==='mixture'?['states']:id==='organic'?['molecule']:['bonds','reaction']}));
export const chemistryById=Object.fromEntries([...chemistryTopics,...chemistryLabs].map(t=>[t.id,t]));
export const chemistryScenes=Object.fromEntries([...chemistryTopics,...chemistryLabs].map(t=>[t.id,t.title]));
