import React,{useEffect,useRef,useState} from 'react';
import {listGroups,groupAction,groupMessages,groupMembers,groupSend,groupAudio,groupRemove,watchGroup} from './experiment-service.js';
import './class-groups.css';
function Voice({id}){const [src,setSrc]=useState(''),[error,setError]=useState('');return <div>{src?<audio src={src} controls preload="none"/>:<button onClick={async()=>{try{const a=await groupAudio(id);if(!a)throw Error('Ovoz muddati tugadi.');setSrc(`data:${a.mime};base64,${a.base64}`)}catch(e){setError(e.message)}}}>Ovozli xabarni ochish</button>}{error&&<span role="status">{error}</span>}</div>}
export default function ClassGroupChat({user}){
 const teacher=['teacher','admin'].includes(user.role),[groups,setGroups]=useState([]),[selected,setSelected]=useState(''),[rows,setRows]=useState([]),[members,setMembers]=useState([]),[title,setTitle]=useState(''),[code,setCode]=useState(''),[body,setBody]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0);
 const audio=useRef(null),timer=useRef(null),alive=useRef(true),selectedRef=useRef(selected);selectedRef.current=selected;
 const group=groups.find(g=>g.id===selected),owner=group?.owner_id===user.id||user.role==='admin';
 const refresh=async()=>{try{const g=await listGroups();setGroups(g);setSelected(v=>g.some(x=>x.id===v)?v:g[0]?.id||'')}catch(e){setStatus(e.message)}};
 useEffect(()=>{alive.current=true;refresh();return()=>{alive.current=false;clearInterval(timer.current);if(audio.current){audio.current.discard=true;audio.current.recorder.state==='recording'&&audio.current.recorder.stop();audio.current.stream.getTracks().forEach(t=>t.stop())}}},[]);
 useEffect(()=>{
  setRows([]);setMembers([]);if(audio.current){audio.current.discard=true;if(audio.current.recorder.state==='recording')audio.current.recorder.stop()}if(!selected)return;
  let active=true,inFlight=false,connected=false,lastRead=0,lastRoster=0,dirty=true,rosterDirty=true,settingsDirty=false,stopWatch=()=>{};
  const poll=async()=>{
   if(!active||document.hidden||inFlight)return;const now=Date.now();setRows(old=>old.filter(r=>now-Date.parse(r.created_at)<86400000));
   if(connected&&!dirty&&now-lastRead<60000)return;
   inFlight=true;const roster=rosterDirty||now-lastRoster>=60000,settings=settingsDirty;dirty=false;rosterDirty=false;settingsDirty=false;
   try{const [m,p]=await Promise.all([groupMessages(selected),roster?groupMembers(selected):Promise.resolve(null)]);if(active){setRows(m);if(p)setMembers(p);lastRead=now;if(roster)lastRoster=now;if(settings||(p&&!owner&&!p.some(x=>x.student_id===user.id)))await refresh()}}
   catch(e){dirty=true;if(active)setStatus(e.message)}finally{inFlight=false}
  };
  watchGroup(selected,change=>{dirty=true;if(change.members)rosterDirty=true;if(change.settings)settingsDirty=true},value=>{connected=value;dirty=true}).then(stop=>{if(active)stopWatch=stop;else stop()}).catch(()=>{connected=false});
  poll();const tick=setInterval(poll,5000),wake=()=>{if(!document.hidden){dirty=true;poll()}};document.addEventListener('visibilitychange',wake);
  return()=>{active=false;clearInterval(tick);stopWatch();document.removeEventListener('visibilitychange',wake)};
 },[selected]);

 const mutate=async fn=>{if(busy)return;setBusy(true);setStatus('');try{await fn()}catch(e){setStatus(e.message)}finally{setBusy(false)}};
 const send=async text=>{const id=selectedRef.current;await groupSend(id,text);if(id===selectedRef.current){setRows(await groupMessages(id));setBody('')}};
 const record=async()=>{if(recording){audio.current?.recorder.stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setStatus('Bu brauzer ovoz yozishni qo‘llamaydi. Matn yuborishingiz mumkin.');return}try{const id=selected,stream=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current||selectedRef.current!==id){stream.getTracks().forEach(t=>t.stop());return}const mime=['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/mp4'].find(m=>MediaRecorder.isTypeSupported(m));if(!mime){stream.getTracks().forEach(t=>t.stop());throw Error('Mos ovoz formati topilmadi.')}const recorder=new MediaRecorder(stream,{mimeType:mime,audioBitsPerSecond:32000}),chunks=[],start=Date.now(),state={recorder,stream,discard:false};audio.current=state;recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=async()=>{clearInterval(timer.current);stream.getTracks().forEach(t=>t.stop());audio.current=null;if(alive.current)setRecording(false);if(state.discard||!alive.current||selectedRef.current!==id)return;try{const blob=new Blob(chunks,{type:mime});if(blob.size>262144||blob.size<75)throw Error('Ovoz hajmi mos emas. Qisqaroq yozing.');const bytes=new Uint8Array(await blob.arrayBuffer());let binary='';bytes.forEach(b=>binary+=String.fromCharCode(b));await groupSend(id,'',{base64:btoa(binary),mime:mime.split(';')[0],duration:Math.min(15,Math.max(1,Math.round((Date.now()-start)/1000)))});if(alive.current)setRows(await groupMessages(id))}catch(e){if(alive.current)setStatus(e.message)}};recorder.start();setSeconds(0);setRecording(true);timer.current=setInterval(()=>{const s=Math.floor((Date.now()-start)/1000);setSeconds(s);if(s>=15&&recorder.state==='recording')recorder.stop()},250)}catch(e){setStatus(e.message||'Mikrofonga ruxsat berilmadi.')}};
 return <section className="cg-chat"><header><h2>Sinf guruhlari</h2><p>Xabarlar 24 soat ko‘rinadi. Guruh kodi faqat taklif etilgan o‘quvchilarga beriladi.</p></header><div className="cg-layout"><aside>{teacher&&<form onSubmit={e=>{e.preventDefault();mutate(async()=>{const g=await groupAction('create',{title:title.trim()});await refresh();setSelected(g.id);setTitle('')})}}><label>Yangi guruh nomi<input required minLength="4" maxLength="80" value={title} onChange={e=>setTitle(e.target.value)}/></label><button disabled={busy}>Guruh yaratish</button></form>}<form onSubmit={e=>{e.preventDefault();mutate(async()=>{const g=await groupAction('join',{code:code.trim().toUpperCase()});await refresh();setSelected(g.id);setCode('')})}}><label>Taklif kodi<input aria-label="Guruh kodi" required minLength="10" maxLength="10" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} autoComplete="off"/></label><button disabled={busy}>Guruhga qo‘shilish</button></form><nav aria-label="Mening guruhlarim">{groups.map(g=><button key={g.id} aria-pressed={g.id===selected} onClick={()=>setSelected(g.id)}>{g.title} · {g.active?'faol':'yopiq'}</button>)}</nav></aside><div className="cg-room">{group?<><h3>{group.title}</h3>{owner&&<p>Kod: <b>{group.join_code}</b> <button disabled={busy} onClick={()=>mutate(async()=>{await groupAction('toggle',{id:group.id,active:!group.active});await refresh()})}>{group.active?'Guruhni yopish':'Faollashtirish'}</button></p>}<details><summary>A’zolar · {members.length}</summary>{members.map(m=><p key={m.student_id}>{m.student_name} {owner&&<button onClick={()=>mutate(async()=>{await groupRemove(group.id,m.student_id);setMembers(await groupMembers(group.id))})}>A’zoni chiqarish</button>}</p>)}</details><div className="cg-messages" role="log" aria-label="Guruh xabarlari" aria-live="polite">{rows.length?rows.map(r=><article key={r.id}><div><b>{r.sender_name}</b><time dateTime={r.created_at}>{new Date(r.created_at).toLocaleTimeString('uz-UZ',{hour:'2-digit',minute:'2-digit'})}</time></div>{r.kind==='voice'?<Voice id={r.id}/>:<p>{r.body}</p>}{(owner||r.sender_id===user.id)&&<button aria-label="Xabarni o‘chirish" onClick={()=>mutate(async()=>{await groupRemove(r.id);setRows(await groupMessages(group.id))})}>O‘chirish</button>}</article>):<p>Hali yangi xabar yo‘q.</p>}</div><form onSubmit={e=>{e.preventDefault();if(body.trim())mutate(()=>send(body.trim()))}}><label>Guruh xabari<textarea aria-label="Guruh xabari" maxLength="800" rows="2" value={body} onChange={e=>setBody(e.target.value)} disabled={!group.active}/></label><div className="cg-actions"><button disabled={busy||recording||!body.trim()||!group.active}>Yuborish</button><button type="button" disabled={busy||!group.active} onClick={record}>{recording?`Yozishni tugatish · ${seconds} s`:'Ovoz yozish · 15 s'}</button></div></form></>:<p>Guruh tanlang yoki ustoz bergan kodni kiriting.</p>}</div></div>{status&&<p role="status">{status}</p>}</section>
}
