import React,{useMemo,useState} from 'react';
import {ArrowDown,ArrowUp,Plus,Search,Trash2,Save} from 'lucide-react';
import {competitionKinds,makeCompetition,sourceKey,stageFromSource,validateCompetition} from './competition-model.js';
import {officeTemplates} from './office-lab-model.js';
import {competitionApi} from './competition-service.js';

const blankQuestion=()=>({id:crypto.randomUUID(),type:'test',text:'',options:['','','',''],correct:0,points:100,answer:'',explanation:''});
const labels={test:'Variantli savol',practical:'Qisqa javob / formula',shortcut:'Tugmalar kombinatsiyasi',python:'Python amaliyoti',office:'Word, Excel yoki PowerPoint',prompt:'Mezonli yozma javob'};
function QuestionEditor({q,index,onChange,onRemove}){
 const change=fields=>onChange({...q,...fields});
 return <fieldset className="comp-question-editor"><legend>{index+1}-savol</legend><div className="comp-row">
  <label>Savol turi<select value={q.type} onChange={e=>change({type:e.target.value})}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
  <label>Savol balli<input type="number" min="10" max="10000" value={q.points} onChange={e=>change({points:Number(e.target.value)})}/></label>
  <button type="button" className="btn btn-ghost" onClick={onRemove} aria-label={index+1+'-savolni olib tashlash'}><Trash2 size={17}/></button></div>
  <label>Savol yoki vazifa<textarea maxLength={2000} value={q.text} onChange={e=>change({text:e.target.value})}/></label>
  {q.type==='test'&&<div className="comp-options-editor">{q.options.map((option,i)=><div key={i}><label><input type="radio" name={'correct-'+q.id} checked={q.correct===i} onChange={()=>change({correct:i})}/><span>{String.fromCharCode(65+i)}</span></label><input aria-label={index+1+'-savol '+String.fromCharCode(65+i)+' varianti'} value={option} maxLength={500} onChange={e=>change({options:q.options.map((x,n)=>i===n?e.target.value:x)})}/></div>)}<small>To‘g‘ri variantning doirasini belgilang.</small></div>}
  {['practical','shortcut','python'].includes(q.type)&&<label>{q.type==='python'?'Kutilgan konsol natijasi':q.type==='shortcut'?'To‘g‘ri kombinatsiya (masalan, Ctrl+C)':'To‘g‘ri javob'}<textarea maxLength={8000} value={q.answer||''} onChange={e=>change({answer:e.target.value})}/></label>}
  {q.type==='practical'&&<label>Boshqa qabul qilinadigan javoblar, har biri alohida qatorda<textarea value={(q.acceptedAnswers||[]).join('\n')} maxLength={1500} onChange={e=>change({acceptedAnswers:e.target.value.split('\n')})}/></label>}
  {q.type==='python'&&<label>Boshlang‘ich kod<textarea spellCheck="false" maxLength={8000} value={q.code||''} onChange={e=>change({code:e.target.value})}/></label>}
  {q.type==='office'&&<label>Amaliy muharrir<select value={q.officeTemplate||''} onChange={e=>change({officeTemplate:e.target.value,officeTask:undefined,officeRubric:undefined})}><option value="">Vazifani tanlang</option>{Object.entries(officeTemplates).map(([id,t])=><option key={id} value={id}>{t.title}</option>)}</select></label>}
  {q.type==='prompt'&&<label>Javobda bo‘lishi kerak bo‘lgan iboralar, har biri alohida qatorda<textarea value={(q.criteria||[]).map(x=>typeof x==='string'?x:(x.keywords||[]).join(' | ')).join('\n')} maxLength={1500} onChange={e=>change({criteria:e.target.value.split('\n')})}/><small>Server yozma javobni shu iboralar asosida baholaydi.</small></label>}
  <label>Javobdan keyingi tushuntirish<textarea maxLength={1000} value={q.explanation||''} onChange={e=>change({explanation:e.target.value})}/></label>
 </fieldset>;
}
export default function CompetitionBuilder({initial,catalog,onSaved,onCancel,onReloadCatalog,catalogError}){
 const [value,setValue]=useState(()=>initial||makeCompetition()),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [editor,setEditor]=useState(null);
 const update=fields=>{setValue(old=>({...old,...fields}));setError('')};
 const stageChange=(i,fields)=>update({stages:value.stages.map((s,n)=>i===n?{...s,...fields}:s)});
 const sources=useMemo(()=>(catalog||[]).filter(s=>(filter==='all'||s.kind===filter)&&[s.title,s.pin,s.subject,s.ownerName,s.subtitle].some(t=>String(t||'').toLowerCase().includes(query.toLowerCase()))),[catalog,query,filter]);
 const addSource=s=>{if(value.stages.length>=24)return;update({stages:[...value.stages,stageFromSource(s)]});setEditor(null)};
 const addCustom=kind=>{update({stages:[...value.stages,{kind,title:kind==='typing'?'Yangi typing bosqichi':'Yangi quiz bosqichi',sourceKind:'custom',duration:kind==='typing'?120:300,weight:1,custom:kind==='typing'?{text:'',language:'uz'}:{questions:[blankQuestion()]}}]});setEditor(value.stages.length)};
 const move=(i,dir)=>{const list=[...value.stages];[list[i],list[i+dir]]=[list[i+dir],list[i]];update({stages:list});setEditor(null)};
 const save=async()=>{
  if(busy)return;let issue=validateCompetition(value);
  if(!issue)for(const stage of value.stages){if(stage.kind!=='quiz'||stage.sourceKind!=='custom')continue;for(const q of stage.custom.questions){
   if(q.text.trim().length<3)issue='Har bir savolning matnini yozing.';
   else if(q.type==='test'&&(q.options.some(o=>!o.trim())||new Set(q.options.map(o=>o.trim().toLowerCase())).size!==q.options.length))issue='Variantlarni to‘ldiring va takrorlamang.';
   else if(['practical','shortcut','python'].includes(q.type)&&!q.answer.trim())issue='Savolning to‘g‘ri javobini kiriting.';
   else if(q.type==='office'&&!q.officeTemplate&&!q.officeTask)issue='Amaliy savol uchun muharrir vazifasini tanlang.';
   else if(q.type==='prompt'&&!(q.criteria||[]).filter(x=>typeof x==='string'?x.trim():x.keywords?.length).length)issue='Yozma javob mezonlarini kiriting.';
  }}
  if(issue){setError(issue);return}
  const config={...value,teams:value.teams.map(t=>({...t,roster:(t.roster||[]).map(n=>n.trim())})),stages:value.stages.map(s=>s.sourceKind==='custom'&&s.kind==='quiz'?{...s,custom:{...s.custom,questions:s.custom.questions.map(q=>({...q,acceptedAnswers:(q.acceptedAnswers||[]).filter(x=>x.trim()),criteria:(q.criteria||[]).filter(x=>typeof x==='string'?x.trim():x.keywords?.length).map(x=>typeof x==='string'?{label:x.trim(),keywords:x.split('|').map(k=>k.trim()).filter(Boolean)}:x)}))}}:s)};
  setBusy(true);setError('');try{const result=await competitionApi('save',{config});onSaved(result.id)}catch(e){setError(e.message)}finally{setBusy(false)}
 };
 return <div className="competition-builder"><header className="comp-page-head"><div><span className="comp-eyebrow">USTOZ UCHUN</span><h1>{initial?'Qoralamani tahrirlash':'Jamoaviy musobaqa tuzing'}</h1><p>Jamoalarni belgilang, kamida 4 bosqich biriktiring. Saqlagach, kirish kodlarini tarqating.</p></div><button className="btn btn-outline" disabled={busy} onClick={onCancel}>Bekor qilish</button></header>
 <form onSubmit={e=>{e.preventDefault();save()}}>
 <section className="comp-panel"><h2>1. Musobaqa ma’lumotlari</h2><label>Musobaqa nomi<input required minLength={4} maxLength={100} value={value.title} onChange={e=>update({title:e.target.value})} placeholder="Masalan, 7-sinflar bilim bahsi"/></label>
 <label>Qisqa izoh<textarea maxLength={800} value={value.description} onChange={e=>update({description:e.target.value})} placeholder="Ishtirokchilarga sana, mavzu yoki qoidalarni ayting."/></label><label>Kimlar topa oladi?<select value={value.visibility} onChange={e=>update({visibility:e.target.value})}><option value="public">Faol musobaqa barcha o‘quvchilarga ko‘rinadi</option><option value="code">Faqat jamoa kodi orqali</option></select></label></section>
 <section className="comp-panel"><h2>2. Jamoalar va ishtirokchilar</h2><div className="comp-row"><label>Har bir jamoada<input type="number" min="1" max="12" value={value.teamSize} onChange={e=>update({teamSize:Number(e.target.value)})}/></label><label>Jamoalar soni<input type="number" min="2" max="32" value={value.teams.length} onChange={e=>{const n=Math.max(2,Math.min(32,Number(e.target.value)||2));update({teams:Array.from({length:n},(_,i)=>value.teams[i]||{title:'Jamoa '+(i+1),roster:[]})})}}/></label><span className="comp-count">{value.teams.length*value.teamSize} ishtirokchi</span></div>
 <p className="comp-muted">Ismlarni yozsangiz, o‘quvchi shu ro‘yxatdagi ism-familiya bilan kiradi. Bo‘sh qoldirsangiz, kod egasi bo‘sh o‘ringa yoziladi. Musobaqa barcha jamoalar to‘lgach boshlanadi.</p>
 <div className="comp-team-editors">{value.teams.map((team,i)=><fieldset key={i}><legend>{i+1}-jamoa</legend><label>Jamoa nomi<input required minLength={2} maxLength={60} value={team.title} onChange={e=>update({teams:value.teams.map((t,n)=>i===n?{...t,title:e.target.value}:t)})}/></label><label>Ishtirokchilar ({value.teamSize} ta, ixtiyoriy)<textarea value={(team.roster||[]).join('\n')} rows={Math.min(6,value.teamSize+1)} maxLength={600} placeholder="Har bir ism-familiya alohida qatorda" onChange={e=>update({teams:value.teams.map((t,n)=>i===n?{...t,roster:e.target.value===''?[]:e.target.value.split('\n')}:t)})}/></label></fieldset>)}</div></section>
 <section className="comp-panel"><h2>3. Bosqichlar <span className="comp-badge">{value.stages.length} / 24</span></h2><p>Quizlar, uzun matnli typing va labirintlarni istalgan tartibda qo‘shing. Manbadagi savollar musobaqa uchun alohida nusxalanadi.</p>
 <div className="comp-stage-list">{value.stages.map((s,i)=><article key={i} className={'comp-stage-editor '+(editor===i?'is-expanded':'')}><div className="comp-stage-top"><span className="comp-step">{i+1}</span><div><b>{s.title}</b><small>{competitionKinds[s.kind]} · {s.sourceKind==='custom'?'O‘zingiz tuzgan':'Biriktirilgan'}</small></div><button type="button" className="btn btn-ghost" aria-label={i+1+'-bosqichni yuqoriga'} disabled={i===0||busy} onClick={()=>move(i,-1)}><ArrowUp size={16}/></button><button type="button" className="btn btn-ghost" aria-label={i+1+'-bosqichni pastga'} disabled={i===value.stages.length-1||busy} onClick={()=>move(i,1)}><ArrowDown size={16}/></button><button type="button" className="btn btn-ghost" onClick={()=>setEditor(editor===i?null:i)}>{editor===i?'Yopish':'Sozlash'}</button><button type="button" className="btn btn-ghost" aria-label={i+1+'-bosqichni olib tashlash'} onClick={()=>{update({stages:value.stages.filter((_,n)=>n!==i)});setEditor(null)}}><Trash2 size={16}/></button></div>
 {editor===i&&<div className="comp-stage-settings"><div className="comp-row"><label>Bosqich nomi<input minLength={3} maxLength={100} value={s.title} onChange={e=>stageChange(i,{title:e.target.value})}/></label><label>Vaqt (sekund)<input type="number" min={30} max={3600} value={s.duration} onChange={e=>stageChange(i,{duration:Number(e.target.value)})}/></label><label>Ball koeffitsiyenti<input type="number" min={1} max={10} value={s.weight} onChange={e=>stageChange(i,{weight:Number(e.target.value)})}/></label></div>
 {s.sourceKind==='custom'&&s.kind==='typing'&&<><label>Teriladigan matn<textarea value={s.custom.text} minLength={20} maxLength={4000} rows={6} onChange={e=>stageChange(i,{custom:{...s.custom,text:e.target.value}})}/></label><label>Matn tili<select value={s.custom.language||'uz'} onChange={e=>stageChange(i,{custom:{...s.custom,language:e.target.value}})}><option value="uz">O‘zbekcha</option><option value="en">Inglizcha</option></select></label></>}
 {s.sourceKind==='custom'&&s.kind==='quiz'&&<>{s.custom.questions.map((q,n)=><QuestionEditor key={q.id||n} q={q} index={n} onChange={next=>stageChange(i,{custom:{...s.custom,questions:s.custom.questions.map((x,k)=>k===n?next:x)}})} onRemove={()=>stageChange(i,{custom:{...s.custom,questions:s.custom.questions.filter((_,k)=>k!==n)}})}/>)}<button type="button" className="btn btn-outline" disabled={s.custom.questions.length>=50} onClick={()=>stageChange(i,{custom:{...s.custom,questions:[...s.custom.questions,blankQuestion()]}})}><Plus size={16}/> Savol qo‘shish</button></>}
 </div>}</article>)}</div>
 <div className="comp-library"><h3>Tizimdagi materiallardan biriktiring</h3><div className="comp-row"><label className="comp-search"><Search size={17}/><input aria-label="Material nomi yoki 6 raqamli quiz kodi" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nom, fan yoki 6 raqamli kod"/></label><label>Tur<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Barchasi</option>{Object.entries(competitionKinds).map(([k,label])=><option value={k} key={k}>{label}</option>)}</select></label></div>
 {catalogError&&<div role="alert" className="comp-error">{catalogError}<button type="button" className="btn btn-outline" onClick={onReloadCatalog}>Manbalarni qayta yuklash</button></div>}
 <p className="comp-muted">O‘zingizning materiallaringiz, ommaviy ustoz testlari va tayyor mashqlar ko‘rinadi. Administrator barcha ustozlarning materiallarini tanlay oladi.</p>
 <div className="comp-source-list">{sources.map(s=><article key={sourceKey(s)}><div><b>{s.title}</b><small>{competitionKinds[s.kind]} · {s.count?s.count+(s.kind==='typing'?' belgi · ':' savol · '):''}{s.pin?'Kod '+s.pin+' · ':''}{s.ownerName||'SinfQuiz'}</small></div><button type="button" className="btn btn-outline" disabled={value.stages.length>=24||busy} onClick={()=>addSource(s)}><Plus size={16}/> Biriktirish</button></article>)}{!sources.length&&<p>Qidiruvga mos material yo‘q. O‘zingiz bosqich tuzishingiz ham mumkin.</p>}</div>
 <div className="comp-row comp-custom-actions"><button type="button" className="btn btn-outline" disabled={value.stages.length>=24||busy} onClick={()=>addCustom('quiz')}><Plus size={16}/> Quizni o‘zim tuzaman</button><button type="button" className="btn btn-outline" disabled={value.stages.length>=24||busy} onClick={()=>addCustom('typing')}><Plus size={16}/> Typing matnini yozaman</button></div></div></section>
 <footer className="comp-save-bar"><div><b>{value.stages.length} bosqich · {value.teams.length} jamoa · {value.teamSize} a’zo</b><small>Har bosqich 0–100 ball. Jamoa balli barcha belgilangan a’zolarning o‘rtacha natijasidir.</small></div><button className="btn btn-primary" type="submit" disabled={busy}><Save size={17}/> {busy?'Saqlanmoqda…':'Qoralamani saqlash'}</button></footer>
 {error&&<p role="alert" className="comp-error">{error}</p>}</form></div>;
}
