import React,{useEffect,useRef,useState} from 'react';
import {io} from 'socket.io-client';
import {ArrowLeft,Check,ChevronRight,Clock3,Plus,Radio,Swords,Trophy,Users} from 'lucide-react';
import {api} from './api.js';
import {playSound} from './effects.jsx';
import ShortcutInput from './ShortcutInput.jsx';
import KurashArena from './KurashArena.jsx';
import './duel.css';
export const phases={waiting:'Qatnashchilar kutilmoqda',countdown:'Boshlanmoqda',running:'Bellashuv davom etmoqda',finished:'Bellashuv tugadi',cancelled:'Bekor qilingan'};
const duration=ms=>(Math.max(0,ms)/1000).toFixed(1)+' s';
function Scoreboard({match,playerId}){return <div className="duel-scoreboard">{[0,1].map(seat=>{const p=match.players.find(p=>p.seat===seat);return <div className={`duel-player seat-${seat} ${p?.id===playerId?'is-you':''}`} key={seat}><div className="duel-badge">{seat===0?'K':'Y'}</div><div><small>{seat===0?'KO‘K':'YASHIL'} {p?.id===playerId?'· SIZ':''}</small><h2>{p?.name||'Raqib kutilmoqda'}</h2><p>{p?(match.phase==='waiting'?(p.ready?'✓ Tayyor':'Tayyorgarlik'):p.done?'Yakunladi':`${p.answers} / ${match.questionCount} javob`):'Ikkinchi o‘quvchi kod bilan kiradi'}</p></div><strong>{p?.correct||0}<span>to‘g‘ri</span></strong></div>})}</div>}
function Outcome({match}){if(match.phase==='cancelled')return <div className="duel-outcome"><h2>Bellashuv bekor qilindi</h2><p>{match.cancelReason}</p></div>;if(match.phase!=='finished')return null;const r=match.result,p=match.players.find(p=>p.id===r.winnerId);return <div className="duel-outcome" role="status"><Trophy size={28}/><h2>{r.kind==='draw'?'DURANG':`${p?.name||'Kurashchi'} g‘olib!`}</h2><p>{r.reason==='accuracy'?'Ko‘proq to‘g‘ri javob bilan g‘alaba.':r.reason==='speed'?'To‘g‘ri javoblar teng — vaqt bo‘yicha g‘alaba.':match.players.every(p=>p.correct===0)?'Ikkala qatnashchida ham to‘liq to‘g‘ri javob yo‘q.':'Natija teng. 0,1 sekundgacha farq durang hisoblanadi.'}</p><div>{match.players.map(p=><span key={p.id}>{p.name}: <b>{p.correct}/{match.questionCount}</b> · {duration(p.elapsedMs)}</span>)}</div></div>}
export function DuelBoard({match,playerId,offset}){const clock=useRef({stamp:0,offset:0});if(clock.current.stamp!==match.serverNow)clock.current={stamp:match.serverNow,offset:(match.serverNow||Date.now())-Date.now()};return <><Scoreboard match={match} playerId={playerId}/><KurashArena match={match} serverOffset={offset??clock.current.offset}/><Outcome match={match}/></>}
export function DuelScreen({duel,onUpdate,onLeave}){
 const {match,question:q}=duel;const mine=match.players.find(p=>p.id===duel.playerId);const [selected,setSelected]=useState(null),[value,setValue]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[connected,setConnected]=useState(true),[now,setNow]=useState(Date.now());
 const offset=useRef((duel.serverNow||Date.now())-Date.now()),polling=useRef(false),sending=useRef(false),lastSound=useRef(''),lastCount=useRef(0),lastGrip=useRef(0);
 useEffect(()=>{offset.current=(duel.serverNow||Date.now())-Date.now()},[duel.serverNow]);
 useEffect(()=>{setSelected(null);setValue('');setError('')},[q?.id]);
 useEffect(()=>{const clock=setInterval(()=>setNow(Date.now()),100);return()=>clearInterval(clock)},[]);
 useEffect(()=>{let alive=true;const refresh=async()=>{if(polling.current)return;polling.current=true;try{const next=await api('/api/duel/session');if(alive){onUpdate(next);setConnected(true)}}catch(e){if(alive){setConnected(false);setError(e.message)}}finally{polling.current=false}};
  const socket=io({withCredentials:true,transports:['websocket','polling']});socket.on('duel',refresh);socket.on('connect',refresh);socket.on('disconnect',()=>setConnected(false));socket.on('connect_error',()=>setConnected(false));const timer=setInterval(refresh,1500);return()=>{alive=false;clearInterval(timer);socket.close()};
 },[duel.playerId]);
 useEffect(()=>{if(lastSound.current===match.phase)return;lastSound.current=match.phase;if(match.phase==='countdown')playSound('arena');if(match.phase==='running')playSound('grip');if(match.phase==='finished')playSound(match.result?.kind==='draw'?'draw':'impact')},[match.phase,match.result?.kind]);
 const current=now+offset.current,seconds=Math.max(0,Math.ceil(((duel.deadline||0)-current)/1000)),countdown=Math.max(0,Math.ceil(((match.startsAt||0)-current)/1000));
 useEffect(()=>{if(match.phase==='countdown'&&countdown>0&&countdown!==lastCount.current){lastCount.current=countdown;playSound('countdown')}},[match.phase,countdown]);
 useEffect(()=>{if(match.phase==='running'&&Math.floor(now/2400)!==lastGrip.current){lastGrip.current=Math.floor(now/2400);playSound('grip')}},[match.phase,now]);
 const action=async(path,data)=>{if(sending.current)return;sending.current=true;setBusy(true);setError('');try{const before=mine?.correct||0,next=await api(path,{method:'POST',role:'duel',data});if(path.endsWith('/answer')){const after=next.match.players.find(p=>p.id===next.playerId)?.correct||0;playSound(after>before?'correct':'wrong')}onUpdate(next)}catch(e){setError(e.message)}finally{sending.current=false;setBusy(false)}};
 return <main className="duel-page"><header className="duel-heading"><div><div className="eyebrow"><Swords size={15}/> BILIM KURASHI · 1 GA 1</div><h1>{match.title}</h1><p>{phases[match.phase]} · {match.questionCount} savol</p></div><span className={`duel-live ${connected?'':'offline'}`}><Radio size={14}/>{connected?'JONLI':'QAYTA ULANMOQDA'}</span></header>
  <DuelBoard match={match} playerId={duel.playerId} offset={offset.current}/>
  {match.phase==='waiting'&&<section className="duel-stage-card"><h2>{match.players.length<2?'Raqibni kutyapmiz':'Ikkala kurashchi maydonda'}</h2><p>O‘qituvchi bergan kod: <b>{match.pin}</b>. Ikkalangiz tayyor bo‘lgach, sanoq boshlanadi.</p><button className="btn btn-primary" disabled={busy||mine?.ready} onClick={()=>action('/api/duel/ready')}>{mine?.ready?<><Check size={18}/> Siz tayyorsiz</>:<><Check size={18}/> Tayyorman</>}</button></section>}
  {match.phase==='countdown'&&<div className="duel-countdown" role="status"><strong>{Math.max(1,countdown)}</strong><span>Tayyorlaning. Savollar bir vaqtda ochiladi.</span></div>}
  {match.phase==='running'&&q&&<section className="duel-question" key={q.id}><div className="duel-question-meta"><span>{duel.index+1} / {match.questionCount} · {q.subject}</span><b><Clock3 size={16}/>{seconds}s</b></div><h2>{q.text}</h2>{q.type==='test'?<div className="answer-grid">{q.options.map((item,i)=><button key={i} disabled={busy||seconds===0} className={selected===i?'selected':''} onClick={()=>setSelected(i)}><span>{String.fromCharCode(65+i)}</span><b>{item}</b></button>)}</div>:q.type==='shortcut'?<ShortcutInput value={value} onChange={setValue} disabled={busy||seconds===0}/>:<><textarea className="duel-answer" aria-label="Kurash javobi" maxLength={8000} value={value} onChange={e=>setValue(e.target.value)} disabled={busy||seconds===0} placeholder={q.type==='prompt'?'Promptingizni yozing…':'Javobingizni yozing…'}/>{q.criteria&&<div className="rubric-hints">{q.criteria.map(c=><span key={c.label}>{c.label}</span>)}</div>}</>}
   <div className="duel-question-footer"><span>{seconds===0?'Vaqt tugadi. Keyingi savol ochilmoqda…':'Javob yuborilgach keyingi savol avtomatik ochiladi.'}</span><button className="btn btn-primary" disabled={busy||seconds===0||(q.type==='test'?selected===null:!value.trim())} onClick={()=>action('/api/duel/answer',{questionId:q.id,value:q.type==='test'?selected:value})}>{busy?'Yuborilmoqda…':'Javobni yuborish'}<ChevronRight size={17}/></button></div></section>}
  {match.phase==='running'&&mine?.done&&<section className="duel-stage-card"><Check size={28}/><h2>Siz yakunladingiz!</h2><p>Raqibning natijasi kutilmoqda. Yakuniy qarorni server chiqaradi.</p></section>}
  {error&&<p className="form-error" role="alert">{error}</p>}
  <div className="duel-bottom"><p>Avval aniqlik, keyin tezlik. Vaqt serverda o‘lchanadi.</p><button className="btn btn-outline" onClick={()=>{if(['finished','cancelled'].includes(match.phase)||confirm('Kurashdan chiqilsinmi? Boshlangan bellashuv bekor qilinadi.'))onLeave()}}><ArrowLeft size={16}/>{['finished','cancelled'].includes(match.phase)?'Bosh sahifa':'Kurashdan chiqish'}</button></div>
 </main>
}
export function DuelAdmin({db,onChanged,notify}){
 const [open,setOpen]=useState(false),[quizId,setQuizId]=useState(''),[title,setTitle]=useState(''),[pin,setPin]=useState(''),[busy,setBusy]=useState(false),[watch,setWatch]=useState(null);
 const matches=db.duels||[];const selected=matches.find(m=>m.id===watch);
 const create=async e=>{e.preventDefault();setBusy(true);try{const result=await api('/api/duels',{method:'POST',data:{quizId,title,pin}});await onChanged();setOpen(false);setWatch(result.match.id);notify('Kurash yaratildi. Kodni ikki o‘quvchiga bering.')}catch(e){notify(e.message)}finally{setBusy(false)}};
 const cancel=async m=>{if(!confirm('Bu kurash bekor qilinsinmi?'))return;try{await api('/api/duels/'+m.id+'/cancel',{method:'POST'});await onChanged()}catch(e){notify(e.message)}};
 return <section className="duel-admin"><div className="duel-admin-title"><div><h2><Swords size={21}/> Bilim kurashi</h2><p>Bir maydon. Ikki o‘quvchi. Bir xil savollar.</p></div><button className="btn btn-primary" disabled={!db.quizzes.length} onClick={()=>{setQuizId(db.quizzes[0]?.id||'');setTitle('Informatika: 1 ga 1');setPin(String(Math.floor(100000+Math.random()*900000)));setOpen(true)}}><Plus size={17}/> Kurash yaratish</button></div>
 {!db.quizzes.length&&<p className="duel-empty">Avval test yarating yoki savollar bankidan test qo‘shing.</p>}
 {open&&<form className="duel-create" onSubmit={create}><label>Kurash nomi<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Savollar olinadigan test<select value={quizId} onChange={e=>setQuizId(e.target.value)}>{db.quizzes.map(q=><option key={q.id} value={q.id}>{q.title} · {q.questions.length} savol</option>)}</select></label><label>6 xonali kod<input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))}/></label><p>Savollar nusxasi saqlanadi. Har bir topshiriqda faqat to‘liq to‘g‘ri javob hisoblanadi.</p><div><button type="button" className="btn btn-ghost" onClick={()=>setOpen(false)}>Bekor qilish</button><button className="btn btn-primary" disabled={busy}>{busy?'Yaratilmoqda…':'Kurashni ochish'}</button></div></form>}
 <div className="duel-match-list">{matches.slice().reverse().map(m=><article key={m.id}><div><b>{m.title}</b><small>{phases[m.phase]} · {m.players.length}/2 o‘quvchi · Kod: <strong>{m.pin}</strong></small></div><button className="btn btn-outline" onClick={()=>setWatch(watch===m.id?null:m.id)}>{watch===m.id?'Yopish':'Kuzatish'}</button>{!['finished','cancelled'].includes(m.phase)&&<button className="btn btn-ghost" onClick={()=>cancel(m)}>Bekor qilish</button>}</article>)}</div>
 {selected&&<div className="duel-watch"><h3>{selected.title} · {selected.pin}</h3><DuelBoard match={selected} offset={undefined}/></div>}
 </section>
}
