import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {ArrowDown,ArrowLeft,ArrowRight,ArrowUp,Check,ChevronRight,Clock3,Maximize,DoorOpen,Headphones,Lightbulb,LockKeyhole,Map as MapIcon,Play,RotateCcw,Settings,ShieldCheck,Volume2,VolumeX,X} from 'lucide-react';
import {api} from './api.js';
import {audioMazeLevels,mazeMapAttribution,mazePath} from './audio-maze-content.js';
import './english-audio-maze.css';
import LearningVisual,{MazeThumbnail} from './LearningVisual.jsx';
import './discovery-theme.css';
import ScenicMaze from './ScenicMaze.jsx';
import './scenic-maze.css';
const noop=()=>{};

const posKey=p=>`${p[0]},${p[1]}`;
const speak=text=>{if(!text||!window.speechSynthesis||!window.SpeechSynthesisUtterance)return false;window.speechSynthesis.cancel();const line=new SpeechSynthesisUtterance(text);line.lang='en-US';line.rate=.84;line.pitch=1;window.speechSynthesis.speak(line);return true};
const playTone=(good)=>{try{const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return;const ctx=new Ctx(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.value=good?620:190;gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.075,ctx.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+(good?0.14:0.2));osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.22);osc.onended=()=>ctx.close()}catch{}};
const levelName=level=>level?.title||'Tinglab top';

export default function EnglishAudioMaze({user,onBack=noop,notify=noop,onPlayingChange=noop}){
 const teacher=['teacher','admin'].includes(user?.role),[page,setPage]=useState('choose'),[loading,setLoading]=useState(false),[error,setError]=useState(''),[activeRuns,setActiveRuns]=useState(()=>audioMazeLevels.map(level=>({id:`practice:${level.id}`,ownerId:'',ownerName:'Mustaqil mashq',level}))),[admin,setAdmin]=useState(null),[selected,setSelected]=useState(`practice:${audioMazeLevels[0].id}`),[mode,setMode]=useState('listen'),[nickname,setNickname]=useState(user?.name||''),[sound,setSound]=useState(true),[run,setRun]=useState(null),[promptGate,setPromptGate]=useState(null),[wrongPick,setWrongPick]=useState(false),[hint,setHint]=useState(0),[clock,setClock]=useState(Date.now()),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[feedback,setFeedback]=useState('');
 const [settingsOpen,setSettingsOpen]=useState(false),[difficulty,setDifficulty]=useState('all'),[delivery,setDelivery]=useState('audio');
 const builtins=audioMazeLevels.map(level=>({id:`practice:${level.id}`,ownerId:'',ownerName:'Mustaqil mashq',level})),visibleRuns=activeRuns.filter(r=>difficulty==='all'||r.level.difficulty===difficulty);
 const [managerTab,setManagerTab]=useState('manage'),[edit,setEdit]=useState(null),[savingEdit,setSavingEdit]=useState(false),[teacherChoice,setTeacherChoice]=useState('maze-01'),[notice,setNotice]=useState('');
 useEffect(()=>{window.scrollTo?.({top:0,behavior:'instant'})},[page]);
 const runRef=useRef(null),finishedRef=useRef(false);
 runRef.current=run;
 const load=useCallback(async()=>{setError('');try{const a=await api('/api/audio-maze/active');setActiveRuns([...(a.active||[]),...builtins]);if(a.active?.length)setSelected(v=>a.active.some(x=>x.id===v)?v:a.active[0].id);if(teacher){const d=await api('/api/audio-maze/admin');setAdmin(d);setTeacherChoice(d.activation?.levelId||audioMazeLevels[0]?.id||'maze-01')}}catch(e){setError(e.message)}finally{setLoading(false)}},[teacher]);
 useEffect(()=>{load();return()=>{if(window.speechSynthesis)window.speechSynthesis.cancel()}},[load]);
 useEffect(()=>{if(!run||run.finished)return;const id=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(id)},[run?.instanceId,run?.finished]);
 const finish=useCallback(async(outcome,latest)=>{const r=latest||runRef.current;if(!r||finishedRef.current)return;finishedRef.current=true;const final={...r,finished:true,outcome,finishedAt:Date.now()};setRun(final);setPromptGate(null);setFeedback('');onPlayingChange(false);setSaving(true);try{if(!r.ownerId){try{const key=`sq-maze-practice:${user?.id||'guest'}`,old=JSON.parse(localStorage.getItem(key)||'[]');localStorage.setItem(key,JSON.stringify([{date:Date.now(),level:r.level.title,delivery:r.delivery,correct:r.correct,wrong:r.wrong,outcome},...old.filter(v=>Date.now()-v.date<72*3600000)].slice(0,20)))}catch{}setSaved(true);return}await api('/api/audio-maze/result',{method:'POST',data:{attemptId:r.instanceId,levelId:r.level.id,ownerId:r.ownerId||'',name:(nickname||'O‘quvchi').trim().slice(0,40),mode:r.mode,delivery:r.delivery,outcome,tasksTotal:r.level.tasks.length,correct:r.correct,wrong:r.wrong,assisted:r.assisted,elapsedMs:Math.min(180000,Date.now()-r.startedAt),mistakes:r.mistakes.map(m=>({taskId:m.task.id,chosen:m.chosen}))}});setSaved(true)}catch(e){setSaved(false);notify(`Mashq yakunlandi. Natijani saqlab bo‘lmadi: ${e.message}`)}finally{setSaving(false)}},[nickname,notify,onPlayingChange]);
 useEffect(()=>{const r=runRef.current;if(r&&!r.finished&&Date.now()>=r.deadline)finish('time',r)},[clock,finish]);
 useEffect(()=>{if(!run||run.finished)return;const timer=setInterval(()=>{const current=runRef.current;if(!current||current.finished)return;const path=mazePath(current.level.grid,current.monster,current.position,current.closedGates);if(!path||path.length<2)return;const monster=path[1],next={...current,monster};if(posKey(monster)===posKey(current.position)){finish('caught',next);return}setRun(next)},7200);return()=>clearInterval(timer)},[run?.instanceId,run?.finished,finish]);
 const begin=level=>{if(!level?.tasks?.length)return;finishedRef.current=false;const now=Date.now(),next={instanceId:globalThis.crypto?.randomUUID?.()||`${now}-${Math.random()}`,level,ownerId:level.ownerId||'',position:[...level.start],monster:[...level.monster],closedGates:level.gateCells.map(posKey),taskIndex:0,correct:0,wrong:0,assisted:0,mistakes:[],startedAt:now,deadline:now+180000,mode,delivery,finished:false};setClock(now);setRun(next);setPromptGate(null);setWrongPick(false);setHint(0);setSaved(false);setFeedback('');setNotice('');setPage('game');onPlayingChange(true)};
 const move=useCallback((dx,dy)=>{const current=runRef.current;if(!current||current.finished||promptGate!==null)return;const from=current.position,to=[from[0]+dx,from[1]+dy],cell=current.level.grid[to[1]]?.[to[0]];if(!cell||cell==='#')return;const k=posKey(to),gateIndex=current.level.gateCells.findIndex(p=>posKey(p)===k);if(current.closedGates.includes(k)){if(gateIndex>=0){setPromptGate(gateIndex);setWrongPick(false);setHint(0);setFeedback('');const task=current.level.tasks[gateIndex];if(task&&current.delivery!=='text'&&current.mode==='listen'&&!speak(task.audio)){setRun(v=>({...v,delivery:'text'}));setFeedback('Savol matnli rejimda ochildi.')}}return}const next={...current,position:to};setRun(next);if(cell==='E'&&next.closedGates.length===0)finish('won',next)},[finish,promptGate]);
 useEffect(()=>{if(page!=='game'||!run||run.finished)return;const handler=e=>{const keys={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0]};const value=keys[e.key];if(value){e.preventDefault();move(...value)}if(e.key==='Escape'){e.preventDefault();if(confirm('Mashqni to‘xtatib chiqasizmi?'))finish('left')}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[page,run?.instanceId,run?.finished,move,finish]);
 const submitOption=index=>{const current=runRef.current;if(!current||promptGate===null)return;const task=current.level.tasks[promptGate];if(index===task.answer){const closed=current.closedGates.filter(k=>k!==posKey(current.level.gateCells[promptGate])),correct=current.correct+1,assisted=current.assisted+Number(hint>0||current.mode==='learn'),next={...current,closedGates:closed,position:[...current.level.gateCells[promptGate]],taskIndex:current.taskIndex+1,correct,assisted};setRun(next);setPromptGate(null);setWrongPick(false);setHint(0);setFeedback('');setNotice(`${task.translation} ${task.explanation}`);setTimeout(()=>setNotice(''),4800);if(sound)playTone(true);if(task.audio&&current.delivery!=='text')speak(task.audio);if(posKey(next.position)===posKey(next.level.exit)&&closed.length===0)finish('won',next)}else{const next={...current,wrong:current.wrong+1,mistakes:[...current.mistakes,{task,chosen:index}]};setRun(next);setWrongPick(true);setFeedback(current.delivery==='text'?'Bu javob mos kelmadi. Gapni qayta o‘qib, kalit so‘zlarini tekshiring.':'Bu javob mos kelmadi. Gapni qayta tinglab, yana urinib ko‘ring.');if(sound)playTone(false)} };
 const selectedRun=activeRuns.find(item=>item.id===selected);
 const previewLevel=selectedRun?.level||audioMazeLevels[0];
 const seconds=run?Math.max(0,Math.ceil((run.deadline-clock)/1000)):180;
 const back=()=>{if(run&&!run.finished){if(!confirm('Mashqni yakunlab chiqasizmi?'))return;finish('left');return}if(window.speechSynthesis)window.speechSynthesis.cancel();onPlayingChange(false);onBack()};

 if(loading)return <main className="audio-maze-page"><div className="audio-maze-loading"><span className="am-spinner"/><p>O‘yin xaritasi yuklanmoqda…</p></div></main>;
 return <main className="audio-maze-page">
  <header className="am-header" hidden={page==='game'&&run&&!run.finished}><button className="am-back" onClick={back} aria-label="Orqaga"><ArrowLeft/></button><div className="am-brand"><span className="am-mark"><Headphones size={19}/></span><div><small>ENGLISH PRACTICE</small><b>Inglizcha labirint</b></div></div><div className="am-head-actions">{teacher&&<button className="am-icon-button" onClick={()=>{setPage('admin');setRun(null);onPlayingChange(false)}}><Settings size={18}/> <span>Ustoz paneli</span></button>}<button className="am-icon-button" onClick={back}><X size={18}/><span>Chiqish</span></button></div></header>
  {error&&<div className="am-error" role="alert">{error}<button onClick={load}>Qayta urinish</button></div>}
  {page==='choose'&&<section className="am-choose">
   <div className="am-discovery-hero"><div className="am-intro"><div className="am-kicker">O‘RGANING · TUSHUNING · YO‘L TOPING</div><h1>Inglizcha savollarga javob bering,<br/><span>labirintdan chiqing.</span></h1><p>Yo‘lingizdagi eshik gapni tushunganingizda ochiladi. Gapni tinglash yoki matndan o‘qish mumkin. Xato javob uchun vaqt jazosi yo‘q.</p><div className="am-facts"><span><Clock3/> 3 daqiqa</span><span><LockKeyhole/> 5–8 eshik</span><span><Volume2/> Ovoz yoki matn</span></div><div className="am-hero-note"><span>01</span><p><b>Har bir eshik — yangi suhbat.</b><br/>Gapni tushuning. Javobni tanlang. Yo‘lingizni davom ettiring.</p></div></div><ScenicMaze level={previewLevel}/></div>
   {teacher?<section className="am-teacher-shortcut"><div><ShieldCheck/><div><b>O‘qituvchi rejimi</b><small>Faollashtirish, darajani tanlash va natijalarni ko‘rish</small></div></div><button className="am-primary" onClick={()=>setPage('admin')}>Boshqaruvga o‘tish <ChevronRight size={18}/></button></section>:null}
   {activeRuns.length? <><div className="am-section-title"><div><small>MUSTAQIL VA SINF MASHQLARI</small><h2>O‘yin xaritasini tanlang</h2></div><label className="am-mode"><input type="checkbox" checked={mode==='learn'} onChange={e=>setMode(e.target.checked?'learn':'listen')}/><span><b>O‘rganish rejimi</b><small>Tarjima va yordamni ko‘rsatadi</small></span></label></div>
    {!user&&<label className="am-name">Ismingiz<input value={nickname} maxLength={40} onChange={e=>setNickname(e.target.value)} placeholder="Ismni kiriting"/></label>}
    <div className="am-learning-options"><label>Daraja<select aria-label="Labirint darajasi" value={difficulty} onChange={e=>{const d=e.target.value;setDifficulty(d);const first=activeRuns.find(r=>d==='all'||r.level.difficulty===d);if(first)setSelected(first.id)}}><option value="all">Barcha darajalar</option><option value="easy">A1 · boshlang‘ich</option><option value="medium">A2 · tayanch</option><option value="hard">B1 · mustahkamlash</option></select></label><label>Savol ko‘rinishi<select aria-label="Labirint savol rejimi" value={delivery} onChange={e=>{setDelivery(e.target.value);if(e.target.value==='text'){setSound(false);window.speechSynthesis?.cancel()}}}><option value="audio">Ovozli · tinglash</option><option value="text">Matnli · o‘qib test ishlash</option></select></label><p>12 tayyor xarita ustoz faollashtirishini kutmaydi. Daraja va rejimni o‘zingiz tanlaysiz.</p></div><div className="am-level-grid">{visibleRuns.map((item,index)=><button key={item.id} className={`am-level-card ${selected===item.id?'chosen':''}`} onClick={()=>setSelected(item.id)}><div className="am-level-art"><MazeThumbnail level={item.level}/><span className="am-chapter">{String(index+1).padStart(2,'0')}</span></div><span className="am-level-top"><span>{item.level.difficulty==='easy'?'A1':item.level.difficulty==='medium'?'A2':'B1'}</span><MapIcon size={17}/></span><b>{levelName(item.level)}</b><small>{item.level.tasks.length} ta topshiriq · {item.ownerName||'O‘qituvchi'}</small></button>)}</div>
    <div className="am-start-row"><div><small>Standart rejimda tarjima javobdan keyin ochiladi. O‘rganish rejimi natijani reytingga qo‘shmaydi.</small></div><button className="am-primary" disabled={!selectedRun||(!user&&!nickname.trim())} onClick={()=>begin({...selectedRun.level,ownerId:selectedRun.ownerId})}><Play size={18} fill="currentColor"/> Boshlash</button></div>
   </>:<div className="am-empty"><Headphones/><h2>O‘yin hozir yopiq</h2><p>Ustoz xaritani faollashtirganda shu yerda ko‘rinadi.</p>{teacher&&<button className="am-primary" onClick={()=>setPage('admin')}>Xaritani faollashtirish</button>}</div>}
   <details className="am-source"><summary>Ochiq manbalar va texnik ma’lumot</summary><p>Labirintlar SinfQuiz uchun alohida tayyorlangan va yo‘li tekshirilgan. Tasodifiy Prim algoritmi bo‘yicha loyiha manbasi: <a href={mazeMapAttribution.source} target="_blank" rel="noreferrer">emadehsan/maze</a> (MIT, usul bo‘yicha ma’lumot). Ovoz brauzerning Speech Synthesis API orqali qurilmada yaratiladi; mavjud ovozlar qurilmaga qarab farq qiladi.</p></details>
  </section>}
  {page==='game'&&run&&!run.finished&&<section className="am-game"><div className="am-game-top"><div className="scenic-brand"><b>SinfQuiz</b><span><Headphones size={19}/> Inglizcha labirint</span></div><div className={`am-timer ${seconds<30?'urgent':''}`}><strong>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</strong><small>/ 03:00</small><progress value={seconds} max="180" aria-label="Qolgan vaqt"/></div><div className="scenic-tools"><button aria-label="Ovoz effektlari" aria-pressed={sound} onClick={()=>setSound(v=>!v)}>{sound?<Volume2/>:<VolumeX/>}</button><button aria-label="To‘liq ekran" onClick={async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('.am-game').requestFullscreen()}catch{setNotice('Brauzeringiz to‘liq ekran rejimini qo‘llamaydi.')}}}><Maximize/></button><button aria-label="O‘yin sozlamalari" aria-expanded={settingsOpen} onClick={()=>setSettingsOpen(v=>!v)}><Settings/></button><button aria-label="Mashqdan chiqish" onClick={back}><X/></button></div></div>
   {settingsOpen&&<div className="scenic-settings"><b>Boshqaruv</b><p>Kompyuterda WASD yoki yo‘nalish tugmalari; telefonda maydon ostidagi tugmalar orqali yuring. Eshikka yaqinlashganda savol ochiladi.</p><label><input type="checkbox" checked={sound} onChange={e=>setSound(e.target.checked)}/> Javob ovoz effektlari</label><button onClick={()=>setSettingsOpen(false)}>Yopish</button></div>}
   {notice&&<div className="am-notice" role="status">{notice}</div>}<div className="am-game-layout"><div className="am-board-wrap"><LearningVisual mode="maze" level={run.level} position={run.position} monster={run.monster} closed={run.closedGates} label={`Labirint: ${run.level.title}. ${run.closedGates.length} ta yopiq eshik.`} fallback={<ScenicMaze level={run.level} position={run.position} monster={run.monster} closed={run.closedGates}/>}/><div className="am-board-help"><span>WASD yoki yo‘nalish tugmalaridan foydalaning</span><span><b>{run.level.tasks.length-run.closedGates.length}</b> / {run.level.tasks.length} eshik ochildi</span></div><div className="am-controls" aria-label="Labirint boshqaruvi"><span/><button onClick={()=>move(0,-1)} aria-label="Yuqoriga"><ArrowUp/></button><span/><button onClick={()=>move(-1,0)} aria-label="Chapga"><ArrowLeft/></button><button onClick={()=>move(0,1)} aria-label="Pastga"><ArrowDown/></button><button onClick={()=>move(1,0)} aria-label="O‘ngga"><ArrowRight/></button></div></div>
</div>
   {promptGate!==null&&<div className="scenic-question-dock"><section className="am-question" role="dialog" aria-modal="false" aria-labelledby="am-question-title"><button className="am-modal-close" onClick={()=>setPromptGate(null)} aria-label="Savolni yopish"><X/></button><div className="am-question-tag"><Headphones size={16}/> {run.delivery==='text'?'O‘QIB JAVOB BERING':'ESHITIB JAVOB BERING'} <span>{promptGate+1}/{run.level.tasks.length}</span></div><h2 id="am-question-title">{run.delivery==='text'?'Gapni o‘qing va javobni tanlang':'Tinglang va mos javobni tanlang'}</h2>{run.delivery==='text'?<p className="am-written-question" lang="en">{run.level.tasks[promptGate].audio}</p>:<div className="am-listen-row"><span className="am-wave" aria-hidden="true"><i/><i/><i/><i/><i/></span><button className="am-play-audio" onClick={()=>{if(!speak(run.level.tasks[promptGate].audio)){setRun(v=>({...v,delivery:'text'}));setFeedback('Savol matnli rejimda ochildi.')}}}><Volume2/> Gapni tinglash <small>Qayta tinglash mumkin</small></button>{run.mode==='learn'&&<small className="am-translation">{run.level.tasks[promptGate].translation}</small>}</div>}<p className="am-question-prompt">{run.delivery==='text'?'Gapning ma’nosiga mos javobni tanlang.':run.mode==='learn'?'Eshitilgan gap nimani bildiradi?':'Eshitganingizga mos javobni tanlang.'}</p><div className="am-options">{run.level.tasks[promptGate].options.map((option,index)=><button key={index} className={wrongPick?'am-after-wrong':''} onClick={()=>submitOption(index)}><span>{String.fromCharCode(65+index)}</span>{option}</button>)}</div>{feedback&&<div className="am-feedback" role="status">{feedback}</div>}<div className="am-hint-row"><button onClick={()=>{const n=Math.min(2,hint+1);setHint(n);if(n===1)setFeedback(run.level.tasks[promptGate].hints?.[0]||'Kalit so‘zlarni ajrating.');else setFeedback(run.level.tasks[promptGate].hints?.[1]||run.level.tasks[promptGate].translation)}}><Lightbulb size={16}/>{hint===0?'Yordam olish':hint===1?'Yana bir ishora':'Javobga ishora'}</button><small>{run.mode==='learn'?'Bu urinish mashq hisobida qoladi.':'Xato javob uchun vaqt kamaymaydi.'}</small></div></section></div>}
   {promptGate===null&&<div className="scenic-idle"><span className="scenic-audio-icon"><Headphones/></span><div><b>{run.delivery==='text'?'Eshikka boring va savolni o‘qing':'Eshikka boring va gapni tinglang'}</b><p>To‘g‘ri javob yo‘lni ochadi. Binafsha izquvardan oldin marraga yeting.</p></div><strong>{run.correct} / {run.level.tasks.length}<small>topshiriq bajarildi</small></strong></div>}
  </section>}
  {page==='game'&&run?.finished&&<section className="am-result"><div className={`am-result-mark ${run.outcome}`}><DoorOpen/></div><small>{run.outcome==='won'?'MARRA':'MASHQ YAKUNLANDI'}</small><h1>{run.outcome==='won'?'Yo‘lni topdingiz!':run.outcome==='caught'?'Izquvar yetib oldi':run.outcome==='left'?'Mashq tugatildi':'Vaqt tugadi'}</h1><p>{run.outcome==='won'?'Savollarga to‘g‘ri javob berib, labirintdan chiqdingiz.':'Javoblarni qayta ko‘rib, yana bir bor urinib ko‘ring.'}</p><div className="am-result-stats"><div><b>{run.correct}/{run.level.tasks.length}</b><span>to‘g‘ri javob</span></div><div><b>{run.wrong}</b><span>xato urinish</span></div><div><b>{Math.floor((run.finishedAt-run.startedAt)/60000)}:{String(Math.floor((run.finishedAt-run.startedAt)%60000/1000)).padStart(2,'0')}</b><span>sarflangan vaqt</span></div></div><p className="am-save-state">{saving?'Natija saqlanmoqda…':saved?'Natija saqlandi.': 'Natija qurilmada ko‘rsatilmoqda.'}</p>{run.mistakes.length>0&&<div className="am-review"><h2>Qayta ko‘rib chiqing</h2>{run.mistakes.slice(-8).map((item,index)=><article key={`${item.task.id}-${index}`}><b>{item.task.audio}</b><span>{item.task.translation}</span><small>Siz tanlagan: {item.task.options[item.chosen]} · To‘g‘ri javob: {item.task.options[item.task.answer]}</small><button onClick={()=>speak(item.task.audio)}><Volume2 size={15}/> Tinglash</button></article>)}</div>}<div className="am-result-actions"><button className="am-primary" onClick={()=>{const level=run.level;finishedRef.current=false;begin(level)}}><RotateCcw/> Yana o‘ynash</button><button className="am-secondary" onClick={()=>{setRun(null);setPage('choose');load()}}>Boshqa xarita</button></div></section>}
  {page==='admin'&&teacher&&<section className="am-admin"><div className="am-admin-heading"><div><small>USTOZ VA ADMIN UCHUN</small><h1>Tinglash labirintini boshqarish</h1><p>O‘quvchilar xaritani bosh sahifadagi ochiq mashqlardan tanlaydi.</p></div><button className="am-secondary" onClick={()=>{setPage('choose');load()}}>O‘yin sahifasi</button></div><div className="am-admin-tabs"><button className={managerTab==='manage'?'active':''} onClick={()=>setManagerTab('manage')}><Settings/> Faollashtirish</button><button className={managerTab==='questions'?'active':''} onClick={()=>{setManagerTab('questions');setEdit(null)}}><Headphones/> Savol yaratish</button><button className={managerTab==='results'?'active':''} onClick={()=>setManagerTab('results')}><MapIcon/> Natijalar</button>{user?.role==='admin'&&<button className={managerTab==='review'?'active':''} onClick={()=>setManagerTab('review')}><ShieldCheck/> Tasdiqlash {admin?.pending?.length?`(${admin.pending.length})`:''}</button>}</div>
   {managerTab==='manage'&&<div className="am-admin-grid"><section className="am-admin-card"><h2>O‘yin xaritasini tanlang</h2><p>Bir ustoz uchun bitta faol xarita. O‘zgartirish o‘quvchi sahifasida darhol aks etadi.</p><label>Xarita<select value={teacherChoice} onChange={e=>setTeacherChoice(e.target.value)}>{audioMazeLevels.map(x=><option value={x.id} key={x.id}>{x.title} · {x.tasks.length} topshiriq</option>)}{(admin?.levels||[]).filter(x=>x.approvalStatus==='approved').map(x=><option value={x.id} key={x.id}>{x.title} · tayyorlangan savollar</option>)}</select></label><div className="am-admin-actions"><button disabled={savingEdit} className="am-primary" onClick={async()=>{setSavingEdit(true);try{await api('/api/audio-maze/activate',{method:'POST',data:{active:true,levelId:teacherChoice}});await load();notify('Audio labirint o‘quvchilar uchun faollashtirildi.')}catch(e){notify(e.message)}finally{setSavingEdit(false)}}}><Play size={17}/> Faollashtirish</button>{admin?.activation?.active&&<button className="am-danger" onClick={async()=>{try{await api('/api/audio-maze/activate',{method:'POST',data:{active:false}});await load();notify('Audio labirint yopildi.')}catch(e){notify(e.message)}}}>Yopish</button>}</div></section><section className="am-admin-card am-status-card"><span className={admin?.activation?.active?'am-status-on':'am-status-off'}/><h2>{admin?.activation?.active?'Hozir ochiq':'Hozir yopiq'}</h2><p>{admin?.activation?.active?`O‘quvchilar “${admin.activation.levelTitle}” xaritasini ko‘rmoqda.`:'Xaritani tanlab “Faollashtirish” tugmasini bosing.'}</p><div><b>{(admin?.results||[]).length}</b><small>Yakunlangan urinishlar</small></div></section></div>}
   {managerTab==='questions'&&<QuestionEditor key={edit?.id||'new'} levels={audioMazeLevels} value={edit} saving={savingEdit} onSave={async payload=>{setSavingEdit(true);try{const result=await api('/api/audio-maze/levels',{method:'POST',data:payload});setEdit(null);await load();notify(result.status==='pending'?'Savollar admin tasdig‘iga yuborildi.':'Yangi savollar saqlandi.')}catch(e){notify(e.message)}finally{setSavingEdit(false)}}}/>}
   {managerTab==='review'&&user?.role==='admin'&&<div className="am-admin-card"><h2>Tasdiq kutayotgan ustoz savollari</h2>{(admin?.pending||[]).length?admin.pending.map(level=><article className="am-pending" key={level.id}><div><b>{level.title}</b><small>{level.ownerName} · {level.tasks?.length||0} ta gap</small></div><button className="am-primary" onClick={async()=>{try{await api(`/api/audio-maze/review/${level.id}`,{method:'POST',data:{decision:'approved'}});await load()}catch(e){notify(e.message)}}}>Tasdiqlash</button><button className="am-danger" onClick={async()=>{try{await api(`/api/audio-maze/review/${level.id}`,{method:'POST',data:{decision:'rejected'}});await load()}catch(e){notify(e.message)}}}>Rad etish</button></article>):<p>Yangi topshiriq yo‘q.</p>}</div>}
    {managerTab==='results'&&<div className="am-admin-card"><h2>O‘quvchi natijalari</h2>{admin?.results?.length?<div className="am-results-table"><div className="am-results-head"><span>O‘QUVCHI</span><span>MASHQ</span><span>XARITA · NATIJA</span><span>SANA</span></div>{admin.results.map(item=><div className="am-results-row" key={item.id}><b>{item.name}</b><span>{item.mode==='learn'?'O‘rganish':item.delivery==='text'?'O‘qib tushunish':'Tinglab tushunish'}</span><span>{item.levelTitle} · {item.correct}/{item.tasksTotal}</span><time>{new Date(item.completedAt||item.createdAt).toLocaleDateString('uz-UZ')}</time></div>)}</div>:<p>Hozircha natija yo‘q. O‘quvchi o‘yinni yakunlaganda natijasi shu yerda chiqadi.</p>}</div>}
  </section>}
 </main>;
}

function MazeBoard({level,position,monster,closed,taskIndex}){
 const rows=level.grid,height=rows.length,width=Math.max(...rows.map(row=>row.length)),cell=28,pad=10,closedSet=new Set(closed),gateMap=new Map(level.gateCells.map((p,i)=>[posKey(p),i]));
 return <div className="am-board" role="img" aria-label={`Labirint xaritasi. ${level.title}. Siz yashil belgidasiz, izquvar binafsha belgida. ${closed.length} eshik qulflangan.`}><svg viewBox={`0 0 ${width*cell+pad*2} ${height*cell+pad*2}`} xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
  <defs><pattern id="am-dots" width="8" height="8" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".8" fill="#d8e5ec"/></pattern></defs><rect x="0" y="0" width={width*cell+pad*2} height={height*cell+pad*2} rx="16" fill="url(#am-dots)"/>
  {rows.flatMap((row,y)=>[...row].map((c,x)=>{const px=pad+x*cell,py=pad+y*cell,k=posKey([x,y]),gateIndex=gateMap.get(k),locked=closedSet.has(k);return <g key={k}><rect x={px+1} y={py+1} width={cell-2} height={cell-2} rx={5} fill={c==='#'?'#17364f':locked?'#f1b84a':c==='E'?'#dff6ee':'#fff'} stroke={c==='#'?'#17364f':locked?'#d5901d':'#d8e5ec'} strokeWidth="1"/>{locked&&<g><rect x={px+9} y={py+13} width="10" height="8" rx="2" fill="#fff"/><path d={`M${px+11} ${py+13}v-3a3 3 0 0 1 6 0v3`} fill="none" stroke="#fff" strokeWidth="2"/><text x={px+14} y={py+9} textAnchor="middle" fontSize="8" fontWeight="700" fill="#775111">{gateIndex+1}</text></g>}{c==='E'&&<text x={px+14} y={py+19} textAnchor="middle" fontSize="13" fontWeight="700" fill="#11765c">E</text>}</g>}))}
  {level.route?.map((p,i)=><circle key={`r${i}`} cx={pad+p[0]*cell+14} cy={pad+p[1]*cell+14} r="1.5" fill="#8db6c7" opacity=".35"/>)}
  <g className="am-mover" transform={`translate(${pad+monster[0]*cell+14} ${pad+monster[1]*cell+14})`}><circle r="10" fill="#8464ce" stroke="#fff" strokeWidth="2"/><circle cx="-3" cy="-2" r="1.4" fill="#fff"/><circle cx="3" cy="-2" r="1.4" fill="#fff"/><path d="M-3 3q3 -3 6 0" fill="none" stroke="#fff" strokeWidth="1.3" strokeLinecap="round"/></g>
  <g className="am-mover am-runner" transform={`translate(${pad+position[0]*cell+14} ${pad+position[1]*cell+14})`}><circle r="10" fill="#0fae8a" stroke="#fff" strokeWidth="2"/><path d="M-5 0h10m-6 -4 6 4-6 4" stroke="#fff" strokeWidth="1.8" fill="none" strokeLinecap="round" strokeLinejoin="round"/></g>
 </svg></div>
}

function QuestionEditor({levels,value,saving,onSave}){
 const [mapId,setMapId]=useState(value?.mapId||levels[0].id),[title,setTitle]=useState(value?.title||''),[tasks,setTasks]=useState(value?.tasks||null);const base=levels.find(x=>x.id===mapId)||levels[0],active=tasks||base.tasks.map(task=>({...task,options:[...task.options]}));
 const change=(i,field,next)=>setTasks(current=>(current||base.tasks.map(task=>({...task,options:[...task.options]}))).map((task,index)=>index===i?{...task,[field]:next}:task));
 useEffect(()=>{setTasks(value?.mapId===mapId?value?.tasks||null:null)},[mapId,value?.id]);
 return <section className="am-admin-card am-editor"><h2>{value?'Savollarni tahrirlash':'O‘zingizning audio topshiriqlaringizni yarating'}</h2><p>Matnlarni o‘zingiz yozing. Saqlangandan so‘ng administrator tasdiqlaydi.</p><div className="am-editor-top"><label>Sahna xaritasi<select value={mapId} onChange={e=>setMapId(e.target.value)}>{levels.map(level=><option key={level.id} value={level.id}>{level.title} · {level.tasks.length} eshik</option>)}</select></label><label>To‘plam nomi<input value={title} maxLength={60} onChange={e=>setTitle(e.target.value)} placeholder="Masalan: Maktab bo‘ylab yo‘l so‘rash"/></label></div>{active.map((task,index)=><article className="am-task-edit" key={`${base.id}-${index}`}><div className="am-task-edit-head"><b>Topshiriq {index+1}</b><small>{task.skill}</small></div><label>Eshitiladigan inglizcha gap<textarea value={task.audio} maxLength={260} onChange={e=>change(index,'audio',e.target.value)}/></label><label>O‘zbekcha ma’nosi<input value={task.translation} maxLength={260} onChange={e=>change(index,'translation',e.target.value)}/></label><div className="am-option-edit">{task.options.map((option,optionIndex)=><label key={optionIndex}>Variant {String.fromCharCode(65+optionIndex)}<input value={option} maxLength={90} onChange={e=>{const options=[...task.options];options[optionIndex]=e.target.value;change(index,'options',options)}}/></label>)}</div><label>To‘g‘ri javob<select value={task.answer} onChange={e=>change(index,'answer',Number(e.target.value))}>{task.options.map((option,i)=><option value={i} key={i}>{String.fromCharCode(65+i)} · {option}</option>)}</select></label></article>)}<button className="am-primary" disabled={saving||!title.trim()||active.some(task=>!task.audio.trim()||task.options.some(option=>!option.trim()))} onClick={()=>onSave({id:value?.id||null,mapId,title:title.trim(),tasks:active})}><Check/> {saving?'Saqlanmoqda…':'Admin tasdig‘iga yuborish'}</button></section>
}
