import React,{useEffect,useState} from 'react';import {ArrowLeft,BookOpen,Compass,LockKeyhole,CheckCircle2,Headphones,Bookmark,PenLine,BarChart3,GraduationCap,ArrowRight} from 'lucide-react';
import {course} from './english-course/service.js';import {catalog,levels,levelNames} from './english-course/catalog.js';
import Lesson from './english-course/Lesson.jsx';import Assessment from './english-course/Assessment.jsx';import Vocabulary from './english-course/Vocabulary.jsx';import Teacher from './english-course/Teacher.jsx';
import './english-course/course.css';
const tabs=[['today','Bugungi dars',BookOpen],['map','O‘quv xaritasi',Compass],['lab','Mashq laboratoriyasi',Headphones],['vocabulary','Mening lug‘atim',Bookmark],['works','Mening ishlarim',PenLine],['results','Natijalarim',BarChart3]];
export default function EnglishCourse({initialLessonId=null,user,onBack,onLogin,onMaze,onActive=()=>{}}){
 const [home,setHome]=useState(null),[tab,setTab]=useState('today'),[level,setLevel]=useState(0),[opened,setOpened]=useState(null),[check,setCheck]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[groupCode,setGroupCode]=useState(''),[groupName,setGroupName]=useState(user?.name||''),[message,setMessage]=useState('');
 const reload=async()=>{const h=await course('home');setHome(h);return h};
 useEffect(()=>{let alive=true;reload().then(async h=>{if(!alive)return;setLevel(h.profile.open_level);const target=initialLessonId||location.hash.match(/^#ingliz-darsi\/lesson\/([^/]+)$/)?.[1];if(target&&!h.lessons.find(l=>l.id===target)?.open){const meta=catalog.find(l=>l.id===target);setTab('map');setLevel(meta?.levelIndex||0);setError('Bu darsning kirish shartlari hali bajarilmagan. Avval daraja tavsiyasi va oldingi darslarni yakunlang.')}else if(target){try{let last=null;try{last=JSON.parse(sessionStorage.getItem('sq_en_last_run:'+h.uid))}catch{};setOpened(await course(last?.base===decodeURIComponent(target)?'run':'begin',last?.base===decodeURIComponent(target)?{id:last.id}:{baseId:decodeURIComponent(target)}))}catch(e){setError(e.message);history.replaceState(null,'','#ingliz-darsi')}}}).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setLoading(false));return ()=>{alive=false;onActive(false)}},[user?.id]);
 const act=async fn=>{setBusy(true);setError('');try{return await fn()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const open=async(id,assignmentId,initialStep)=>act(async()=>{const d=await course('begin',{baseId:id,...(assignmentId?{assignmentId}: {})});history.replaceState(null,'','#ingliz-darsi/lesson/'+encodeURIComponent(id));sessionStorage.setItem('sq_en_last_run:'+home.uid,JSON.stringify({base:id,id:d.run.id}));setOpened({...d,initialStep})});
 const openWork=id=>act(async()=>{const d=await course('run',{id});history.replaceState(null,'','#ingliz-darsi/lesson/'+d.run.baseId);sessionStorage.setItem('sq_en_last_run:'+home.uid,JSON.stringify({base:d.run.baseId,id:d.run.id}));setOpened(d)});
 const startCheck=kind=>act(async()=>{const c=await course('checkStart',{kind,level:home.profile.open_level});setCheck(c)});
 const startPlacedLesson=()=>act(async()=>{const h=await reload();const first=h.lessons.find(l=>l.open&&!l.mastered&&!l.testPassed)||h.lessons.find(l=>l.open);if(!first)throw Error('Avval daraja tavsiyasini yakunlang.');const d=await course('begin',{baseId:first.id});history.replaceState(null,'','#ingliz-darsi/lesson/'+first.id);sessionStorage.setItem('sq_en_last_run:'+h.uid,JSON.stringify({base:first.id,id:d.run.id}));setCheck(null);setOpened(d)});
 const leaveLesson=()=>{setOpened(null);history.replaceState(null,'','#ingliz-darsi');reload().catch(e=>setError(e.message))};
 if(loading)return <section className="en-course"><p className="en-loading" role="status">O‘quv yo‘lingiz ochilmoqda…</p></section>;
 if(!home)return <section className="en-course"><h1>Ingliz tili darsi</h1><p className="en-error" role="alert">{error}</p><div className="en-actions"><button type="button" onClick={()=>{setLoading(true);reload().catch(e=>setError(e.message)).finally(()=>setLoading(false))}}>Qayta urinib ko‘rish</button><button type="button" onClick={onLogin}>Mavjud hisobga kirish</button><button type="button" onClick={onBack}>Bosh sahifaga chiqish</button></div></section>;
 if(opened)return <main className="en-course"><Lesson key={opened.run.id} data={opened} uid={home.uid} onBack={leaveLesson} onUpdated={()=>reload().catch(()=>{})} onActive={onActive}/></main>;
 if(check)return <main className="en-course"><Assessment key={check.id} initial={check} uid={home.uid} onBack={()=>{setCheck(null);reload().catch(()=>{})}} onUpdated={()=>reload().catch(()=>{})} onActive={onActive} onStartLesson={startPlacedLesson}/></main>;
 const current=home.lessons.find(l=>l.open&&!l.mastered&&!l.testPassed)||home.lessons.find(l=>l.open&&!l.mastered)||home.lessons[0];
 const runs=home.runs,unplaced=!home.profile.placement_complete,activeCheck=home.checks.find(c=>c.status==='started');
 return <main className="en-course"><header className="en-top"><button type="button" onClick={onBack}><ArrowLeft size={17}/> Bosh sahifa</button><span className="en-badge">INGLIZ TILI DARSI</span><span>108 dars · tayyorlovdan C1 gacha</span></header><div className="en-layout"><aside className="en-sidebar"><h2>O‘quv yo‘lingiz</h2><nav aria-label="Ingliz tili bo‘limlari">{tabs.map(([id,t,Icon])=><button type="button" key={id} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}><Icon size={18}/>{t}</button>)}{home.staff&&<button type="button" aria-current={tab==='teacher'?'page':undefined} onClick={()=>setTab('teacher')}><GraduationCap size={18}/> Ustoz boshqaruvi</button>}</nav><div className="en-sidebar-note"><b>{home.profile.placement_complete?levels[home.profile.open_level]:'Daraja aniqlanmagan'}</b><p>Ichki o‘quv natijasi. Rasmiy sertifikat emas.</p><small>{user?'Natijalar hisobingizga saqlanadi.':'Natijalar shu mehmon UIDga saqlanadi. Brauzer ma’lumotini o‘chirsangiz sessiya yo‘qolishi mumkin.'}</small></div></aside><div className="en-main">{error&&<p role="alert" className="en-error">{error}</p>}{message&&<p role="status" className="en-success">{message}</p>}{!home.active&&!home.staff?<section><h1>Ingliz tili darsi hozir faol emas</h1><p>Admin faollashtirgach o‘quv yo‘lingiz davom etadi.</p></section>:<>
 {tab==='today'&&<><section className="en-hero"><div><span className="en-eyebrow">Har darsda tushuning, sinang va gapiring</span><h1>Noldan C1 gacha,<br/>o‘z yo‘lingiz bilan.</h1><p>Qisqa izoh, aniq misol va amaliy vazifa. Bugungi qadamni tugating, keyingisini dalil bilan oching.</p><button type="button" className="en-primary" disabled={busy} onClick={()=>unplaced?startCheck('placement'):activeCheck?setCheck(activeCheck):open(current.id)}>{unplaced?'Darajamni aniqlash':activeCheck?'Testni davom ettirish':'Bugungi darsni boshlash'}<ArrowRight size={18}/></button></div><svg viewBox="0 0 330 230" role="img" aria-label="Tayyorlovdan C1 gacha olti bosqichli o‘quv yo‘li"><path d="M30 190C40 80 110 170 150 80S240 25 295 40" fill="none" stroke="#c6e2e5" strokeWidth="15"/>{levels.map((l,i)=><g key={l} transform={`translate(${30+i*53},${190-i*30})`}><circle r="23" fill={i<=home.profile.open_level?'#176e77':'#d9e8ec'}/><text textAnchor="middle" dy="5" fill={i<=home.profile.open_level?'white':'#223d51'} fontSize="13" fontWeight="bold">{l==='PRE'?'0':l}</text></g>)}</svg></section><section className="en-today-card"><span className="en-eyebrow">BUGUNGI DARSINGIZ</span><h2>{unplaced?'Avval boshlang‘ich nuqtani toping':current.title}</h2><p>{unplaced?'Grammar, vocabulary, reading va listeningdan oson savollar bilan boshlaymiz.':current.objective}</p><p>{current.level} · {catalog.find(l=>l.id===current.id)?.minutes} daqiqa · {runs.filter(r=>r.status==='mastered').length} dars o‘zlashtirilgan</p>{!unplaced&&<button type="button" disabled={busy} onClick={()=>open(current.id)} className="en-primary">Davom etish</button>}{activeCheck&&<button type="button" onClick={()=>setCheck(activeCheck)}>To‘xtagan testni davom ettirish</button>}</section>{home.assignments.length>0&&<section><h2>Ustozdan vazifalar</h2>{home.assignments.map(a=><article key={a.id} className="en-assignment"><b>{catalog.find(l=>l.id===a.base_id)?.title}</b><span>{a.deadline?'Muddat: '+new Date(a.deadline).toLocaleString():'Muddat belgilanmagan'}</span><small>Kontent v{a.revision} · chiqish mezoni {a.threshold}%</small><button type="button" disabled={busy} onClick={()=>open(a.base_id,a.id)}>Biriktirilgan darsni ochish</button></article>)}</section>}<section className="en-join-group"><h2>Ustozingiz guruhiga ulaning</h2><p>Writing va speakingni ustoz guruhingiz orqali tekshiradi. Mavjud chat guruhining kodidan foydalaning.</p><label>Guruhdagi ismingiz<input value={groupName} maxLength={60} onChange={e=>setGroupName(e.target.value)}/></label><label>Guruh kodi<input value={groupCode} maxLength={10} onChange={e=>setGroupCode(e.target.value.toUpperCase())}/></label><button type="button" disabled={busy||groupCode.length!==10} onClick={()=>act(async()=>{await course('joinGroup',{code:groupCode,name:groupName});setMessage('Guruhga qo‘shildingiz. Ustoz ishlaringizni tekshira oladi.');await reload()})}>Guruhga qo‘shilish</button></section></>}
 {tab==='map'&&<section><h1>O‘quv xaritasi</h1><p>Quyi bosqichlarni takrorlashingiz mumkin. O‘zlashtirish ustoz bahosi va tekshiruvlarga bog‘liq.</p><div className="en-levels">{levels.map((l,i)=><button type="button" key={l} className={i===level?'selected':''} onClick={()=>setLevel(i)}>{i>home.profile.open_level?<LockKeyhole size={14}/>:<BookOpen size={14}/>} {l==='PRE'?'Tayyorlov':l}</button>)}</div><h2>{levelNames[level]}</h2><label>Dars qidirish<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Mavzu yoki maqsad"/></label><div className="en-lesson-map">{home.lessons.filter(l=>levels.indexOf(l.level)===level&&(`${l.title} ${l.objective}`).toLowerCase().includes(search.toLowerCase())).map(l=><article key={l.id} className={!l.open?'locked':l.mastered?'mastered':''}><span className="en-map-number">{l.mastered?<CheckCircle2 size={21}/>:l.open?l.order:<LockKeyhole size={19}/>}</span><div><h3>{l.title}</h3><p>{l.objective}</p><small>{l.mastered?'O‘zlashtirilgan':l.testPassed?'Test orqali o‘tilgan':l.open?'Boshlash mumkin':unplaced?'Avval darajangizni aniqlang':levels.indexOf(l.level)>home.profile.open_level?`${levels[Math.max(0,levels.indexOf(l.level)-1)]} bosqichi va yakuniy tekshiruv kerak.`:'Oldingi dars chiqish tekshiruvi va ustoz bahosi kerak.'}</small></div><button type="button" disabled={busy} onClick={()=>open(l.id)}>{l.open?'Ochish':'Ochilish shartini tekshirish'}</button></article>)}</div><button type="button" disabled={busy} onClick={()=>startCheck('level')}>Joriy daraja yakuniy tekshiruvi</button><p>Daraja ochilishi uchun majburiy darslar, reading, listening va rubrikada baholangan writing/speaking zarur.</p></section>}
 {tab==='lab'&&<section><h1>Mashq laboratoriyasi</h1><p>Ko‘nikmani tanlang va ochiq darsdagi tegishli qadamni takrorlang.</p><div className="en-skill-grid">{['Grammar','Vocabulary','Listening','Reading','Writing','Speaking'].map((t,i)=><button type="button" key={t} onClick={()=>open(current.id,null,[2,1,3,4,5,6][i])}>{t}<span>Bugungi darsda mashq qilish</span></button>)}</div><div className="en-maze-link"><Headphones/><div><h2>Audio Labirint</h2><p>Tinglash yoki matn savollari bilan alohida amaliy o‘yin. O‘yin darsdagi o‘zlashtirish bahosini almashtirmaydi.</p></div><button type="button" onClick={onMaze}>Labirintga kirish</button></div>{home.checks.filter(c=>c.status!=='started').map(c=><article key={c.id}><b>{c.kind==='placement'?'Daraja tavsiyasi':'Daraja yakuniy tekshiruvi'}</b><button type="button" onClick={()=>setCheck(c)}>Amaliy namuna va natijani ochish</button></article>)}</section>}
 {tab==='vocabulary'&&<Vocabulary words={home.vocabulary} onUpdated={()=>reload().catch(()=>{})}/>}
 {tab==='works'&&<section><h1>Mening ishlarim</h1><p>Yozma variantlar, speaking yozuvi va ustoz feedbacki dars versiyasi bilan saqlanadi.</p>{!runs.length&&<p>Birinchi darsingizdan ishlar shu yerda ko‘rinadi.</p>}{runs.map(r=><article key={r.id} className="en-work"><h2>{r.title}</h2><p>{r.status==='mastered'?'O‘zlashtirilgan':r.status==='submitted'?'Topshirilgan':r.status==='needs_revision'?'Qayta ishlash kerak':'Qoralama'} · v{r.revision}</p><p lang="en">{r.state.writing?.slice(0,200)||'Yozma draft hali yo‘q.'}</p>{r.feedback&&<p>{r.feedback.text}</p>}<button type="button" onClick={()=>openWork(r.id)}>Ishni ochish</button></article>)}</section>}
 {tab==='results'&&<section><h1>Natijalarim</h1><p>Darsni ko‘rish, topshirish va o‘zlashtirish turli natijalar.</p><div className="en-skill-grid">{['grammar','vocabulary','reading','listening'].map(skill=>{const h=runs.flatMap(r=>r.state.history||[]).filter(v=>v.skill===skill);return <article key={skill}><b>{skill}</b><span>{h.length?Math.round(100*h.filter(v=>v.correct).length/h.length)+'%':'Hali dalil yo‘q'}</span><small>{h.length} urinish</small></article>})}</div>{runs.filter(r=>r.feedback).map(r=><article key={r.id}><h2>{r.title}</h2><p>Writing {r.feedback.writing}% · Speaking {r.feedback.speaking}%</p><p>{r.feedback.text}</p></article>)}<h2>Qayta ishlash tavsiyalari</h2>{runs.filter(r=>Object.values(r.state.results||{}).some(v=>!v.correct)).map(r=><article key={r.id}><b>{r.title}</b>{Object.values(r.state.results).filter(v=>!v.correct).map((v,i)=><p key={i}>{v.explanation}</p>)}<button type="button" onClick={()=>open(r.baseId)}>Qayta mashq qilish</button></article>)}</section>}
 {tab==='teacher'&&home.staff&&<Teacher home={home} onUpdated={()=>reload().catch(()=>{})}/>}</>}</div></div></main>
}
