import React,{useEffect,useRef,useState} from 'react';
import {loadAssignments,recordExperiment} from './experiment-service.js';
import './experiment-tools.css';
export function ProgressiveHelp({hints,onHint}){const [level,setLevel]=useState(0);return <div className="ex-help"><button disabled={level>=hints.length} onClick={()=>{setLevel(level+1);onHint?.(level+1)}}>{level===0?'Ishora':level===1?'Batafsil yordam':'Yechimni ochish'}</button>{level>0&&<p role="status">{hints[level-1]}</p>}</div>}
function draft(key){try{const d=JSON.parse(localStorage.getItem(key));return d&&Date.now()-d.date<72*3600000?d:{}}catch{return {}}}
export default function ExperimentNotebook({subject,topic,user,probe,checks=[],snapshots=[],hintsUsed=0,missionReady=true,initialAssignment,onAssignment}){
 const key=`sq-experiment:${user?.id||'guest'}:${subject}:${topic.id}`,[old]=useState(()=>draft(key)),[prediction,setPrediction]=useState(old.prediction||''),[observation,setObservation]=useState(old.observation||''),[conclusion,setConclusion]=useState(old.conclusion||''),[assignments,setAssignments]=useState([]),[assignment,setAssignment]=useState(initialAssignment?.id||''),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[sent,setSent]=useState('');
 const latest=useRef({}),token=useRef(null),sending=useRef(false);latest.current={date:Date.now(),prediction,observation,conclusion};
 useEffect(()=>{const flush=()=>{try{localStorage.setItem(key,JSON.stringify(latest.current))}catch{}};const t=setTimeout(flush,700);return()=>clearTimeout(t)},[key,prediction,observation,conclusion]);
 useEffect(()=>{const flush=()=>{try{localStorage.setItem(key,JSON.stringify(latest.current))}catch{}};window.addEventListener('pagehide',flush);return()=>{flush();window.removeEventListener('pagehide',flush)}},[key]);
 useEffect(()=>{let live=true;loadAssignments(subject).then(rows=>live&&setAssignments(rows.filter(r=>r.topic_id===topic.id&&r.active&&r.status==='published'))).catch(()=>{});return()=>{live=false}},[subject,topic.id]);
 const data={prediction,observation,conclusion,parameters:probe?.parameters||{},checks:checks.slice(-20),snapshots:snapshots.slice(-6),hintsUsed},identity=JSON.stringify([data,assignment]),valid=prediction.trim().length>=3&&observation.trim().length>=15&&conclusion.trim().length>=15&&missionReady;
 const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({subject,topic:topic.title,...data},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`sinfquiz-${subject}-${topic.id.replace(/[^a-z0-9-]/gi,'')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const save=async()=>{if(sending.current||busy||!valid||sent===identity)return;sending.current=true;setBusy(true);if(token.current?.identity!==identity)token.current={identity,value:crypto.randomUUID()};try{await recordExperiment({student_id:user.id,student_name:user.name||'O‘quvchi',subject,topic_id:topic.id,topic_title:topic.title,assignment_id:assignment||null,data,client_token:token.current.value});setSent(identity);setStatus(assignment?'Ish ustozga yuborildi.':'Natija shaxsiy hisobingizga saqlandi.')}catch(e){setStatus(e.message)}finally{sending.current=false;setBusy(false)}};
 return <section className="ex-notebook"><small>TAJRIBA DAFTARI</small><h3>Taxmin → kuzatish → xulosa</h3><label>Avvalgi taxmin<textarea aria-label="Avvalgi taxmin" maxLength="500" rows="2" value={prediction} onChange={e=>setPrediction(e.target.value)}/></label><div className="ex-two"><label>Kuzatish<textarea aria-label="Tajriba kuzatishi" maxLength="1500" rows="3" value={observation} onChange={e=>setObservation(e.target.value)}/></label><label>Xulosa<textarea aria-label="Tajriba xulosasi" maxLength="1500" rows="3" value={conclusion} onChange={e=>setConclusion(e.target.value)}/></label></div>{assignments.length>0&&<label>Ustozning faol ishi<select aria-label="Ustozning faol ishi" value={assignment} onChange={e=>{setAssignment(e.target.value);onAssignment?.(assignments.find(a=>a.id===e.target.value)||null)}}><option value="">Mustaqil mashq · shaxsiy natija</option>{assignments.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label>}{assignment&&<p>{assignments.find(a=>a.id===assignment)?.instructions||initialAssignment?.instructions}</p>}<p className="ex-note">Taxmin kamida 3, kuzatish va xulosa 15 belgidan bo‘lsin. Qoralama shu brauzerda 72 soat saqlanadi. {!missionReady?'Avval amaliy ish maqsadini bajaring.':''}</p><div className="ex-actions"><button onClick={download}>Daftarni yuklash</button>{user?.id&&<button onClick={save} disabled={!valid||busy||sent===identity}>{busy?'Saqlanmoqda…':sent===identity?'Saqlangan':assignment?'Ustozga yuborish':'Natijani saqlash'}</button>}</div>{status&&<p role="status">{status}</p>}</section>
}
