// Public descriptions contain no student, teacher, test or chat data.
export const islandDestinations = [
 {id:'mathAtlas',slug:'matematika',label:'Matematika',title:'Matematika atlasi',x:35,y:31,mx:28,my:34,
  summary:'Son, formula, jadval va grafik orasidagi bog‘lanishni o‘zgartirib ko‘ring. Shakllarning o‘lchovi bilan hisob birga yangilanadi.',
  topics:['Son chizig‘i, kasr, foiz va nisbat','Tenglama tarozisi va funksiya grafigi','Uchburchak yuzi, Pifagor teoremasi va fazoviy jismlar'],
  question:'Asosi 8 sm, balandligi 5 sm bo‘lgan uchburchakning yuzi qancha?',
  answer:'Yuza 8 × 5 ÷ 2 = 20 sm². Bir xil asos va balandlikka ega ikki uchburchak parallelogrammni to‘ldiradi. Shu sababli ko‘paytma ikkiga bo‘linadi.',
  path:'/fanlar/matematika/',hash:'matematika'},
 {id:'chemistry',slug:'kimyo',label:'Kimyo',title:'Kimyo atlasi va virtual laboratoriya',x:56,y:24,mx:57,my:26,
  summary:'Atom tarkibini tekshiring, molekulalarni ko‘ring va virtual laboratoriyada modda, miqdor hamda sharoitni tanlab natijani kuzating.',
  topics:['Atom, davriy jadval va kimyoviy bog‘','pH, modda holati va atomlar saqlanishi','Eritma, filtrlash, kristallanish va reaksiya tezligi'],
  question:'2H₂ + O₂ → 2H₂O tenglamasida nechta vodorod va kislorod atomi bor?',
  answer:'Har ikki tomonda 4 ta vodorod va 2 ta kislorod atomi bor. Koeffitsiyent butun formulaga tegishli; pastki indeks esa bitta zarrachadagi atomlar sonini bildiradi.',
  path:'/fanlar/kimyo/',hash:'kimyo'},
 {id:'biology',slug:'biologiya',label:'Biologiya',title:'Biologiya: Tirik tabiat atlasi',x:81,y:34,mx:79,my:40,
  summary:'Bargning parchalanishidan ildiz orqali oziqa olinishigacha bo‘lgan jarayonni kuzating. O‘simlik, hayvon va odam tanasini qatlamlar orqali o‘rganing.',
  topics:['Hujayra, urug‘ unishi va fotosintez','Barg, tuproq, suv singishi va oziqa aylanishi','Nafas olish, qon aylanish va hazm qilish'],
  question:'Yerga tushgan barg darhol o‘simlik o‘zlashtiradigan oziqaga aylanadimi?',
  answer:'Yo‘q. Bakteriya, zamburug‘ va tuproq jonivorlari organik qoldiqni bosqichma-bosqich parchalaydi. Organik qoldiq, chirindi va mineral oziqa bir xil tushuncha emas. Tezlik namlik, harorat va kislorodga bog‘liq.',
  path:'/fanlar/biologiya/',hash:'biologiya'},
 {id:'englishCourse',slug:'ingliz-tili',label:'Ingliz tili',title:'Ingliz tili darslari va labirint',x:23,y:51,mx:23,my:54,
  summary:'Boshlang‘ich darajadan C1 gacha darslarni o‘rganing. Tinglash, o‘qish, yozish va gapirish mashqlarini bajaring; labirintda matn yoki audio rejimini tanlang.',
  topics:['Daraja testi va bosqichma-bosqich darslar','Grammar, Listening, Reading, Writing va Speaking','Matnli yoki audio savollar bilan inglizcha labirint'],
  question:'“I ___ to school every day.” gapida go yoki goes so‘zidan qaysi biri ishlatiladi?',
  answer:'“I go to school every day.” I olmoshi bilan hozirgi oddiy zamonda go ishlatiladi. He yoki she bilan “goes” bo‘ladi. “Every day” takrorlanadigan odatni bildiradi.',
  path:'/fanlar/ingliz-tili/',hash:'ingliz-darsi'},
 {id:'catalog',slug:'informatika',label:'Informatika',title:'Informatika va amaliy Python',x:82,y:48,mx:78,my:56,
  summary:'Python kodini brauzerda yozib ishga tushiring. Word, Excel va PowerPoint bo‘yicha nazariy bilimni amaliy topshiriqlarda tekshiring.',
  topics:['Kompyuter, klaviatura va dasturlar bilan ishlash','Python: print, o‘zgaruvchi, tur, shart va sikl','Word hujjati, Excel yacheykalari va formulalar'],
  question:'Excelda A1:A3 yacheykalarida 4, 8 va 12 bo‘lsa, o‘rtacha qiymat qanday topiladi?',
  answer:'Inglizcha funksiyada =AVERAGE(A1:A3), ruscha funksiyada =СРЗНАЧ(A1:A3) ishlatiladi. (4 + 8 + 12) ÷ 3 = 8. Sonning o‘zi, yacheyka manzili va formula alohida tushunchalardir.',
  path:'/fanlar/informatika/',hash:'informatika'},
 {id:'iq',slug:'iq-mantiq',label:'IQ va mantiq',title:'Mantiq va diqqat mashqlari',x:40,y:65,mx:43,my:68,
  summary:'Qonuniyat, fazoviy tasavvur, diqqat va dalildan xulosa chiqarishni mashq qiling. Javobdan keyin yechim sababini tekshiring.',
  topics:['Sonli va shaklli qonuniyatlar','Fazoviy munosabatlar va diqqat','Dalil, taxmin va xulosani ajratish'],
  question:'2, 6, 12, 20 ketma-ketligida keyingi son nima bo‘lishi mumkin?',
  answer:'Farqlar 4, 6, 8: shu qoida davom etsa keyingi farq 10 va keyingi son 30 bo‘ladi. Cheklangan ketma-ketlikka boshqa qoidalar ham mos kelishi mumkin; tanlangan qoidani tushuntirish muhim. Bu mashqlar klinik yoki standartlashtirilgan IQ tashxisi emas.',
  path:'/fanlar/iq-mantiq/',hash:'iq'},
];

export const islandLinks = [
 {id:'audioMaze',label:'Inglizcha labirint',detail:'Matn yoki ovoz bilan yo‘l toping.'},
 {id:'exerciseHub',label:'Mashqlar',detail:'Amaliyot va mustaqil sinovlar.'},
 {id:'practice',label:'Tayyor testlar',detail:'Python, matematika va ingliz tili.'},
 {id:'national',label:'Milliy test',detail:'Fan variantlari va javoblar tahlili.'},
 {id:'cefrManaged',label:'CEFR / Multilevel',detail:'To‘rtta til ko‘nikmasini mashq qiling.'},
 {id:'chat',label:'Ustozlar bilan chat',detail:'Guruh va dars suhbatlari.'},
];
