import React,{useEffect,useState,useRef} from 'react';
import {clamp,distance,equationSolution,lineTable,lineY,round,solidMeasures,transformPoint,triangleMeasures} from './math-atlas-math.js';

const ink='#183b59',teal='#087f83',orange='#ed9055',pale='#d3f0ed';
const fmt=value=>String(round(value));
const svgLabel=(name,action)=>({role:'button',tabIndex:0,'aria-label':name,onClick:action,onKeyDown:event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();action()}}});
function Range({label,value,onChange,min=-10,max=10,step=1,unit=''}){return <label className="ma-range"><span>{label}<b>{fmt(value)}{unit}</b></span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function useProbe(report,question,value,reason){useEffect(()=>report({question,value,reason}),[report,question,value,reason])}
function Stage({label,children}){return <div className="ma-stage"><svg viewBox="0 0 440 250" role="group" aria-label={label} preserveAspectRatio="xMidYMid meet">{children}</svg></div>}
function Axes({grid=true}){return <>{grid&&Array.from({length:9},(_,i)=><React.Fragment key={i}><path d={`M${40+i*45} 22v204 M40 ${22+i*25.5}h360`} stroke="#dce8ef" strokeWidth="1"/></React.Fragment>)}<path d="M40 125h360M220 22v204" stroke="#7c99ab" strokeWidth="1.5"/><text x="402" y="141" fill={ink} fontSize="13">x</text><text x="228" y="34" fill={ink} fontSize="13">y</text></>}
function NumberScene({topic,report}){
 const [value,setValue]=useState(topic.parameters?.value??-3),[step,setStep]=useState(topic.parameters?.step??2),[part,setPart]=useState('Nuqta');
 useProbe(report,'Boshlang‘ich son + qadam nechaga teng?',value+step,`${value} + (${step}) = ${value+step}. Son chizig‘ida har qadam bir birlik.`);
 const x=n=>220+n*18,drag=event=>{const bounds=event.currentTarget.getBoundingClientRect();setValue(clamp(Math.round(((event.clientX-bounds.left)/bounds.width*440-220)/18),-10,10))};
 return <><Stage label={`Son chizig‘i: nuqta ${value} da. ${step} qadamdan keyin ${value+step}.`}><path d="M28 126h384" stroke={ink} strokeWidth="3" markerEnd="url(#ma-arrow)"/><defs><marker id="ma-arrow" markerWidth="8" markerHeight="8" refX="8" refY="4" orient="auto"><path d="M0 0L8 4 0 8" fill={ink}/></marker></defs>{Array.from({length:21},(_,i)=>i-10).map(n=><g key={n} {...svgLabel(`${n} sonini tanlash`,()=>{setValue(n);setPart('Nuqta')})}><path d={`M${x(n)} 119v14`} stroke={n===0?orange:ink}/>{n%2===0&&<text x={x(n)} y="151" textAnchor="middle" fontSize="11" fill={ink}>{n}</text>}</g>)}<path d={`M${x(value)} 96Q${(x(value)+x(value+step))/2} 42 ${x(value+step)} 96`} fill="none" stroke={orange} strokeWidth="3"/><circle cx={x(value)} cy="126" r="11" fill={teal} {...svgLabel('Nuqtani tanlash',()=>setPart('Nuqta'))}/><circle cx={x(clamp(value+step,-10,10))} cy="126" r="7" fill={orange} {...svgLabel('Qadamdan keyingi nuqta',()=>setPart('Qadam'))}/><rect x="38" y="103" width="365" height="46" fill="transparent" style={{touchAction:'none',cursor:'crosshair'}} onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);drag(event)}} onPointerMove={event=>{if(event.buttons)drag(event)}} aria-hidden="true"/></Stage><div className="ma-controls"><Range label="Boshlang‘ich son" value={value} onChange={setValue}/><Range label="Qadam" value={step} onChange={setStep} min={-4} max={4}/></div><p className="ma-result" aria-live="polite">{part}: {value} {step>=0?'+':'−'} {Math.abs(step)} = <b>{value+step}</b>. O‘ngga yurish qiymatni oshiradi, chapga yurish kamaytiradi.</p><p className="ma-formula">|{value}| = {Math.abs(value)} — nolgacha masofa</p></>;
}
function FractionScene({topic,report}){
 const [percent,setPercent]=useState(topic.parameters?.percent??25),[whole,setWhole]=useState(topic.parameters?.whole??200),[part,setPart]=useState('Bo‘yalgan ulush');
 useProbe(report,`${whole} ning ${percent}% qismi qancha?`,whole*percent/100,`${whole} × ${percent}/100 = ${fmt(whole*percent/100)}.`);
 return <><Stage label={`${whole} ning ${percent}% qismi ${fmt(whole*percent/100)}.`}>{Array.from({length:10},(_,row)=>Array.from({length:10},(_,col)=>{const n=row*10+col;return <rect key={n} x={80+col*28} y={22+row*19} width="26" height="17" rx="3" fill={n<percent?teal:'#edf4f7'} stroke="#9fb8c5" {...svgLabel(n<percent?'Bo‘yalgan foiz katagi':'Bo‘sh foiz katagi',()=>setPart(n<percent?'Bo‘yalgan ulush':'Qolgan qism'))}/>;}))}<text x="220" y="235" fill={ink} textAnchor="middle">100 ta teng katak = butun</text></Stage><div className="ma-controls"><Range label="Foiz" value={percent} onChange={setPercent} min={0} max={100} unit="%"/><Range label="Butun miqdor" value={whole} onChange={setWhole} min={20} max={500} step={10}/></div><p className="ma-result" aria-live="polite">{part}: {percent}/100 × {whole} = <b>{fmt(whole*percent/100)}</b>. Bo‘laklar teng bo‘lgani uchun yuzdan bir ulushni sanay olamiz.</p></>;
}
function LinkedAlgebraViews({x,polynomial}){
 const fn=n=>polynomial?n*n+3*n+2:2*n+3,rows=[-2,-1,0,1,2],coords=rows.map(n=>`${220+n*32},${125-fn(n)*5}`).join(' ');
 return <section className="ma-linked" aria-label="Ifoda, qiymatlar jadvali va grafik"><div><span>Ifoda</span><b>{polynomial?'x² + 3x + 2':'y = 2x + 3'}</b><small>x = {x} → {fn(x)}</small></div><div className="ma-linked-table" role="table" aria-label="x va ifoda qiymatlari"><span>x</span>{rows.map(n=><span key={`x${n}`}>{n}</span>)}<span>f(x)</span>{rows.map(n=><span key={`y${n}`}>{fn(n)}</span>)}</div><svg viewBox="0 0 440 250" role="img" aria-label={`${polynomial?'Ko‘phad':'Chiziqli ifoda'} qiymatlari grafigi`}><path d="M40 125h360M220 20v210" stroke="#9bb3c1"/><polyline points={coords} fill="none" stroke={teal} strokeWidth="4"/>{rows.map(n=><circle key={n} cx={220+n*32} cy={125-fn(n)*5} r="5" fill={n===x?orange:teal}/>)}</svg></section>;
}
function AlgebraScene({topic,report}){
 const [x,setX]=useState(topic.parameters?.x??3),[paren,setParen]=useState(topic.parameters?.paren??false),[part,setPart]=useState('Ifoda');
 const kind=topic.scene,poly=['kophad','kopaytuvchilar'].includes(topic.id),result=topic.id==='amal-tartibi'?(paren?20:14):poly?x*x+3*x+2:2*x+3;
 useProbe(report,'Hozirgi ifoda qiymati qancha?',result,`x = ${x} qo‘yilganda ifoda ${result} ga teng.`);
 return <><Stage label={`Algebraik ifoda, x = ${x}; natija ${result}.`}><rect x="65" y="65" width="300" height="116" rx="20" fill="#edf8f7" stroke="#b1dcda"/><text x="220" y="119" textAnchor="middle" fill={ink} fontSize="27" fontWeight="700">{topic.id==='amal-tartibi'?(paren?'(2 + 3) × 4':'2 + 3 × 4'):poly?'x² + 3x + 2':'2x + 3'}</text><text x="220" y="158" textAnchor="middle" fill={teal} fontSize="22">= {result}</text><g {...svgLabel('O‘zgaruvchi x',()=>setPart('x ning qiymati'))}><circle cx="100" cy="210" r="14" fill={teal}/><text x="100" y="215" textAnchor="middle" fill="white">x</text></g><text x="135" y="215" fill={ink} fontSize="13">{poly?'x × x + 3 × x + 2':topic.id==='amal-tartibi'?'Avval ko‘paytirish':'2 × x + 3'}</text></Stage>{topic.id!=='amal-tartibi'&&<LinkedAlgebraViews x={x} polynomial={poly}/>}<div className="ma-controls">{topic.id==='amal-tartibi'?<button className="ma-toggle" aria-pressed={paren} onClick={()=>setParen(!paren)}>{paren?'Qavsni olib tashlash':'2 + 3 ni qavsga olish'}</button>:<Range label="x qiymati" value={x} onChange={setX} min={-5} max={8}/>}</div><p className="ma-result" aria-live="polite">{part}: <b>{result}</b>. {topic.id==='amal-tartibi'?'Qavs amal tartibini o‘zgartiradi.':poly?`(x + 1)(x + 2) = ${result}; ikki yozuvning qiymati teng.`:`x birga oshsa, 2x + 3 qiymati ikkiga oshadi.`}</p></>;
}
function BalanceScene({topic,report}){
 const [count,setCount]=useState(topic.parameters?.count??3),[extra,setExtra]=useState(topic.parameters?.extra??2),[total,setTotal]=useState(topic.parameters?.total??17),[take,setTake]=useState(topic.parameters?.take??0),[part,setPart]=useState('Muvozanat');
 const answer=equationSolution(count,extra,total),left=extra-take,right=total-take;
 useProbe(report,'Tarozidagi tenglikda x nechaga teng?',answer,`${count}x = ${total} − ${extra}; x = ${fmt(answer)}. Ikkala palladan teng son ayiriladi.`);
 return <><Stage label={`${count}x + ${left} = ${right}. Ikkala tomondan ${take} ayirildi. x=${fmt(answer)}.`}><path d="M63 142h312M220 142v64M160 206h120" stroke={ink} strokeWidth="5" strokeLinecap="round"/><path d="M68 142l24 33h112l24-33M212 142l24 33h112l24-33" fill="#e6f5f5" stroke={teal} strokeWidth="3"/><text x="148" y="167" textAnchor="middle" fill={ink} fontSize="21" fontWeight="700">{count}x + {left}</text><text x="292" y="167" textAnchor="middle" fill={ink} fontSize="21" fontWeight="700">{right}</text><text x="220" y="76" textAnchor="middle" fill={ink} fontSize="18">{count}x + {extra} = {total}</text><g {...svgLabel('Ikkala tomondan bir xil sonni ayirish',()=>{setTake(Math.min(extra,take+1));setPart('Ikkala palladan ayirish')})}><rect x="150" y="94" width="140" height="34" rx="10" fill={orange}/><text x="220" y="117" fill="white" textAnchor="middle">ikkala tomondan −1</text></g></Stage><div className="ma-controls"><Range label="x lar soni" value={count} onChange={setCount} min={1} max={5}/><Range label="Qo‘shimcha son" value={extra} onChange={v=>{setExtra(v);setTake(0)}} min={0} max={10}/><Range label="O‘ng palla" value={total} onChange={setTotal} min={0} max={30}/><Range label="Ikki palladan ayrildi" value={take} onChange={setTake} min={0} max={extra}/></div><p className="ma-result" aria-live="polite">{part}: {count}x + {left} = {right}. <b>x = {fmt(answer)}</b>, chunki ({total} − {extra}) / {count} = {fmt(answer)}. Ikki palladan teng miqdor ayirilsa muvozanat saqlanadi.</p></>;
}
function GraphScene({topic,report}){
 const quadratic=topic.scene==='quadratic',system=topic.id==='sistema',sequence=topic.scene==='sequence';
 const [m,setM]=useState(topic.parameters?.m??2),[b,setB]=useState(topic.parameters?.b??1),[second,setSecond]=useState(topic.parameters?.second??-1),[part,setPart]=useState('Grafik');
 const fx=x=>quadratic?m*x*x+b:sequence?b+m*x:m*x+b;
 const points=Array.from({length:101},(_,i)=>{const x=-4+i*.08;return `${220+x*45},${125-fx(x)*17}`}).join(' ');
 const intersection=system&&m!==second?(3-b)/(m-second):null;
 useProbe(report,'x = 2 bo‘lganda grafikdagi y qancha?',fx(2),`x o‘rniga 2 qo‘ying: y = ${fmt(fx(2))}. Jadvaldagi x = 2 ustunini grafikdagi nuqta bilan solishtiring.`);
 return <><Stage label={`${quadratic?'Parabola':'Chiziq'} grafigi; x=2 da y=${fmt(fx(2))}.`}><Axes/><polyline points={points} fill="none" stroke={teal} strokeWidth="3"/><circle cx={220+2*45} cy={125-fx(2)*17} r="7" fill={orange} {...svgLabel(`x = 2, y = ${fmt(fx(2))}`,()=>setPart('Jadval nuqtasi'))}/>{system&&<><path d={`M40 ${125-(second*-4+3)*17}L400 ${125-(second*4+3)*17}`} fill="none" stroke={orange} strokeWidth="3"/>{intersection!==null&&Math.abs(intersection)<=4&&<circle cx={220+intersection*45} cy={125-(m*intersection+b)*17} r="8" fill={ink} {...svgLabel('Chiziqlar kesishgan nuqta',()=>setPart('Kesishuv'))}/>}</>}</Stage><div className="ma-controls"><Range label={quadratic?'a koeffitsiyent':'m qiyalik'} value={m} onChange={setM} min={-3} max={3} step={.5}/><Range label={quadratic?'c ozod had':'b boshlang‘ich qiymat'} value={b} onChange={setB} min={-5} max={5}/>{system&&<Range label="Ikkinchi chiziq qiyaligi" value={second} onChange={setSecond} min={-3} max={3} step={.5}/>}</div><div className="ma-table" aria-label="Qiymatlar jadvali"><span>x</span>{lineTable(m,b).map(row=><span key={row.x}>{row.x}</span>)}<span>y</span>{lineTable(m,b).map(row=><span key={row.x}>{fmt(fx(row.x))}</span>)}</div><p className="ma-result" aria-live="polite">{part}: {quadratic?`y = ${m}x² + ${b}`:`y = ${m}x + ${b}`}; x = 2 da <b>y = {fmt(fx(2))}</b>. {system?intersection===null?'Chiziqlar parallel: bu holatda kesishuv yo‘q.':`Kesishuvda x = ${fmt(intersection)}.`:quadratic?'a ishorasi parabolaning ochilish yo‘nalishini belgilaydi.':`Har 1 x qadamda y ${m} ga o‘zgaradi; x = 0 da y = ${b}.`}</p></>;
}
function CoordinateScene({topic,report}){
 const [x,setX]=useState(topic.parameters?.x??2),[y,setY]=useState(topic.parameters?.y??3),[x2,setX2]=useState(topic.parameters?.x2??-2),[part,setPart]=useState('A nuqta');
 const coord=n=>220+n*38,vertical=n=>125-n*30,d=distance({x,y},{x:x2,y:0});
 useProbe(report,'A va B orasidagi masofa qancha?',d,`Gorizontal farq ${Math.abs(x-x2)}, vertikal farq ${Math.abs(y)}; Pifagor orqali ${fmt(d)}.`);
 return <><Stage label={`A (${x}; ${y}), B (${x2}; 0); masofa ${fmt(d)}.`}><Axes/><path d={`M${coord(x)} ${vertical(y)}L${coord(x2)} 125`} stroke={orange} strokeWidth="3"/><path d={`M${coord(x)} ${vertical(y)}V125H${coord(x2)}`} fill="none" stroke={teal} strokeDasharray="5 4"/><circle cx={coord(x)} cy={vertical(y)} r="9" fill={teal} {...svgLabel('A nuqta',()=>setPart('A nuqta'))}/><circle cx={coord(x2)} cy="125" r="8" fill={orange} {...svgLabel('B nuqta',()=>setPart('B nuqta'))}/><text x={coord(x)+12} y={vertical(y)-8} fill={ink}>A</text><text x={coord(x2)+12} y="117" fill={ink}>B</text></Stage><div className="ma-controls"><Range label="A: x" value={x} onChange={setX} min={-4} max={4}/><Range label="A: y" value={y} onChange={setY} min={-3} max={3}/><Range label="B: x" value={x2} onChange={setX2} min={-4} max={4}/></div><p className="ma-result" aria-live="polite">{part}: Δx = {Math.abs(x-x2)}, Δy = {Math.abs(y)}. Masofa <b>{fmt(d)}</b>, chunki {fmt((x-x2)**2)} + {y*y} = {fmt(d*d)}.</p></>;
}
function TriangleScene({topic,report}){
 const right=['togri-uchburchak','pifagor','trigonometriya'].includes(topic.id);const [cx,setCx]=useState(topic.parameters?.cx??(right?100:260)),[cy,setCy]=useState(topic.parameters?.cy??60),[base,setBase]=useState((topic.parameters?.base??11)*20),[showDouble,setShowDouble]=useState(false),[part,setPart]=useState('Uchburchak');const ref=useRef(null);
 const a={x:100,y:204},b={x:100+base,y:204},c={x:cx,y:cy},scale=20,info=triangleMeasures(a,b,c),baseUnits=info.base/scale,height=info.height/scale,area=info.area/scale**2;
 useProbe(report,'Hozirgi uchburchakning yuzi nechta kvadrat birlik?',area,`Asos ${fmt(baseUnits)} × tik balandlik ${fmt(height)} ÷ 2 = ${fmt(area)}.`);
 const drag=e=>{const bounds=ref.current?.getBoundingClientRect();if(!bounds)return;setCx(right?100:clamp((e.clientX-bounds.left)/bounds.width*440,35,405));setCy(clamp((e.clientY-bounds.top)/bounds.height*250,30,180))};
 return <><div className="ma-stage"><svg ref={ref} viewBox={showDouble?`0 0 ${Math.max(440,cx+base+25)} 250`:'0 0 440 250'} role="group" aria-label={`Uchburchak: asos ${fmt(baseUnits)}, balandlik ${fmt(height)}, yuza ${fmt(area)}, burchaklar ${info.angles.map(fmt).join(', ')} gradus.`} style={{touchAction:'none'}}><path d={`M100 204L${b.x} 204L${cx} ${cy}Z`} fill="#c7ebe7" stroke={teal} strokeWidth="3"/>{showDouble&&<path d={`M${b.x} 204L${cx} ${cy}L${cx+base} ${cy}Z`} fill="#ffd8b7" stroke={orange} strokeWidth="2" opacity=".7" />}<path d={`M${cx} ${cy}V204`} stroke={orange} strokeDasharray="5 4" strokeWidth="2"/><path d={`M${cx-12} 204v-12h12`} stroke={orange} fill="none"/><text x={210} y="228" fill={ink} textAnchor="middle">asos = {fmt(baseUnits)}</text><text x={cx+8} y={(cy+204)/2} fill={ink}>h = {fmt(height)}</text>{[[a,'A','Asosning chap uchi'],[b,'B','Asosning o‘ng uchi']].map(([p,l,name])=><g key={l} {...svgLabel(name,()=>setPart(name))}><circle cx={p.x} cy={p.y} r="9" fill={ink}/><text x={p.x-12} y={p.y-8} fill={ink}>{l}</text></g>)}<circle cx={cx} cy={cy} r="15" fill={orange} stroke="white" strokeWidth="3" style={{cursor:'grab'}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag(e)}} onPointerMove={e=>{if(e.buttons)drag(e)}} {...svgLabel('C uchini tanlash va sudrash',()=>setPart('C uchi'))}/></svg></div><div className="ma-controls"><Range label="Asos uzunligi" value={baseUnits} onChange={v=>setBase(v*20)} min={5} max={14}/><Range label="C uchi gorizontal o‘rni" value={cx} onChange={setCx} min={45} max={400}/><Range label="C uchi balandligi" value={Math.round((204-cy)/20)} onChange={v=>setCy(204-v*20)} min={2} max={8}/><button className="ma-toggle" aria-pressed={showDouble} onClick={()=>setShowDouble(!showDouble)}>{showDouble?'Ikki nusxani yashirish':'Yuzani ikki nusxada ko‘rsatish'}</button></div><p className="ma-result" aria-live="polite">{part}: S = {fmt(baseUnits)} × {fmt(height)} ÷ 2 = <b>{fmt(area)} kvadrat birlik</b>. Ikki bir xil uchburchak asos × balandlik yuzali parallelogramni to‘ldiradi.</p><p className="ma-formula">Burchaklar: {info.angles.map(v=>fmt(v)+'°').join(' + ')} = {fmt(info.angles.reduce((a,b)=>a+b,0))}°. {topic.id==='pifagor'?`Tomonlar: ${info.sides.map(fmt).join(', ')}. Katet kvadratlari yig‘indisi gipotenuza kvadratiga teng.`:''}</p></>;
}
function ShapeScene({topic,report}){
 const [a,setA]=useState(topic.parameters?.a??5),[b,setB]=useState(topic.parameters?.b??3),[n,setN]=useState(topic.parameters?.n??6),[part,setPart]=useState('Shakl');const kind=topic.scene;
 const area=kind==='circle'?Math.PI*a*a:kind==='square'?a*a:kind==='trapezoid'?(a+b)*3/2:kind==='rhombus'?a*b/2:kind==='polygon'?n*a*a/(4*Math.tan(Math.PI/n)):a*b;
 const p=kind==='circle'?2*Math.PI*a:kind==='square'?4*a:kind==='trapezoid'?a+b+2*Math.hypot((a-b)/2,3):kind==='rhombus'?2*Math.hypot(a,b):kind==='parallelogram'?2*(a+Math.hypot(b,2)):kind==='polygon'?n*a:2*(a+b);
 useProbe(report,'Ko‘rsatilgan shaklning yuzi qancha kvadrat birlik?',area,`O‘lchamlarni yuzaga qo‘yib, ${fmt(area)} kvadrat birlik hosil bo‘ladi. Yuza kvadrat birlikda o‘lchanadi.`);
 const polygon=kind==='polygon',circle=kind==='circle';
 const w=Math.min(190,a*19),height=Math.min(180,(kind==='square'?a:b)*19),polyR=Math.min(97,(a/(2*Math.sin(Math.PI/n)))*16);
 const vertices=polygon?Array.from({length:n},(_,i)=>`${220+polyR*Math.sin(i*2*Math.PI/n)},${125-polyR*Math.cos(i*2*Math.PI/n)}`).join(' '):kind==='trapezoid'?`${220-w/2},175 ${220+w/2},175 ${220+b*19/2},118 ${220-b*19/2},118`:kind==='rhombus'?`220,${125-height/2} ${220+w/2},125 220,${125+height/2} ${220-w/2},125`:kind==='parallelogram'?`${240-w/2},${125-height/2} ${240+w/2},${125-height/2} ${200+w/2},${125+height/2} ${200-w/2},${125+height/2}`:`${220-w/2},${125-height/2} ${220+w/2},${125-height/2} ${220+w/2},${125+height/2} ${220-w/2},${125+height/2}`;
 return <><Stage label={`${topic.title}. Yuza ${fmt(area)}, chegaraning uzunligi ${fmt(p)}.`}>{circle?<><circle cx="220" cy="125" r={a*11} fill={pale} stroke={teal} strokeWidth="3" {...svgLabel('Aylana va doira',()=>setPart('Doira ichki qismi'))}/><circle cx="220" cy="125" r="5" fill={ink} {...svgLabel('Markaz',()=>setPart('Markaz'))}/><path d={`M220 125h${a*11}`} stroke={orange} strokeWidth="3" {...svgLabel('Radius',()=>setPart('Radius'))}/><text x={220+a*6} y="116" fill={ink}>r</text></>:<polygon points={vertices} fill={pale} stroke={teal} strokeWidth="3" {...svgLabel(`${topic.title} yuzi va tomonlari`,()=>setPart('Shaklning yuzi'))}/>} {polygon&&<text x="220" y="132" textAnchor="middle" fill={ink}>n = {n}</text>}<text x="220" y="238" fill={ink} textAnchor="middle">{part}</text></Stage><div className="ma-controls"><Range label={circle?'Radius':kind==='rhombus'?'Birinchi diagonal':polygon?'Tomon':'Birinchi o‘lcham'} value={a} onChange={setA} min={1} max={10}/>{!circle&&!polygon&&kind!=='square'&&<Range label={kind==='rhombus'?'Ikkinchi diagonal':'Ikkinchi o‘lcham'} value={b} onChange={setB} min={1} max={10}/>} {polygon&&<Range label="Tomonlar soni" value={n} onChange={setN} min={3} max={10}/>}</div><p className="ma-result" aria-live="polite">{part}: <b>yuza {fmt(area)} kvadrat birlik</b>, perimetr {fmt(p)} birlik. {circle?`π × ${a}² = ${fmt(area)}; radius ikki marta oshsa yuza to‘rt marta oshadi.`:kind==='trapezoid'?`(${a} + ${b}) × 3 ÷ 2 = ${fmt(area)}; asoslar o‘rtachasi × tik balandlik.`:kind==='rhombus'?`${a} × ${b} ÷ 2 = ${fmt(area)}; diagonallar ko‘paytmasining yarmi.`:polygon?`Muntazam ${n} burchak markazdan ${n} ta uchburchakka ajraladi.`:kind==='square'?`${a} × ${a} = ${fmt(area)}; barcha tomonlar teng.`:`${a} × ${b} = ${fmt(area)}; asos × tik balandlik.`}</p></>;
}
function AngleScene({topic,report}){
 const [angle,setAngle]=useState(topic.parameters?.angle??70),[length,setLength]=useState(topic.parameters?.length??100),[part,setPart]=useState('Burchak');const rad=angle*Math.PI/180;
 useProbe(report,'Ikki nur orasidagi burchak necha gradus?',angle,`Nur uzunligi burchakni o‘zgartirmaydi; hozirgi burilish ${angle}°.`);
 return <><Stage label={`Ikki nur orasidagi burchak ${angle} gradus.`}><path d="M220 170h140" stroke={teal} strokeWidth="4"/><path d={`M220 170L${220+length*Math.cos(rad)} ${170-length*Math.sin(rad)}`} stroke={orange} strokeWidth="4" {...svgLabel('Ikkinchi nur',()=>setPart('Ikkinchi nur'))}/><circle cx="220" cy="170" r="8" fill={ink} {...svgLabel('Uch nuqta',()=>setPart('Burchak uchi'))}/><path d={`M250 170 A30 30 0 0 0 ${220+30*Math.cos(rad)} ${170-30*Math.sin(rad)}`} fill="none" stroke={ink} strokeWidth="2"/><text x="256" y="146" fill={ink}>{angle}°</text></Stage><div className="ma-controls"><Range label="Burchak" value={angle} onChange={setAngle} min={10} max={170} unit="°"/><Range label="Nur uzunligi" value={length} onChange={setLength} min={60} max={155}/></div><p className="ma-result" aria-live="polite">{part}: <b>{angle}°</b>. Nur uzunligi o‘zgarsa ham burchakning gradusi o‘zgarmaydi. {angle===90?'Bu to‘g‘ri burchak.':angle<90?'Bu o‘tkir burchak.':'Bu o‘tmas burchak.'}</p></>;
}
function PerpendicularScene({report}){
 const [rotation,setRotation]=useState(0),rad=rotation*Math.PI/180,cx=220,cy=125,L=85,u={x:Math.cos(rad),y:Math.sin(rad)},v={x:-Math.sin(rad),y:Math.cos(rad)};
 useProbe(report,'Perpendikulyar chiziqlar necha gradusda kesishadi?',90,'Ular 90° burchak ostida kesishadi. Burish chiziqlar orasidagi burchakni o‘zgartirmaydi.');
 const point=(a,b)=>`${cx+a*u.x+b*v.x},${cy+a*u.y+b*v.y}`;
 return <><Stage label="Ikki perpendikulyar chiziq 90 gradus ostida kesishadi."><path d={`M${point(-L,0)}L${point(L,0)}`} stroke={teal} strokeWidth="4"/><path d={`M${point(0,-L)}L${point(0,L)}`} stroke={orange} strokeWidth="4"/><path d={`M${point(0,0)}L${point(14,0)}L${point(14,14)}L${point(0,14)}`} fill="none" stroke={ink} strokeWidth="2"/><text x="250" y="110" fill={ink}>90°</text><circle cx="220" cy="125" r="5" fill={ink} {...svgLabel('Kesishish nuqtasi',()=>{})}/></Stage><div className="ma-controls"><Range label="Chiziqlar juftini birga burish" value={rotation} onChange={setRotation} min={-180} max={180} step={5} unit="°"/></div><p className="ma-result" aria-live="polite">Chiziqlar birga burildi, ammo ular orasidagi burchak <b>90°</b> bo‘lib qoldi. Shu sababli ular har qanday holatda ham perpendikulyar.</p></>;
}
function LineScene({topic,report}){
 const [length,setLength]=useState(topic.parameters?.length??6),[tilt,setTilt]=useState(topic.parameters?.tilt??0),[gap,setGap]=useState(topic.parameters?.gap??3),[part,setPart]=useState('Chiziq');const parallel=topic.id==='parallel',segment=['kesma','kesma-nur'].includes(topic.id),ray=topic.id==='nur';const half=length*19,dy=tilt*7;
 useProbe(report,parallel?'Parallel chiziqlar orasidagi tik masofa qancha?':ray?'Nurning nechta boshlang‘ich nuqtasi bor?':'A va B orasidagi kesma uzunligi nechaga teng?',parallel?gap:ray?1:length,parallel?`Ikki chiziq orasidagi tik masofa ${gap} birlik; ular kesishmaydi.`:ray?'Nur bitta boshlang‘ich nuqtaga ega va bir tomonga cheksiz davom etadi.':`Kesma uchlari orasidagi masofa ${length} birlik.`);
 return <><Stage label={`${topic.title}: ${parallel?`orasidagi masofa ${gap}`:ray?'bitta boshlanish nuqtasi':`AB uzunligi ${length}`}.`}><defs><marker id="line-arrow" markerWidth="8" markerHeight="8" refX="6" refY="4" orient="auto"><path d="M0 0L8 4 0 8Z" fill={teal}/></marker></defs><path d={`M${ray?220-half:220-half} ${130+dy}L${ray?420:220+half} ${130-dy}`} stroke={teal} strokeWidth="4" strokeLinecap="round" markerEnd={segment?undefined:'url(#line-arrow)'} markerStart={!segment&&!ray?'url(#line-arrow)':undefined}/>{parallel&&<path d={`M${220-half} ${130+dy-gap*20}L${220+half} ${130-dy-gap*20}`} stroke={orange} strokeWidth="4" markerEnd="url(#line-arrow)" markerStart="url(#line-arrow)"/>}{!parallel&&segment&&<><circle cx={220-half} cy={130+dy} r="8" fill={ink} {...svgLabel('A kesma uchi',()=>setPart('A nuqta'))}/><circle cx={220+half} cy={130-dy} r="8" fill={orange} {...svgLabel('B kesma uchi',()=>setPart('B nuqta'))}/><text x={210-half} y={110+dy} fill={ink}>A</text><text x={230+half} y={112-dy} fill={ink}>B</text></>}{ray&&<circle cx={220-half} cy={130+dy} r="8" fill={orange} {...svgLabel('Nurning boshlanish nuqtasi',()=>setPart('Boshlanish nuqtasi'))}/>}<text x="220" y="220" textAnchor="middle" fill={ink}>{part} · {parallel?`tik masofa ${gap}`:ray?'bitta boshlanish nuqtasi':segment?`AB = ${length}`:'ikki tomonga cheksiz'}</text></Stage><div className="ma-controls">{!ray&&<Range label={segment?'AB uzunligi':'Ko‘rish oynasi'} value={length} onChange={setLength} min={2} max={9}/>}<Range label="Yo‘nalish" value={tilt} onChange={setTilt} min={-3} max={3}/>{parallel&&<Range label="Tik oraliq" value={gap} onChange={setGap} min={1} max={5}/>}</div><p className="ma-result" aria-live="polite">{part}: {parallel?`ikki chiziqning qiyaligi teng, oralig‘i ${gap} birlik.`:ray?'Boshlang‘ich nuqta bitta; nur strelka tomonga cheksiz davom etadi.':segment?`Kesmaning ikki uchi belgilangan; AB = ${length} birlik.`:'Chiziqning ikkala tomonida ham oxiri yo‘q. Rasm faqat ko‘rish oynasidir.'}</p></>;
}
function TransformScene({topic,report}){
 const [dx,setDx]=useState(topic.parameters?.dx??2),[dy,setDy]=useState(topic.parameters?.dy??1),[angle,setAngle]=useState(topic.parameters?.angle??0),[scale,setScale]=useState(topic.parameters?.scale??1),[reflect,setReflect]=useState(topic.parameters?.reflect??false),[part,setPart]=useState('Mos nuqtalar');
 const original=[{x:-2,y:-1},{x:0,y:-1},{x:-1.5,y:1}],opts={dx,dy,angle,scale,reflect},moved=original.map(p=>transformPoint(p,opts)),px=p=>`${220+p.x*34},${125-p.y*34}`;
 const area0=1.75,area=area0*scale*scale;
 useProbe(report,'Yangi yuzaning eski yuzaga nisbati nechaga teng?',scale*scale,`Masshtab ${scale} bo‘lsa, ikki o‘lcham ham o‘zgaradi: ${scale}² = ${fmt(scale*scale)}.`);
 return <><Stage label={`Shakl ko‘chirildi (${dx}; ${dy}), ${angle} gradus burildi, ${scale} marta masshtablandi; yuza nisbati ${fmt(scale*scale)}.`}><Axes/><polygon points={original.map(px).join(' ')} fill="#dceaf2" stroke={ink} strokeWidth="2"/><polygon points={moved.map(px).join(' ')} fill={pale} stroke={teal} strokeWidth="3" {...svgLabel('O‘zgargan uchburchak',()=>setPart('Yangi shakl'))}/>{original.map((p,i)=><g key={i} {...svgLabel(`Mos nuqta ${i+1}`,()=>setPart(`Mos nuqta ${i+1}`))}><circle cx={220+moved[i].x*34} cy={125-moved[i].y*34} r="6" fill={orange}/><path d={`M${px(p)}L${px(moved[i])}`} stroke={orange} strokeDasharray="4 3"/></g>)}</Stage><div className="ma-controls"><Range label="Gorizontal ko‘chirish" value={dx} onChange={setDx} min={-3} max={3}/><Range label="Vertikal ko‘chirish" value={dy} onChange={setDy} min={-2} max={2}/><Range label="Burish" value={angle} onChange={setAngle} min={-180} max={180} step={15} unit="°"/><Range label="Masshtab" value={scale} onChange={setScale} min={.5} max={2} step={.25}/><button className="ma-toggle" aria-pressed={reflect} onClick={()=>setReflect(!reflect)}>{reflect?'Akslantirishni o‘chirish':'Y o‘qiga nisbatan akslantirish'}</button></div><p className="ma-result" aria-live="polite">{part}: mos birinchi nuqta ({fmt(moved[0].x)}; {fmt(moved[0].y)}). Dastlabki yuza {area0}, yangi yuza <b>{fmt(area)}</b>. Faqat masshtab yuzani o‘zgartiradi: k² = {fmt(scale*scale)}.</p></>;
}
function SolidScene({topic,report}){
 const kind=topic.scene;const [a,setA]=useState(topic.parameters?.a??3),[b,setB]=useState(topic.parameters?.b??2),[h,setH]=useState(topic.parameters?.h??3),[r,setR]=useState(topic.parameters?.r??2),[open,setOpen]=useState(topic.parameters?.open??0),[yaw,setYaw]=useState(topic.parameters?.yaw??30),[section,setSection]=useState(topic.parameters?.section??false),[part,setPart]=useState('Butun jism');const measure=solidMeasures(kind,{a,b,c:h,r,h});
 useProbe(report,'Jismning hajmi qancha kub birlik?',measure.volume,`${measure.formula}; shu o‘lchamlarda V = ${fmt(measure.volume)} kub birlik.`);
 const cubeLike=['cube','cuboid'].includes(kind),radiusPx=Math.min(72,r*12),heightPx=Math.min(120,h*15),depths=kind==='cube'?[a,a,a]:[a,b,h];
 const verts=cubeLike?[-1,1].flatMap(x=>[-1,1].flatMap(y=>[-1,1].map(z=>({x,y,z})))):[];
 const rad=yaw*Math.PI/180,project=p=>({x:150+(p.x*depths[0]*15*Math.cos(rad)+p.z*depths[2]*15*Math.sin(rad)),y:128+(p.x*depths[0]*7*Math.sin(rad)-p.z*depths[2]*7*Math.cos(rad)-p.y*depths[1]*18)});
 const faces=cubeLike?[{name:'Old yoq',idx:[1,3,7,5],fill:'#80cfca'},{name:'Yon yoq',idx:[4,5,7,6],fill:'#56aaa9'},{name:'Yuqori yoq',idx:[2,3,7,6],fill:'#b1e7db'}]:[];
 const netFaces=[[-1,0],[0,0],[1,0],[2,0],[0,-1],[0,1]];
 return <><Stage label={`${topic.title}: hajmi ${fmt(measure.volume)} kub birlik, sirt yuzi ${fmt(measure.surface)} kvadrat birlik. ${measure.net}.`}>
 {cubeLike?faces.map(face=><polygon key={face.name} points={face.idx.map(i=>{const p=project(verts[i]);return `${p.x},${p.y}`}).join(' ')} fill={face.fill} stroke={ink} strokeWidth="2" {...svgLabel(face.name,()=>setPart(face.name))}/>):<><ellipse cx="145" cy={185} rx={radiusPx} ry={radiusPx*.3} fill="#7ac9c3" stroke={ink} strokeWidth="2"/>{kind==='sphere'?<circle cx="145" cy="128" r={radiusPx} fill={pale} stroke={teal} strokeWidth="3" {...svgLabel('Shar sirti',()=>setPart('Shar sirti'))}/>:kind==='cylinder'?<><path d={`M${145-radiusPx} ${128-heightPx/2}v${heightPx}M${145+radiusPx} ${128-heightPx/2}v${heightPx}`} stroke={ink} strokeWidth="2"/><ellipse cx="145" cy={128-heightPx/2} rx={radiusPx} ry={radiusPx*.3} fill={pale} stroke={teal} strokeWidth="3" {...svgLabel('Yuqori asos',()=>setPart('Doira asosi'))}/></>:kind==='cone'||kind==='pyramid'?<path d={`M145 ${128-heightPx/2}L${145-radiusPx} ${128+heightPx/2}  ${145+radiusPx} ${128+heightPx/2}Z`} fill={pale} stroke={teal} strokeWidth="3" {...svgLabel('Yon yoq',()=>setPart('Yon sirt'))}/>:<><polygon points="75,75 160,50 230,95 145,120" fill={pale} stroke={teal} strokeWidth="2"/><path d="M75 75v110l70 25V120M230 95v90l-85 25" fill="#8dd4cb" stroke={ink} strokeWidth="2" {...svgLabel('Prizma yon yog‘i',()=>setPart('Yon yoq'))}/></>}</>}
 {section&&<><path d="M65 128h160" stroke={orange} strokeWidth="3" strokeDasharray="5 4"/><text x="145" y="119" textAnchor="middle" fill={ink} fontSize="12">ko‘ndalang kesim</text></>}
 <g opacity={open/100} transform="translate(251 75)">{kind==='sphere'?<><circle cx="72" cy="52" r="47" fill="#e5f5f1" stroke={teal}/><text x="72" y="108" textAnchor="middle" fill={ink} fontSize="11">Tekis yoyilma yo‘q</text></>:cubeLike?netFaces.map(([x,y],i)=><rect key={i} x={x*38+37} y={y*38+37} width="37" height="37" fill={i===0?'#87d3c9':'#e5f5f1'} stroke={teal} {...svgLabel(`${i+1}-yoyilma yog‘i`,()=>setPart(`${i+1}-yoyilma yog‘i`))}/>):kind==='cylinder'?<><rect x="20" y="18" width="100" height="72" fill={pale} stroke={teal}/><circle cx="68" cy="4" r="14" fill={pale} stroke={teal}/><circle cx="68" cy="106" r="14" fill={pale} stroke={teal}/></>:kind==='cone'?<><path d="M65 78L8 21A80 80 0 0 1 122 21Z" fill={pale} stroke={teal}/><circle cx="65" cy="102" r="16" fill={pale} stroke={teal}/></>:<><rect x="43" y="43" width="52" height="52" fill={pale} stroke={teal}/>{[[0,-1],[1,0],[0,1],[-1,0]].map(([x,y],i)=><path key={i} d={`M${x===1?95:x===-1?43:43} ${y===1?95:y===-1?43:43}l${x*45-y*26} ${y*45-x*26} 52 0Z`} fill="#ddf1ed" stroke={teal}/>)}</>}</g><text x="320" y="226" fill={ink} textAnchor="middle" fontSize="12">{open?'Yoyilma / kesim':'Yoyilmani oching'}</text></Stage>
 <div className="ma-controls">{cubeLike?<><Range label="a uzunlik" value={a} onChange={setA} min={1} max={7}/>{kind==='cuboid'&&<Range label="b eni" value={b} onChange={setB} min={1} max={7}/>}</>:<Range label="Radius yoki asos" value={r} onChange={setR} min={1} max={6}/>} {kind!=='cube'&&kind!=='sphere'&&<Range label="Balandlik" value={h} onChange={setH} min={1} max={7}/>}{cubeLike&&<Range label="Ko‘rish burchagi" value={yaw} onChange={setYaw} min={-55} max={55} step={5} unit="°"/>}<Range label="Yoyilmani ochish" value={open} onChange={setOpen} min={0} max={100} step={10} unit="%"/><button className="ma-toggle" aria-pressed={section} onClick={()=>setSection(!section)}>{section?'Kesimni yashirish':'Ko‘ndalang kesimni ko‘rsatish'}</button></div><p className="ma-result" aria-live="polite">{part}: <b>V = {fmt(measure.volume)} kub birlik</b>, S = {fmt(measure.surface)} kvadrat birlik. {measure.formula}. Yoyilma: {measure.net}.</p><p className="ma-formula">{measure.faces} tekis yoq · {measure.curvedSurfaces||0} egri sirt · {measure.edges} qirra · {measure.vertices} uch.</p></>;
}
function PowerScene({topic,report}){
 const [base,setBase]=useState(topic.parameters?.base??2),[exponent,setExponent]=useState(topic.parameters?.exponent??3),[part,setPart]=useState('Daraja');const value=base**exponent,root=topic.id==='ildizlar';
 useProbe(report,root?'Ko‘rsatilgan sonning kvadrat ildizi qancha?':topic.id==='logarifm'?'Ko‘rsatilgan logarifmning qiymati qancha?':'Darajaning qiymati qancha?',root?Math.sqrt(value):topic.id==='logarifm'?exponent:value,root?`√${value} = ${fmt(Math.sqrt(value))}.`:topic.id==='logarifm'?`${base} ning ${exponent}-darajasi ${value}.`:`${base} sonini ${exponent} marta ko‘paytiramiz.`);
 return <><Stage label={`${base} ning ${exponent}-darajasi ${value}.`}><text x="220" y="73" textAnchor="middle" fill={ink} fontSize="26">{root?`√${value} = ${fmt(Math.sqrt(value))}`:`${base}^${exponent} = ${value}`}</text>{Array.from({length:Math.min(exponent,7)},(_,i)=><g key={i} {...svgLabel(`${i+1}-ko‘paytuvchi`,()=>setPart(`${i+1}-ko‘paytuvchi`))}><rect x={62+i*46} y="113" width="38" height="42" rx="8" fill={teal}/><text x={81+i*46} y="140" fill="white" textAnchor="middle">{base}</text></g>)}<text x="220" y="205" fill={ink} textAnchor="middle">{Array.from({length:exponent},()=>base).join(' × ')}</text></Stage><div className="ma-controls"><Range label="Asos" value={base} onChange={setBase} min={2} max={5}/><Range label="Daraja" value={exponent} onChange={setExponent} min={1} max={5}/></div><p className="ma-result" aria-live="polite">{part}: <b>{value}</b>. {topic.id==='logarifm'?`log_${base}(${value}) = ${exponent}: ${base} ni ${exponent}-darajaga ko‘tarsak ${value} chiqadi.`:root?`√${value} = ${fmt(Math.sqrt(value))}; ildiz belgisi nomanfiy qiymatni beradi.`:`Asosni bir marta ko‘proq ko‘paytirsangiz natija ${base} marta oshadi.`}</p></>;
}
function SequenceScene({report}){const [first,setFirst]=useState(topic.parameters?.first??2),[diff,setDiff]=useState(topic.parameters?.diff??3);useProbe(report,'Beshinchi had nechaga teng?',first+4*diff,`${first} + 4 × ${diff} = ${first+4*diff}. Birinchi hadga to‘rtta qadam qo‘shiladi.`);return <><Stage label={`Ketma-ketlik: ${Array.from({length:5},(_,i)=>first+i*diff).join(', ')}.`}>{Array.from({length:5},(_,i)=><g key={i}><circle cx={60+i*80} cy={130} r="26" fill={i===4?orange:teal}/><text x={60+i*80} y="137" textAnchor="middle" fill="white" fontSize="18">{first+i*diff}</text>{i<4&&<text x={96+i*80} y="125" textAnchor="middle" fill={ink}>+{diff}</text>}</g>)}</Stage><div className="ma-controls"><Range label="Birinchi had" value={first} onChange={setFirst} min={-5} max={10}/><Range label="Qadam" value={diff} onChange={setDiff} min={-3} max={8}/></div><p className="ma-result" aria-live="polite">Beshinchi had = {first} + 4 × {diff} = <b>{first+4*diff}</b>. Har keyingi hadga bir xil {diff} qo‘shiladi.</p></>}
export function AtlasScene({topic}){
 const [answer,setAnswer]=useState(''),[feedback,setFeedback]=useState(''),[probe,setProbe]=useState(null);
 const key=topic.id,scene=topic.scene;
 const Component=topic.id==='perpendikulyar'?PerpendicularScene:scene==='number'?NumberScene:scene==='fraction'?FractionScene:scene==='balance'?BalanceScene:scene==='linear'||scene==='quadratic'?GraphScene:scene==='coordinate'?CoordinateScene:scene==='triangle'?TriangleScene:scene==='transform'?TransformScene:scene==='power'?PowerScene:scene==='sequence'?SequenceScene:scene==='expression'?AlgebraScene:scene==='angle'?AngleScene:scene==='line'?LineScene:['cube','cuboid','prism','pyramid','cylinder','cone','sphere'].includes(scene)?SolidScene:ShapeScene;
 return <div key={key} className="ma-experience"><div className="ma-visual-head"><span>KO‘RIB TUSHUN</span><strong>{topic.title}</strong></div><Component topic={topic} report={setProbe}/><section className="ma-try"><h3>O‘zing sinab ko‘r</h3><p>{topic.challenge}</p><form onSubmit={event=>{event.preventDefault();if(!probe||answer.trim()==='')return;const guess=Number(answer.replace(',','.'));setFeedback(Number.isFinite(guess)&&Math.abs(guess-probe.value)<=Math.max(.02,Math.abs(probe.value)*.005)?`To‘g‘ri. ${probe.reason}`:`Yana bir bor ko‘rib chiqing. ${probe.reason} ${topic.misconception}`)}}><label htmlFor="ma-probe">{probe?.question||'Qiymatni toping'}</label><div className="ma-probe-row"><input id="ma-probe" type="text" inputMode="decimal" value={answer} onChange={event=>{setAnswer(event.target.value);setFeedback('')}} placeholder="Sonni kiriting" required/><button type="submit">Tekshirish</button></div></form>{feedback&&<p role="status" className="ma-feedback">{feedback}</p>}</section></div>;
}
