import React,{useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,ChevronRight,Compass,Filter,Layers,Pencil,Plus,Search,Trash2,X} from 'lucide-react';
import {atlasGroups,atlasTopicById,atlasTopics} from './math-atlas-content.js';
import {AtlasScene} from './MathAtlasScenes.jsx';
import {deleteAtlasConcept,loadAtlasConcepts,reviewAtlasConcept,saveAtlasConcept} from './math-atlas-service.js';
import {atlasDefaultParams,atlasSceneParams} from './math-atlas-scene-config.js';
import './math-atlas.css';

const sceneNames={number:'Son chizig‘i',fraction:'Yuz katak',balance:'Tenglama tarozisi',linear:'Koordinata grafigi',quadratic:'Parabola',coordinate:'Koordinatalar',triangle:'Uchburchak',transform:'Harakat',power:'Daraja',sequence:'Ketma-ketlik',expression:'Ifoda',angle:'Burchak',line:'Chiziq',rectangle:'To‘rtburchak',square:'Kvadrat',parallelogram:'Parallelogram',trapezoid:'Trapetsiya',rhombus:'Romb',polygon:'Ko‘pburchak',circle:'Doira',cube:'Kub',cuboid:'Parallelepiped',prism:'Prizma',pyramid:'Piramida',cylinder:'Silindr',cone:'Konus',sphere:'Shar'};
const defaultForm={title:'',domain:'Algebra',grade:6,scene:'number',parameters:atlasDefaultParams('number'),definition:'',reason:'',life:'',challenge:'',misconception:'',prerequisites:[],group:'O‘qituvchi mavzulari'};
const titleFor=id=>atlasTopicById[id]?.title||id;
const validText=(value,min=12,max=600)=>typeof value==='string'&&value.trim().length>=min&&value.length<=max;
function validate(form){if(!validText(form.title,4,100))return 'Mavzu nomi 4–100 belgi bo‘lsin.';for(const [key,label,max] of [['definition','Ta’rif',500],['reason','Sabab izohi',600],['life','Hayotiy misol',500],['misconception','Xato tushuncha izohi',500],['challenge','Tajriba vazifasi',500]])if(!validText(form[key],12,max))return `${label} kamida 12, ko‘pi bilan ${max} belgi bo‘lsin.`;for(const [key,spec] of Object.entries(atlasSceneParams[form.scene]||{})){const value=form.parameters?.[key]??spec.value;if(typeof value!=='number'||!Number.isFinite(value)||value<spec.min||value>spec.max)return `${spec.label}: qiymat ${spec.min} dan ${spec.max} gacha bo‘lsin.`}return ''}

export default function MathAtlas({user,onBack}){
 const teacher=['teacher','admin'].includes(user?.role),admin=user?.role==='admin';
 const [rows,setRows]=useState([]),[loadError,setLoadError]=useState(''),[selected,setSelected]=useState(null),[domain,setDomain]=useState('Barchasi'),[grade,setGrade]=useState('all'),[query,setQuery]=useState(''),[edit,setEdit]=useState(null),[form,setForm]=useState(defaultForm),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const refresh=async()=>{try{setRows(await loadAtlasConcepts());setLoadError('')}catch(e){setLoadError(e.message)}};
 useEffect(()=>{let active=true;loadAtlasConcepts().then(data=>active&&setRows(data)).catch(e=>active&&setLoadError(e.message));return()=>{active=false}},[]);
 const custom=useMemo(()=>rows.filter(row=>row.status==='published'||(teacher&&(row.owner_id===user.id||admin))).map(row=>({id:`custom:${row.id}`,...row.data,ownerId:row.owner_id,status:row.status,dbId:row.id,custom:true,group:row.data.group||'O‘qituvchi mavzulari',prerequisites:row.data.prerequisites||[]})),[rows,teacher,admin,user?.id]);
 const all=[...atlasTopics,...custom];const current=all.find(topic=>topic.id===selected);
 const filtered=all.filter(topic=>(domain==='Barchasi'||topic.domain===domain)&&(grade==='all'||topic.grade<=Number(grade))&&(!query||`${topic.title} ${topic.definition} ${topic.group}`.toLocaleLowerCase('uz').includes(query.toLocaleLowerCase('uz'))));
 const grouped=[...new Set([...atlasGroups,...filtered.map(item=>item.group)])].map(name=>({name,items:filtered.filter(item=>item.group===name)})).filter(group=>group.items.length);
 const open=id=>{setSelected(id);setEdit(null);setMessage('');window.scrollTo?.({top:0,behavior:'instant'})};
 const newEditor=source=>{const scene=source?.scene||defaultForm.scene;setEdit(source?.custom?source.dbId:'new');setForm(source?{title:source.custom?source.title:`${source.title} — mening sahnam`,domain:source.domain,grade:source.grade,scene,parameters:source.parameters||atlasDefaultParams(scene),definition:source.definition,reason:source.reason,life:source.life,challenge:source.challenge,misconception:source.misconception,prerequisites:source.prerequisites||[],group:source.group}:defaultForm);setError('');setMessage('');window.scrollTo?.({top:0,behavior:'instant'})};
 const save=async status=>{const problem=validate(form);if(problem){setError(problem);return}setBusy(true);setError('');try{const own=rows.find(row=>row.id===edit&&row.owner_id===user.id);const row=await saveAtlasConcept({id:own?.id,ownerId:user.id,status:admin&&status==='published'?'published':status,data:{...form,title:form.title.trim(),definition:form.definition.trim(),reason:form.reason.trim(),life:form.life.trim(),challenge:form.challenge.trim(),misconception:form.misconception.trim(),grade:Number(form.grade)}});await refresh();setEdit(null);setSelected(`custom:${row.id}`);setMessage(status==='pending'?'Mavzu tasdiqlash uchun adminga yuborildi.':'Mavzu saqlandi.')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const remove=async topic=>{if(!window.confirm('Bu mavzu o‘chirilsinmi?'))return;setBusy(true);try{await deleteAtlasConcept(topic.dbId,user.id);await refresh();setSelected(null);setMessage('Mavzu o‘chirildi.')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const review=async(topic,status)=>{setBusy(true);try{await reviewAtlasConcept(topic.dbId,status);await refresh();setMessage(status==='published'?'Mavzu ommaga chiqarildi.':'Mavzu qoralamaga qaytarildi.')}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <main className="math-atlas">
  <header className="ma-header"><button className="ma-back" onClick={edit?()=>setEdit(null):current?()=>setSelected(null):onBack} aria-label="Ortga"><ArrowLeft size={20}/></button><div><small>SINFQUIZ · MATEMATIKA</small><h1>{edit?'Sahna matnini tayyorlash':current?current.title:'Matematika atlasi'}</h1><p>{edit?'Parametr shablonini tanlang va har bir qatlamga o‘z izohingizni yozing.':current?`${current.domain} · ${current.grade}-sinfdan boshlab · ${current.group}`:'Tushunchani tanlang, parametrlarni o‘zgartiring va natijani o‘z ko‘zingiz bilan ko‘ring.'}</p></div><div className="ma-header-mark" aria-hidden="true"><Compass size={30}/></div></header>
  {message&&<p className="ma-notice" role="status">{message}</p>}{error&&<p className="ma-error" role="alert">{error}</p>}{loadError&&teacher&&<p className="ma-notice" role="status">Tayyor 55 sahna ishlaydi. O‘qituvchi mavzulari uchun {loadError}</p>}
  {edit?<section className="ma-editor" aria-label="Matematika mavzusi tahriri"><div className="ma-editor-grid"><label>Mavzu nomi<input maxLength={100} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Yo‘nalish<select value={form.domain} onChange={e=>setForm({...form,domain:e.target.value})}><option>Algebra</option><option>Geometriya</option></select></label><label>Tavsiya etilgan sinf<select value={form.grade} onChange={e=>setForm({...form,grade:Number(e.target.value)})}>{[5,6,7,8,9,10,11].map(g=><option key={g}>{g}</option>)}</select></label><label>Interaktiv sahna<select value={form.scene} onChange={e=>{const scene=e.target.value;setForm({...form,scene,parameters:atlasDefaultParams(scene)})}}>{Object.entries(sceneNames).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label></div><fieldset className="ma-param-editor"><legend>Sahna boshlang‘ich parametrlari</legend>{Object.entries(atlasSceneParams[form.scene]||{}).map(([key,spec])=><label key={key}>{spec.label}<input type="number" min={spec.min} max={spec.max} step="any" value={form.parameters?.[key]??spec.value} onChange={e=>setForm({...form,parameters:{...form.parameters,[key]:Number(e.target.value)}})}/></label>)}</fieldset><fieldset className="ma-prereq-editor"><legend>Oldingi tushunchalar</legend><select multiple aria-label="Tayanch tushunchalarni tanlang" value={form.prerequisites||[]} onChange={e=>setForm({...form,prerequisites:[...e.target.selectedOptions].map(option=>option.value)})}>{atlasTopics.map(topic=><option key={topic.id} value={topic.id}>{topic.title}</option>)}</select><small>Bir nechtesini tanlash uchun Ctrl yoki Command tugmasini bosib turing.</small></fieldset>{[['definition','Bu nima?','Bitta yoki ikkita jumlada aniq ta’rif.'],['reason','Nima o‘zgardi va nega?','Parametr va natija orasidagi sabab.'],['life','Hayotda qayerda uchraydi?','Aniq kundalik vaziyat.'],['challenge','O‘zing sinab ko‘r','O‘quvchi qaysi parametrni o‘zgartirsin?'],['misconception','Ko‘p uchraydigan xato','Noto‘g‘ri fikrni aniqlang va tuzating.']].map(([name,label,hint])=><label className="ma-editor-field" key={name}>{label}<small>{hint}</small><textarea rows={2} maxLength={name==='reason'?600:500} value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})}/></label>)}<div className="ma-editor-actions"><button className="ma-secondary" onClick={()=>setEdit(null)}>Bekor qilish</button><button disabled={busy} onClick={()=>save('draft')}>Qoralama saqlash</button><button disabled={busy} onClick={()=>save(admin?'published':'pending')}>{admin?'Ommaga chiqarish':'Adminga yuborish'} <ArrowRight size={16}/></button></div><p className="ma-editor-note">O‘qituvchining qoralamasi faqat o‘ziga ko‘rinadi. Ommaviy mavzu administrator tasdig‘idan so‘ng o‘quvchilarga chiqadi.</p></section>:current?<> 
   <nav className="ma-breadcrumb" aria-label="Matematika xaritasi"><button onClick={()=>setSelected(null)}>Xarita</button><ChevronRight size={15}/><span>{current.group}</span><ChevronRight size={15}/><b>{current.title}</b></nav>
   <div className="ma-topic-layout"><article className="ma-topic"><div className="ma-topic-intro"><span>{current.domain.toUpperCase()} · {current.grade}-SINF</span><h2>Bu nima?</h2><p>{current.definition}</p></div><AtlasScene topic={current}/><div className="ma-explain"><section><h3>Nima o‘zgardi va nega?</h3><p>{current.reason}</p></section><section><h3>Hayotda qayerda uchraydi?</h3><p>{current.life}</p></section><section><h3>Adashmaslik uchun</h3><p>{current.misconception}</p></section></div>{teacher&&<div className="ma-author-actions"><button onClick={()=>newEditor(current)}><Pencil size={16}/>{current.custom&&current.ownerId===user.id?'Tahrirlash':'Nusxa olib moslash'}</button>{current.custom&&current.ownerId===user.id&&<button onClick={()=>remove(current)} disabled={busy}><Trash2 size={16}/> O‘chirish</button>}{admin&&current.custom&&current.status==='pending'&&<button disabled={busy} onClick={()=>review(current,'published')}>Tasdiqlash</button>}</div>}</article>
   <aside className="ma-path"><h3>Tushunchalar yo‘li</h3><small>OLDINGI TUSHUNCHA</small>{current.prerequisites.length?current.prerequisites.map(id=><button key={id} onClick={()=>open(id)}>{titleFor(id)} <ChevronRight size={15}/></button>):<p>Bu mavzu boshlang‘ich tayanchdir.</p>}<small>HOZIR</small><strong>{current.title}</strong><small>KEYINGI TUSHUNCHA</small>{all.filter(topic=>topic.prerequisites?.includes(current.id)).slice(0,3).map(topic=><button key={topic.id} onClick={()=>open(topic.id)}>{topic.title} <ChevronRight size={15}/></button>)}{!all.some(topic=>topic.prerequisites?.includes(current.id))&&<p>Xaritadagi boshqa yo‘nalishga o‘ting.</p>}</aside></div>
  </>:<>
   <div className="ma-map-intro"><div><Layers size={22}/><b>{atlasTopics.length} tayyor sahna</b><span>5–11-sinflar uchun erkin yo‘l</span></div><div><BookOpen size={22}/><b>Ko‘rish · o‘zgartirish · tushunish</b><span>Har bir tushunchada amaliy tajriba</span></div>{teacher&&<button onClick={()=>newEditor()}><Plus size={18}/> Yangi sahna yaratish</button>}</div>
   <div className="ma-filters"><label><Search size={18}/><span className="ma-sr-only">Mavzu qidirish</span><input placeholder="Mavzu yoki atamani qidiring" value={query} onChange={e=>setQuery(e.target.value)}/></label><label><Filter size={17}/><span className="ma-sr-only">Tayyorgarlik darajasi</span><select value={grade} onChange={e=>setGrade(e.target.value)}><option value="all">Barcha bosqichlar</option>{[5,6,7,8,9,10,11].map(g=><option value={g} key={g}>{g}-sinfgacha</option>)}</select></label><div className="ma-domains" aria-label="Yo‘nalishlar">{['Barchasi','Algebra','Geometriya'].map(item=><button key={item} aria-pressed={domain===item} className={domain===item?'active':''} onClick={()=>setDomain(item)}>{item}</button>)}</div></div>
   <p className="ma-filter-count" role="status">{filtered.length} ta tushuncha · sinf tavsiya, cheklov emas</p>{grouped.map(group=><section className="ma-group" key={group.name}><div className="ma-group-head"><div><small>MATEMATIKA XARITASI</small><h2>{group.name}</h2></div><span>{group.items.length} mavzu</span></div><div className="ma-cards">{group.items.map((topic,i)=><button className="ma-card" key={topic.id} onClick={()=>open(topic.id)}><span className="ma-card-num">{String(i+1).padStart(2,'0')}</span><span className="ma-card-text"><small>{topic.domain} · {topic.grade}-sinfdan{topic.custom?` · ${topic.status==='published'?'Ommaviy':topic.status==='pending'?'Tasdiq kutilmoqda':'Qoralama'}`:''}</small><strong>{topic.title}</strong><span>{topic.definition}</span><em>Tayanch: {topic.prerequisites.length?topic.prerequisites.map(titleFor).join(', '):'boshlang‘ich tushuncha'}</em></span><ChevronRight size={18}/></button>)}</div></section>)}{filtered.length===0&&<div className="ma-empty">Mos mavzu topilmadi. Qidiruv yoki bosqich filtrini o‘zgartiring.</div>}
  </>}
 </main>;
}
