import MathSolidFallback,{sectionData} from './MathSolidFallback.jsx';
import MathRelationViews from './MathRelationViews.jsx';
import ExperimentNotebook,{ProgressiveHelp} from './ExperimentNotebook.jsx';
import {FractionLab,BalanceLab,FunctionStudio,TriangleLab,PythagorasLab,InequalityLab,RatioLab,DataLab} from './MathExperienceScenes.jsx';
import {atlasSceneParams} from './math-atlas-scene-config.js';
import LearningVisual from './LearningVisual.jsx';
import React,{useEffect,useState,useRef} from 'react';
import {clamp,distance,equationSolution,lineTable,lineY,round,solidMeasures,transformPoint,triangleMeasures} from './math-atlas-math.js';

const ink='#183b59',teal='#087f83',orange='#ed9055',pale='#d3f0ed';
const fmt=value=>String(round(value));
const svgLabel=(name,action)=>({role:'button',tabIndex:0,'aria-label':name,onClick:action,onKeyDown:event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();action()}}});
function Range({label,value,onChange,min=-10,max=10,step=1,unit=''}){return <label className="ma-range"><span>{label}<b>{fmt(value)}{unit}</b></span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function useProbe(report,question,value,reason){useEffect(()=>report({question,value,reason}),[report,question,value,reason])}
function Stage({label,children}){return <div className="ma-stage"><svg viewBox="0 0 440 250" role="group" aria-label={label} preserveAspectRatio="xMidYMid meet">{children}</svg></div>}
function Axes({unit=30}){return <>{Array.from({length:13},(_,i)=>i-6).map(i=><g key={i}><path d={`M${220+i*unit} 20v210M35 ${125+i*unit}h370`} stroke="#dce8ef"/><text x={220+i*unit} y="141" fontSize="9" textAnchor="middle">{i||''}</text><text x="214" y={125-i*unit} fontSize="9" textAnchor="end">{i||''}</text></g>)}<path d="M35 125h370M220 20v210" stroke="#7c99ab"/><text x="406" y="141">x</text><text x="228" y="25">y</text></>}

function NumberScene({topic,report}){
 const [value,setValue]=useState(topic.parameters?.value??-3),[step,setStep]=useState(topic.parameters?.step??2),[part,setPart]=useState('Nuqta');
 useProbe(report,'Boshlang‘ich son + qadam nechaga teng?',value+step,`${value} + (${step}) = ${value+step}. Son chizig‘ida har qadam bir birlik.`);
 const x=n=>220+n*13,drag=event=>{const svg=event.currentTarget.ownerSVGElement,pt=svg.createSVGPoint();pt.x=event.clientX;pt.y=event.clientY;const local=pt.matrixTransform(svg.getScreenCTM().inverse());setValue(clamp(Math.round((local.x-220)/13),-10,10))};

 return <><Stage label={`Son chizig‘i: nuqta ${value} da. ${step} qadamdan keyin ${value+step}.`}><path d="M28 126h384" stroke={ink} strokeWidth="3" markerEnd="url(#ma-arrow)"/><defs><marker id="ma-arrow" markerWidth="8" markerHeight="8" refX="8" refY="4" orient="auto"><path d="M0 0L8 4 0 8" fill={ink}/></marker></defs>{Array.from({length:21},(_,i)=>i-10).map(n=><g key={n} {...svgLabel(`${n} sonini tanlash`,()=>{setValue(n);setPart('Nuqta')})}><path d={`M${x(n)} 119v14`} stroke={n===0?orange:ink}/>{n%2===0&&<text x={x(n)} y="151" textAnchor="middle" fontSize="11" fill={ink}>{n}</text>}</g>)}<path d={`M${x(value)} 96Q${(x(value)+x(value+step))/2} 42 ${x(value+step)} 96`} fill="none" stroke={orange} strokeWidth="3"/><circle cx={x(value)} cy="126" r="11" fill={teal} {...svgLabel('Nuqtani tanlash',()=>setPart('Nuqta'))}/><circle cx={x(value+step)} cy="126" r="7" fill={orange} {...svgLabel('Qadamdan keyingi nuqta',()=>setPart('Qadam'))}/><rect x="38" y="103" width="365" height="46" fill="transparent" style={{touchAction:'none',cursor:'crosshair'}} onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);drag(event)}} onPointerMove={event=>{if(event.buttons)drag(event)}} aria-hidden="true"/></Stage><div className="ma-controls"><Range label="Boshlang‘ich son" value={value} onChange={setValue}/><Range label="Qadam" value={step} onChange={setStep} min={-4} max={4}/></div><p className="ma-result" aria-live="polite">{part}: {value} {step>=0?'+':'−'} {Math.abs(step)} = <b>{value+step}</b>. O‘ngga yurish qiymatni oshiradi, chapga yurish kamaytiradi.</p><p className="ma-formula">|{value}| = {Math.abs(value)} — nolgacha masofa</p></>;
}
function LinkedAlgebraViews({x,polynomial}){const fn=n=>polynomial?n*n+3*n+2:2*n+3;return <MathRelationViews formula={polynomial?'x² + 3x + 2':'y = 2x + 3'} rows={[-5,-2,0,2,5,8].map(n=>[n,fn(n)])} currentX={x} fn={fn}/>}

function AlgebraScene({topic,report}){
 const [x,setX]=useState(topic.parameters?.x??3),[paren,setParen]=useState(topic.parameters?.paren??false),[part,setPart]=useState('Ifoda');
 const kind=topic.scene,poly=['kophad','kopaytuvchilar'].includes(topic.id),result=topic.id==='amal-tartibi'?(paren?20:14):poly?x*x+3*x+2:2*x+3;
 useProbe(report,'Hozirgi ifoda qiymati qancha?',result,`x = ${x} qo‘yilganda ifoda ${result} ga teng.`);
 return <><Stage label={`Algebraik ifoda, x = ${x}; natija ${result}.`}><rect x="65" y="65" width="300" height="116" rx="20" fill="#edf8f7" stroke="#b1dcda"/><text x="220" y="119" textAnchor="middle" fill={ink} fontSize="27" fontWeight="700">{topic.id==='amal-tartibi'?(paren?'(2 + 3) × 4':'2 + 3 × 4'):poly?'x² + 3x + 2':'2x + 3'}</text><text x="220" y="158" textAnchor="middle" fill={teal} fontSize="22">= {result}</text><g {...svgLabel('O‘zgaruvchi x',()=>setPart('x ning qiymati'))}><circle cx="100" cy="210" r="14" fill={teal}/><text x="100" y="215" textAnchor="middle" fill="white">x</text></g><text x="135" y="215" fill={ink} fontSize="13">{poly?'x × x + 3 × x + 2':topic.id==='amal-tartibi'?'Avval ko‘paytirish':'2 × x + 3'}</text></Stage>{topic.id!=='amal-tartibi'&&<LinkedAlgebraViews x={x} polynomial={poly}/>}<div className="ma-controls">{topic.id==='amal-tartibi'?<button className="ma-toggle" aria-pressed={paren} onClick={()=>setParen(!paren)}>{paren?'Qavsni olib tashlash':'2 + 3 ni qavsga olish'}</button>:<Range label="x qiymati" value={x} onChange={setX} min={-5} max={8}/>}</div><p className="ma-result" aria-live="polite">{part}: <b>{result}</b>. {topic.id==='amal-tartibi'?'Qavs amal tartibini o‘zgartiradi.':poly?`(x + 1)(x + 2) = ${result}; ikki yozuvning qiymati teng.`:`x birga oshsa, 2x + 3 qiymati ikkiga oshadi.`}</p></>;
}
function CoordinateScene({topic,report}){
 const [x,setX]=useState(topic.parameters?.x??2),[y,setY]=useState(topic.parameters?.y??3),[x2,setX2]=useState(topic.parameters?.x2??-2),[part,setPart]=useState('A nuqta');
 const coord=n=>220+n*30,vertical=n=>125-n*30,d=distance({x,y},{x:x2,y:0});
 useProbe(report,'A va B orasidagi masofa qancha?',d,`Gorizontal farq ${Math.abs(x-x2)}, vertikal farq ${Math.abs(y)}; Pifagor orqali ${fmt(d)}.`);
 return <><Stage label={`A (${x}; ${y}), B (${x2}; 0); masofa ${fmt(d)}.`}><Axes/><path d={`M${coord(x)} ${vertical(y)}L${coord(x2)} 125`} stroke={orange} strokeWidth="3"/><path d={`M${coord(x)} ${vertical(y)}V125H${coord(x2)}`} fill="none" stroke={teal} strokeDasharray="5 4"/><circle cx={coord(x)} cy={vertical(y)} r="9" fill={teal} {...svgLabel('A nuqta',()=>setPart('A nuqta'))}/><circle cx={coord(x2)} cy="125" r="8" fill={orange} {...svgLabel('B nuqta',()=>setPart('B nuqta'))}/><text x={coord(x)+12} y={vertical(y)-8} fill={ink}>A</text><text x={coord(x2)+12} y="117" fill={ink}>B</text></Stage><div className="ma-controls"><Range label="A: x" value={x} onChange={setX} min={-4} max={4}/><Range label="A: y" value={y} onChange={setY} min={-3} max={3}/><Range label="B: x" value={x2} onChange={setX2} min={-4} max={4}/></div><p className="ma-result" aria-live="polite">{part}: Δx = {Math.abs(x-x2)}, Δy = {Math.abs(y)}. Masofa <b>{fmt(d)}</b>, chunki {fmt((x-x2)**2)} + {y*y} = {fmt(d*d)}.</p></>;
}
function ShapeScene({topic,report}){
 const [a,setA]=useState(topic.parameters?.a??5),[b,setB]=useState(topic.parameters?.b??3),[n,setN]=useState(topic.parameters?.n??6),[stretch,setStretch]=useState(1),[part,setPart]=useState('Shakl'),kind=topic.scene,irregular=topic.id==='nomuntazam-kopburchak',circle=kind==='circle',polygon=kind==='polygon';
 const radius=a/(2*Math.sin(Math.PI/n)),raw=Array.from({length:n},(_,i)=>({x:radius*Math.sin(i*2*Math.PI/n),y:-radius*Math.cos(i*2*Math.PI/n)*(i===0&&irregular?stretch:1)})),polyArea=Math.abs(raw.reduce((sum,p,i)=>sum+p.x*raw[(i+1)%n].y-p.y*raw[(i+1)%n].x,0))/2,polyP=raw.reduce((sum,p,i)=>sum+Math.hypot(p.x-raw[(i+1)%n].x,p.y-raw[(i+1)%n].y),0);
 const area=circle?Math.PI*a*a:kind==='square'?a*a:kind==='trapezoid'?(a+b)*3/2:kind==='rhombus'?a*b/2:polygon?polyArea:a*b,p=circle?2*Math.PI*a:kind==='square'?4*a:kind==='trapezoid'?a+b+2*Math.hypot((a-b)/2,3):kind==='rhombus'?2*Math.hypot(a,b):kind==='parallelogram'?2*(a+Math.hypot(b,2)):polygon?polyP:2*(a+b);
 useProbe(report,'Ko‘rsatilgan shaklning yuzi qancha kvadrat birlik?',area,`O‘lchamlar bo‘yicha yuza ${fmt(area)} kvadrat birlik. ${irregular?'Muntazam ko‘pburchak formulasini har qanday ko‘pburchakka qo‘llab bo‘lmaydi.':''}`);
 const unit=Math.min(19,95/Math.max(1,a/2,b/2,circle?a:polygon?radius*stretch:0,kind==='parallelogram'?a/2+1:0)),w=a*unit,height=(kind==='square'?a:b)*unit,points=polygon?raw.map(p=>[220+p.x*unit,125+p.y*unit]):kind==='trapezoid'?[[220-w/2,125+1.5*unit],[220+w/2,125+1.5*unit],[220+b*unit/2,125-1.5*unit],[220-b*unit/2,125-1.5*unit]]:kind==='rhombus'?[[220,125-height/2],[220+w/2,125],[220,125+height/2],[220-w/2,125]]:kind==='parallelogram'?[[220+unit-w/2,125-height/2],[220+unit+w/2,125-height/2],[220-unit+w/2,125+height/2],[220-unit-w/2,125+height/2]]:[[220-w/2,125-height/2],[220+w/2,125-height/2],[220+w/2,125+height/2],[220-w/2,125+height/2]];
 return <><Stage label={`${topic.title}. Yuza ${fmt(area)}, perimetr ${fmt(p)}. Bir birlik ${fmt(unit)} chizma nuqtasi.`}>{circle?<><circle cx="220" cy="125" r={a*unit} fill={pale} stroke={teal} strokeWidth="3" {...svgLabel('Doira ichki qismi',()=>setPart('Doira'))}/><circle cx="220" cy="125" r="5" fill={ink} {...svgLabel('Markaz',()=>setPart('Markaz'))}/><path d={`M220 125h${a*unit}`} stroke={orange} strokeWidth="3" {...svgLabel('Radius',()=>setPart('Radius'))}/><text x={220+a*unit/2} y="116">r = {a}</text></>:<polygon points={points.map(p=>p.join(',')).join(' ')} fill={pale} stroke={teal} strokeWidth="3" {...svgLabel(`${topic.title} yuzi va tomonlari`,()=>setPart('Yuza va perimetr'))}/>}<text x="220" y="238" textAnchor="middle">{part}{polygon?` · ${n} uch`:''}</text></Stage><div className="ma-controls"><Range label={circle?'Radius':kind==='rhombus'?'Birinchi diagonal':polygon?'Boshlang‘ich tomon':'Birinchi o‘lcham'} value={a} onChange={setA} min={1} max={10}/>{!circle&&!polygon&&kind!=='square'&&<Range label={kind==='rhombus'?'Ikkinchi diagonal':'Ikkinchi o‘lcham'} value={b} onChange={setB} min={1} max={10}/>} {polygon&&<Range label="Tomonlar soni" value={n} onChange={setN} min={3} max={10}/>} {irregular&&<Range label="Birinchi uchni cho‘zish" value={stretch} onChange={setStretch} min={.6} max={1.8} step={.1}/>}</div><p className="ma-result" aria-live="polite">{part}: <b>yuza {fmt(area)} kvadrat birlik</b>, perimetr {fmt(p)} birlik. {circle?`π × ${a}²; radius ikki marta oshsa yuza to‘rt marta oshadi.`:kind==='trapezoid'?`(${a} + ${b}) × 3 ÷ 2; tik balandlik 3 birlik.`:kind==='rhombus'?`${a} × ${b} ÷ 2; diagonallar ko‘paytmasining yarmi.`:irregular?'Yuza uchlarning koordinatalari, perimetr esa tomonlar uzunliklari yig‘indisi orqali hisoblandi.':polygon?`Muntazam ${n} burchak markazdan ${n} ta uchburchakka ajraladi.`:kind==='square'?`${a} × ${a}; barcha tomonlar teng.`:`${a} × ${b}; asos × tik balandlik.`}</p></>;
}

function AngleScene({topic,report}){
 const [angle,setAngle]=useState(topic.parameters?.angle??70),[length,setLength]=useState(topic.parameters?.length??100),[part,setPart]=useState('Burchak');const rad=angle*Math.PI/180;
 useProbe(report,'Ikki nur orasidagi burchak necha gradus?',angle,`Nur uzunligi burchakni o‘zgartirmaydi; hozirgi burilish ${angle}°.`);
 return <><Stage label={`Ikki nur orasidagi burchak ${angle} gradus.`}><path d="M220 170h140" stroke={teal} strokeWidth="4"/><path d={`M220 170L${220+length*Math.cos(rad)} ${170-length*Math.sin(rad)}`} stroke={orange} strokeWidth="4" {...svgLabel('Ikkinchi nur',()=>setPart('Ikkinchi nur'))}/><circle cx="220" cy="170" r="8" fill={ink} {...svgLabel('Uch nuqta',()=>setPart('Burchak uchi'))}/><path d={`M250 170 A30 30 0 0 0 ${220+30*Math.cos(rad)} ${170-30*Math.sin(rad)}`} fill="none" stroke={ink} strokeWidth="2"/><text x="256" y="146" fill={ink}>{angle}°</text></Stage><div className="ma-controls"><Range label="Burchak" value={angle} onChange={setAngle} min={10} max={170} unit="°"/><Range label="Nur uzunligi" value={length} onChange={setLength} min={60} max={155}/></div><p className="ma-result" aria-live="polite">{part}: <b>{angle}°</b>. Nur uzunligi o‘zgarsa ham burchakning gradusi o‘zgarmaydi. {angle===90?'Bu to‘g‘ri burchak.':angle<90?'Bu o‘tkir burchak.':'Bu o‘tmas burchak.'}</p></>;
}
function PerpendicularScene({report}){
 const [rotation,setRotation]=useState(0),rad=rotation*Math.PI/180,cx=220,cy=125,L=85,u={x:Math.cos(rad),y:Math.sin(rad)},v={x:-Math.sin(rad),y:Math.cos(rad)};
 useProbe(report,'Perpendikulyar chiziqlar necha gradusda kesishadi?',90,'Ular 90° burchak ostida kesishadi. Burish chiziqlar orasidagi burchakni o‘zgartirmaydi.');
 const point=(a,b)=>`${cx+a*u.x+b*v.x},${cy+a*u.y+b*v.y}`;
 return <><Stage label="Ikki perpendikulyar chiziq 90 gradus ostida kesishadi."><path d={`M${point(-L,0)}L${point(L,0)}`} stroke={teal} strokeWidth="4"/><path d={`M${point(0,-L)}L${point(0,L)}`} stroke={orange} strokeWidth="4"/><path d={`M${point(0,0)}L${point(14,0)}L${point(14,14)}L${point(0,14)}`} fill="none" stroke={ink} strokeWidth="2"/><text x="250" y="110" fill={ink}>90°</text><circle cx="220" cy="125" r="5" fill={ink} {...svgLabel('Kesishish nuqtasi',()=>{})}/></Stage><div className="ma-controls"><Range label="Chiziqlar juftini birga burish" value={rotation} onChange={setRotation} min={-180} max={180} step={5} unit="°"/></div><p className="ma-result" aria-live="polite">Chiziqlar birga burildi, ammo ular orasidagi burchak <b>90°</b> bo‘lib qoldi. Shu sababli ular har qanday holatda ham perpendikulyar.</p></>;
}
function LineScene({topic,report}){
 const [length,setLength]=useState(topic.parameters?.length??6),[tilt,setTilt]=useState(topic.parameters?.tilt??0),[gap,setGap]=useState(topic.parameters?.gap??3),[part,setPart]=useState('Chiziq'),parallel=topic.id==='parallel',segment=['kesma','kesma-nur'].includes(topic.id),ray=topic.id==='nur',theta=tilt*.12,unit=20,L=(segment?length:12)*unit/2,dx=L*Math.cos(theta),dy=L*Math.sin(theta),offset={x:gap*unit*Math.sin(theta),y:gap*unit*Math.cos(theta)};
 useProbe(report,parallel?'Parallel chiziqlar orasidagi tik masofa qancha?':ray?'Nurning nechta boshlang‘ich nuqtasi bor?':'A va B orasidagi kesma uzunligi nechaga teng?',parallel?gap:ray?1:length,parallel?`Ikki chiziq orasidagi tik masofa ${gap} birlik.`:ray?'Nur bitta boshlang‘ich nuqtaga ega.':`AB uzunligi ${length} birlik; yo‘nalish uning uzunligini o‘zgartirmaydi.`);
 return <><Stage label={`${topic.title}: ${parallel?`tik oraliq ${gap}`:ray?'bir boshlanish nuqtasi':`AB = ${length}`}.`}><defs><marker id="line-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto-start-reverse"><path d="M0 0L7 3.5 0 7Z" fill={teal}/></marker></defs><path d={`M${220-dx} ${125+dy}L${220+dx} ${125-dy}`} stroke={teal} strokeWidth="3" markerStart={!segment&&!ray?'url(#line-arrow)':undefined} markerEnd={!segment?'url(#line-arrow)':undefined}/>{parallel&&<><path d={`M${220-dx+offset.x} ${125+dy+offset.y}L${220+dx+offset.x} ${125-dy+offset.y}`} stroke={orange} strokeWidth="3"/><path d={`M220 125l${offset.x} ${offset.y}`} stroke={ink} strokeDasharray="4 3"/></>}{segment&&[-1,1].map(sign=><g key={sign} {...svgLabel(sign===-1?'A kesma uchi':'B kesma uchi',()=>setPart(sign===-1?'A uchi':'B uchi'))}><circle cx={220+sign*dx} cy={125-sign*dy} r="8" fill={sign===-1?ink:orange}/><text x={220+sign*dx} y={112-sign*dy} textAnchor="middle">{sign===-1?'A':'B'}</text></g>)}{ray&&<circle cx={220-dx} cy={125+dy} r="8" fill={orange} {...svgLabel('Nurning boshlanish nuqtasi',()=>setPart('Boshlanish nuqtasi'))}/>}</Stage><div className="ma-controls">{segment&&<Range label="AB uzunligi" value={length} onChange={setLength} min={2} max={9}/>}<Range label="Yo‘nalish" value={tilt} onChange={setTilt} min={-3} max={3}/>{parallel&&<Range label="Tik oraliq" value={gap} onChange={setGap} min={1} max={5}/>}</div><p className="ma-result" aria-live="polite">{part}: {parallel?`parallel chiziqlar orasidagi tik masofa ${gap} birlik.`:ray?'Bitta boshlanish nuqtasi bor; nur strelka tomonga cheksiz davom etadi.':segment?`AB = ${length} birlik; har bir birlik ${unit} chizma nuqtasi.`:'Chiziq ikki tomonga cheksiz davom etadi; chizma faqat ko‘rish oynasidir.'}</p></>;
}

function TransformScene({topic,report}){
 const [dx,setDx]=useState(topic.parameters?.dx??2),[dy,setDy]=useState(topic.parameters?.dy??1),[angle,setAngle]=useState(topic.parameters?.angle??0),[scale,setScale]=useState(topic.parameters?.scale??1),[reflect,setReflect]=useState(topic.parameters?.reflect??false),[part,setPart]=useState('Mos nuqtalar');
 const original=[{x:-2,y:-1},{x:0,y:-1},{x:-1.5,y:1}],opts={dx,dy,angle,scale,reflect},moved=original.map(p=>transformPoint(p,opts)),extent=Math.max(4,...moved.map(p=>Math.abs(p.x)),...moved.map(p=>Math.abs(p.y))),unit=Math.min(30,95/extent),px=p=>`${220+p.x*unit},${125-p.y*unit}`;
 const area0=2,area=area0*scale*scale;
 useProbe(report,'Yangi yuzaning eski yuzaga nisbati nechaga teng?',scale*scale,`Masshtab ${scale} bo‘lsa, ikki o‘lcham ham o‘zgaradi: ${scale}² = ${fmt(scale*scale)}.`);
 return <><Stage label={`Shakl ko‘chirildi (${dx}; ${dy}), ${angle} gradus burildi, ${scale} marta masshtablandi; yuza nisbati ${fmt(scale*scale)}.`}><Axes unit={unit}/><polygon points={original.map(px).join(' ')} fill="#dceaf2" stroke={ink} strokeWidth="2"/><polygon points={moved.map(px).join(' ')} fill={pale} stroke={teal} strokeWidth="3" {...svgLabel('O‘zgargan uchburchak',()=>setPart('Yangi shakl'))}/>{original.map((p,i)=><g key={i} {...svgLabel(`Mos nuqta ${i+1}`,()=>setPart(`Mos nuqta ${i+1}`))}><circle cx={220+moved[i].x*unit} cy={125-moved[i].y*unit} r="6" fill={orange}/><path d={`M${px(p)}L${px(moved[i])}`} stroke={orange} strokeDasharray="4 3"/></g>)}</Stage><div className="ma-controls"><Range label="Gorizontal ko‘chirish" value={dx} onChange={setDx} min={-3} max={3}/><Range label="Vertikal ko‘chirish" value={dy} onChange={setDy} min={-2} max={2}/><Range label="Burish" value={angle} onChange={setAngle} min={-180} max={180} step={15} unit="°"/><Range label="Masshtab" value={scale} onChange={setScale} min={.5} max={2} step={.25}/><button className="ma-toggle" aria-pressed={reflect} onClick={()=>setReflect(!reflect)}>{reflect?'Akslantirishni o‘chirish':'Y o‘qiga nisbatan akslantirish'}</button></div><p className="ma-result" aria-live="polite">{part}: mos birinchi nuqta ({fmt(moved[0].x)}; {fmt(moved[0].y)}). Dastlabki yuza {area0}, yangi yuza <b>{fmt(area)}</b>. Faqat masshtab yuzani o‘zgartiradi: k² = {fmt(scale*scale)}.</p></>;
}
function SolidScene({topic,report}){
 const kind=topic.scene;const [a,setA]=useState(topic.parameters?.a??3),[b,setB]=useState(topic.parameters?.b??2),[h,setH]=useState(topic.parameters?.h??3),[r,setR]=useState(topic.parameters?.r??2),[open,setOpen]=useState(topic.parameters?.open??0),[yaw,setYaw]=useState(topic.parameters?.yaw??30),[section,setSection]=useState(topic.parameters?.section??false),[sectionAt,setSectionAt]=useState(50),[part,setPart]=useState('Butun jism');const measure=solidMeasures(kind,{a,b,c:h,r,h});
 useProbe(report,'Jismning hajmi qancha kub birlik?',measure.volume,`${measure.formula}; shu o‘lchamlarda V = ${fmt(measure.volume)} kub birlik.`);
 const cubeLike=['cube','cuboid'].includes(kind);const diagram=<MathSolidFallback {...{kind,a,b,h,r,open,yaw,section,sectionAt}} onPart={setPart}/>;

 return <><LearningVisual mode="solid" kind={kind} a={a} b={b} h={h} r={r} open={open} yaw={yaw} section={section} sectionAt={sectionAt} label={`${topic.title}. Hajm ${fmt(measure.volume)} kub birlik.`} fallback={diagram}/>{!cubeLike&&open>0&&<div className="ma-net-detail">{diagram}</div>}
 <div className="ma-controls">{(cubeLike||kind==='prism'||kind==='pyramid')?<><Range label="a uzunlik" value={a} onChange={setA} min={1} max={7}/>{(kind==='cuboid'||kind==='prism')&&<Range label="b eni" value={b} onChange={setB} min={1} max={7}/>}</>:<Range label="Radius" value={r} onChange={setR} min={1} max={6}/>} {kind!=='cube'&&kind!=='sphere'&&<Range label="Balandlik" value={h} onChange={setH} min={1} max={7}/>}{<Range label="Ko‘rish burchagi" value={yaw} onChange={setYaw} min={-55} max={55} step={5} unit="°"/>}<Range label="Yoyilmani ochish" value={open} onChange={v=>{setOpen(v);setSection(false)}} min={0} max={100} step={10} unit="%"/><button className="ma-toggle" aria-pressed={section} onClick={()=>{setSection(!section);setOpen(0)}}>{section?'Kesimni yashirish':'Ko‘ndalang kesimni ko‘rsatish'}</button>{section&&<Range label="Kesim balandligi" value={sectionAt} onChange={setSectionAt} min={5} max={95} unit="%"/>}</div><p className="ma-result" aria-live="polite">{part}: <b>V = {fmt(measure.volume)} kub birlik</b>, S = {fmt(measure.surface)} kvadrat birlik. {measure.formula}. Yoyilma: {measure.net}.</p><p className="ma-formula">{section&&`Kesim yuzi: ${fmt(sectionData({kind,a,b,h,r,sectionAt}).area)} kvadrat birlik. `}{['cylinder','cone'].includes(kind)&&open>0?'Oraliq ochilish — ko‘rgazmali interpolatsiya; yopiq jism va to‘liq yoyilma o‘lchamlari aniq. ':''}{measure.faces} tekis yoq · {measure.curvedSurfaces||0} egri sirt · {measure.edges} qirra · {measure.vertices} uch.</p></>;
}
function PowerScene({topic,report}){
 const [base,setBase]=useState(topic.parameters?.base??2),[exponent,setExponent]=useState(topic.parameters?.exponent??3),[part,setPart]=useState('Ko‘paytuvchilar'),value=base**exponent,root=topic.id==='ildizlar',log=topic.id==='logarifm',answer=root?Math.sqrt(value):log?exponent:value,fn=x=>root?Math.sqrt(x):log?Math.log(x)/Math.log(base):base**x,rows=Array.from({length:6},(_,i)=>root||log?[base**i,fn(base**i)]:[i,base**i]),formula=root?'y = √x':log?`y = log_${base}(x)`:`y = ${base}^x`,equal=Number.isInteger(answer)?'=':'≈';
 useProbe(report,root?'Ko‘rsatilgan sonning kvadrat ildizi qancha?':log?'Ko‘rsatilgan logarifmning qiymati qancha?':'Darajaning qiymati qancha?',answer,root?`√${value} ${equal} ${fmt(answer)}.`:log?`${base} ning ${exponent}-darajasi ${value}; log_${base}(${value}) = ${exponent}.`:`${base}^${exponent} = ${value}. ${exponent===0?'Nol daraja 1 ga teng.':`${base} soni ${exponent} marta ko‘paytiriladi.`}`);
 return <><Stage label={`${base} ning ${exponent}-darajasi ${value}.`}><text x="220" y="73" textAnchor="middle" fill={ink} fontSize="26">{root?`√${value} ${equal} ${fmt(answer)}`:log?`log_${base}(${value}) = ${exponent}`:`${base}^${exponent} = ${value}`}</text>{Array.from({length:exponent},(_,i)=><g key={i} {...svgLabel(`${i+1}-ko‘paytuvchi`,()=>setPart(`${i+1}-ko‘paytuvchi`))}><rect x={100+i*46} y="113" width="38" height="42" rx="8" fill={teal}/><text x={119+i*46} y="140" fill="white" textAnchor="middle">{base}</text></g>)}<text x="220" y="205" fill={ink} textAnchor="middle">{exponent===0?'Nol daraja: bo‘sh ko‘paytma 1 ga teng.':Array.from({length:exponent},()=>base).join(' × ')}</text></Stage><div className="ma-controls"><Range label="Asos" value={base} onChange={setBase} min={2} max={5}/><Range label="Daraja" value={exponent} onChange={setExponent} min={0} max={5}/></div><p className="ma-result" aria-live="polite">{part}: <b>{fmt(answer)}</b>. {log?`${base} ni qaysi darajaga ko‘tarsak ${value} hosil bo‘ladi? Javob: ${exponent}.`:root?`Ildiz belgisi nomanfiy qiymatni beradi; ${fmt(answer)}² ${equal} ${value}.`:`Har keyingi darajada natija ${base} marta oshadi.`}</p><MathRelationViews formula={formula} rows={rows} currentX={root||log?value:exponent} fn={fn}/></>;
}
function SequenceScene({topic,report}){
 const [first,setFirst]=useState(topic.parameters?.first??2),[diff,setDiff]=useState(topic.parameters?.diff??3),fn=n=>first+(n-1)*diff,rows=Array.from({length:5},(_,i)=>[i+1,fn(i+1)]);
 useProbe(report,'Beshinchi had nechaga teng?',fn(5),`${first} + 4 × (${diff}) = ${fn(5)}. Birinchi hadga to‘rtta qadam qo‘shiladi.`);
 return <><Stage label={`Ketma-ketlik: ${rows.map(r=>r[1]).join(', ')}.`}>{rows.map(([n,y],i)=><g key={n}><circle cx={60+i*80} cy="130" r="26" fill={i===4?orange:teal}/><text x={60+i*80} y="137" textAnchor="middle" fill="white" fontSize="18">{y}</text>{i<4&&<text x={100+i*80} y="85" textAnchor="middle" fill={ink}>{diff>=0?'+':'−'}{Math.abs(diff)}</text>}</g>)}</Stage><div className="ma-controls"><Range label="Birinchi had" value={first} onChange={setFirst} min={-5} max={10}/><Range label="Qadam" value={diff} onChange={setDiff} min={-3} max={8}/></div><p className="ma-result" aria-live="polite">Beshinchi had = {first} + 4 × ({diff}) = <b>{fn(5)}</b>. {diff<0?'Hadlar kamayadi':diff===0?'Barcha hadlar teng':'Hadlar oshadi'}; ketma-ket hadlar ayirmasi {diff}.</p><MathRelationViews formula={`a_n = ${first} + (n − 1) × (${diff})`} rows={rows} xLabel="n" yLabel="a_n" currentX={5} fn={fn} discrete/></>;
}

export function AtlasScene({topic,user,initialAssignment}){
 const [answer,setAnswer]=useState(''),[feedback,setFeedback]=useState(''),[probe,setProbe]=useState(null),[checks,setChecks]=useState([]),[snapshots,setSnapshots]=useState([]),[hintsUsed,setHintsUsed]=useState(0),[resetKey,setResetKey]=useState(0),[assignment,setAssignment]=useState(initialAssignment||null),root=useRef(null),scene=topic.scene;
 const Component=topic.id==='pifagor'?PythagorasLab:topic.id==='tengsizlik'?InequalityLab:topic.id==='nisbat'?RatioLab:topic.id==='perpendikulyar'?PerpendicularScene:scene==='number'?NumberScene:scene==='fraction'?FractionLab:scene==='balance'?BalanceLab:scene==='linear'||scene==='quadratic'?FunctionStudio:scene==='coordinate'?CoordinateScene:scene==='triangle'?TriangleLab:scene==='transform'?TransformScene:scene==='power'?PowerScene:scene==='sequence'?SequenceScene:scene==='expression'?AlgebraScene:scene==='angle'?AngleScene:scene==='line'?LineScene:['statistics','probability'].includes(scene)?DataLab:['cube','cuboid','prism','pyramid','cylinder','cone','sphere'].includes(scene)?SolidScene:ShapeScene;
 const parameters={...topic.parameters};Object.entries(assignment?.settings||{}).forEach(([key,n])=>{const spec=atlasSceneParams[scene]?.[key];if(spec&&Number.isFinite(n))parameters[key]=['n','d','n2','d2','exponent','count'].includes(key)?Math.round(Math.max(spec.min,Math.min(spec.max,n))):Math.max(spec.min,Math.min(spec.max,n))});
 const snapshot=()=>({parameters:probe?.parameters||Object.fromEntries([...root.current?.querySelectorAll('.ma-controls input,.ma-controls select')||[]].map((e,i)=>[e.getAttribute('aria-label')||`parametr${i}`,e.type==='checkbox'?e.checked:e.value])),value:probe?.value,question:probe?.question});
 useEffect(()=>{setFeedback('')},[probe?.value,probe?.question]);
 return <div ref={root} className="ma-experience"><div className="ma-visual-head"><span>KO‘RIB TUSHUN</span><strong>{topic.title}</strong><button className="ma-secondary" onClick={()=>{setResetKey(v=>v+1);setAnswer('');setFeedback('');setChecks([]);setSnapshots([]);setHintsUsed(0)}}>Qayta boshlash</button></div><Component key={`${topic.id}:${assignment?.id||'local'}:${resetKey}`} topic={{...topic,parameters}} report={setProbe}/><div className="ma-comparison"><button onClick={()=>{const data=snapshot();setSnapshots(old=>old.some(v=>JSON.stringify(v.parameters)===JSON.stringify(data.parameters))?old:[...old.slice(-5),data])}}>Natijani taqqoslashga qo‘shish</button>{snapshots.length>0&&<table><caption>Parametrlar va natijalar</caption><thead><tr><th>Sinov</th><th>Parametrlar</th><th>Natija</th></tr></thead><tbody>{snapshots.map((v,i)=><tr key={i}><td>{i+1}</td><td>{Object.entries(v.parameters).map(([k,val])=>`${k}: ${typeof val==='object'?JSON.stringify(val):val}`).join(' · ')}</td><td>{fmt(v.value)}</td></tr>)}</tbody></table>}</div><section className="ma-try"><h3>O‘zing sinab ko‘r</h3><p>{topic.challenge}</p><form onSubmit={e=>{e.preventDefault();if(!probe||!answer.trim())return;const guess=Number(answer.replace(',','.')),correct=Number.isFinite(guess)&&Math.abs(guess-probe.value)<=Math.max(.005,Math.abs(probe.value)*.002);setChecks(old=>[...old.slice(-19),{question:probe.question,guess:Number.isFinite(guess)?guess:null,correct,expected:probe.value,parameters:snapshot().parameters}]);setFeedback(correct?`To‘g‘ri. ${probe.reason}`:`Yana bir bor ko‘rib chiqing. O‘lchovlar va tanlangan parametrni solishtiring. ${topic.misconception}`)}}><label htmlFor="ma-probe">{probe?.question||'Qiymatni toping'}</label><div className="ma-probe-row"><input id="ma-probe" type="text" inputMode="decimal" value={answer} onChange={e=>{setAnswer(e.target.value);setFeedback('')}} placeholder="Sonni kiriting" required/><button type="submit">Tekshirish</button></div></form>{feedback&&<p role="status" className="ma-feedback">{feedback}</p>}<ProgressiveHelp key={resetKey} hints={[topic.misconception,'Belgilangan o‘lchovlarni o‘qing. Formula yoki jadval bilan parametrni solishtiring.',probe?.reason||topic.reason]} onHint={setHintsUsed}/></section>{user&&<ExperimentNotebook {...{topic,user,probe,checks,snapshots,hintsUsed,initialAssignment}} subject="math" onAssignment={setAssignment}/>}</div>;
}
