import React,{useEffect,useState} from 'react';
import {ImagePlus,Plus,Table2} from 'lucide-react';
import {excelValue,officeTemplates} from './office-lab-model.js';
import './office-lab.css';

const blankSlide=()=>({title:'',body:'',notes:'',imageInserted:false});
const initial=(task)=>!task?{}:task.kind==='word'?{kind:'word',title:'',body:'',table:[],imageInserted:false,wrap:'inline',reference:{recipient:'',date:'',source:''}}:
 task.kind==='excel'?{kind:'excel',cells:{...(task.initialCells||{})}}:{kind:'ppt',slides:[blankSlide()]};

export default function OfficeLab({question,onChange,disabled=false}){
 const task=question.officeTask||officeTemplates[question.officeTemplate];
 const [value,setValue]=useState(()=>initial(task));const [uploaded,setUploaded]=useState(''),[fileError,setFileError]=useState(''),[activeCell,setActiveCell]=useState('A1');
 useEffect(()=>{onChange(JSON.stringify(value))},[value]);
 if(!task)return <p role="alert">Amaliy topshiriq sozlanmagan. O‘qituvchiga xabar bering.</p>;
 const update=change=>setValue(old=>({...old,...change}));
 const addImage=event=>{
  const file=event.target.files?.[0];if(!file)return;
  if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)||file.size>1024*1024){setFileError('Faqat PNG, JPEG, WebP yoki GIF; 1 MB dan kichik rasm tanlang.');return}
  const reader=new FileReader();reader.onload=()=>{setUploaded(String(reader.result||''));setFileError('');update({imageInserted:true})};reader.readAsDataURL(file);
 };
 return <div className="office-lab"><div className="office-lab-intro"><b>{task.title}</b><p>{task.prompt}</p></div>
 {task.kind==='word'&&<div className="office-document"><div className="office-ribbon"><b>Hujjat</b><button disabled={disabled} onClick={()=>update({table:[['',''],['','']]})}><Table2 size={15}/> Jadval qo‘shish</button><button disabled={disabled} onClick={()=>update({imageInserted:true})}><ImagePlus size={15}/> Namuna rasm</button><label className="office-file"><ImagePlus size={15}/> O‘z rasmim<input disabled={disabled} type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={addImage}/></label></div>
  <div className="office-paper"><label>Hujjat sarlavhasi<input aria-label="Word sarlavhasi" disabled={disabled} value={value.title} onChange={event=>update({title:event.target.value.slice(0,120)})} placeholder="Maktab kutubxonasi"/></label>
   <div className="office-text-and-image">{value.imageInserted&&<figure className={'office-inline-image '+value.wrap}><img src={uploaded||'/course-visuals/word-images.svg'} alt="Hujjatga qo‘shilgan rasm"/><figcaption>Hujjat rasmi</figcaption></figure>}<label>Asosiy matn<textarea aria-label="Word hujjati matni" disabled={disabled} value={value.body} onChange={event=>update({body:event.target.value.slice(0,1000)})} placeholder="Hujjat mavzusi haqida ikki yoki uch gap yozing."/></label></div>
   {value.imageInserted&&<label>Rasmni matnga o‘rash<select disabled={disabled} value={value.wrap} onChange={event=>update({wrap:event.target.value})}><option value="inline">Matn bilan qatorda</option><option value="left">Chapda, matn atrofida</option><option value="right">O‘ngda, matn atrofida</option></select></label>}
   {!!value.table.length&&<div className="office-table-block"><b>Jadval</b><table><tbody>{value.table.map((row,r)=><tr key={r}>{row.map((cell,c)=><td key={c}><input aria-label={`Jadval ${r+1}-qator ${c+1}-ustun`} disabled={disabled} value={cell} maxLength={100} onChange={event=>update({table:value.table.map((items,i)=>i===r?items.map((item,j)=>j===c?event.target.value:item):items)})}/></td>)}</tr>)}</tbody></table><button disabled={disabled||value.table.length>=6} onClick={()=>update({table:[...value.table,['','']]})}><Plus size={14}/> Qator qo‘shish</button></div>}
   <div className="office-reference"><b>Ma’lumotnoma ma’lumotlari</b>{[['recipient','Kimga'],['date','Sana'],['source','Manba yoki muallif']].map(([field,label])=><label key={field}>{label}<input aria-label={label} disabled={disabled} value={value.reference[field]} maxLength={120} onChange={event=>update({reference:{...value.reference,[field]:event.target.value}})}/></label>)}</div>
  </div>{fileError&&<p role="alert" className="form-error">{fileError}</p>}</div>}
 {task.kind==='excel'&&<div className="office-sheet"><p>Katakni tanlab son yoki formula yozing. Formulani <code>=</code> bilan boshlang; masalan, <code>=B2+C2</code> yoki <code>=AVERAGE(B2:B4)</code>.</p><div className="office-formula-bar"><output aria-live="polite">{activeCell} · {activeCell[0]} ustun, {activeCell.slice(1)}-qator</output><label>Formula / qiymat<input aria-label="Tanlangan katak qiymati" disabled={disabled} value={value.cells[activeCell]||''} maxLength={120} onChange={e=>update({cells:{...value.cells,[activeCell]:e.target.value}})}/></label></div><div className="office-sheet-scroll"><table><thead><tr><th></th>{['A','B','C','D'].map(col=><th key={col}>{col}</th>)}</tr></thead><tbody>{Array.from({length:6},(_,i)=>i+1).map(row=><tr key={row}><th>{row}</th>{['A','B','C','D'].map(col=>{const address=col+row,raw=value.cells[address]||'';let result='';if(raw.startsWith('='))try{result=String(excelValue(value.cells,address))}catch{result='Xato'}return <td className={activeCell===address?'office-active-cell':''} key={address}><input aria-label={`Katak ${address}`} onFocus={()=>setActiveCell(address)} disabled={disabled} value={raw} maxLength={120} onChange={event=>update({cells:{...value.cells,[address]:event.target.value}})}/>{raw.startsWith('=')&&<small>{result}</small>}</td>})}</tr>)}</tbody></table></div></div>}
 {task.kind==='ppt'&&<div className="office-slides"><nav aria-label="Slaydlar">{value.slides.map((slide,index)=><button type="button" className={index===0?'office-slide-tab':''} key={index} onClick={()=>document.getElementById(`sq-slide-${question.id}-${index}`)?.scrollIntoView({behavior:'smooth',block:'nearest'})}>{index+1}. {slide.title||'Yangi slayd'}</button>)}<button type="button" disabled={disabled||value.slides.length>=5} onClick={()=>update({slides:[...value.slides,blankSlide()]})}><Plus size={14}/> Slayd qo‘shish</button></nav>{value.slides.map((slide,index)=><article id={`sq-slide-${question.id}-${index}`} key={index} className="office-slide"><small>{index+1}-SLAYD</small><input aria-label={`${index+1}-slayd sarlavhasi`} disabled={disabled} maxLength={120} value={slide.title} placeholder="Slayd sarlavhasi" onChange={event=>update({slides:value.slides.map((item,i)=>i===index?{...item,title:event.target.value}:item)})}/><textarea aria-label={`${index+1}-slayd matni`} disabled={disabled} maxLength={1000} value={slide.body} placeholder="Asosiy fikrlarni yozing" onChange={event=>update({slides:value.slides.map((item,i)=>i===index?{...item,body:event.target.value}:item)})}/>{slide.imageInserted&&<img src="/course-visuals/ppt-media.svg" alt="Slaydda rasm namunasi"/>}<button disabled={disabled} onClick={()=>update({slides:value.slides.map((item,i)=>i===index?{...item,imageInserted:!item.imageInserted}:item)})}><ImagePlus size={14}/>{slide.imageInserted?'Rasmni olib tashlash':'Slaydga rasm qo‘shish'}</button><label>So‘zlovchi qaydlari<textarea aria-label={`${index+1}-slayd qaydlari`} disabled={disabled} value={slide.notes} maxLength={600} onChange={event=>update({slides:value.slides.map((item,i)=>i===index?{...item,notes:event.target.value}:item)})}/></label></article>)}</div>}
 <p className="office-lab-note">Bu o‘quv muharriri. Yakuniy javob amallar bo‘yicha tekshiriladi; fayl Word, Excel yoki PowerPoint formatida eksport qilinmaydi.</p></div>;
}
