import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Check,Clock3,Code2,Flag,GraduationCap,Search,X,Download} from 'lucide-react';
import {openExams,getOpenExam,getOpenGroup} from '../data/open-exams.js';
import {newAttempt,validAttempt,finishAttempt,updateAttempt,attemptReview} from './open-exam-engine.js';
import './open-exam.css';

const subjects={all:'Barchasi',english:'Ingliz tili',math:'Matematika',python:'Python'};
const timeLabel=ms=>Math.floor(Math.max(0,ms)/60000)+':'+String(Math.floor(Math.max(0,ms)%60000/1000)).padStart(2,'0');
function readSaved(key){try{return JSON.parse(localStorage.getItem(key))}catch{return null}}
function restore(key){const s=readSaved(key),exam=getOpenExam(s?.examId);return validAttempt(s,exam)?(Date.now()>=s.endsAt?finishAttempt(s):s):null}
const textAnswer=q=>Array.isArray(q.answer)?q.answer.join(' / '):q.answer;
function Modal({title,children,onClose}){
 const ref=useRef(null),previous=useRef(null);
 useEffect(()=>{previous.current=document.activeElement;ref.current?.focus();return()=>previous.current?.focus?.()},[]);
 const keydown=e=>{if(e.key==='Escape'){e.preventDefault();onClose()}if(e.key==='Tab'){const nodes=ref.current.querySelectorAll('button:not(:disabled),input,a[href]'),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};
 return <div className="nx-overlay"><section className="nx-modal" role="dialog" aria-modal="true" aria-labelledby="nx-modal-title" tabIndex={-1} ref={ref} onKeyDown={keydown}><button className="nx-close" onClick={onClose} aria-label="Oynani yopish"><X/></button><h2 id="nx-modal-title">{title}</h2>{children}</section></div>;
}
function download(data,name){
 const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export default function OpenExamHub({user,onBack,onStatus,initialSubject='all'}){
 const key='sq_open_attempt_'+user.id,historyKey='sq_open_results_'+user.id;
 const [attempt,setAttempt]=useState(()=>restore(key)),ref=useRef(attempt);ref.current=attempt;
 const [subject,setSubject]=useState(initialSubject),[query,setQuery]=useState(''),[preview,setPreview]=useState(null),[confirmFinish,setConfirmFinish]=useState(false),[error,setError]=useState(''),[now,setNow]=useState(Date.now()),[reviewFilter,setReviewFilter]=useState('wrong'),[font,setFont]=useState(18);
 const [results,setResults]=useState(()=>{const rows=readSaved(historyKey);return Array.isArray(rows)?rows.slice(0,30):[]});
 const heading=useRef(null),active=!!attempt&&!attempt.finished,exam=attempt?getOpenExam(attempt.examId):null;
 const persist=next=>{ref.current=next;setAttempt(next);try{localStorage.setItem(key,JSON.stringify(next))}catch{setError('Javoblarni qurilmaga saqlab bo‘lmadi. Oynani yopmasdan testni tugating va natijani yuklab oling.')}};
 const finish=()=>{persist(finishAttempt(ref.current));setConfirmFinish(false);setReviewFilter('wrong')};
 useEffect(()=>{onStatus(active);if(active)history.replaceState(null,'',location.pathname+location.search+'#open-exam');return()=>onStatus(false)},[active]);
 useEffect(()=>{if(!active)return;const timer=setInterval(()=>{setNow(Date.now());if(Date.now()>=ref.current.endsAt)finish()},1000);return()=>clearInterval(timer)},[active]);
 useEffect(()=>{heading.current?.focus()},[attempt?.index,attempt?.finished]);
 useEffect(()=>{
  if(!attempt?.finished||!exam)return;
  const id=attempt.examId+':'+attempt.startedAt,review=attemptReview(attempt,exam),row={id,examId:exam.id,title:exam.title,correct:review.filter(q=>q.correct).length,total:review.length,at:attempt.finishedAt};
  setResults(old=>{const next=[row,...old.filter(r=>r.id!==id)].slice(0,30);try{localStorage.setItem(historyKey,JSON.stringify(next))}catch{setError('Natijalar tarixini saqlab bo‘lmadi. Natijani yuklab oling.')}return next});
 },[attempt?.finished,attempt?.startedAt]);
 const change=data=>persist(updateAttempt(ref.current,data));
 const returnCatalog=()=>{setAttempt(null);ref.current=null;setError('');try{localStorage.removeItem(key)}catch{setError('Oldingi sessiyani xotiradan tozalab bo‘lmadi.')}history.replaceState(null,'',location.pathname+location.search)};
 if(!attempt){
  const visible=openExams.filter(e=>(subject==='all'||e.subject===subject)&&e.title.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  return <main className="nx-page nx-catalog"><div className="nx-topline"><button className="nx-text-button" onClick={onBack}><ArrowLeft size={17}/> Chiqish</button><span>SINFQUIZ / MUSTAQIL MASHQ</span></div>
   <header className="nx-hero"><div><p className="nx-kicker">BILIMINGIZNI AMALDA SINANG</p><h1>O‘qing. Javob bering.<br/><em>Natijangizni tushuning.</em></h1><p>Matn va savollar shu yerda. Mavzuni tanlang, testni ishlang va har bir javobingizning izohini ko‘ring.</p></div><div className="nx-hero-stat"><BookOpen size={28}/><strong>75</strong><span>manbali va original savol</span><small>30 English · 30 matematika · 15 Python</small></div></header>
   <div className="nx-toolbar"><div className="nx-subjects" aria-label="Fan filtri">{Object.entries(subjects).map(([id,label])=><button key={id} aria-pressed={subject===id} onClick={()=>setSubject(id)}>{label}</button>)}</div><label className="nx-search"><Search size={18}/><input aria-label="Test qidirish" placeholder="Mavzu bo‘yicha qidirish" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
   {error&&<p className="nx-error" role="alert">{error}</p>}
   <div className="nx-section-title"><h2>{subjects[subject]} <span>{visible.length} test</span></h2><span>Javoblar avtomatik saqlanadi</span></div>
   <div className="nx-cards">{visible.map((e,i)=>{const last=results.find(r=>r.examId===e.id);return <article className={'nx-card '+e.subject} key={e.id}><div className="nx-card-top"><span className="nx-icon">{e.subject==='python'?<Code2/>:e.subject==='math'?<GraduationCap/>:<BookOpen/>}</span><span className="nx-badge">{e.questions.length===30?'Aralash variant':e.subject==='python'?'Boshlang‘ich':'Mavzu mashqi'}</span></div><small>{subjects[e.subject]} · {String(i+1).padStart(2,'0')}</small><h3>{e.title}</h3><p>{e.description}</p><div className="nx-card-meta"><span><BookOpen size={15}/>{e.questions.length} savol</span><span><Clock3 size={15}/>{e.minutes} daqiqa</span></div>{last&&<div className="nx-last">Oxirgi natija <b>{last.correct}/{last.total}</b></div>}<button className="nx-start" aria-label={'Boshlash: '+e.title} onClick={()=>setPreview(e)}>Testni boshlash <ArrowRight size={17}/></button></article>})}</div>
   {!visible.length&&<div className="nx-empty">Bu nomdagi test topilmadi. Boshqa so‘z bilan qidiring.</div>}
   <section className="nx-note"><BookOpen/><div><b>Materiallar haqida</b><p>Inglizcha matnlar VOA Learning English’dan; matematika masalalari W. C. Boyden kitobidan olindi. Python savollari rasmiy hujjatlarga tayangan holda tuzildi. Bular mustaqil tayyorgarlik mashqlari; to‘liq CEFR mock yoki rasmiy milliy sertifikat imtihoni emas.</p></div></section>
   {preview&&<Modal title={preview.title} onClose={()=>setPreview(null)}><p>{preview.questions.length} savol · {preview.minutes} daqiqa</p><ul><li>Istalgan savolga qaytishingiz mumkin.</li><li>Ikkilangan savolingizni belgilab qo‘ying.</li><li>Vaqt tugaganda test avtomatik yakunlanadi.</li><li>Natija va izohlar “Tugatish”dan keyin ochiladi.</li></ul><p className="nx-muted">Natija shu brauzerda saqlanadi. Matnlardagi sana va raqamlar asl nashr davriga tegishli.</p><div className="nx-actions"><button onClick={()=>setPreview(null)}>Bekor qilish</button><button className="nx-primary" onClick={()=>{persist(newAttempt(preview));setNow(Date.now());setPreview(null)}}>Boshlash</button></div></Modal>}
  </main>;
 }
 const review=attemptReview(attempt,exam);
 if(attempt.finished){
  const right=review.filter(q=>q.correct).length,blank=review.filter(q=>!q.selected.trim()).length,list=review.filter(q=>reviewFilter==='all'||reviewFilter==='wrong'&&!q.correct||reviewFilter==='blank'&&!q.selected.trim()),percent=Math.round(right/review.length*100);
  return <main className="nx-page nx-result"><header className="nx-result-head"><span className="nx-kicker">TEST YAKUNLANDI</span><h1>{exam.title}</h1><p>{attempt.reason==='time'?'Ajratilgan vaqt tugadi.':'Javoblaringiz topshirildi.'} Quyida natija va yechimlarni ko‘ring.</p></header><section className="nx-scoreboard"><div className="nx-score"><strong>{percent}<small>%</small></strong><span>To‘g‘ri javoblar</span></div><div><b>{right}/{review.length}</b><span>To‘g‘ri</span></div><div><b>{review.length-right-blank}</b><span>Xato</span></div><div><b>{blank}</b><span>Javobsiz</span></div><div><b>{timeLabel(attempt.finishedAt-attempt.startedAt)}</b><span>Sarflangan vaqt</span></div></section>{error&&<p role="alert" className="nx-error">{error}</p>}
   <div className="nx-actions nx-result-actions"><button className="nx-primary" onClick={returnCatalog}><ArrowLeft size={16}/> Testlarga qaytish</button><button onClick={()=>download({exam:exam.title,startedAt:attempt.startedAt,finishedAt:attempt.finishedAt,correct:right,total:review.length,review},'sinfquiz-natija.json')}><Download size={16}/> Natijani saqlash</button></div>
   <div className="nx-review-head"><h2>Javoblar tahlili</h2><div className="nx-subjects">{[['wrong','Xatolar'],['blank','Javobsiz'],['all','Barchasi']].map(([id,label])=><button aria-pressed={id===reviewFilter} onClick={()=>setReviewFilter(id)} key={id}>{label}</button>)}</div></div>
   {!list.length&&<div className="nx-empty">{reviewFilter==='wrong'?'Barcha javoblar to‘g‘ri. Barakalla!':'Bu bo‘limda savol yo‘q.'}</div>}
   <div className="nx-review-list">{list.map(q=>{const group=getOpenGroup(q.group);return <article key={q.id} className={'nx-review-item '+(q.correct?'is-correct':'is-wrong')}><div className="nx-review-label"><b>{q.number}-savol · {group.title}</b><span>{q.correct?'To‘g‘ri':q.selected?'Xato':'Javobsiz'}</span></div><h3>{q.text}</h3>{q.code&&<pre><code>{q.code}</code></pre>}<dl><div><dt>Sizning javobingiz</dt><dd>{q.selected||'Javob berilmagan'}</dd></div><div><dt>To‘g‘ri javob</dt><dd>{textAnswer(q)}</dd></div></dl><p>{q.explanation}</p><details><summary>Manba va matn</summary><p>{group.publisher} · {group.year} · {q.sourceReference}</p><p>{group.adaptation}</p>{group.text&&<div className="nx-review-passage">{group.text}</div>}<a href={q.sourceUrl||group.sourceUrl} target="_blank" rel="noopener noreferrer">Muallif va manba ma’lumoti ↗</a></details></article>})}</div><p className="nx-muted">Foiz — shu mashqdagi to‘g‘ri javoblar ulushi. Rasmiy CEFR yoki milliy sertifikat darajasi hisoblanmaydi.</p>
  </main>;
 }
 const q=exam.questions[attempt.index],group=getOpenGroup(q.group),answered=exam.questions.filter(item=>attempt.answers[item.id]?.trim()).length,flagCount=Object.values(attempt.flags).filter(Boolean).length;
 return <main className="nx-page nx-workspace"><header className="nx-exam-bar"><div><small>{subjects[exam.subject]} / MUSTAQIL MASHQ</small><h1>{exam.title}</h1></div><div className={'nx-timer '+(attempt.endsAt-now<300000?'urgent':'')} aria-label="Qolgan vaqt"><Clock3 size={18}/>{timeLabel(attempt.endsAt-now)}</div><button className="nx-primary" onClick={()=>setConfirmFinish(true)}>Tugatish <Check size={17}/></button></header><div className="nx-progress" role="progressbar" aria-label="Javob berilgan savollar" aria-valuenow={answered} aria-valuemin={0} aria-valuemax={exam.questions.length}><i style={{width:answered/exam.questions.length*100+'%'}}/></div>{error&&<p role="alert" className="nx-error">{error}</p>}
  <div className={'nx-exam-grid '+(!group.text?'no-passage':'')}><aside className="nx-map"><div><b>Savollar</b><span>{answered}/{exam.questions.length}</span></div><nav aria-label="Savollar xaritasi">{exam.questions.map((item,index)=><button key={item.id} aria-label={(index+1)+'-savol'+(attempt.flags[item.id]?', belgilangan':'')} aria-current={index===attempt.index?'step':undefined} className={(attempt.answers[item.id]?.trim()?'answered ':'')+(index===attempt.index?'current ':'')+(attempt.flags[item.id]?'flagged':'')} onClick={()=>change({type:'navigate',index})}>{index+1}{attempt.flags[item.id]&&<i/>}</button>)}</nav><small>● Javob berilgan<br/>◆ Keyin ko‘rish: {flagCount}</small><p>Javoblar shu qurilmada saqlanmoqda.</p></aside>
  {group.text&&<section className="nx-passage"><div className="nx-passage-top"><span>READING MATNI</span><div><button aria-label="Matnni kichraytirish" disabled={font<=16} onClick={()=>setFont(font-1)}>A−</button><button aria-label="Matnni kattalashtirish" disabled={font>=24} onClick={()=>setFont(font+1)}>A+</button></div></div><h2>{group.title}</h2><p className="nx-source-caption">{group.publisher} · {group.year}{group.year===2004?' · Arxiv matni':''}</p><div className="nx-passage-body" lang="en" style={{fontSize:font}}>{group.text.split('\n\n').map((p,i)=><p key={i}>{p}</p>)}</div></section>}
  <section className="nx-question"><div className="nx-question-top"><span>{attempt.index+1}-savol / {exam.questions.length}</span><button aria-pressed={!!attempt.flags[q.id]} onClick={()=>change({type:'flag',id:q.id})}><Flag size={16}/>{attempt.flags[q.id]?'Belgilangan':'Keyin ko‘rish'}</button></div><h2 ref={heading} tabIndex={-1}>{q.text}</h2>{q.code&&<pre><code>{q.code}</code></pre>}
   {q.type==='choice'?<fieldset className="nx-choices"><legend className="nx-sr">Bitta javob tanlang</legend>{q.options.map((option,i)=><label key={option} className={attempt.answers[q.id]===option?'selected':''}><input type="radio" name={q.id} checked={attempt.answers[q.id]===option} onChange={()=>change({type:'answer',id:q.id,value:option})}/><span>{String.fromCharCode(65+i)}</span><b>{option}</b>{attempt.answers[q.id]===option&&<Check size={17}/>}</label>)}</fieldset>:<label className="nx-written">Javobingiz<input value={attempt.answers[q.id]||''} autoComplete="off" maxLength={200} aria-label="Javobingiz" onChange={e=>change({type:'answer',id:q.id,value:e.target.value})}/><small>{q.numeric?'Faqat son kiriting. Masalan: 5.5 yoki 11/2.':'Savoldagi ma’lumotga mos qisqa javob kiriting.'}</small></label>}
   <button className="nx-clear" disabled={!attempt.answers[q.id]} onClick={()=>change({type:'answer',id:q.id,value:''})}>Javobni tozalash</button><footer className="nx-question-footer"><button disabled={attempt.index===0} onClick={()=>change({type:'navigate',index:attempt.index-1})}><ArrowLeft size={16}/> Oldingi</button>{attempt.index===exam.questions.length-1?<button className="nx-primary" onClick={()=>setConfirmFinish(true)}>Yakunlash <Check size={16}/></button>:<button className="nx-primary" onClick={()=>change({type:'navigate',index:attempt.index+1})}>Keyingi <ArrowRight size={16}/></button>}</footer><p className="nx-muted">Javob izohi test tugagandan keyin ko‘rinadi.</p>
  </section></div>
  {confirmFinish&&<Modal title="Testni tugatasizmi?" onClose={()=>setConfirmFinish(false)}><p>{answered} ta savolga javob berildi. <b>{exam.questions.length-answered} ta javobsiz</b>, {flagCount} ta belgilangan savol bor.</p><p>Yakunlangandan so‘ng javoblar o‘zgartirilmaydi.</p><div className="nx-actions"><button onClick={()=>setConfirmFinish(false)}>Davom ettirish</button><button className="nx-primary" onClick={finish}>Ha, tugatish</button></div></Modal>}
 </main>;
}
