import React,{useId,useMemo,useState} from 'react';
import {BookOpen,ChevronDown,Check,Download,FlaskConical,Layers} from 'lucide-react';
import {chemistryLessons,biologyLessons} from '../data/science-textbooks.js';
import {comparisonChanges,curveExtent,curveCSV} from './science-measurements.js';
import './science-studio.css';
const number=n=>Number.isFinite(n)?Number(n.toFixed(3)).toLocaleString('uz-UZ'):'—';
export function ScienceLesson({topic,subject,reviewOnly=false}) {
 const [open,setOpen]=useState(false),[chosen,setChosen]=useState(null),[checked,setChecked]=useState(false),[solution,setSolution]=useState(false);
 const id=useId(),source=(subject==='biology'?biologyLessons:chemistryLessons),lesson=source[topic.templateId||topic.id]||source[topic.scene];
 const quiz=lesson&&(<fieldset className="ss-check"><legend>{lesson[2]}</legend>{lesson[3].map((option,i)=><label key={i}><input type="radio" name={id} checked={chosen===i} onChange={()=>{setChosen(i);setChecked(false);setSolution(false)}}/>{option}</label>)}<button disabled={chosen===null} onClick={()=>setChecked(true)}>Bilimni tekshirish</button>{checked&&<div role="status" className="ss-feedback"><b>{chosen===lesson[4]?'To‘g‘ri.':'Misolni yana kuzating.'}</b><p>{chosen===lesson[4]?lesson[5]:topic.misconception}</p>{chosen!==lesson[4]&&<button onClick={()=>setSolution(v=>!v)}>{solution?'Yechimni yopish':'Yechim izohini ochish'}</button>}{solution&&<p>{lesson[5]}</p>}</div>}</fieldset>);
 if(reviewOnly)return <section className="ss-lesson ss-reader-check"><div className="ss-lesson-content"><h2>O‘zingizni tekshiring</h2>{quiz}</div></section>;
 return <section className="ss-lesson"><button className="ss-lesson-toggle" aria-expanded={open} aria-controls={id} onClick={()=>setOpen(v=>!v)}><span className="ss-icon"><BookOpen size={21}/></span><span><small>DARS VA TAJRIBA BIR JOYDA</small><b>{open?'Dars izohini yopish':'Tajriba oldidan qisqa dars'}</b></span><ChevronDown size={19}/></button>{open&&<div id={id} className="ss-lesson-content"><div className="ss-learning-grid"><section><small>01 / TUSHUNCHA</small><h3>{topic.title}</h3><p>{topic.definition}</p></section><section><small>02 / SABAB</small><h3>Nima bilan bog‘liq?</h3><p>{topic.reason}</p></section></div>{lesson&&<><h3>Bir misolni tekshiramiz</h3><p>{lesson[0]}</p><aside className="ss-task"><FlaskConical size={22}/><div><b>Modelda bajariladigan amal</b><p>{lesson[1]}</p></div></aside>{quiz}</>}<details><summary>Chalkashtirmaslik uchun</summary><p>{topic.misconception}</p><p>{topic.life}</p></details></div>}</section>;
}

export function ScienceMeasurements({points,current,defaultMetric,measurementUnits={},xLabel='Jarayon ulushi',xUnit='%',progress=0,baseline=null,baselineLabel='Oldingi sinov',onRestore,parameters,parameterLabels={}}) {
 const keys=Object.keys(current).filter(k=>Number.isFinite(current[k]));
 const [selection,setSelection]=useState(defaultMetric||keys[0]),id=useId();
 const metric=keys.includes(selection)?selection:keys[0],unit=measurementUnits[metric]||'';
 const extent=useMemo(()=>curveExtent(points,metric),[points,metric]);
 if(!metric)return null;
 const maxX=Math.max(...points.map(p=>p.x),1e-6),scaleX=x=>52+x/maxX*480,scaleY=y=>172-(y-extent.lo)/(extent.hi-extent.lo)*140;
 const path=points.filter(p=>Number.isFinite(p.values[metric])).map((p,i)=>`${i?'L':'M'}${scaleX(p.x).toFixed(2)},${scaleY(p.values[metric]).toFixed(2)}`).join(' ');
 const x=Math.max(0,Math.min(maxX,progress)),now=current[metric],previous=baseline?.readings?.[metric];
 const differences=baseline?comparisonChanges(baseline.parameters,parameters):[];
 const download=()=>{const url=URL.createObjectURL(new Blob([curveCSV(points,metric,xLabel,{unit,xUnit})],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='sinfquiz-tajriba-grafik.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 return <section className="ss-measurements" aria-label="Jonli o‘lchovlar va grafik"><div className="ss-section-heading"><div><small>KUZATISH</small><h3>Natijani o‘zgarish bilan bog‘lang</h3></div><label htmlFor={id}>Grafikdagi o‘lchov<select id={id} value={metric} onChange={e=>setSelection(e.target.value)}>{keys.map(k=><option key={k}>{k}</option>)}</select></label></div><div className="ss-plot-layout"><figure className="ss-plot"><svg viewBox="0 0 570 225" role="img" aria-label={`${metric}: joriy qiymat ${number(now)} ${unit}. Gorizontal o‘q ${xLabel}. Grafik bu sahnadagi modeldan hisoblangan.`}>{[0,.25,.5,.75,1].map(t=><g key={t}><path d={`M52 ${172-t*140}H532`} className="ss-grid"/><text x="44" y={176-t*140} textAnchor="end">{number(extent.lo+t*(extent.hi-extent.lo))}</text><text x={52+t*480} y="195" textAnchor="middle">{number(xUnit==='%'?t*100:t*maxX)}</text></g>)}<path d="M52 28V172H532" className="ss-axis"/><path d={path} className="ss-curve"/><path d={`M${scaleX(x)} 28V172`} className="ss-cursor"/><circle cx={scaleX(x)} cy={scaleY(now)} r="5" className="ss-current"/><text x="290" y="219" textAnchor="middle">{xLabel} {xUnit&&`(${xUnit})`}</text></svg><figcaption>Chiziq — shu sharoitdagi model. Nuqta — hozirgi bosqich. Kelajakdagi chiziq dala o‘lchovi emas.</figcaption></figure><div className="ss-live-value"><small>{metric}</small><strong>{number(now)}{unit&&<small> {unit}</small>}</strong>{Number.isFinite(previous)&&<><span>{baselineLabel}: <b>{number(previous)}</b></span><span>Farq: <b>{number(now-previous)}</b></span></>}<button onClick={download}><Download size={15}/> Grafikni CSV olish</button></div></div>{baseline&&<div className="ss-compare-note"><Layers size={18}/><p>{differences.length?`O‘zgargan sharoit: ${differences.map(k=>parameterLabels[k]||k).join(', ')}.`:'Sharoitlar bir xil.'} {differences.length>1?'Sababni ajratish uchun bitta omilni o‘zgartirib qayta solishtiring.':'Vaqt va boshqa sharoitlarni teng saqlab solishtiring.'}</p>{onRestore&&<button onClick={onRestore}>Oldingi sharoitni tiklash</button>}</div>}<details className="ss-values"><summary>Barcha joriy qiymatlar</summary><dl>{keys.map(k=><React.Fragment key={k}><dt>{k}</dt><dd>{number(current[k])}</dd></React.Fragment>)}</dl></details></section>;
}

export function ScienceFlow({running,progress,trials=0,complete=false}) {
 const step=complete?4:trials>0?3:progress>0?2:running?1:0;
 return <ol className="ss-flow" aria-label="Tajriba yo‘li">{['Savol va taxmin','Sharoitni tanlash','Jarayonni kuzatish','Sinovlarni solishtirish','Xulosa'].map((text,i)=><li key={text} className={i===step?'is-current':i<step?'is-done':''} aria-current={i===step?'step':undefined}><span>{i<step?<Check size={14}/>:i+1}</span>{text}</li>)}</ol>;
}
