import React,{useEffect,useMemo,useState} from 'react';
import {ArrowLeft,BookOpen,Check,Eye,EyeOff,Keyboard,LockKeyhole,RefreshCw,Save,Trophy,UserRound} from 'lucide-react';
import {changeOwnPassword,loadStudentResults,studentProfile,updateStudentProfile} from './profile-service.js';
import './student-profile.css';

const kinds={all:'Barchasi',quiz:'Sinf testlari',typing:'Typing',national:'Milliy test',cefr:'CEFR',practice:'Mustaqil mashq',race:'1v1 poyga'};
const date=at=>new Date(at).toLocaleString('uz-UZ',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
function localRows(id){try{const value=JSON.parse(localStorage.getItem('sq_open_results_'+id)||'[]');return Array.isArray(value)?value:[]}catch{return []}}

export default function StudentProfile({user,onBack,onSaved}){
 const [profile,setProfile]=useState(null),[form,setForm]=useState(null),[history,setHistory]=useState([]),[filter,setFilter]=useState('all'),[shown,setShown]=useState(24);
 const [password,setPassword]=useState({old:'',next:'',again:''}),[show,setShow]=useState(false);
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[partial,setPartial]=useState(false);
 const load=async()=>{
  setBusy('load');setError('');
  const [info,results]=await Promise.allSettled([studentProfile(),loadStudentResults(localRows(user.id))]);
  if(info.status==='fulfilled'){setProfile(info.value);setForm(info.value)}else setError(info.reason.message);
  if(results.status==='fulfilled'){setHistory(results.value.rows);setPartial(results.value.partial)}else setError(results.reason.message);
  setBusy('');
 };
 useEffect(()=>{load()},[user.id]);
 const visible=useMemo(()=>filter==='all'?history:history.filter(row=>row.type===filter),[history,filter]);
 const save=async event=>{event.preventDefault();setBusy('profile');setError('');setMessage('');try{const value=await updateStudentProfile(form);setProfile(value);setForm(value);onSaved(value);setMessage('Ma’lumotlaringiz saqlandi.')}catch(e){setError(e.message)}finally{setBusy('')}};
 const renew=async event=>{event.preventDefault();if(password.next!==password.again){setError('Yangi parollar bir xil emas.');return}setBusy('password');setError('');setMessage('');try{await changeOwnPassword(password.old,password.next);setPassword({old:'',next:'',again:''});setMessage('Parol yangilandi. Keyingi kirishda yangi paroldan foydalaning.')}catch(e){setError(e.message)}finally{setBusy('')}};
 return <main className="sp-page"><header className="sp-header"><button className="back-circle" onClick={onBack} aria-label="Bosh sahifaga qaytish"><ArrowLeft/></button><div><small>O‘QUVCHI KABINETI</small><h1>Mening profilim</h1><p>Ma’lumotlaringiz va mashqlar tarixi shu yerda.</p></div><button className="btn btn-outline" onClick={load} disabled={!!busy}><RefreshCw size={16}/> Yangilash</button></header>
  {error&&<p className="sp-alert" role="alert">{error}</p>}{message&&<p className="sp-success" role="status"><Check size={18}/>{message}</p>}
  <div className="sp-layout"><section className="sp-card"><div className="sp-card-heading"><UserRound/><div><h2>Shaxsiy ma’lumotlar</h2><p>Ism va sinfingizni to‘ldiring.</p></div></div>{form?<form onSubmit={save} className="sp-form"><label>Ism va familiya<input required minLength={2} maxLength={60} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>{form.provider==='email'&&<label>Email<input value={form.email} readOnly/></label>}<label>Maktab<input maxLength={100} value={form.school} onChange={e=>setForm({...form,school:e.target.value})} placeholder="Maktabingiz"/></label><label>Sinf yoki guruh<input maxLength={30} value={form.className} onChange={e=>setForm({...form,className:e.target.value})} placeholder="Masalan, 8-A"/></label><label>O‘zim haqimda<textarea maxLength={400} rows={3} value={form.about} onChange={e=>setForm({...form,about:e.target.value})} placeholder="Qaysi fanlar sizni qiziqtiradi?"/></label><button className="btn btn-primary" disabled={!!busy}><Save size={16}/>{busy==='profile'?'Saqlanmoqda…':'Saqlash'}</button></form>:<p className="sp-muted">Profil ochilmoqda…</p>}</section>
  <section className="sp-card"><div className="sp-card-heading"><LockKeyhole/><div><h2>Parolni yangilash</h2><p>Joriy parolni kiritib, yangi parol belgilang.</p></div></div>{profile?.provider==='email'?<form className="sp-form" onSubmit={renew}><label>Joriy parol<input required type={show?'text':'password'} autoComplete="current-password" value={password.old} onChange={e=>setPassword({...password,old:e.target.value})}/></label><label>Yangi parol<input required minLength={12} type={show?'text':'password'} autoComplete="new-password" value={password.next} onChange={e=>setPassword({...password,next:e.target.value})}/></label><label>Yangi parolni takrorlang<input required minLength={12} type={show?'text':'password'} autoComplete="new-password" value={password.again} onChange={e=>setPassword({...password,again:e.target.value})}/></label><button type="button" className="sp-show" onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>} {show?'Parollarni yashirish':'Parollarni ko‘rsatish'}</button><button className="btn btn-primary" disabled={!!busy||password.next.length<12||!password.old}>Parolni yangilash</button></form>:<p className="sp-muted">Telegram bilan kirgansiz. Hisobingizga Telegram orqali kirasiz.</p>}</section></div>
  <section className="sp-card sp-history"><div className="sp-card-heading"><Trophy/><div><h2>Natijalar tarixi</h2><p>Hisobingiz bilan ishlangan test va mashqlar.</p></div><span className="sp-total">{history.length} ta</span></div>{partial&&<p className="sp-warning">Ayrim natijalar yuklanmadi. 7.9 SQL yangilanishini tekshiring va qayta urinib ko‘ring.</p>}<div className="sp-filters" aria-label="Natija turlari">{Object.entries(kinds).map(([kind,label])=><button key={kind} className={filter===kind?'active':''} aria-pressed={filter===kind} onClick={()=>{setFilter(kind);setShown(24)}}>{label}</button>)}</div>{visible.length?<div className="sp-list">{visible.slice(0,shown).map(row=><article key={`${row.type}-${row.id}`}><span className="sp-kind">{row.type==='typing'?<Keyboard size={20}/>:<BookOpen size={20}/>}</span><div><small>{kinds[row.type]} · {date(row.at)}</small><h3>{row.title}</h3><p>{row.score}</p></div></article>)}</div>:<div className="sp-empty">{busy==='load'?'Natijalar yuklanmoqda…':'Bu turda natija yo‘q.'}</div>}{visible.length>shown&&<button className="btn btn-outline sp-more" onClick={()=>setShown(value=>value+24)}>Yana {Math.min(24,visible.length-shown)} ta natija</button>}<p className="sp-muted">Kodli test, typing va 1v1’da hisobingizga kirib qatnashgan bo‘lsangiz, natija shu profilga bog‘lanadi. Hisobsiz ishlangan eski mashqlarni keyin bog‘lab bo‘lmaydi.</p></section>
 </main>;
}
