import StudioArt from './StudioArt.jsx';
import React,{useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,Atom,BookOpen,Check,Code2,Languages,Leaf,Search} from 'lucide-react';
import {api} from './api.js';
import {books} from './iq/service.js';
import {subjects,availableBooks,filterBooks} from './textbooks/model.js';
import BookReader from './textbooks/Reader.jsx';
import './learning-hub.css';
const icons={chemistry:Atom,english:Languages,biology:Leaf,informatics:Code2,other:BookOpen};
export default function TextbookHub({user,onBack,onEnglish,onDocument,onActivity,onCatalog,onManage}){
 const [documents,setDocuments]=useState([]),[subject,setSubject]=useState('all'),[query,setQuery]=useState(''),[group,setGroup]=useState('all'),[progress,setProgress]=useState({}),[selected,setSelected]=useState(null),[expanded,setExpanded]=useState({}),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const reload=async()=>{const [catalog,own]=await Promise.all([api('/api/catalog'),['teacher','admin'].includes(user.role)?api('/api/lessons'):Promise.resolve({lessons:[]})]);setDocuments([...new Map([...catalog.lessons,...own.lessons].map(l=>[l.id,l])).values()]);setError('')};
 useEffect(()=>{let alive=true;Promise.allSettled([reload(),books('home').then(p=>alive&&setProgress(p))]).then(results=>{if(!alive)return;const errors=results.filter(r=>r.status==='rejected').map(r=>r.reason.message);if(errors.length)setError(errors.join(' '));setLoading(false)});return()=>{alive=false}},[user.id]);
 const all=useMemo(()=>availableBooks(documents,user),[documents,user.id,user.role]),filtered=useMemo(()=>filterBooks(all,{subject,query,group}),[all,subject,query,group]);
 const chooseSubject=id=>{setSubject(id);setGroup('all');setSelected(null)};
 const open=b=>{if(b.document)return onDocument(b.document,b.id);if(b.kind==='english')return onEnglish(b.courseId);setSelected(b.id);window.scrollTo({top:0,behavior:'instant'})};
 const book=all.find(b=>b.id===selected),ordered=all.filter(b=>b.subject===book?.subject&&b.group===book?.group).sort((a,b)=>a.ordinal-b.ordinal),next=book&&ordered[ordered.findIndex(b=>b.id===book.id)+1];
 const sections=[...subjects,...(filtered.some(b=>b.subject==='other')?[{id:'other',title:'Ustozlarning boshqa fanlari',subtitle:'Mavjud e’lon qilingan darslar',color:'blue'}]:[])];
 return <main className="sq-learning textbook-hub"><header className="learning-top"><button onClick={onBack}><ArrowLeft size={18}/> Bosh sahifa</button><span className="learning-kicker">SINFQUIZ / DARSLIKLAR</span><button onClick={onCatalog}>Testlar va kabinet <ArrowRight size={17}/></button></header>{book?<BookReader key={book.id} book={book} onBack={()=>setSelected(null)} onOpen={open} onActivity={onActivity} onProgress={setProgress} progress={progress} next={next}/>:<><section className="books-hero"><span className="learning-kicker">O‘QING. TUSHUNING. AMALDA SINANG.</span><h1>Darsliklar,<br/><em>bitta joyda.</em></h1><p>To‘rtta fan ochiq. Mavzuni toping, ketma-ket o‘qing va amaliyotga o‘ting. Ustozingiz e’lon qilgan darslar ham o‘z muallifi bilan ko‘rinadi.</p><div className="learning-search"><Search size={19}/><label className="sr-only" htmlFor="book-search">Dars yoki mavzu qidirish</label><input id="book-search" type="search" placeholder="Masalan: atom, fotosintez, Present Simple, Excel…" value={query} onChange={e=>setQuery(e.target.value)}/></div></section>
 <nav className="book-subjects" aria-label="Darslik fanlari">{subjects.map(s=>{const Icon=icons[s.id],n=all.filter(b=>b.subject===s.id).length;return <button key={s.id} className={`book-subject ${s.color} ${subject===s.id?'selected':''}`} aria-pressed={subject===s.id} onClick={()=>chooseSubject(subject===s.id?'all':s.id)}><StudioArt subject={s.id}/><b>{s.title}</b><span>{n} dars</span><small>{s.subtitle}</small></button>})}</nav>
 <div className="books-filter"><button aria-pressed={subject==='all'} className={subject==='all'?'selected':''} onClick={()=>chooseSubject('all')}>Barcha fanlar</button><label>Bo‘lim<select value={group} onChange={e=>setGroup(e.target.value)}><option value="all">Barcha bo‘limlar</option>{[...new Set(all.filter(b=>subject==='all'||b.subject===subject).map(b=>b.group))].map(g=><option key={g}>{g}</option>)}</select></label><span>{filtered.length} dars topildi</span>{onManage&&<button onClick={onManage}>Darsliklarimni boshqarish</button>}</div>
 {error&&<div className="learning-message" role="status"><p>{error} Asosiy darsliklarni o‘qishingiz mumkin.</p><button disabled={loading} onClick={()=>{setLoading(true);Promise.allSettled([reload(),books('home').then(setProgress)]).then(r=>{const e=r.find(x=>x.status==='rejected');setError(e?e.reason.message:'')}).finally(()=>setLoading(false))}}>Qayta ulanish</button></div>}{loading&&<p role="status">Ustoz darslari va o‘qish tarixi olinmoqda…</p>}
 <div className="books-sections">{sections.map(s=>{const items=filtered.filter(b=>b.subject===s.id);if(!items.length)return null;const Icon=icons[s.id],visible=subject!=='all'||query||group!=='all'||expanded[s.id]?items:items.slice(0,6);return <section className="learning-card book-section" key={s.id} aria-labelledby={`book-section-${s.id}`}><header><Icon size={23}/><div><h2 id={`book-section-${s.id}`}>{s.title}</h2><p>{s.subtitle}</p></div><span>{items.length} dars</span></header><ol>{visible.map(b=><li key={b.id}><button onClick={()=>open(b)}><span className="book-number">{String(b.ordinal).padStart(2,'0')}</span><span className="book-list-text"><small>{b.group} · {b.source}</small><b>{b.title}</b><span>{b.summary}</span></span>{progress[b.id]?.read&&<Check size={18} aria-label="O‘qilgan"/>}<ArrowRight size={17}/></button></li>)}</ol>{visible.length<items.length?<button className="book-expand" onClick={()=>setExpanded(e=>({...e,[s.id]:true}))}>{s.title}: barcha {items.length} darsni ko‘rish <ArrowRight size={17}/></button>:subject==='all'&&!query&&group==='all'&&items.length>6&&<button className="book-expand" onClick={()=>setExpanded(e=>({...e,[s.id]:false}))}>Ro‘yxatni qisqartirish</button>}</section>})}</div>{!filtered.length&&<section className="learning-card"><h2>Mavzu topilmadi</h2><p>Qisqaroq so‘z yozing yoki boshqa bo‘limni tanlang.</p><button onClick={()=>{setQuery('');chooseSubject('all')}}>Barcha darsliklarni ko‘rish</button></section>}
 </>}</main>
}
